---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= Solution NetApp avec les workloads gérés de la plateforme de conteneurs Red Hat OpenShift
:allow-uri-read: 




== Solution NetApp avec les workloads gérés de la plateforme de conteneurs Red Hat OpenShift

[role="lead"]
Les clients peuvent être « nés dans le cloud » ou se trouver à un point de leur parcours de modernisation lorsqu'ils sont prêts à déplacer des workloads spécifiques ou tous les workloads de leurs data centers vers le cloud. Ils peuvent choisir d'utiliser des conteneurs OpenShift gérés par un fournisseur et du stockage NetApp géré par un fournisseur dans le cloud pour exécuter leurs workloads. Ils doivent planifier et déployer les clusters de conteneurs Red Hat OpenShift gérés dans le cloud pour assurer la réussite de leur environnement de production pour leurs workloads de conteneurs. . NetApp propose des offres de stockage entièrement gérées pour les solutions Red Hat gérées dans les trois principaux clouds publics.

*Amazon FSX pour NetApp ONTAP (FSX ONTAP)*

FSX ONTAP assure la protection, la fiabilité et la flexibilité des données pour les déploiements de conteneurs dans AWS. Trident sert de mécanisme de provisionnement de stockage dynamique pour consommer le stockage persistant FSX ONTAP pour les applications avec état des clients.

COMME ROSA peut être déployée en mode HA avec des nœuds de plan de contrôle répartis sur plusieurs zones de disponibilité, FSX ONTAP peut également être provisionné avec l'option multi-AZ qui assure la haute disponibilité et la protection contre les défaillances AZ.

*Google Cloud NetApp volumes*

Red Hat OpenShift Dedicated est une plateforme d'applications entièrement gérée qui vous permet de créer, déployer et faire évoluer rapidement vos applications dans le cloud hybride. Google Cloud NetApp volumes fournit des volumes persistants apportant à des déploiements OpenShift dans Google Cloud l'ensemble des fonctionnalités de gestion des données d'entreprise de la suite ONTAP.
