---
sidebar: sidebar 
permalink: rhhc/rhhc-sm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= Solution NetApp avec les workloads de plateforme de conteneurs Red Hat OpenShift dans le cloud hybride
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les clients peuvent se trouver à un point de leur parcours de modernisation lorsqu'ils sont prêts à déplacer des workloads spécifiques ou tous les workloads de leurs data centers vers le cloud. Ils peuvent choisir d'utiliser des conteneurs OpenShift autogérés et du stockage NetApp autogéré dans le cloud pour diverses raisons. Ils doivent planifier et déployer Red Hat OpenShift Container Platform (OCP) dans le cloud pour que l'environnement soit prêt à la production et puisse migrer les workloads de conteneurs depuis leurs data centers. Leurs clusters OCP peuvent être déployés sur VMware ou bare Metal dans leurs data centers, ainsi que sur AWS, Azure ou Google Cloud dans l'environnement cloud.

Le stockage NetApp Cloud Volumes ONTAP assure la protection, la fiabilité et la flexibilité des données pour les déploiements de conteneurs dans AWS, Azure et dans Google Cloud. ASTRA Trident sert de mécanisme de provisionnement de stockage dynamique pour consommer le stockage Cloud Volumes ONTAP persistant pour les applications avec état des clients. ASTRA Control Center peut être utilisé pour orchestrer les nombreuses exigences de gestion des données des applications avec état, telles que la protection des données, la migration et la continuité de l'activité.



== Solution de protection et de migration des données pour les workloads de conteneurs OpenShift dans un cloud hybride via Astra Control Center

Image sur site et AWS ::rhhc-autogéré-aws.png[]

Image sur site et Google Cloud ::rhhc-autogéré-gcp.png[]

Image sur site et cloud Azure ::rhhc-autogéré-Azure.png[]
