---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Trident Protect, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= Propositions de valeur des solutions multicloud hybrides NetApp pour les workloads de conteneurs Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La plupart des clients ne se contentent pas de créer des environnements Kubernetes sans infrastructure existante. Il s'agit peut-être d'un service INFORMATIQUE traditionnel qui exécute la plupart de ses applications d'entreprise sur des machines virtuelles (dans de grands environnements VMware, par exemple). Ils commencent ensuite à créer de petits environnements basés sur des conteneurs pour répondre aux besoins de leurs équipes de développement d'applications modernes. Ces initiatives commencent généralement à petite échelle et commencent à devenir plus omniprésentes lorsque les équipes apprennent ces nouvelles technologies et compétences, et commencent à reconnaître les nombreux avantages de leur adoption. La bonne nouvelle pour les clients est que NetApp répond aux besoins des deux environnements. Cet ensemble de solutions pour le multicloud hybride avec Red Hat OpenShift permettra aux clients NetApp d'adopter des technologies et des services cloud modernes sans avoir à remanier l'ensemble de leur infrastructure et de leur organisation. Que les applications et les données des clients soient hébergées sur site, dans le cloud, sur des machines virtuelles ou sur des conteneurs, NetApp offre des fonctionnalités cohérentes de gestion, de protection, de sécurité et de portabilité des données. Avec ces nouvelles solutions, la valeur ajoutée qu'offre NetApp dans les environnements de data Center sur site pendant des décennies sera disponible à l'échelle de l'entreprise à tous les niveaux, sans nécessiter d'investissements importants pour changer d'outil, acquérir de nouvelles compétences ou constituer de nouvelles équipes. NetApp est bien placé pour aider les clients à relever ces défis métier, quelle que soit l'étape de leur transition vers le cloud.

NetApp Hybrid Multi-Cloud avec Red Hat OpenShift :

* Fournit aux clients des conceptions et des pratiques validées qui démontrent la meilleure façon de gérer, protéger, sécuriser et migrer leurs données et applications lors de l'utilisation de Red Hat OpenShift avec les solutions de stockage NetApp.
* Présenter les meilleures pratiques pour les clients exécutant Red Hat OpenShift avec le stockage NetApp dans des environnements VMware, une infrastructure bare Metal ou une combinaison des deux.
* Présentez les stratégies et les options des environnements sur site et cloud, ainsi que des environnements hybrides dans lesquels les deux sont utilisés.

