---
sidebar: sidebar 
permalink: xcp/xcp-bp-high-performance-computing-to-ontap-nfs.html 
keywords: use case, gpfs, nfs 
summary: 'Nous avons utilisé NetApp XCP pour migrer les données de GPFS vers NFS, de sorte que les GPU puissent traiter les données. L"IA traite généralement les données d"un système de fichiers en réseau.' 
---
= L'informatique haute performance pour ONTAP NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-data-lake-to-ontap-nfs.html["Précédent : Data Lake à ONTAP NFS."]

[role="lead"]
Ce cas d'utilisation est basé sur les demandes des organisations de terrain. Certains clients de NetApp disposent de leurs données dans un environnement informatique hautes performances, qui assure l'analytique des modèles d'entraînement et permet aux organismes de recherche de mieux comprendre un grand nombre de données numériques. Les ingénieurs de terrain NetApp ont besoin d'une procédure détaillée pour extraire les données de GPFS d'IBM vers NFS. Nous avons utilisé NetApp XCP pour migrer les données de GPFS vers NFS, de sorte que les GPU puissent traiter les données. L'IA traite généralement les données d'un système de fichiers en réseau.

Pour plus d'informations sur le calcul haute performance du cas d'utilisation de ONTAP NFS, une démonstration enregistrée et les résultats des tests, consultez le https://["Utilisation de XCP pour transférer des données d'un Data Lake et de calcul haute performance vers NFS ONTAP"^] blog.

Pour des étapes détaillées sur le transfert des données de MapR-FS vers ONTAP NFS à l'aide de NetApp XCP, voir l'annexe A : GPFS vers NFS―étapes détaillées https://["Tr-4732 : analytique Big Data dans l'intelligence artificielle"^].

link:xcp-bp-using-the-xcp-data-mover-to-migrate-millions-of-small-files-to-flexible-storage.html["Suivant : utilisation de XCP Data Mover pour migrer des millions de petits fichiers vers un système de stockage flexible."]
