---
sidebar: sidebar 
permalink: xcp/xcp-bp-using-the-xcp-data-mover-to-migrate-large-files.html 
keywords: migrate, large files, rman, ebs, pacemaker 
summary: 'Ce cas d"utilisation est basé sur un client réseau de télévision. Le client souhaitait migrer les fichiers de sauvegarde RMAN (Oracle Recovery Manager) vers le cloud et exécuter l"application Oracle E-Business Suite (EBS) à l"aide du logiciel Azure NetApp Files with Pacemaker. Il souhaitait également migrer ses fichiers de sauvegarde de base de données vers un stockage cloud à la demande et transférer des fichiers volumineux (de 25 à 50 Go chacun) vers Azure.' 
---
= Utilisation du Data Mover XCP pour migrer des fichiers volumineux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-using-the-xcp-data-mover-to-migrate-millions-of-small-files-to-flexible-storage.html["Précédent : utilisation de XCP Data Mover pour migrer des millions de petits fichiers vers un système de stockage flexible."]

[role="lead"]
Ce cas d'utilisation est basé sur un client réseau de télévision. Le client souhaitait migrer les fichiers de sauvegarde RMAN (Oracle Recovery Manager) vers le cloud et exécuter l'application Oracle E-Business Suite (EBS) à l'aide du logiciel Azure NetApp Files with Pacemaker. Il souhaitait également migrer ses fichiers de sauvegarde de base de données vers un stockage cloud à la demande et transférer des fichiers volumineux (de 25 à 50 Go chacun) vers Azure.

La figure suivante illustre la migration des données entre une infrastructure sur site et un système Azure NetApp Files pour des fichiers volumineux.

Pour plus d'informations, reportez-vous à la section https://blog.netapp.com/XCP-cloud-data-migration["Solution NetApp XCP Data Mover : du site au cloud"^] blog.

link:xcp-bp-duplicate-files.html["Suivant : fichiers en double."]
