---
sidebar: sidebar 
permalink: xcp/xcp-bp-best-practice-guidelines-and-recommendations.html 
keywords: best practices, guidelines, recommendations, IMT 
summary: 'Cette section contient les meilleures pratiques, des instructions et des recommandations pour la migration de données à l"aide de NetApp XCP.' 
---
= Recommandations et recommandations sur les bonnes pratiques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
* Utilisez le système d'exploitation client XCP, qui est pris en charge par IMT. Le client pris en charge par IMT est qualifié par NetApp.
* Exécutez XCP en tant qu'utilisateur root dans le système d'exploitation Linux pour effectuer la migration. Vous pouvez exécuter la commande xcp en tant qu'utilisateur sudo, mais elle n'est pas prise en charge par XCP.
* Exécutez une seule instance de XCP par client. Techniquement, vous pouvez exécuter plusieurs instabilités de XCP sur le même hôte à partir d'un emplacement différent, mais cette pratique n'est pas prise en charge. En effet, l'exécution de nombreuses instances peut entraîner une défaillance.
* XCP NFS est capable de migrer d'un dataset source en direct et cette configuration est prise en charge. Les migrations SMB XCP à partir d'un dataset source actif ne sont pas prises en charge et peuvent entraîner des défaillances.
* Il est recommandé de créer un nouveau snapshot avec un nom différent pour chaque synchronisation incrémentielle afin de créer facilement un chemin de migration incrémentielle basé sur le nom du snapshot en cas de défaillance.
* Si vous effectuez une migration basée sur des snapshots, il est conseillé de continuer la migration basée sur des snapshots jusqu'à la mise en service.
* Si vous avez plus de 10 millions de fichiers et que vous avez une modification incrémentielle des données de plus de 50 %, il est recommandé d'utiliser un nombre de cœurs supérieur et plus de mémoire que le minimum recommandé dans le guide d'installation et d'administration.

