---
sidebar: sidebar 
permalink: data-analytics/apache-spark-conclusion.html 
keywords: conclusion 
summary: Cette section récapitule les solutions de stockage NetApp pour Apache Spark. 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:apache-spark-python-scripts-for-each-major-use-case.html["Précédent : scripts Python pour chaque cas d'utilisation majeur."]

Dans ce document, nous présenterons l'architecture Apache Spark, les utilisations client et le portefeuille de solutions de stockage NetApp en ce qui concerne le Big Data, l'analytique moderne, l'IA, LE ML et le DL. Dans le cadre de tests de validation des performances basés sur des outils de banc d'essai standard et sur la demande client, les solutions NetApp Spark offrent des performances supérieures à celles des systèmes Hadoop natifs. La combinaison des cas d'utilisation clients et des résultats de performances présentés dans ce rapport peut vous aider à choisir la solution Spark la mieux adaptée à votre déploiement.

link:apache-spark-where-to-find-additional-information.html["Suivant : où trouver des informations supplémentaires ?"]
