---
sidebar: sidebar 
permalink: data-analytics/apache-spark-target-audience.html 
keywords: audience, data scientist, engineer, devops, cloud administrator, architect 
summary: 'Cette section décrit les personnes susceptibles d"être intéressées par le contenu de cette solution.' 
---
= Public visé
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:apache-spark-solution-overview.html["Précédent : présentation de la solution."]

[role="lead"]
L'univers de l'analytique et de la science des données touche plusieurs disciplines au NIVEAU DE L'INFORMATIQUE et des activités :

* Les data Scientists doivent donc pouvoir utiliser leurs outils et leurs bibliothèques de choix.
* L'ingénieur doit savoir comment les données circulent et où elles résident.
* Un ingénieur DevOps doit disposer des outils nécessaires pour intégrer les nouvelles applications d'IA et DE ML dans son pipeline d'intégration et de livraison continues.
* Les administrateurs et architectes cloud doivent être en mesure de configurer et de gérer des ressources de cloud hybride.
* Les utilisateurs professionnels veulent avoir accès à des applications d'analytique, d'IA, DE ML et de DL.


Dans ce rapport technique, nous explique comment NetApp AFF, E-Series, StorageGRID, NFS direct, Apache Spark Horovod et Keras aident chacun de ces rôles à apporter de la valeur aux entreprises.

link:apache-spark-solution-technology.html["Suivant : technologie de la solution."]
