---
sidebar: sidebar 
permalink: data-analytics/bda-ai-business-benefits.html 
keywords: business, benefits 
summary: Cette section décrit les avantages commerciaux de cette solution. 
---
= Avantages pour l'entreprise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:bda-ai-hdfs-and-mapr-fs-to-ontap-nfs.html["Précédent : HDFS et MapR-FS sur ONTAP NFS."]

Le déplacement des données de l'analytique Big Data vers l'IA présente plusieurs avantages :

* La possibilité d'extraire les données de différents systèmes de fichiers Hadoop et GPFS dans un système de stockage NFS unifié
* Transfert de données automatisé et intégré à Hadoop
* Réduction du coût de développement de la librairie pour le déplacement des données à partir des systèmes de fichiers Hadoop
* Performances maximales grâce au débit agrégé de plusieurs interfaces réseau à partir d'une seule source de données à l'aide de NIPAM
* Méthodes planifiées et à la demande pour le transfert des données
* L'efficacité du stockage et une fonctionnalité de gestion d'entreprise pour les données NFS unifiées grâce au logiciel de gestion des données ONTAP
* Transfert de données sans coût supplémentaire avec la méthode Hadoop


link:bda-ai-gpfs-to-nfs-detailed-steps.html["Suivant : étapes GPFS vers NFS détaillées."]
