---
sidebar: sidebar 
permalink: data-analytics/bda-ai-customer-challenges.html 
keywords: customer, challenge, data lake, repository, syncing, moving data 
summary: 'Cette page présente les challenges que peuvent relever les clients lorsqu"ils cherchent à accéder aux données issues de l"analytique Big Data pour les opérations d"IA.' 
---
= Défis des clients
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:bda-ai-introduction.html["Précédent : introduction."]

[role="lead"]
Lorsque vous essayez d'accéder aux données issues de l'analytique Big Data pour les opérations d'IA, vous devez :

* Les données des clients se trouvent dans un référentiel de data Lake. Le data Lake peut contenir différents types de données, qu'elles soient structurées, non structurées, semi-structurées, journaux ou encore machines à machines. L'ensemble de ces types de données doit être traité dans des systèmes d'IA.
* L'IA n'est pas compatible avec les systèmes de fichiers Hadoop. Une architecture d'IA standard n'est pas en mesure d'accéder directement aux données HDFS et HCFS, qui doit être déplacée vers un système de fichiers compréhensible par l'IA (NFS).
* Le déplacement des données du data Lake vers l'IA nécessite généralement des processus spécialisés. Le volume de données dans le data Lake peut être très élevé. Un client doit disposer d'un moyen efficace, haut débit et économique de déplacer des données vers des systèmes d'IA.
* Synchronisation des données. Si un client souhaite synchroniser des données entre la plateforme Big Data et l'IA, parfois les données traitées par l'IA peuvent être utilisées avec le Big Data à des fins de traitement analytique.


link:bda-ai-data-mover-solution.html["Ensuite, une solution de déplacement des données."]
