---
sidebar: sidebar 
permalink: data-analytics/cdm-fod-conclusion.html 
keywords: conclusion 
summary: 'À partir de cette validation, les data Scientists et les ingénieurs peuvent accéder aux données NFS depuis les ordinateurs portables AWS SageMaker Jupyter via des compartiments S3 à partir de NetApp Cloud Volumes ONTAP. Cette approche facilite l"accès et le partage des mêmes données à partir des protocoles NFS et S3 sans recourir à des logiciels supplémentaires.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:cdm-fod-data-duality-for-data-scientists-and-other-applications.html["Précédent : la dualité des données pour les data Scientists et d'autres applications"]

[role="lead"]
À partir de cette validation, les data Scientists et les ingénieurs peuvent accéder aux données NFS depuis les ordinateurs portables AWS SageMaker Jupyter via des compartiments S3 à partir de NetApp Cloud Volumes ONTAP. Cette approche facilite l'accès et le partage des mêmes données à partir des protocoles NFS et S3 sans recourir à des logiciels supplémentaires.



== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Classification de texte à l'aide de SageMaker BlazingText
+
https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html["https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html"^]

* Prise en charge de la version ONTAP pour le stockage objet S3
+
https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html"^]





== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Avril 2023 | Version initiale 
|===