---
sidebar: sidebar 
permalink: data-analytics/cdm-fod-solution-overview.html 
keywords: tr4967, 4967, introduction, overview 
summary: 'Les data Scientists et les ingénieurs doivent souvent accéder aux données stockées au format NFS, mais l"accès à ces données directement à partir du protocole S3 dans AWS SageMaker peut être compliqué, car AWS prend uniquement en charge l"accès au compartiment S3. Cependant, NetApp ONTAP propose une solution qui permet un accès à double protocole pour NFS et S3. Avec cette solution, les data Scientists et les ingénieurs peuvent accéder aux données NFS depuis les ordinateurs portables AWS SageMaker via des compartiments S3 de NetApp Cloud Volumes ONTAP. Cette approche facilite l"accès et le partage des mêmes données à partir des protocoles NFS et S3 sans recourir à des logiciels supplémentaires.' 
---
= Tr-4967 : gestion des données cloud avec NetApp File-Object Duality et AWS SageMaker
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthikeyan Nagalingam, NetApp

[role="lead"]
Les data Scientists et les ingénieurs doivent souvent accéder aux données stockées au format NFS, mais l'accès à ces données directement à partir du protocole S3 dans AWS SageMaker peut être compliqué, car AWS prend uniquement en charge l'accès au compartiment S3. Cependant, NetApp ONTAP propose une solution qui permet un accès à double protocole pour NFS et S3. Avec cette solution, les data Scientists et les ingénieurs peuvent accéder aux données NFS depuis les ordinateurs portables AWS SageMaker via des compartiments S3 de NetApp Cloud Volumes ONTAP. Cette approche facilite l'accès et le partage des mêmes données à partir des protocoles NFS et S3 sans recourir à des logiciels supplémentaires.

link:cdm-fod-solution-technology.html["Suivant : technologie de la solution."]
