---
sidebar: sidebar 
permalink: data-analytics/confluent-kafka-conclusion.html 
keywords: conclusion 
summary: 'Ce document fournit des recommandations sur les bonnes pratiques pour l"utilisation de Kafka avec le stockage NetApp, notamment les tests de certification Fluent Kafka, les résultats de performances, le réglage, les connecteurs Kafka et la fonctionnalité d"auto-rééquilibrage.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Ce document fournit des recommandations sur les meilleures pratiques pour l'utilisation en traitant le stockage à plusieurs niveaux avec un stockage NetApp, notamment des tests de vérification, des résultats de performances de stockage à plusieurs niveaux, un réglage, des connecteurs S3 confluent et la fonctionnalité d'équilibrage automatique. Compte tenu des règles ILM, des performances fluides avec de multiples tests de performances pour la vérification et des API S3 standard, le stockage objet NetApp StorageGRID est la solution idéale pour parler du stockage hiérarchisé.



== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Qu'est-ce que Apache Kafka
+
https://www.confluent.io/what-is-apache-kafka/["https://www.confluent.io/what-is-apache-kafka/"^]

* Documentation produit NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Détails des paramètres de l'évier S3
+
https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html["https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html#s3-configuration-options"^]

* Apache Kafka
+
https://en.wikipedia.org/wiki/Apache_Kafka["https://en.wikipedia.org/wiki/Apache_Kafka"^]

* Stockage infini dans une plateforme fluide
+
https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/["https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/"^]

* Stockage à plusieurs niveaux confluent : meilleures pratiques et dimensionnement
+
https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations["https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations"^]

* Connecteur de dissipateur Amazon S3 pour plate-forme de raccordement
+
https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html["https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html"^]

* Dimensionnement de Kafka
+
https://eventsizer.io["https://eventsizer.io"]

* Dimensionnement de StorageGRID
+
https://fusion.netapp.com/["https://fusion.netapp.com/"^]

* Cas d'utilisation de Kafka
+
https://kafka.apache.org/uses["https://kafka.apache.org/uses"^]

* Clusters Kafka autoéquilibrant dans la plateforme confluent 6.0
+
https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/["https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/"^]

+
https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/["https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/"^]


