---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-conclusion.html 
keywords: conclusion 
summary: 'Ce document fournit les meilleures pratiques pour l"utilisation de Dremio avec le stockage NetApp, y compris les tests de certification TPCDS, le réglage et les détails de l"utilisation client.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En conclusion, ce rapport technique fournit des informations détaillées sur le déploiement de q Lakehouse d'Iceberg hybride avec Dremio en conjonction avec diverses sources de données des contrôleurs de stockage NetApp, dont ONTAP S3, NAS et StorageGRID. Le processus de déploiement a été exécuté avec succès et l'outil d'évaluation TPC-DS a été utilisé pour exécuter 99 requêtes SQL sur les différentes sources de données. Ce rapport a également exploré les cas d'utilisation chez NetApp, démontrant ainsi la polyvalence et l'efficacité de Dremio pour répondre à diverses exigences métier. En outre, un cas d'utilisation spécifique impliquant un client de vente de pièces automobiles a été examiné, mettant en évidence l'application pratique et les avantages de l'exploitation de Dremio pour l'analyse de données et les informations exploitables.

Dans l'ensemble, ce document constitue une ressource précieuse pour comprendre le déploiement et l'utilisation de Dremio avec les contrôleurs de stockage NetApp. Il présente ses capacités et son potentiel en matière de prise de décision et d'optimisation basées sur les données dans de nombreux secteurs.



== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Installation de Zookeeper
+
https://medium.com/@ahmetfurkandemir/distributed-hadoop-cluster-1-spark-with-all-dependincies-03c8ec616166[]

* Dremio
+
https://docs.dremio.com/current/get-started/cluster-deployments/deployment-models/standalone/standalone-tarball/[]

* Configuration de Dremio avec StorageGRID
+
https://docs.netapp.com/us-en/storagegrid-enable/tools-apps-guides/configure-dremio-storagegrid.html#configure-dremio-data-source[]

* Cas d'utilisation de NetApp
+
https://www.dremio.com/customers/netapp/[]


