---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-introduction.html 
keywords: introduction, best practices, dremio, lakehouse 
summary: 'Ce document présente les bonnes pratiques en matière d"utilisation de Dremio sur un contrôleur de stockage NetApp.' 
---
= La solution hybride de nouvelle génération NetApp et Dremio Iceberg Lakehouse
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans ce document, nous présentons les détails de déploiement de Dremio avec différentes sources de données des contrôleurs de stockage NetApp, notamment ONTAP S3, NAS et StorageGRID. Au cours du déploiement, nous avons utilisé l'outil d'évaluation TPC-DS pour exécuter 99 requêtes SQL sur différentes sources. Il explore également les cas d'utilisation chez les clients au sein de NetApp, ainsi qu'un cas d'utilisation impliquant un client de vente de pièces automobiles.

*Auteurs*

Karthikeyan Nagalingam, architecte principal, NetApp, Inc. Roger Frey, Vice-président, alliances, Dremio Corporation. Mark Shainman, responsable marketing produit principal.Dremio Corporation.
