---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-overview-of-hadoop-data-protection-use-cases.html 
keywords: summary, overview, backup, devtest, data protection 
summary: 'Cette section décrit de manière détaillée les cas d"utilisation de protection des données qui constituent le centre de ce document. Les sections restantes fournissent des informations détaillées sur chaque cas d"utilisation, telles que le problème d"un client (scénario), les exigences, les défis et les solutions.' 
---
= Présentation des cas d'utilisation de protection des données Hadoop
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit de manière détaillée les cas d'utilisation de protection des données qui constituent le centre de ce document. Les sections restantes fournissent des informations détaillées sur chaque cas d'utilisation, telles que le problème d'un client (scénario), les exigences, les défis et les solutions.



== Cas d'utilisation 1 : sauvegarde des données Hadoop

Pour ce cas d'utilisation, le volume NFS de NetApp a permis à une grande institution financière de réduire la durée de la fenêtre de sauvegarde, qui est passée de plus de 24 heures à seulement quelques heures.



== Cas d'utilisation 2 : sauvegarde et reprise après incident du cloud vers les environnements sur site

En utilisant Data Fabric optimisé par NetApp comme éléments de base, une grande entreprise de diffusion a pu satisfaire aux exigences de sauvegarde instantanée des données cloud dans son data Center sur site, selon les différents modes de transfert de données, comme à la demande, Ou en fonction de la charge du cluster Hadoop/Spark.



== Cas d'utilisation 3 : activation de DevTest sur les données Hadoop existantes

Les solutions NetApp ont permis à un distributeur de musique en ligne de créer rapidement plusieurs clusters Hadoop peu encombrants dans différentes succursales pour créer des rapports et exécuter des tâches quotidiennes DevTest à l'aide de règles planifiées.



== Cas d'utilisation 4 : protection des données et connectivité multicloud

Un grand fournisseur de services a utilisé la Data Fabric optimisée par NetApp pour fournir des fonctionnalités d'analytique multicloud à ses clients à partir de différentes instances de cloud.



== Cas d'utilisation 5 : accélération des workloads d'analytique

L'une des plus grandes banques d'investissement et de services financiers a eu recours à la solution de stockage NAS de NetApp pour réduire le temps d'attente des E/S et accélérer sa plateforme d'analytique financière quantitative.
