---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-conclusion.html 
keywords: conclusion, summary, data protection, hadoop, more information, Acknowledgements, version history 
summary: Cette section présente un récapitulatif des utilisations et des solutions proposées par NetApp pour répondre à différents besoins de protection de données Hadoop. 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:hdcs-sh-use-case-5--accelerate-analytic-workloads.html["Précédent : cas d'utilisation 5 - accélération des charges de travail analytiques."]

Cette section présente un récapitulatif des utilisations et des solutions proposées par NetApp pour répondre à différents besoins de protection de données Hadoop. Grâce à la Data Fabric optimisée par NetApp, les clients peuvent :

* Choisissez les solutions de protection des données adaptées en tirant parti des fonctionnalités avancées de gestion des données de NetApp et en intégrant les flux de travail natifs Hadoop.
* Réduire la durée des fenêtres de sauvegarde des clusters Hadoop de près de 70 %.
* Éliminez les effets des sauvegardes de clusters Hadoop sur les performances.
* Protégez les données multicloud et assurez l'accès aux données provenant de différents fournisseurs cloud simultanément à une seule source d'analytique.
* Création de copies de clusters Hadoop rapides et compactes à l'aide de la technologie FlexClone




== Où trouver des informations complémentaires

Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web :

* Solutions NetApp d'analytique Big Data
+
https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx["https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx"^]

* Charge de travail Apache Spark avec le stockage NetApp
+
https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf["https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf"^]

* Solutions de stockage NetApp pour Apache Spark
+
https://www.netapp.com/media/16864-tr-4570.pdf["https://www.netapp.com/media/16864-tr-4570.pdf"^]

* Apache Hadoop sur l'environnement Data Fabric optimisé par NetApp
+
https://www.netapp.com/media/16877-tr-4529.pdf["https://www.netapp.com/media/16877-tr-4529.pdf"^]

* Module d'analytique sur place NetApp
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2854071["https://library.netapp.com/ecm/ecm_download_file/ECMLP2854071"^]





== Remerciements

* Paul Burland, Ingénieur commercial, ventes pour le district ANZ Victoria District, NetApp
* Hoseb Dermanilian, responsable du développement commercial, NetApp
* Lee Dorrier, Directeur MPSG, NetApp
* David Thiessen, Ingénieur système, ANZ Victoria District se, NetApp




== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Janvier 2018 | Version initiale 


| Version 2.0 | Octobre 2021 | Mise à jour avec le cas d'utilisation n° 5 : accélération de la charge de travail analytique 
|===