---
sidebar: sidebar 
permalink: data-analytics/kafka-sc-performance-best-practice-guidelines.html 
keywords: best practices, get size, s3 buckets, ethernet links, mtu 
summary: 'Cette page décrit les meilleures pratiques en matière d"amélioration des performances de cette solution.' 
---
= Instructions sur les bonnes pratiques en matière de performances
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:kafka-sc-performance-tests-with-produce-consume-workload-generator.html["Précédent : tests de performances avec générateur de charges de travail produisant de consommation"]

* Pour ONTAP, lorsque possible, utilisez une taille D'OBTENTION >=1 Mo.
* Croissantes `num.network.threads` et `num.io.threads` dans `server.properties` Sur les nœuds de courtage, vous pouvez envoyer davantage d'activités de Tiering vers le Tier S3. Ces résultats sont obtenus avec `num.network.threads` et `num.io.threads` réglez sur 32.
* Les compartiments S3 doivent cibler huit composants par agrégat de membres.
* Les liaisons Ethernet conduisant le trafic S3 doivent utiliser une MTU de 9 000 si possible sur le stockage et le client.


link:kafka-sc-conclusion.html["Suivant: Conclusion."]
