---
sidebar: sidebar 
permalink: data-analytics/kafka-ontap-overview.html 
keywords: tr4941, 4941, introduction 
summary: 'Ce document présente les bancs d"essai sur les performances de la plateforme confluent sur NetApp ONTAP grâce à un kit de test des performances de stockage à plusieurs niveaux.' 
---
= Tr-4941 : association avec les contrôleurs de stockage NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthikeyan Nagalingam, Joe Scott, NetApp Rankesh Kumar, confluent

[role="lead"]
Pour que la plateforme confluent soit plus évolutive et plus élastique, elle doit pouvoir faire évoluer et équilibrer les charges de travail très rapidement. Le stockage à plusieurs niveaux permet le stockage de volumes massifs de données en parfaite maîtrise, en réduisant cette charge opérationnelle. Il s'agit de séparer le stockage des données du traitement, ce qui facilite la mise à niveau de chacun de manière indépendante.

Chargé d'innovations de pointe, le logiciel de gestion des données NetApp ONTAP apporte une maîtrise parfaite des avantages, quel que soit le lieu où résident les données.

Ce document présente les bancs d'essai sur les performances de la plateforme confluent sur NetApp ONTAP grâce à un kit de test des performances de stockage à plusieurs niveaux.

link:kafka-sc-solution.html["Ensuite, la solution."]
