---
sidebar: sidebar 
permalink: data-analytics/kafka-nfs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Où trouver des informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:kafka-nfs-conclusion.html["Précédent: Conclusion."]

[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Qu'est-ce qu'Apache Kafka ?
+
https://["https://www.confluent.io/what-is-apache-kafka/"^]

* Qu'est-ce qu'un changement de nom ?
+
https://["https://linux-nfs.org/wiki/index.php/Server-side_silly_rename"^]

* ONAT est lu pour les applications de streaming.
+
https://["https://www.netapp.com/blog/ontap-ready-for-streaming-applications/"^]

* Problème de changement de nom avec Kafka
+
https://["https://sbg.technology/2018/07/10/kafka-nfs/"^]

* Documentation des produits NetApp
+
https://["https://www.netapp.com/support-and-training/documentation/"^]

* Qu'est-ce que NFS ?
+
https://["https://en.wikipedia.org/wiki/Network_File_System"^]

* Qu'est-ce que la réaffectation de la partition Kafka ?
+
https://["https://docs.cloudera.com/runtime/7.2.10/kafka-managing/topics/kafka-manage-cli-reassign-overview.html"^]

* Qu'est-ce que le banc d'essai OpenMessaging ?
+
https://["https://openmessaging.cloud/"^]

* Comment migrer un courtier Kafka ?
+
https://["https://medium.com/@sanchitbansal26/how-to-migrate-kafka-cluster-with-no-downtime-58c216129058"^]

* Comment surveiller le courtier Kafka avec Prometheus ?
+
https://[]

* Plateforme gérée pour Apache Kafka
+
https://[]

* Prise en charge d'Apache Kafka
+
https://[]

* Services de conseil pour Apache Kafka
+
https://[]





== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Mars 2023 | Version initiale. 
|===