---
sidebar: sidebar 
permalink: data-analytics/sb-4154-link.html 
keywords:  
summary:  
---
= Analytique moderne : différentes solutions pour différentes stratégies d'analytique
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Ce livre blanc présente les stratégies des solutions d'analytique modernes de NetApp. Vous y trouverez des informations détaillées sur les résultats commerciaux, les défis des clients, les tendances technologiques, l'architecture existante concurrente, les workflows modernes, cas d'utilisation, secteurs, cloud, partenaires technologiques, mécanismes de déplacement des données, NetApp Active IQ, le kit NetApp DataOps, Hadoop to Spark, le stockage Software-defined avec NetApp Astra Control, les conteneurs, la gestion des données d'entreprise, l'archivage et le Tiering pour atteindre les objectifs de l'IA et de l'analytique, et la façon dont NetApp et ses clients modernisent leur architecture de données.

link:https://www.netapp.com/pdf.html?item=/media/58015-sb-4154.pdf["Analytique moderne : différentes solutions pour différentes stratégies d'analytique"^]
