---
sidebar: sidebar 
permalink: data-analytics/sb-4154.html 
keywords:  
summary:  
---
= Analytique moderne : différentes solutions pour différentes stratégies d'analytique
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce livre blanc présente les stratégies des solutions d'analytique modernes de NetApp. Vous y découvrirez notamment les résultats commerciaux, les challenges des clients, les tendances technologiques, l'architecture existante de la concurrence, les workflows modernes, les cas d'utilisation, les secteurs, le cloud, les partenaires technologiques, les mécanismes de déplacement des données, le conseiller digital NetApp Active IQ NetApp (également appelé conseiller digital), le kit NetApp DataOps Toolkit, Hadoop à Spark, le stockage Software-defined avec NetApp Trident Protect, les conteneurs, la gestion des données d'entreprise, l'archivage et le Tiering pour atteindre les objectifs de l'analytique et moderniser ensemble de l'IA et l'architecture de données.

link:https://www.netapp.com/pdf.html?item=/media/58015-sb-4154.pdf["Analytique moderne : différentes solutions pour différentes stratégies d'analytique"^]
