---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-conclusion.html 
keywords: conclusion, references 
summary: 'Splunk Enterprise est une solution SIEM leader du marché qui favorise la réussite des équipes de sécurité, D"IT et de DevOps. L"utilisation de Splunk a considérablement augmenté dans l"ensemble des organisations de nos clients. Il est donc nécessaire d"ajouter davantage de sources de données tout en conservant les données pendant une période plus longue, ce qui met l"infrastructure Splunk à l"épreuve.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Splunk Enterprise est une solution SIEM leader du marché qui favorise la réussite des équipes de sécurité, D'IT et de DevOps. L'utilisation de Splunk a considérablement augmenté dans l'ensemble des organisations de nos clients. Il est donc nécessaire d'ajouter davantage de sources de données tout en conservant les données pendant une période plus longue, ce qui met l'infrastructure Splunk à l'épreuve.

L'association de Splunk SmartStore et de NetApp StorageGRID a pour objectif de fournir une architecture évolutive qui permet aux entreprises de améliorer les performances d'entrée des données avec le stockage objet SmartStore et StorageGRID, ainsi qu'une meilleure évolutivité pour un environnement Splunk répartis sur plusieurs régions géographiques.



== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Ressources de documentation NetApp StorageGRID
+
https://www.netapp.com/data-storage/storagegrid/documentation/["https://www.netapp.com/data-storage/storagegrid/documentation/"^]

* Documentation produit NetApp
+
https://docs.netapp.com["https://docs.netapp.com"^]

* Documentation Splunk Enterprise
+
https://docs.splunk.com/Documentation/Splunk["https://docs.splunk.com/Documentation/Splunk"^]

* Splunk Enterprise à propos de SmartStore
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore"^]

* Manuel de déploiement distribué Splunk Enterprise
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview["https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview"^]

* Solutions Splunk Enterprise pour la gestion d'indexeurs et de clusters d'indexeurs
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers["https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers"^]


