---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-benefits.html 
keywords: benefits, performance, multi-site, scalability, capacity, availability, cache 
summary: 'La solution permet d"ajouter des ressources de calcul, de stockage à chaud ou S3 pour répondre à la demande croissante en termes de nombre d"utilisateurs ou de taux d"ingestion sur des déploiements mono et multi-sites.' 
---
= Avantages de cette solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La solution permet d'ajouter des ressources de calcul, de stockage à chaud ou S3 pour répondre à la demande croissante en termes de nombre d'utilisateurs ou de taux d'ingestion sur des déploiements mono et multi-sites.

* *Performance.* la combinaison de Splunk SmartStore et de NetApp StorageGRID permet une migration rapide des données entre des compartiments actifs et des compartiments chauds à l'aide du stockage objet. StorageGRID accélère le processus de migration en fournissant des performances rapides pour les workloads d'objets volumineux.
* *Multisite Ready.* l'architecture distribuée StorageGRID permet à Splunk SmartStore d'étendre les déploiements sur un seul et plusieurs sites via un espace de noms global unique où les données sont accessibles depuis n'importe quel site, quel que soit l'emplacement où elles résident.
* *Évolutivité améliorée.* faites évoluer les ressources de stockage indépendamment des ressources de calcul pour répondre à l'évolution des besoins et des demandes de votre environnement Splunk, tout en améliorant le coût total de possession.
* *Capacité* Découvrez les volumes en pleine croissance dans un déploiement Splunk avec StorageGRID en faisant évoluer un seul namespace jusqu'à plus de 560 po.
* *Disponibilité des données.* optimisation de la disponibilité des données, des performances, de la répartition géographique, de la conservation, de la protection, et les coûts de stockage grâce à des règles basées sur des métadonnées qui peuvent s'adapter de façon dynamique afin de rester en phase avec la valeur commerciale de vos données.


Améliorez vos performances grâce au cache SmartStore, composant de l'indexeur qui gère le transfert de copies de compartiment entre le stockage local (chaud) et le stockage distant (chaud). . La solution permet d'ajouter des ressources de calcul, de stockage à chaud ou S3 pour répondre à la demande croissante en termes de nombre d'utilisateurs ou de taux d'ingestion sur des déploiements mono et multi-sites
