---
sidebar: sidebar 
permalink: data-analytics/tr-4623-link.html 
keywords:  
summary:  
---
= Tr-4623 : systèmes NetApp E-Series E5700 et Splunk Enterprise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mitch Blackburn, NetApp

Le rapport TR-4623 décrit l'architecture intégrée de la conception des systèmes NetApp E-Series et Splunk. Optimisé pour l'équilibre du stockage entre nœuds, la fiabilité, la performance, la capacité de stockage et la densité Cette conception utilise le modèle de nœud d'index en cluster Splunk, offrant une plus grande évolutivité et un TCO réduit. En découplant le stockage des ressources de calcul, vous contribuez à l'évolutivité individuelle, ce qui réduit le coût du sur-provisionnement l'un ou l'autre. De plus, ce document récapitule les résultats des tests de performances obtenus avec un outil de simulation d'événements du journal de machine Splunk.

link:https://www.netapp.com/pdf.html?item=/media/16851-tr-4623pdf.pdf["https://www.netapp.com/pdf.html?item=/media/16851-tr-4623pdf.pdf"^]
