---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: 'La solution fournit les étapes nécessaires au déploiement d"Hyper-V sur un stockage NetApp' 
---
= Déploiement de Microsoft Hyper-V sur un système de stockage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La plate-forme Windows Server utilise le rôle Hyper-V pour fournir une technologie de virtualisation. Hyper-V est l'un des nombreux rôles facultatifs qui sont proposés avec Windows Server.



== Présentation

Le rôle Hyper-V nous permet de créer et de gérer un environnement informatique virtualisé à l'aide de la technologie de virtualisation intégrée à Windows Server. La technologie Hyper-V virtualise le matériel pour fournir un environnement dans lequel vous pouvez exécuter plusieurs systèmes d'exploitation simultanément sur un seul ordinateur physique. Hyper-V vous permet de créer et de gérer des machines virtuelles et leurs ressources. Chaque machine virtuelle est un système informatique isolé et virtualisé qui peut exécuter son propre système d'exploitation. Hyper-V fournit une infrastructure permettant de virtualiser les applications et les charges de travail qui prennent en charge divers objectifs commerciaux visant à améliorer l'efficacité et à réduire les coûts, ce qui constitue une alternative parfaite à VMware® vSphere, en particulier lorsque les entreprises recherchent la coexistence de plusieurs hyperviseurs dans les conditions actuelles du marché.



== Public

Ce document décrit les procédures d'architecture et de déploiement de la configuration de cluster Hyper-V avec les systèmes NetApp ONTAP. Ce document est destiné aux ingénieurs commerciaux, aux consultants de terrain, aux services professionnels, aux responsables INFORMATIQUES, aux ingénieurs partenaires, et aux clients qui souhaitent déployer Hyper-V en tant qu'hyperviseur principal ou secondaire.



== Architecture

L'architecture décrite dans ce document inclut spécifiquement la virtualisation Microsoft® Windows Server® 2022 et Hyper-V®. Dans le cadre de chaque déploiement, NetApp recommande vivement le logiciel de virtualisation et le logiciel de gestion de l'infrastructure. La configuration utilise les meilleures pratiques pour chaque composant afin de mettre en place une infrastructure fiable de niveau entreprise.



== Récapitulatif des cas d'utilisation

Ce document décrit les procédures de déploiement et les meilleures pratiques à suivre pour configurer un cluster Hyper-V de manière optimale en tant que charge de travail sur Microsoft Windows Server 2022 à l'aide des modèles de baies FAS et ASA 100 % Flash de NetApp. Le système d'exploitation/hyperviseur du serveur est Microsoft Windows Server 2022. Les recommandations portent sur les systèmes de stockage NetApp qui fournissent des données via les protocoles SAN et NAS.
