---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy-conclusion.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization 
summary: 'La solution fournit les étapes nécessaires au déploiement d"Hyper-V sur un stockage NetApp' 
---
= Déploiement de Microsoft Hyper-V sur un système de stockage NetApp : conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP est la base de stockage partagé optimale pour déployer de nombreuses charges de travail IT. Les plateformes ONTAP AFF ou ASA sont à la fois flexibles et évolutives pour de nombreuses utilisations et applications. Windows Server 2022 et Hyper-V sont souvent utilisés comme solution de virtualisation, décrite dans ce document. La flexibilité et l'évolutivité du stockage ONTAP et des fonctionnalités associées permettent aux clients de démarrer avec une couche de stockage correctement dimensionnée, capable d'évoluer et de s'adapter à leurs besoins. Dans les conditions actuelles du marché, Hyper-V propose une alternative idéale à l'hyperviseur, qui offre la plupart des fonctionnalités fournies par VMware.
