---
sidebar: sidebar 
permalink: legal-notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc. 
---
= Mentions légales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc.



== Droits d'auteur

http://www.netapp.com/us/legal/copyright.aspx[]



== Marques déposées

NetApp, le logo NETAPP et les marques mentionnées sur la page des marques commerciales NetApp sont des marques commerciales de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques commerciales de leurs propriétaires respectifs.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Brevets

Vous trouverez une liste actuelle des brevets appartenant à NetApp à l'adresse suivante :

https://www.netapp.com/us/media/patents-page.pdf[]



== Politique de confidentialité

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Source ouverte

Les fichiers de notification fournissent des informations sur les droits d'auteur et les licences de tiers utilisés dans le logiciel NetApp.
---
permalink: legal-notices.html
encadré : encadré
mots-clés :
résumé :
---



= Mentions légales

[role="lead"]
Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc.



== Droits d'auteur

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marques déposées

NetApp, le logo NETAPP et les marques mentionnées sur la page des marques commerciales NetApp sont des marques commerciales de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques commerciales de leurs propriétaires respectifs.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Brevets

Vous trouverez une liste actuelle des brevets appartenant à NetApp à l'adresse suivante :

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Politique de confidentialité

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Source ouverte

Les fichiers de notification fournissent des informations sur les droits d'auteur et les licences de tiers utilisés dans le logiciel NetApp.
