---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions.zip
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation des solutions NetApp
    url: index.html
  - section: ai
  - section: data-analytics
  - section: cloud
  - section: virtualization
  - section: containers
  - section: databases
  - section: data-access
  - section: automation
  - title: SAP HANA
    url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - title: Les solutions FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Journal des modifications
    url: change-log-display.html
  - title: À propos des solutions NetApp
    url: about.html
  - title: Mentions légales
    url: "/legal-notices.html"
