---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de
sidebar:
  entries:
  - title: Documentation des solutions NetApp
    url: "/index.html"
  - section: ai
  - section: containers
  - section: data-access
  - title: Les applications d'entreprise
    entries:
    - title: SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: virtualization
  - section: automation
  - title: Les solutions FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Solutions NetApp HCI existantes
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Journal des modifications
    url: "/change-log-display.html"
  - title: À propos des solutions NetApp
    url: "/about.html"
  - title: Mentions légales
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Introduction
    links:
    - title: À propos de ce référentiel
      url: about.html
    - title: Modifier l'historique
      url: change-log-display.html
    - title: Blogs
      url: blogs.html
    - title: Vidéos de démonstration
      url: videos.html
    - title: Mentions légales
      url: reference_legal_notices.html
  - title: Pages d'accueil de la solution
    links:
    - title: L'intelligence artificielle
      url: ai/index.html
    - title: Conteneurs
      url: containers/index.html
    - title: Les bases de données d'entreprise
      url: databases/index.html
    - title: Analytique moderne
      url: data-analytics/index.html
    - title: Multicloud hybride NetApp avec VMware
      url: ehc/index.html
    - title: SAP ET SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/index.html
    - title: Virtualisation
      url: virtualization/index.html
  - title: Automatisation de la solution
    links:
    - title: Introduction
      url: automation/automation_introduction.html
    - title: Mise en route
      url: automation/getting-started.html
    - title: Automatisation des demandes
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: FlexPod - une solution NetApp Cisco
    links:
    - title: Contenu technique Solutions FlexPod
      url: https://docs.netapp.com/us-en/flexpod/
    - title: Page de vente FlexPod
      url: https://flexpod.com
    - title: Vidéos et démonstrations
      url: https://tv.netapp.com/search?q=flexpod
    - title: Blogs
      url: https://blog.netapp.com/tag/FlexPod/
  - title: Commentaires
    links:
    - title: Proposer une nouvelle solution
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: Fournir des commentaires sur la solution
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
