---
sidebar: sidebar 
permalink: videos.html 
summary: Série de vidéos et démonstrations montrant les fonctionnalités de nombreuses solutions NetApp 
keywords: netapp, solutions, videos, demos 
---
= Solutions NetApp : vidéos et démonstrations
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
Présentation des vidéos et des démonstrations illustrant les fonctionnalités spécifiques des nombreuses solutions NetApp.

.L'intelligence artificielle (IA) et l'analytique moderne
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["Solutions NetApp d'IA"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps"^]


====
.Les bases de données et les applications d'entreprise
[#db%collapsible]
====
[Souligné]#*vidéos pour bases de données open source*#

[cols="5a, 5a, 5a"]
|===


 a| 
Déploiement automatisé PostgreSQL, configuration de la réplication haute disponibilité/reprise après incident, basculement, resynchronisation

 a| 
 a| 

|===
[Souligné]#*vidéos pour la modernisation d'Oracle avec le cloud hybride dans AWS et FSX*#

[cols="5a, 5a, 5a"]
|===


 a| 
Partie 1 : cas d'utilisation et architecture de la solution

 a| 
Partie 2a – migration des bases de données depuis les environnements sur site vers AWS grâce à la relocalisation automatisée de l'infrastructure de distribution des données avec une disponibilité maximale

 a| 
2b : migration de base de données sur site vers AWS en utilisant la console BlueXP via SnapMirror




 a| 
Partie 3 - Configuration automatisée de la réplication haute disponibilité/reprise après incident des bases de données, basculement, resynchronisation

 a| 
Partie 4a : clone de base de données pour les opérations de développement/test avec l'interface utilisateur SnapCenter à partir de la copie de secours répliquée

 a| 
Partie 4b : sauvegarde, restauration de base de données et clonage avec l'interface utilisateur SnapCenter




 a| 
4e partie : sauvegarde de base de données, restauration avec sauvegarde et restauration des applications SaaS BlueXP

 a| 
 a| 

|===
[Souligné]#*vidéos pour base de données SQL Server*#

[cols="5a, 5a, 5a"]
|===


 a| 
Déploiement de SQL Server sur AWS EC2 à l'aide d'Amazon FSX pour NetApp ONTAP

 a| 
Clonage de base de données enfichable mutualisé Oracle à l'aide des snapshots de stockage

video::krzMWjrrMb0[youtube,width=360] a| 
Déploiement automatisé d'Oracle 19c RAC sur FlexPod avec Ansible

video::VcQMJIRzhoY[youtube,width=360]
|===
*Étude de cas*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["SAP sur Azure NetApp Files"^]


====
.Multicloud hybride (HMC)
[#hmc%collapsible]
====
[Souligné]#*vidéos pour AWS/VMC*#

[cols="5a, 5a, 5a"]
|===


 a| 
Stockage connecté à un invité Windows avec ONTAP FSX utilisant iSCSI

 a| 
Stockage connecté par un invité Linux avec FSX ONTAP à l'aide de NFS

 a| 
Économies en termes de coût total de possession de VMware Cloud sur AWS avec Amazon FSX pour NetApp ONTAP




 a| 
VMware Cloud sur AWS datastore supplémentaire avec Amazon FSX pour NetApp ONTAP

 a| 
Déploiement et configuration de VMware HCX pour VMC

 a| 
Démonstration de la migration VMotion avec VMware HCX pour VMC et FSxN




 a| 
Démonstration de la migration à froid avec VMware HCX pour VMC et FSxN

 a| 
 a| 

|===
[Souligné]#*vidéos pour Azure/AVS*#

[cols="5a, 5a, 5a"]
|===


 a| 
Solution Azure VMware datastore supplémentaire avec Azure NetApp Files

 a| 
Solution de reprise après incident Azure VMware avec Cloud Volumes ONTAP, SnapCenter et JetStream

 a| 
Démonstration de la migration à froid avec VMware HCX pour AVS et ANF




 a| 
Démonstration de VMotion avec VMware HCX pour AVS et ANF

 a| 
Démonstration de la migration en bloc avec VMware HCX pour AVS et ANF

 a| 

|===
====
.Multicloud hybride avec Red Hat OpenShift
[#rhhc%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Reprise d'activité ROSA à l'aide d'Astra Control Service

 a| 
Intégration de FSxN avec Astra Trident

 a| 
Basculement et retour arrière des applications SUR ROSA avec FSxN




 a| 
Reprise d'activité à l'aide d'Astra Control Center

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["Regarder sur NetAppTV"]
 a| 
 a| 

|===
====
.Virtualisation
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["Collection de vidéos VMware"]


====
.Conteneurs/Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["Vidéos NetApp pour Anthos de Google"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["Vidéos NetApp avec VMware Tanzu"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["Vidéos NetApp pour le DevOps"]
* link:containers/rh-os-n_videos_and_demos.html["Vidéos NetApp avec Red Hat OpenShift"]


====
.Automatisation de la solution
[#automation%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Déploiement automatisé d'Oracle 19c RAC sur FlexPod avec Ansible

video::VcQMJIRzhoY[youtube,width=360] a| 
 a| 

|===
====