---
sidebar: sidebar 
permalink: ehc/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Fonctionnalités NetApp pour AWS VMC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En savoir plus sur les fonctionnalités que NetApp propose à AWS VMware Cloud (VMC) : de NetApp en tant que système de stockage connecté à l'invité ou un datastore NFS supplémentaire pour migrer les flux de travail, étendre/bursting sur le cloud, la sauvegarde/restauration et la reprise après incident.

Passez directement à la section du contenu souhaité en sélectionnant l'une des options suivantes :

* link:#config["Configuration de VMC dans AWS"]
* link:#datastore["Options de stockage NetApp pour VMC"]
* link:#solutions["Solutions clouds NetApp/VMware"]




== Configuration de VMC dans AWS

Comme sur site, il est essentiel de planifier un environnement de virtualisation basé sur le cloud pour créer des machines virtuelles et migrer vers un environnement prêt pour la production.

Cette section décrit comment configurer et gérer VMware Cloud sur AWS SDDC et l'utiliser en association avec les options de connexion de stockage NetApp disponibles.


NOTE: Le stockage invité est la seule méthode prise en charge pour connecter Cloud Volumes ONTAP à AWS VMC.

Le processus de configuration peut être divisé en plusieurs étapes :

* Déploiement et configuration de VMware Cloud pour AWS
* Connectez le cloud VMware à FSX ONTAP


Afficher les détails link:aws-setup.html["Étapes de configuration pour VMC"].



== Options de stockage NetApp pour VMC

Le stockage NetApp peut être utilisé de plusieurs façons - soit en tant que connexion soit en tant que datastore NFS supplémentaire - dans AWS VMC.

Visitez le site link:ehc-support-configs.html["Options de stockage NetApp prises en charge"] pour en savoir plus.

AWS prend en charge le stockage NetApp dans les configurations suivantes :

* FSX ONTAP en tant que stockage invité connecté
* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* FSX ONTAP en tant que datastore NFS supplémentaire


Afficher les détails link:aws-guest.html["Options de stockage à connexion invité pour VMC"]. Afficher les détails link:aws-native-nfs-datastore-option.html["Options supplémentaires des datastores NFS pour VMC"].



== Cas d'utilisation de la solution

Avec les solutions clouds NetApp et VMware, vous pouvez facilement déployer de nombreux cas d'utilisation dans votre système AWS VMC. Des cas d'utilisation sont définis pour chaque domaine de cloud défini par VMware :

* Protection (inclut la reprise après incident et la sauvegarde/restauration)
* Extension
* Migrer


link:aws-solutions.html["Découvrez les solutions NetApp pour AWS VMC"]
