---
sidebar: sidebar 
permalink: ehc/aws-storage-options.html 
keywords: aws, netapp, fsxn, storage, options, nfs, supplemental, cvo 
summary: Le stockage NetApp peut être attaché au service Azure VMware en tant que stockage invité ou supplémentaire. 
---
= Amazon Web Services : options d'utilisation du stockage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le stockage NetApp peut être connecté à Amazon Web Services en tant que stockage invité ou supplémentaire.



== Amazon FSX pour NetApp ONTAP (FSX ONTAP) en tant que datastore NFS supplémentaire

Amazon FSX ONTAP offre d'excellentes options pour déployer et gérer les workloads applicatifs ainsi que les services de fichiers, tout en réduisant le coût total de possession en rendant les besoins en données transparents pour la couche applicative. Quel que soit le cas d'usage, choisissez VMware Cloud on AWS avec Amazon FSX ONTAP pour bénéficier rapidement des avantages du cloud, d'une infrastructure cohérente et des opérations sur site vers AWS, de la portabilité bidirectionnelle des workloads, ainsi que d'une capacité et d'une performance haute performance. Il s'agit du même processus et des mêmes procédures que ceux utilisés pour connecter le stockage.

Pour plus d'informations, rendez-vous sur :

* link:aws-native-overview.html["FSX ONTAP en tant que datastore NFS supplémentaire : présentation"]
* link:aws-native-nfs-datastore-option.html["Amazon FSX pour ONTAP en tant que datastore supplémentaire"]




== Amazon FSX pour NetApp ONTAP en tant que stockage invité connecté

Amazon FSX ONTAP est un service entièrement géré qui offre un stockage de fichiers extrêmement fiable, évolutif, haute performance et riche en fonctionnalités, basé sur le célèbre système de fichiers ONTAP de NetApp. FSX ONTAP combine les fonctionnalités, les performances, les capacités et les opérations d'API familières des systèmes de fichiers NetApp avec l'agilité, l'évolutivité et la simplicité d'un service AWS entièrement géré.

FSX ONTAP offre un stockage de fichiers partagés riche en fonctionnalités, rapide et flexible, largement accessible depuis les instances de calcul Linux, Windows et MacOS exécutées dans AWS ou sur site. FSX ONTAP offre un stockage SSD haute performance avec une latence inférieure à la milliseconde. Avec FSX ONTAP, vous pouvez atteindre des niveaux de performances SSD pour votre workload tout en payant un stockage SSD pour une petite fraction de vos données.

La gestion de vos données avec FSX ONTAP est plus simple, car vous pouvez créer des copies Snapshot, cloner et répliquer vos fichiers en un seul clic. De plus, FSX ONTAP hiérarchise automatiquement vos données pour obtenir un stockage élastique à moindre coût, réduisant ainsi le besoin de provisionner ou de gérer la capacité.

FSX ONTAP fournit également un stockage hautement disponible et durable avec des sauvegardes entièrement gérées et la prise en charge de la reprise d'activité entre les régions. Pour simplifier la protection et la sécurité de vos données, FSX ONTAP prend en charge les applications courantes de sécurité des données et antivirus.

Pour plus d'informations, rendez-vous sur le site link:aws-guest.html#fsx-ontap["FSX ONTAP en tant que stockage connecté à l'invité"]



== Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité

Cloud Volumes ONTAP, ou CVO, est la solution de gestion des données cloud leader qui repose sur le logiciel de stockage ONTAP de NetApp, disponible de façon native dans Amazon Web Services (AWS), Microsoft Azure et Google Cloud Platform (GCP).

Il s'agit d'une version Software-defined de ONTAP qui utilise le stockage cloud natif. Vous pouvez ainsi utiliser le même logiciel de stockage dans le cloud et sur site, limitant ainsi la nécessité de former à nouveau votre personnel IT à des méthodes entièrement nouvelles de gestion des données.

Ce logiciel permet au client de déplacer des données de la périphérie, vers le data Center, puis vers le cloud, et inversement, en réunissant votre cloud hybride, le tout géré à l'aide d'une console de gestion centralisée, NetApp Cloud Manager.

Grâce à sa conception, CVO offre des performances extrêmes et des fonctionnalités avancées de gestion des données pour répondre aux besoins de vos applications les plus exigeantes dans le cloud.

Pour plus d'informations, veuillez visiter link:aws-guest.html#aws-cvo["CVO pour le stockage connecté à l'invité"].
