---
sidebar: sidebar 
permalink: ehc/dr-draas-overview.html 
keywords: dr, draas, bluexp, disaster recovery, vmfs datastore, nfs datastore, overview 
summary: Cette section du document décrit la configuration de la DRaaS BlueXP  pour la configuration de la reprise après incident pour les machines virtuelles VMware sur site sur un autre site désigné. 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La reprise sur incident est la priorité de tous les administrateurs VMware. Étant donné que VMware encapsule des serveurs entiers dans une série de fichiers qui composent la machine virtuelle, les administrateurs tirent parti de techniques basées sur le stockage bloc, telles que les clones, les snapshots et les répliques, pour protéger ces VM. Les baies ONTAP proposent une réplication intégrée pour le transfert des données de volume, et donc des serveurs virtuels résidant sur les LUN de datastore désignées, d'un site à un autre. La DRaaS de BlueXP  s'intègre à vSphere et automatise l'ensemble du workflow pour un basculement et un retour arrière transparents en cas d'incident. En associant la réplication du stockage à une automatisation intelligente, les administrateurs disposent désormais d'un moyen simple de configurer, d'automatiser et de tester les plans de reprise après incident, mais aussi de les exécuter facilement en cas d'incident.

Le basculement de reprise après incident dans un environnement VMware vSphere prend le plus de temps en exécutant les étapes nécessaires pour inventorier, enregistrer, reconfigurer et mettre sous tension les machines virtuelles sur le site de reprise après incident. La solution idéale présente à la fois un RPO faible (mesuré en minutes) et un RTO faible (mesuré en minutes, voire en heures). Il est souvent négligé dans une solution de reprise sur incident car elle permet de tester efficacement la solution de reprise sur incident à intervalles réguliers.

Facteurs à prendre en compte pour concevoir une solution de reprise d'activité :

* L'objectif de délai de restauration (RTO). L'objectif de délai de restauration est la rapidité avec laquelle une entreprise peut se remettre d'un incident, ou plus particulièrement le temps nécessaire à l'exécution du processus de restauration pour assurer la disponibilité des services de l'entreprise.
* L'objectif de point de récupération (RPO). L'objectif de point de récupération est l'âge à partir duquel les données restaurées ont été mises à disposition, par rapport à l'heure à laquelle l'incident s'est produit.
* Évolutivité et adaptabilité. Ce facteur permet d'accroître les ressources de stockage progressivement en fonction de la demande.


Pour plus d'informations techniques sur les solutions disponibles, consultez :

* link:dr-draas-nfs.html["Reprise après incident à l'aide de la DRaaS BlueXP  pour les datastores NFS"]
* link:dr-draas-vmfs.html["Reprise après incident à l'aide de la DRaaS BlueXP  pour les datastores VMFS"]

