---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= Cas d'utilisation de l'environnement multicloud hybride NetApp avec VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Présentation des cas d'utilisation importants pour les ÉQUIPES IT lors de la planification de déploiements de cloud hybride ou premier cloud.



== Cas d'utilisation populaires

Cas d'utilisation :

* Reprise sur incident,
* Hébergement de charges de travail pendant la maintenance du data Center, * rafale rapide dans laquelle des ressources supplémentaires sont requises au-delà de ce qui est provisionné dans le data Center local,
* L'extension de site VMware,
* Migration rapide vers le cloud,
* Développement/test et
* La modernisation des applications en tirant parti de technologies complémentaires du cloud.


Dans cette documentation, les références aux charges de travail cloud seront détaillées dans les cas d'utilisation de VMware. Ces utilisations sont les suivantes :

* Protection (inclut la reprise après incident et la sauvegarde/restauration)
* Migrer
* Extension




=== Inside ® le parcours DE L'IT

La plupart des entreprises sont en voie de transformation et de modernisation. Dans le cadre de ce processus, les entreprises tentent d'utiliser leurs investissements VMware existants, tout en tirant parti des avantages du cloud et en explorant les façons de rendre le processus de migration aussi transparent que possible. Cette approche facilite grandement la tâche de modernisation, car les données sont déjà dans le cloud.

La réponse la plus simple à ce scénario est d'utiliser des offres VMware pour chaque hyperscaler. Comme NetApp® Cloud volumes, VMware offre un moyen de déplacer ou d'étendre les environnements VMware sur site vers n'importe quel cloud. Vous pouvez ainsi conserver vos ressources, compétences et outils sur site existants tout en exécutant les charges de travail de façon native dans le cloud. Les risques sont réduits, car aucun service n'est disponible ni modifié IP. De plus, l'équipe INFORMATIQUE est en mesure de gérer ses pratiques sur site à l'aide des compétences et des outils existants. Cela permet d'accélérer les migrations vers le cloud et de faciliter la transition vers une architecture multicloud hybride.



=== Comprendre l'importance d'autres options de stockage NFS

Même si VMware quel que soit le cloud offre des fonctionnalités hybrides uniques à chaque client, les options de stockage NFS supplémentaires limitées ne sont pas utiles pour les entreprises qui traite de charges de travail très exigeantes en termes de stockage. Comme le stockage est directement lié aux hôtes, le seul moyen de faire évoluer le stockage consiste à ajouter d'autres hôtes, ce qui représente une augmentation des coûts de 35 à 40 % ou plus pour les charges de travail consommatrices de stockage. Ces charges de travail ont simplement besoin d'espace de stockage supplémentaire et ne sont pas de puissance supplémentaire. Mais cela signifie que les hôtes supplémentaires sont payants.

Examinons ce scénario :

Un client ne requiert que cinq hôtes pour le processeur et la mémoire, mais ses besoins en stockage sont nombreux et doit disposer de 12 hôtes pour répondre aux besoins en stockage. En fin de compte, il est indispensable de faire évoluer l'infrastructure financière en achetant de la puissance supplémentaire si nécessaire.

Lorsque vous planifiez l'adoption et les migrations du Cloud, il est toujours important d'évaluer la meilleure approche et de prendre le chemin le plus simple qui réduit les investissements totaux. L'approche la plus courante et la plus simple pour toute migration d'applications est le réhébergement (aussi appelé lift and shift) où il n'existe pas de machine virtuelle (VM) ou de conversion des données. L'utilisation de NetApp Cloud volumes avec le Software-Defined Data Center VMware (SDDC), tout en complétant VSAN, offre une option facile à déplacer.
