---
sidebar: sidebar 
permalink: ehc/ehc-solutions.html 
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst 
summary:  
---
= Solutions NetApp pour les fournisseurs de cloud hyperscale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En savoir plus sur les solutions qui font appel à NetApp pour l'environnement VMware de chacun des hyperscalers : migration des workflows, extension/bursting vers le cloud, sauvegarde/restauration et reprise après incident.



== Solutions NetApp pour les environnements VMware

Que vous utilisiez un modèle de cloud hybride ou « Cloud First », NetApp propose une large gamme de solutions pour prendre en charge les cas d'utilisation les plus courants pour gérer les charges de travail dans un modèle de cloud ou de cloud hybride.

NetApp propose également des solutions pour le stockage provisionné en tant que stockage invité (connecté à l'invité) ou en tant que datastore NFS supplémentaire dans chacun des hyperscalers. Toutes les solutions sont classées en plusieurs catégories avec la classification VMware des charges de travail cloud. Ces classifications comprennent :

* Protection (inclut la reprise après incident et la sauvegarde/restauration)
* Migrer
* Extension


Pour plus d'informations sur les solutions disponibles pour chaque hyperscaler, consultez la page :

* link:aws-solutions.html["Solutions pour AWS/VMC"]
* link:azure-solutions.html["Solutions pour Azure/AVS"]
* link:gcp-solutions.html["Solutions pour GCP/GCVE"]

