---
sidebar: sidebar 
permalink: ehc/ehc-config-vmware-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration 
summary:  
---
= Configuration de l'environnement de virtualisation dans le fournisseur cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous trouverez plus d'informations sur la configuration de l'environnement de virtualisation dans chacun des hyperscalers pris en charge.

[role="tabbed-block"]
====
.AWS/VMC
--
Cette section décrit comment configurer et gérer VMware Cloud sur AWS SDDC et l'utiliser en association avec les options de connexion de stockage NetApp disponibles.


NOTE: Le stockage invité est la seule méthode prise en charge pour connecter Cloud Volumes ONTAP à AWS VMC.

Le processus de configuration peut être divisé en plusieurs étapes :

* Déploiement et configuration de VMware Cloud pour AWS
* Connectez le cloud VMware à FSX ONTAP


Afficher les détails link:aws-setup.html["Étapes de configuration pour VMC"].

--
.Azure/AVS
--
Cette section décrit comment configurer et gérer Azure VMware solution et l'utiliser en association avec les options disponibles pour connecter le stockage NetApp.


NOTE: Le stockage In-guest est la seule méthode prise en charge de connexion de Cloud Volumes ONTAP à Azure VMware solution.

Le processus de configuration peut être divisé en plusieurs étapes :

* Enregistrez le fournisseur de ressources et créez un cloud privé
* Connectez-vous à une passerelle réseau virtuelle ExpressRoute nouvelle ou existante
* Validation de la connectivité réseau et accès au cloud privé


Afficher les détails link:azure-setup.html["Étapes de configuration de AVS"].

--
.GCP/GCVE
--
Cette section décrit comment configurer et gérer GCVE et l'utiliser en association avec les options disponibles pour la connexion du stockage NetApp.


NOTE: Le stockage « en invité » est la seule méthode prise en charge pour connecter Cloud Volumes ONTAP et Cloud volumes Services à GCVE.

Le processus de configuration peut être divisé en plusieurs étapes :

* Déployer et configurer GCVE
* Activez l'accès privé à GCVE


Afficher les détails link:gcp-setup.html["Étapes de configuration pour GCVE"].

--
====