---
sidebar: sidebar 
permalink: ehc/ehc-summary.html 
keywords: NetApp Solutions, hybrid, Multicloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= Synthèse et conclusion : pourquoi NetApp offre un multicloud hybride avec VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Cloud volumes et les solutions VMware pour les principaux hyperscalers offrent un grand potentiel aux entreprises qui cherchent à exploiter le cloud hybride. Le reste de cette section présente des cas d'utilisation permettant l'intégration de NetApp Cloud volumes offre de véritables fonctionnalités multicloud hybrides.



== Cas d'utilisation n° 1 : optimisation du stockage

Lors d'un exercice de dimensionnement à l'aide des outils RVTools, il est toujours évident que l'évolutivité de la puissance (vCPU/vmem) est parallèle au stockage. Elles sont souvent nombreuses à se retrouver dans une situation où l'espace de stockage nécessaire permet de définir la taille du cluster bien au-delà de ce qui est nécessaire en puissance.

L'intégration de NetApp Cloud volumes permet aux entreprises de réaliser une solution cloud vSphere selon une approche de migration simple, sans changement de plateforme, ni modification de l'architecture. De plus, cette optimisation vous permet de faire évoluer l'empreinte du stockage tout en réduisant le nombre d'hôtes à un volume minimal dans vSphere, sans modification de la hiérarchie de stockage, de la sécurité ou des fichiers disponibles. Vous pouvez ainsi optimiser le déploiement et réduire le coût total de possession de 35 à 45 %. Cette intégration vous permet également de faire évoluer le stockage depuis le stockage chaud jusqu'au niveau de production en quelques secondes.



== Cas d'utilisation n°2 : migration vers le cloud

Les entreprises subissent une pression considérable pour migrer les applications depuis les data centers sur site vers le cloud public pour de nombreuses raisons : une expiration de bail imminente, une directive financière pour passer des dépenses d'investissement aux dépenses d'exploitation (OpEx) ou simplement un mandat descendante pour déplacer l'ensemble du cloud.

Lorsque la vitesse est essentielle, seule une approche de migration rationalisée est possible, car le changement de plateforme et le remaniement d'applications pour l'adapter à la plateforme IaaS spécifique au cloud sont lents et onéreux, et prennent souvent des mois. En associant NetApp Cloud volumes à la réplication SnapMirror économe en bande passante pour les systèmes de stockage connectés à l'invité (dont RDM avec des copies Snapshot cohérentes au niveau des applications et HCX, par exemple, pour la migration vers le cloud Azure Migrate) ou produits tiers pour la réplication des machines virtuelles), cette transition est encore plus simple que s'appuyant sur des mécanismes de filtres d'E/S chronophages.



== Cas d'utilisation n°3 : extension du data Center

Lorsqu'un data Center atteint ses limites de capacité en raison de pics de demande saisonniers ou simplement d'une croissance organique soutenue, il est facile de migrer vers le cloud VMware avec NetApp Cloud volumes. En exploitant NetApp Cloud volumes, vous pouvez créer, répliquer et étendre votre stockage très facilement en assurant une haute disponibilité sur les zones de disponibilité et des fonctionnalités d'évolutivité dynamique. En exploitant NetApp Cloud volumes, vous pouvez minimiser la capacité des clusters hôtes en surpassant la nécessité de clusters étendus.



== Cas d'utilisation n°4 : reprise après incident dans le cloud

Dans une approche classique, en cas d'incident, les machines virtuelles répliquées dans le cloud nécessitent une conversion vers la propre plateforme d'hyperviseur du cloud avant qu'elles ne puissent être restaurées, pas une tâche à traiter en cas de crise.

L'utilisation de NetApp Cloud volumes pour le stockage connecté à l'invité via la réplication SnapCenter et SnapMirror depuis des systèmes sur site ainsi que des solutions de virtualisation de cloud public améliore la reprise d'activité. De cette manière, les réplicas de VM peuvent être récupérés sur une infrastructure VMware SDDC entièrement cohérente, ainsi que sur des outils de restauration spécifiques au cloud (par exemple Azure site Recovery) ou des outils tiers équivalents tels que Veeam. Ainsi, vous pouvez réaliser rapidement des tests de reprise après incident et des opérations de reprise après incident en cas d'attaque par ransomware. Cela vous permet également d'évoluer vers une production complète à des fins de test ou lors d'un incident en ajoutant des hôtes à la demande.



== Cas d'utilisation n°5 : modernisation des applications

Une fois que les applications sont dans le cloud public, les entreprises voudront exploiter des centaines de services cloud puissants pour les moderniser et les étendre. Avec NetApp Cloud volumes, la modernisation est un processus simple, car les données applicatives ne sont pas verrouillées dans VSAN et permet la mobilité des données pour un large éventail d'utilisations, y compris Kubernetes.



== Conclusion

Que vous cibliez un cloud hybride ou 100 % cloud, NetApp Cloud volumes offre une excellente option pour déployer et gérer les charges de travail applicatives avec les services de fichiers et les protocoles de bloc, tout en réduisant le coût total de possession grâce à une intégration transparente des données à la couche applicative.

Quelles que soient les utilisations, vous pouvez choisir votre cloud/hyperscaler favori et NetApp Cloud volumes pour bénéficier rapidement des avantages du cloud, d'une infrastructure cohérente et des opérations entre plusieurs clouds et sur site, de la portabilité bidirectionnelle des workloads, et de la capacité et des performances élevées.

Il s'agit du même processus et procédures que ceux utilisés pour connecter le stockage. N'oubliez pas que la position des données a changé de nom. Les outils et les processus restent identiques, et NetApp Cloud volumes contribue à optimiser le déploiement global.
