---
sidebar: sidebar 
permalink: ehc/evs-mount-fsxn-conclusion.html 
keywords: Amazon, AWS, EVS, Elastic VMware Service, ONTAP, FSx 
summary: Cet article fournit des instructions sur la façon de configurer FSx pour ONTAP en tant que stockage externe pour Amazon EVS pour une utilisation avec les protocoles NFS et iSCSI. 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce document fournit des instructions sur la façon de configurer FSx pour ONTAP en tant que stockage externe pour Amazon EVS pour une utilisation avec les protocoles NFS et iSCSI.

Utiliser FSx for ONTAP comme stockage externe pour Amazon EVS offre des avantages opérationnels et commerciaux évidents. Il améliore la résilience, la protection, la réplication et la rentabilité des données grâce à la technologie ONTAP, et optimise le coût total de possession grâce au découplage de l'architecture hyperconvergée VMware. Avec FSx for ONTAP, les utilisateurs d'Amazon EVS peuvent faire évoluer leur stockage sans ajouter de ressources de calcul ni augmenter leurs coûts. Cela ouvre ainsi tout le potentiel d'élasticité et d'évolutivité du cloud AWS.

Pour en savoir plus, lisez l'annonce des nouveautés d'Amazon : link:https://aws.amazon.com/about-aws/whats-new/2025/06/amazon-elastic-vmware-service-fsx-netapp-ontap/["Amazon EVS s'intègre désormais à FSx pour ONTAP"] , et le blog NetApp : link:https://www.netapp.com/blog/amazon-elastic-vmware-service-fsx-ontap/["Amazon EVS annonce la prise en charge de FSx pour ONTAP"] .
