---
sidebar: sidebar 
permalink: ehc/gcp-storage-options.html 
keywords: gcp, gcve, gcnv, nfs, supplemental, datastore, vcenter, vmware, cvo, storage, options 
summary: Le stockage NetApp peut être connecté au moteur de virtualisation Google Cloud en tant que stockage invité ou supplémentaire. 
---
= Google Cloud VMware Engine : options d'utilisation du stockage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le stockage NetApp peut être connecté au moteur de virtualisation Google Cloud en tant que stockage invité ou supplémentaire.



== Google Cloud NetApp volumes (NetApp volumes) en tant que datastore NFS supplémentaire

Les clients qui ont besoin de capacité de stockage supplémentaire dans leur environnement Google Cloud VMware Engine (GCVE) peuvent utiliser Google Cloud NetApp volumes pour le montage en tant que datastore NFS supplémentaire. Stocker les données sur Google Cloud NetApp volumes permet aux clients de répliquer entre différentes régions pour les protéger contre les diaaster.

Pour plus d'informations, rendez-vous sur le site link:gcp-ncvs-datastore.html["Google Cloud NetApp volumes (NetApp volumes) en tant que datastore NFS supplémentaire"]



== NetApp CVO comme stockage connecté en invité

Cloud Volumes ONTAP, ou CVO, est la solution de gestion des données cloud leader qui repose sur le logiciel de stockage ONTAP de NetApp, disponible de façon native dans Amazon Web Services (AWS), Microsoft Azure et Google Cloud Platform (GCP).

Il s'agit d'une version Software-defined de ONTAP qui utilise le stockage cloud natif. Vous pouvez ainsi utiliser le même logiciel de stockage dans le cloud et sur site, limitant ainsi la nécessité de former à nouveau votre personnel IT à des méthodes entièrement nouvelles de gestion des données.

Ce logiciel permet au client de déplacer des données de la périphérie, vers le data Center, puis vers le cloud, et inversement, en réunissant votre cloud hybride, le tout géré à l'aide d'une console de gestion centralisée, NetApp Cloud Manager.

Grâce à sa conception, CVO offre des performances extrêmes et des fonctionnalités avancées de gestion des données pour répondre aux besoins de vos applications les plus exigeantes dans le cloud.

Pour plus d'informations, rendez-vous sur le site link:gcp-guest.html#gcp-cvo["NetApp CVO comme stockage connecté en invité"]



== Google Cloud NetApp volumes (NetApp volumes) en tant que stockage connecté en invité

Les partages Google Cloud NetApp volumes peuvent être montés à partir des machines virtuelles créées dans l'environnement VMware Engine. Les volumes peuvent également être montés sur le client Linux et mappés sur le client Windows, car Google Cloud NetApp volumes prend en charge les protocoles SMB et NFS. La configuration des volumes Google Cloud NetApp peut s'effectuer en quelques étapes simples.

Le cloud privé Google Cloud NetApp volumes et Google Cloud VMware Engine doivent se trouver dans la même région.

Pour plus d'informations, rendez-vous sur le site link:gcp-guest.html#gcnv["Google Cloud NetApp volumes (NetApp volumes) en tant que stockage connecté en invité"]
