---
sidebar: sidebar 
permalink: ehc/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Fonctionnalités NetApp pour Google Cloud Platform GCVE
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez les fonctionnalités qu'NetApp apporte à Google Cloud Platform (GCP) Google Cloud VMware Engine (GCVE) : de NetApp en tant que périphérique de stockage connecté par l'invité ou datastore NFS supplémentaire en tant que migration des workflows, extension/bursting dans le cloud, sauvegarde/restauration et reprise après incident.

Passez directement à la section du contenu souhaité en sélectionnant l'une des options suivantes :

* link:#config["Configuration de GCVE dans GCP"]
* link:#datastore["Options de stockage NetApp pour GCVE"]
* link:#solutions["Solutions clouds NetApp/VMware"]




== Configuration de GCVE dans GCP

Comme sur site, il est essentiel de planifier un environnement de virtualisation basé sur le cloud pour créer des machines virtuelles et migrer vers un environnement prêt pour la production.

Cette section décrit comment configurer et gérer GCVE et l'utiliser en association avec les options disponibles pour la connexion du stockage NetApp.


NOTE: Le stockage invité est la seule méthode prise en charge pour connecter Cloud Volumes ONTAP et Google Cloud NetApp volumes à GCVE.

Le processus de configuration peut être divisé en plusieurs étapes :

* Déployer et configurer GCVE
* Activez l'accès privé à GCVE


Afficher les détails link:gcp-setup.html["Étapes de configuration pour GCVE"].



== Options de stockage NetApp pour GCVE

Le stockage NetApp peut être utilisé de plusieurs façons - soit en tant que connexion soit en tant que datastore NFS supplémentaire - dans GCP GCVE.

Visitez le site link:ehc-support-configs.html["Options de stockage NetApp prises en charge"] pour en savoir plus.

Google Cloud prend en charge le stockage NetApp dans les configurations suivantes :

* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* Google Cloud NetApp volumes (NetApp volumes) en tant que stockage connecté en tant qu'invité
* Google Cloud NetApp volumes (NetApp volumes) en tant que datastore NFS supplémentaire


Afficher le détail link:gcp-guest.html["Options de stockage de connexion invité pour GCVE"]. Afficher le détail link:gcp-ncvs-datastore.html["Options supplémentaires de datastore NFS pour GCVE"].

En savoir plus sur link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Prise en charge du datastore Google Cloud NetApp volumes pour Google Cloud VMware Engine (blog NetApp)"^] ou link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Comment utiliser Google Cloud NetApp volumes en tant que datastores pour Google Cloud VMware Engine (blog Google)"^]



== Cas d'utilisation de la solution

Avec les solutions cloud de NetApp et VMware, le déploiement dans Azure AVS est très simple. Des cas se sont définis pour chaque domaine cloud défini par VMware :

* Protection (inclut la reprise après incident et la sauvegarde/restauration)
* Extension
* Migrer


link:gcp-solutions.html["Découvrez les solutions NetApp pour Google Cloud GCVE"]
