---
sidebar: sidebar 
permalink: ehc/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: 'La sécurité, notamment dans le cloud où l"infrastructure ne contrôle pas les administrateurs du stockage, est primordiale pour faire confiance aux données des offres de services des fournisseurs cloud. Ce document présente les offres de sécurité de Google Cloud NetApp volumes dans Google Cloud.' 
---
= Tr-4918 : présentation de la sécurité - Google Cloud NetApp volumes dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Oliver Krause, Justin Parisi, NetApp

[role="lead"]
La sécurité, notamment dans le cloud où l'infrastructure ne contrôle pas les administrateurs du stockage, est primordiale pour faire confiance aux données des offres de services des fournisseurs cloud. Ce document présente les offres de sécurité que https://cloud.netapp.com/cloud-volumes-service-for-gcp["Google Cloud NetApp volumes est disponible dans Google Cloud"^].



== Public visé

Le public visé par ce document comprend, mais sans s'y limiter, les rôles suivants :

* Fournisseurs de cloud
* Administrateurs du stockage
* Les architectes du stockage
* Ressources sur site
* Décideurs de l'entreprise


Pour toute question sur le contenu de ce rapport technique, consultez la section link:ncvs-gc-additional-information.html#contact-us["« Contactez-nous. »"]

|===
| Abréviation | Définition 


| NetApp volumes-logiciel | Google Cloud NetApp volumes, Type de service NetApp volumes 


| Performances de NetApp volumes | Cloud volumes Service, Type de service NetApp volumes-Performance 


| PSA |  
|===