---
sidebar: sidebar 
permalink: ehc/ncvs-gc-basics-of-nas-protocols.html 
keywords: nas, basics, gcp, nfs, smb 
summary: 'Les protocoles NAS permettent à plusieurs clients sur un réseau d"accéder aux mêmes données sur un système de stockage, notamment Cloud Volumes Service sur GCP. NFS et SMB sont les protocoles NAS définis et fonctionnent sur une base client/serveur où Cloud Volumes Service fait office de serveur.' 
---
= Notions de base sur les protocoles NAS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les protocoles NAS permettent à plusieurs clients sur un réseau d'accéder aux mêmes données sur un système de stockage, notamment Cloud Volumes Service sur GCP. NFS et SMB sont les protocoles NAS définis et fonctionnent sur une base client/serveur où Cloud Volumes Service fait office de serveur. Les clients envoient des demandes d'accès, de lecture et d'écriture au serveur, et le serveur est responsable de la coordination des mécanismes de verrouillage des fichiers, du stockage des autorisations et du traitement des demandes d'identité et d'authentification.

Par exemple, le processus général suivant est suivi si un client NAS souhaite créer un nouveau fichier dans un dossier.

. Le client demande au serveur des informations sur le répertoire (autorisations, propriétaire, groupe, ID de fichier, espace disponible, et ainsi de suite) ; le serveur répond avec les informations si le client et l'utilisateur demandeur disposent des autorisations nécessaires sur le dossier parent.
. Si les autorisations du répertoire autorisent l'accès, le client demande alors au serveur si le nom de fichier en cours de création existe déjà dans le système de fichiers. Si le nom de fichier est déjà utilisé, la création échoue. Si le nom de fichier n'existe pas, le serveur indique au client qu'il peut continuer.
. Le client envoie un appel au serveur pour créer le fichier avec le descripteur de répertoire et le nom du fichier et définit l'accès et les heures modifiées. Le serveur émet un ID de fichier unique pour s'assurer qu'aucun autre fichier n'est créé avec le même ID de fichier.
. Le client envoie un appel pour vérifier les attributs du fichier avant l'opération D'ÉCRITURE. Si les autorisations le permettent, le client écrit le nouveau fichier. Si le verrouillage est utilisé par le protocole/l'application, le client demande au serveur un verrouillage pour empêcher les autres clients d'accéder au fichier lorsqu'il est verrouillé afin d'éviter la corruption des données.

