---
sidebar: sidebar 
permalink: ehc/ncvs-gc-dual-protocol-multiprotocol.html 
keywords: access control, user mapping, permission model 
summary: 'Google Cloud NetApp volumes permet de partager les mêmes datasets avec les clients SMB et NFS tout en conservant les autorisations d"accès appropriées à un double protocole. Il coordonne le mappage des identités entre les protocoles et l"utilisation d"un serveur LDAP back-end centralisé afin de fournir les identités UNIX aux volumes Google Cloud NetApp. Vous pouvez utiliser Windows Active Directory pour fournir à la fois aux utilisateurs Windows et UNIX la facilité d"utilisation.' 
---
= Double protocole/multiprotocole
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp volumes permet de partager les mêmes datasets avec les clients SMB et NFS tout en conservant les autorisations d'accès appropriées (https://cloud.google.com/architecture/partners/netapp-cloud-volumes/managing-dual-protocol-access["double protocole"^]). Il coordonne le mappage des identités entre les protocoles et l'utilisation d'un serveur LDAP back-end centralisé afin de fournir les identités UNIX aux volumes Google Cloud NetApp. Vous pouvez utiliser Windows Active Directory pour fournir à la fois aux utilisateurs Windows et UNIX la facilité d'utilisation.



== Contrôle d'accès

* *Partager les contrôles d'accès.* Déterminez quels clients et/ou utilisateurs et groupes peuvent accéder à un partage NAS. Dans le cas de NFS, les export-policy et les règles contrôlent l'accès client aux exports. Les exportations NFS sont gérées à partir de l'instance Google Cloud NetApp volumes. SMB utilise les partages CIFS/SMB et les listes de contrôle d'accès de partage pour fournir un contrôle plus granulaire au niveau de l'utilisateur et du groupe. Vous ne pouvez configurer des listes de contrôle d'accès de niveau partage qu'à partir des clients SMB en utilisant https://library.NetApp.com/ecmdocs/ECMP1401220/html/GUID-C1772CDF-8AEE-422B-AB87-CFCB7E50FF94.html[gestion des ordinateurs/MMC^] avec un compte disposant de droits d'administrateur sur l'instance de Google Cloud NetApp volumes (voir la section comptes de sauvegarde locale/BIN/BIN).
* *Contrôles d'accès aux fichiers.* les autorisations de contrôle au niveau d'un fichier ou d'un dossier sont toujours gérées à partir du client NAS. Les clients NFS peuvent utiliser les bits de mode classiques (rwx) ou les listes de contrôle d'accès NFSv4. Les clients SMB exploitent les autorisations NTFS.


Le contrôle d'accès pour les volumes qui fournissent des données à la fois aux protocoles NFS et SMB dépend du protocole utilisé. Pour plus d'informations sur les autorisations avec double protocole, reportez-vous à la section «<<Modèle d'autorisation>>. »



== Mappage d'utilisateurs

Lorsqu'un client accède à un volume, Google Cloud NetApp volumes tente de mapper l'utilisateur entrant à un utilisateur valide dans la direction opposée. Cela est nécessaire pour que l'accès soit déterminé dans l'ensemble des protocoles et pour s'assurer que l'utilisateur qui demande l'accès est bien celui qu'il prétend être.

Par exemple, si un utilisateur Windows appelé `joe` tente d'accéder à un volume avec des autorisations UNIX via SMB, Google Cloud NetApp volumes effectue une recherche pour trouver l'utilisateur UNIX correspondant nommé `joe`. S'il en existe un, les fichiers écrits sur un partage SMB en tant qu'utilisateur Windows apparaissent en tant `joe` qu'utilisateur UNIX `joe` à partir de clients NFS.

Sinon, si un utilisateur UNIX appelé `joe` tente d'accéder à un volume Google Cloud NetApp volumes avec des autorisations Windows, l'utilisateur UNIX doit pouvoir le mapper à un utilisateur Windows valide. Dans le cas contraire, l'accès au volume est refusé.

Actuellement, seul Active Directory est pris en charge pour la gestion externe des identités UNIX avec LDAP. Pour plus d'informations sur la configuration de l'accès à ce service, reportez-vous à la section https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes["Création d'une connexion AD"^].



== Modèle d'autorisation

Lors de l'utilisation de configurations à double protocole, Google Cloud NetApp volumes utilise les styles de sécurité pour les volumes afin de déterminer le type de liste de contrôle d'accès. Ces styles de sécurité sont définis en fonction du protocole NAS spécifié, ou dans le cas d'un double protocole, il est possible de choisir lors de la création du volume Google Cloud NetApp volumes.

* Si vous utilisez uniquement NFS, les volumes Google Cloud NetApp utilisent des autorisations UNIX.
* Si vous utilisez uniquement SMB, les volumes Google Cloud NetApp utilisent des autorisations NTFS.


Si vous créez un volume à double protocole, vous pouvez choisir le style ACL lors de la création du volume. Cette décision doit être prise en fonction de la gestion des autorisations souhaitée. Si vos utilisateurs gèrent les autorisations des clients Windows/SMB, sélectionnez NTFS. Si vos utilisateurs préfèrent utiliser des clients NFS et chmod/chown, utilisez des styles de sécurité UNIX.
