---
sidebar: sidebar 
permalink: ehc/ncvs-gc-data-encryption-at-rest.html 
keywords: aes-256 encryption, cmek 
summary: 'Tous les volumes de Google Cloud NetApp volumes sont chiffrés au repos à l"aide du chiffrement AES-256. Ainsi, toutes les données utilisateur écrites sur le support sont chiffrées et ne peuvent être déchiffrées qu"à l"aide d"une clé par volume.' 
---
= Chiffrement des données au repos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Tous les volumes de Google Cloud NetApp volumes sont chiffrés au repos à l'aide du chiffrement AES-256. Ainsi, toutes les données utilisateur écrites sur le support sont chiffrées et ne peuvent être déchiffrées qu'à l'aide d'une clé par volume.

* Pour NetApp volumes-SW, les clés générées par Google sont utilisées.
* Pour NetApp volumes-Performance, les clés par volume sont stockées dans un gestionnaire de clés intégré à Google Cloud NetApp volumes.


Depuis novembre 2021, un aperçu des fonctionnalités de clés de chiffrement gérées par les clients (CMEK) a été disponible. Vous pouvez ainsi chiffrer les clés par volume avec une clé principale par projet et par région hébergée dans https://cloud.google.com/kms/docs["Google Key Management Service (KMS)."^] LES KILOMÈTRES vous permettent d'associer des gestionnaires de clés externes.

Pour plus d'informations sur la configuration de KMS pour NetApp volumes-Performance, consultezla section https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["La configuration des clés de chiffrement gérées par le client"^].
