---
sidebar: sidebar 
permalink: ehc/ncvs-gc-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Google Cloud NetApp volumes expose plusieurs ports TCP pour servir les partages NFS et SMB. 
---
= Pare-feu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp volumes expose plusieurs ports TCP pour desservir les partages NFS et SMB :

* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Ports requis pour l'accès NFS"^]
* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Ports requis pour l'accès SMB"^]


En outre, SMB, NFS avec LDAP, y compris Kerberos, et des configurations à double protocole requièrent l'accès à un domaine Windows Active Directory. Les connexions Active Directory doivent être de https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes?hl=en_US["configuré"^] par région. Les contrôleurs de domaine (DC) Active Directory sont identifiés à l'aide de https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04["Découverte de data Center basée sur DNS"^] Utilisation des serveurs DNS spécifiés. Tous les DCS renvoyés sont utilisés. La liste des DCS admissibles peut être limitée en spécifiant un site Active Directory.

Google Cloud NetApp volumes atteint ses adresses IP à partir de la plage CIDR allouée à la `gcloud compute address` commande while https://cloud.google.com/architecture/partners/netapp-cloud-volumes/setting-up-private-services-access?hl=en_US["Intégration de Google Cloud NetApp volumes"^]. Vous pouvez utiliser ce CIDR comme adresses source pour configurer les pare-feu entrants sur vos contrôleurs de domaine Active Directory.

Les contrôleurs de domaine Active Directory doivent https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Exposez les ports aux CIDR Google Cloud NetApp volumes, comme indiqué ici"^].
