---
sidebar: sidebar 
permalink: ehc/ncvs-gc-service-operation.html 
keywords: physical security, operations team, customer responsibilities, malicious sre protection, certifications, gdpr 
summary: 'L"équipe Google Cloud NetApp volumes gère les services back-end dans Google Cloud et utilise plusieurs stratégies pour sécuriser la plateforme et empêcher tout accès indésirable.' 
---
= Opération d'entretien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'équipe Google Cloud NetApp volumes gère les services back-end dans Google Cloud et utilise plusieurs stratégies pour sécuriser la plateforme et empêcher tout accès indésirable.

Chaque client obtient son propre sous-réseau unique dont l'accès est isolé des autres clients par défaut. Chaque locataire dans Google Cloud NetApp volumes bénéficie de son propre espace de noms et de son propre VLAN pour une isolation totale des données. Après l'authentification d'un utilisateur, le moteur de fourniture de services (SDE) peut uniquement lire les données de configuration spécifiques à ce locataire.



== Sécurité physique

Une fois la préapprobation adéquate obtenue, seuls les ingénieurs sur site et les ingénieurs de support de terrain (FSE) certifiés NetApp ont accès à la cage et aux racks pour les travaux physiques. La gestion du réseau et du stockage n'est pas autorisée. Seules ces ressources sur site sont en mesure d'effectuer les tâches de maintenance du matériel.

Pour les ingénieurs sur site, un ticket est émis pour l'énoncé des travaux (SOW) qui inclut l'ID de rack et l'emplacement du périphérique (RU). Toutes les autres informations sont incluses dans le ticket. Pour les FSE NetApp, un ticket de visite sur site doit être levé avec la COLOCATION. Le ticket inclut également les détails, la date et l'heure du visiteur à des fins d'audit. Le cahier des charges du FSE est communiqué à NetApp en interne.



== Équipe chargée des opérations

L'équipe des opérations pour Google Cloud NetApp volumes est composée d'ingénieurs de production et d'un ingénieur de fiabilité des sites (SRE) pour Google Cloud NetApp volumes et des ingénieurs de support sur site NetApp, ainsi que de partenaires pour le matériel. Tous les membres de l'équipe des opérations sont accrédités pour travailler dans Google Cloud et des dossiers de travail détaillés sont conservés pour chaque billet émis. De plus, un processus rigoureux de contrôle et d'approbation du changement est en place pour s'assurer que chaque décision est examinée de façon appropriée.

L'équipe de fiabilité des sites gère le plan de contrôle et le routage des données à partir des demandes de l'interface vers le matériel et les logiciels back-end dans Google Cloud NetApp volumes. L'équipe SRE gère également les ressources système, telles que les volumes et les volumes d'inode maximaux. Les SRES ne sont pas autorisés à interagir avec les données clients ou à y accéder. SRES assure également la coordination des autorisations de renvoi de matériel (RMA), telles que les demandes de remplacement de nouveau disque ou de mémoire pour le matériel interne.



== Obligations du client

Les clients de Google Cloud NetApp volumes gèrent Active Directory et les rôles d'utilisateur de leur entreprise, ainsi que les opérations de volume et de données. Les clients peuvent disposer de rôles administratifs et déléguer des autorisations à d'autres utilisateurs au sein du même projet Google Cloud à l'aide des deux rôles prédéfinis de NetApp et Google Cloud (Administrateur et Viewer).

L'administrateur peut faire passer n'importe quel VPC du projet du client vers Google Cloud NetApp volumes que le client détermine comme approprié. Il est de la responsabilité du client de gérer l'accès à son abonnement à Google Cloud Marketplace et de gérer les VPC qui ont accès au plan de données.



== Protection de SRE malveillante

Une préoccupation majeure est la manière dont Google Cloud NetApp volumes protège-t-il contre les scénarios où il existe une SRE malveillante ou lorsque des informations d'identification de fiabilité de site ont été compromises ?

L'accès à l'environnement de production n'est possible qu'avec un nombre limité de SRE particuliers. Les privilèges administratifs sont en outre limités à une poignée d'administrateurs expérimentés. Toutes les actions réalisées par n'importe qui dans l'environnement de production Google Cloud NetApp volumes sont consignées et toute anomalie relative aux activités de base ou suspectes est détectée par notre plateforme de veille sur les menaces SIEM (Security information and Event Management). Par conséquent, les actions malveillantes peuvent être suivies et atténuées avant que le système back-end Google Cloud NetApp volumes ne soit trop endommagé.



== Cycle de vie du volume

Google Cloud NetApp volumes ne gère que les objets du service, pas les données au sein des volumes. Seuls les clients qui accèdent aux volumes peuvent gérer les données, les listes de contrôle d'accès, les propriétaires de fichiers, etc. Les données de ces volumes sont chiffrées au repos et l'accès est limité aux locataires de l'instance Google Cloud NetApp volumes.

Le cycle de vie des volumes pour Google Cloud NetApp volumes est de type création, mise à jour, suppression. Les volumes conservent des copies Snapshot des volumes jusqu'à la suppression des volumes. Seuls les administrateurs de Google Cloud NetApp volumes validés peuvent supprimer des volumes dans Google Cloud NetApp volumes. Lorsqu'un administrateur demande la suppression d'un volume, une étape supplémentaire de la saisie du nom du volume est requise pour vérifier la suppression. Un volume est supprimé et ne peut plus être restauré.

Lorsque le contrat Google Cloud NetApp volumes est résilié, NetApp marque les volumes pour suppression au bout d'une période spécifique. Avant l'expiration de cette période, vous pouvez récupérer des volumes à la demande du client.



== Certifications

Google Cloud NetApp volumes pour Google Cloud est actuellement certifié ISO/IEC 27001:2013 et ISO/IEC 27018:2019. Le service a aussi récemment reçu son rapport d'attestation de type I de la SOC2. Pour plus d'informations sur l'engagement de NetApp en matière de sécurité et de confidentialité des données, reportez-vous à la section https://www.netapp.com/company/trust-center/compliance/["Conformité : sécurité et confidentialité des données"^].



== LE RGPD

Notre engagement en matière de confidentialité et de conformité avec le RGPD est disponible dans un certain nombre de nos  https://www.netapp.com/how-to-buy/sales-terms-and-conditions%22%20/o%20%22SEO%20-%20Sales%20Terms%20and%20Conditions["contrats clients"^], comme notre https://netapp.na1.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhCqPPgcufskl_71q-FelD4DHz5EMJVOkqqT0iiORT10DlfZnZeMpDrse5W6K9LEw6o*["Addenda relatif au traitement des données client"^], qui inclut le  https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en["Clauses contractuelles standard"^] Fourni par la Commission européenne. Nous prenons également ces engagements dans notre politique de confidentialité, soutenue par les valeurs fondamentales énoncées dans notre Code de conduite d'entreprise.
