---
sidebar: sidebar 
permalink: ehc/ncvs-gc-architecture_overview.html 
keywords: architecture overview, control plane, data plane 
summary: 'L"architecture et la sécurité font partie des processus de confiance aux solutions cloud. Cette section présente les différents aspects de l"architecture de Google Cloud NetApp volumes dans Google pour résoudre les problèmes potentiels sur la sécurité des données, ainsi que les domaines dans lesquels des étapes de configuration supplémentaires peuvent être nécessaires pour obtenir le déploiement le plus sécurisé.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'architecture et la sécurité font partie des processus de confiance aux solutions cloud. Cette section présente les différents aspects de l'architecture de Google Cloud NetApp volumes dans Google pour résoudre les problèmes potentiels sur la sécurité des données, ainsi que les domaines dans lesquels des étapes de configuration supplémentaires peuvent être nécessaires pour obtenir le déploiement le plus sécurisé.

L'architecture générale de Google Cloud NetApp volumes peut être décomposée en deux composants principaux : le plan de contrôle et le plan de données.



== Plan de contrôle

Le plan de contrôle dans Google Cloud NetApp volumes constitue l'infrastructure back-end gérée par les administrateurs de Google Cloud NetApp volumes et le logiciel d'automatisation natif NetApp. Ce plan est totalement transparent pour les utilisateurs finaux et inclut la mise en réseau, le matériel de stockage, les mises à jour logicielles, etc. Pour aider à valoriser une solution résidant dans le cloud comme Google Cloud NetApp volumes.



== Plan de données

Le plan de données dans Google Cloud NetApp volumes inclut les volumes de données réels et la configuration globale de Google Cloud NetApp volumes (contrôle d'accès, authentification Kerberos, etc.). Le plan de données est entièrement sous le contrôle des utilisateurs finaux et des consommateurs de la plateforme Google Cloud NetApp volumes.

La façon dont chaque plan est sécurisé et géré est différente. Les sections suivantes présentent ces différences, à commencer par une présentation de l'architecture de Google Cloud NetApp volumes.
