---
sidebar: sidebar 
permalink: ehc/ncvs-gc-data-encryption-at-rest.html 
keywords: aes-256 encryption, cmek 
summary: 'Tous les volumes Cloud Volumes Service sont chiffrés au repos à l"aide du chiffrement AES-256, qui signifie que toutes les données utilisateur écrites sur le support sont chiffrées et ne peuvent être déchiffrées qu"à l"aide d"une clé par volume.' 
---
= Chiffrement des données au repos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Tous les volumes Cloud Volumes Service sont chiffrés au repos à l'aide du chiffrement AES-256, qui signifie que toutes les données utilisateur écrites sur le support sont chiffrées et ne peuvent être déchiffrées qu'à l'aide d'une clé par volume.

* Pour CVS-SW, des clés générées par Google sont utilisées.
* Pour CVS-Performance, les clés par volume sont stockées dans un gestionnaire de clés intégré dans Cloud Volumes Service.


Depuis novembre 2021, un aperçu des fonctionnalités de clés de chiffrement gérées par les clients (CMEK) a été disponible. Vous pouvez ainsi chiffrer les clés par volume avec une clé principale par projet et par région hébergée dans https://cloud.google.com/kms/docs["Google Key Management Service (KMS)."^] LES KILOMÈTRES vous permettent d'associer des gestionnaires de clés externes.

Pour plus d'informations sur la configuration de KMS pour CVS-Performance, reportez-vous à la section https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["La configuration des clés de chiffrement gérées par le client"^].
