---
sidebar: sidebar 
permalink: containers/tanzu_with_netapp/vtwn_videos_and_demos.html 
keywords: video, demonstration, deployment, VMware Tanzu with NetApp, NetApp, Tanzu 
summary: Cette page contient des liens vers des vidéos qui présentent certaines des fonctionnalités décrites dans ce document. 
---
= Vidéos et démonstrations : VMware Tanzu avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Les vidéos suivantes présentent certaines des fonctionnalités décrites dans ce document :

.Utilisez Astra Trident pour provisionner le stockage persistant dans VMware Tanzu - VMware Tanzu avec NetApp
video::8db3092b-3468-4754-b2d7-b01200fbb38d[panopto,width=360]
.Utilisez Astra Control Center pour cloner des applications dans VMware Tanzu - VMware Tanzu avec NetApp
video::01aff358-a0a2-4c4f-9062-b01200fb9abd[panopto,width=360]

NOTE: Ces démonstrations ont été enregistrées sous forme de présentation technique à l'aide de la version 1.3.1 de TKG et de la version 21.12 d'Astra Control Center. Consultez la matrice de support pour connaître les versions officielles prises en charge.
REMARQUE : ces démonstrations ont été enregistrées sous forme de présentation technique à l'aide de la version 1.3.1 de TKG et de la version 21.12 d'Astra Control Center. Consultez la matrice de support pour connaître les versions officielles prises en charge.

link:vtwn_additional_information.html["Suivant : informations complémentaires : VMware Tanzu avec NetApp."]
