---
sidebar: sidebar 
permalink: containers/tanzu_with_netapp/vtwn_solution_overview.html 
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Astra Trident, Astra Control, Astra 
summary: 'Ce document de référence apporte une validation du déploiement de différentes solutions Kubernetes VMware tanzu, déployées sous la forme Tanzu Kubernetes Grid (TKG), Tanzu Kubernetes Grid Service (TKGS) ou Tanzu Kubernetes Grid Integrated (TKGI) dans plusieurs environnements de data Center différents et validés par NetApp.' 
---
= NVA-1166 : VMware Tanzu avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Alan Cowles et Nikhil M Kulkarni, NetApp

Ce document de référence apporte une validation du déploiement de différentes solutions Kubernetes VMware tanzu, déployées sous la forme Tanzu Kubernetes Grid (TKG), Tanzu Kubernetes Grid Service (TKGS) ou Tanzu Kubernetes Grid Integrated (TKGI) dans plusieurs environnements de data Center différents et validés par NetApp. Il décrit également l'intégration du stockage avec les systèmes de stockage NetApp et l'orchestrateur de stockage Astra Trident pour la gestion du stockage persistant et Astra Control Center pour la sauvegarde et le clonage des applications avec état qui utilisent ce stockage persistant. Enfin, ce document propose des démonstrations vidéo des intégrations et validations de solutions.



== Cas d'utilisation

L'architecture de la solution VMware Tanzu avec NetApp a été conçue pour offrir une valeur exceptionnelle aux clients dans les cas d'utilisation suivants :

* Solutions VMware Tanzu Kubernetes Grid faciles à déployer et à gérer sur VMware vSphere et intégrées avec les systèmes de stockage NetApp.
* La puissance combinée des workloads virtualisés et de conteneurs d'entreprise avec les offres VMware Tanzu Kubernetes Grid.
* Des cas d'utilisation et de configuration réels soulignant les fonctionnalités de VMware Tanzu utilisées avec le stockage NetApp et la suite de produits NetApp Astra.
* Protection ou migration cohérentes au niveau des applications des workloads conteneurisés déployés sur des clusters VMware Tanzu Kubernetes Grid dont les données résident sur des systèmes de stockage NetApp via Astra Control Center.




== Valeur commerciale

Les entreprises se tournent de plus en plus vers les pratiques DevOps pour créer de nouveaux produits, réduire les cycles de lancement et ajouter rapidement de nouvelles fonctionnalités. En raison de leur nature inné et agile, les conteneurs et les microservices ont un rôle essentiel dans l'accompagnement des pratiques DevOps. Cependant, la pratique du DevOps à l'échelle de production dans un environnement d'entreprise présente ses propres défis et impose certaines exigences à l'infrastructure sous-jacente, notamment :

* Haute disponibilité à tous les niveaux de la pile
* Simplicité des procédures de déploiement
* Des opérations et des mises à niveau non disruptives
* Une infrastructure programmable et basée sur des API pour suivre le rythme de l'agilité des microservices
* Colocation avec garanties de performances
* Possibilité d'exécuter simultanément des workloads virtualisés et conteneurisés
* Possibilité de faire évoluer indépendamment l'infrastructure en fonction des besoins des workloads
* Déploiement dans un modèle de cloud hybride avec conteneurs s'exécutant à la fois dans des data centers sur site et dans le cloud.


VMware Tanzu avec NetApp prend en compte ces défis et présente une solution qui aide à résoudre chaque problème en déployant des offres Kubernetes VMware Tanzu dans l'environnement de cloud hybride choisi par le client.



== Présentation de la technologie

La solution VMware Tanzu avec NetApp comprend les principaux composants suivants :



=== Plateformes VMware Tanzu Kubernetes

VMware Tanzu est présente dans une multitude de versions que l'équipe d'ingénieurs solutions de NetApp a validées dans nos laboratoires. Chaque version de Tanzu s'intègre avec succès avec le portefeuille de solutions de stockage de NetApp, et chacune d'elles peut répondre à certaines exigences de l'infrastructure. Les points saillants suivants décrivent les caractéristiques et les offres de chaque version de Tanzu décrite dans ce document.

*VMware Tanzu Kubernetes Grid (TKG)*

* Environnement Kubernetes en amont standard déployé dans un environnement VMware vSphere.
* Anciennement connu sous le nom de Essential PKS (de Heppo acquisition, février 2019).
* TKG est déployé avec une instance de cluster de gestion distincte pour la prise en charge de vSphere 6.7U3 ultérieure.
* Les déploiements TKG peuvent être déployés dans le cloud, aussi bien avec AWS ou Azure.
* Permet l'utilisation de nœuds workers Windows ou Linux (Ubuntu/Photon).
* NSX-T, un proxy HA, un réseau AVI ou des équilibreurs de charge peuvent être utilisés pour le plan de contrôle.
* TKG prend en charge MetalLB pour le plan d'application/de données.
* Peut utiliser vSphere CSI ainsi que des services tiers tels que NetApp Astra Trident.


*VMware Tanzu Kubernetes Grid Service (TKGS)*

* Environnement Kubernetes en amont standard déployé dans un environnement VMware vSphere.
* Anciennement connu sous le nom de Essential PKS (de Heppo acquisition, février 2019).
* TKGS est déployé avec un cluster Supervisor et des clusters de charges de travail uniquement sur vSphere 7.0U1.
* Permet l'utilisation de nœuds workers Windows ou Linux (Ubuntu/Photon).
* NSX-T, un proxy HA, un réseau AVI ou des équilibreurs de charge peuvent être utilisés pour le plan de contrôle.
* TKGS prend en charge MetalLB pour les plans d'application/de données.
* Peut utiliser vSphere CSI ainsi que des services tiers tels que NetApp Astra Trident.
* Prend en charge les pods vSphere avec Tanzu, ce qui permet d'exécuter directement les pods sur des hôtes ESXi activés dans l'environnement.


*VMware Tanzu Kubernetes Grid Integrated (TKGI)*

* Anciennement Enterprise PKS (d'après l'acquisition de Heptio, février 2019).
* Peut utiliser NSX-T, HA Proxy ou AVI. Vous pouvez également fournir votre propre équilibreur de charge.
* Prise en charge à partir de vSphere 6.7U3 et de AWS, Azure et GCP.
* Configuration via un assistant pour faciliter le déploiement
* Exécute Tanzu dans des machines virtuelles immuables contrôlées gérées par BOSH.
* Vous pouvez utiliser vSphere CSI et des services tiers tels que NetApp Astra Trident (certaines conditions s'appliquent).


*VSphere avec Tanzu (vSphere Pods)*

* Les pods vSphere natifs s'exécutent dans une couche mince basée sur des photons avec le matériel virtuel prescrit pour une isolation totale.
* Utilise NSX-T, mais cela permet d'utiliser d'autres fonctionnalités comme un registre d'images Harbour.
* Déployé et géré dans vSphere 7.0U1 à partir d'un cluster Supervisor virtuel tel que TKGS. Exécute les pods directement sur des nœuds ESXi.
* Intégration complète à vSphere, visibilité et contrôle optimaux grâce à l'administration vSphere.
* Des modules CRX isolés pour un niveau de sécurité optimal.
* Prend uniquement en charge vSphere CSI pour le stockage persistant. Aucun orchestrateurs de stockage tiers pris en charge




=== Systèmes de stockage NetApp

NetApp propose plusieurs systèmes de stockage parfaitement adaptés aux data centers d'entreprise et aux déploiements de cloud hybride. Le portefeuille NetApp inclut des systèmes de stockage NetApp ONTAP, NetApp Element et E-Series, tous capables d'assurer un stockage persistant pour les applications conteneurisées.

Pour plus d'informations, rendez-vous sur le site Web de NetApp https://www.netapp.com["ici"].



=== Intégrations du stockage NetApp

NetApp Astra Control Center propose un ensemble complet de services de gestion du stockage et des données respectueuse des applications pour les workloads Kubernetes avec état, déployé dans un environnement sur site et optimisé par la technologie de protection des données NetApp de confiance.

Pour plus d'informations, rendez-vous sur le site Web NetApp Astra https://cloud.netapp.com/astra["ici"].

Astra Trident est un orchestrateur de stockage open source entièrement pris en charge pour les conteneurs et les distributions Kubernetes, y compris VMware Tanzu.

Pour en savoir plus, rendez-vous sur le site Web Astra Trident https://docs.netapp.com/us-en/trident/index.html["ici"].



== Matrice de prise en charge actuelle pour les versions validées

|===


| De déduplication | Objectif | Version logicielle 


| NetApp ONTAP | Stockage | 9.9.1 


| NetApp Astra Control Center | Gestion des données intégrant la cohérence applicative | 22.04 


| NetApp Astra Trident | Orchestration du stockage | 22.04.0 


| VMware Tanzu Kubernetes Grid | Orchestration de conteneurs | 1.4+ 


.2+| Service de grille VMware Tanzu Kubernetes .2+| Orchestration de conteneurs | 0.0.15 [espaces de noms vSphere] 


| 1.22.6 [Supervisor Cluster Kubernetes] 


| VMware Tanzu Kubernetes Grid intégré | Orchestration de conteneurs | 1.13.3 


| VMware vSphere | Virtualisation du data Center | 7,0U3 


| Data Center VMware NSX-T | Mise en réseau et sécurité | 3.1.3 


| Équilibreur de charge avancé de VMware NSX | Équilibreur de charge | 20.1.3 
|===