= 
:allow-uri-read: 


. Connectez-vous au site de support NetApp et téléchargez la dernière version de NetApp Astra Control Center. Une licence associée à votre compte NetApp est requise. Après avoir téléchargé le fichier tarball, transférez-le sur le poste de travail d'administration.
+

NOTE: Pour commencer avec une licence d'essai d'Astra Control, visitez le https://cloud.netapp.com/astra-register["Site d'inscription à Astra"^].

. Déballez la boule tar et remplacez le répertoire de travail par le dossier obtenu.
+
[listing]
----
[netapp-user@rhel7 ~]$ tar -vxzf astra-control-center-21.08.65.tar.gz
[netapp-user@rhel7 ~]$ cd astra-control-center-21.08.65
----
. Avant de commencer l'installation, poussez les images du centre de contrôle Astra vers un registre d'images.
+

NOTE: Vous pouvez choisir de le faire avec Docker ou Podman ; les instructions pour les deux sont fournies dans cette étape.



[role="tabbed-block"]
====
'''
. Exportez le FQDN du Registre avec le nom de l'organisation/espace de noms/projet comme variable d'environnement 'regiant'.
+
[listing]
----
[netapp-user@rhel7 ~]$ export registry=astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra
----
. Connectez-vous au registre.
+
[listing]
----
[netapp-user@rhel7 ~]$ podman login -u ocp-user -p password --tls-verify=false astra-registry.apps.ocp-vmw.cie.netapp.com
----
+

NOTE: Si vous utilisez `kubeadmin` l'utilisateur doit se connecter au registre privé, puis utiliser un jeton au lieu du mot de passe - `podman login -u ocp-user -p token --tls-verify=false astra-registry.apps.ocp-vmw.cie.netapp.com`.

+

NOTE: Vous pouvez également créer un compte de service, attribuer un rôle d'éditeur de registre et/ou de visualiseur de registre (selon que vous avez besoin d'un accès Push/Pull) et vous connecter au registre à l'aide du jeton du compte de service.

. Créez un fichier de script shell et collez le contenu suivant dans celui-ci.
+
[listing]
----
[netapp-user@rhel7 ~]$ vi push-images-to-registry.sh

for astraImageFile in $(ls images/*.tar); do
   astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')
   podman tag $astraImage $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
   podman push $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
done
----
+

NOTE: Si vous utilisez des certificats non approuvés pour votre registre, modifiez le script de shell et utilisez-le `--tls-verify=false` pour la commande push podman `podman push $registry/$(echo $astraImage | sed 's/^[^\/]\+\///') --tls-verify=false`.

. Rendre le fichier exécutable.
+
[listing]
----
[netapp-user@rhel7 ~]$ chmod +x push-images-to-registry.sh
----
. Exécutez le script de shell.
+
[listing]
----
[netapp-user@rhel7 ~]$ ./push-images-to-registry.sh
----
+
'''
+
'''
. Exportez le FQDN du Registre avec le nom de l'organisation/espace de noms/projet comme variable d'environnement 'regiant'.
+
[listing]
----
[netapp-user@rhel7 ~]$ export registry=astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra
----
. Connectez-vous au registre.
+
[listing]
----
[netapp-user@rhel7 ~]$ docker login -u ocp-user -p password astra-registry.apps.ocp-vmw.cie.netapp.com
----
+

NOTE: Si vous utilisez `kubeadmin` l'utilisateur doit se connecter au registre privé, puis utiliser un jeton au lieu du mot de passe - `docker login -u ocp-user -p token astra-registry.apps.ocp-vmw.cie.netapp.com`.

+

NOTE: Vous pouvez également créer un compte de service, attribuer un rôle d'éditeur de registre et/ou de visualiseur de registre (selon que vous avez besoin d'un accès Push/Pull) et vous connecter au registre à l'aide du jeton du compte de service.

. Créez un fichier de script shell et collez le contenu suivant dans celui-ci.
+
[listing]
----
[netapp-user@rhel7 ~]$ vi push-images-to-registry.sh

for astraImageFile in $(ls images/*.tar); do
   astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
   docker tag $astraImage $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
   docker push $registry/$(echo $astraImage | sed 's/^[^\/]\+\///')
done
----
. Rendre le fichier exécutable.
+
[listing]
----
[netapp-user@rhel7 ~]$ chmod +x push-images-to-registry.sh
----
. Exécutez le script de shell.
+
[listing]
----
[netapp-user@rhel7 ~]$ ./push-images-to-registry.sh
----
+
'''


====
. Ensuite, chargez les certificats TLS du registre d'images sur les nœuds OpenShift. Pour ce faire, créez une configuration dans le `openshift-config` Espace de noms à l'aide des certificats TLS et le patch dans la configuration d'image du cluster pour que le certificat soit fiable.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create configmap default-ingress-ca -n openshift-config --from-file=astra-registry.apps.ocp-vmw.cie.netapp.com=tls.crt

[netapp-user@rhel7 ~]$ oc patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"default-ingress-ca"}}}' --type=merge
----
+

NOTE: Si vous utilisez un registre interne OpenShift avec des certificats TLS par défaut de l'opérateur d'entrée portant une route, vous devez suivre l'étape précédente pour corriger le nom d'hôte de la route. Pour extraire les certificats de l'opérateur Ingress, vous pouvez utiliser la commande `oc extract secret/router-ca --keys=tls.crt -n openshift-ingress-operator`.

. Créer un espace de noms `netapp-acc-operator` Pour la pose de l'opérateur du centre de commande Astra.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create ns netapp-acc-operator
----
. Créez un secret avec des informations d'identification pour vous connecter au registre d'images dans `netapp-acc-operator` espace de noms.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create secret docker-registry astra-registry-cred --docker-server=astra-registry.apps.ocp-vmw.cie.netapp.com --docker-username=ocp-user --docker-password=password -n netapp-acc-operator
secret/astra-registry-cred created
----
. Modifiez le CR du conducteur du centre de contrôle Astra `astra_control_center_operator_deploy.yaml`, Qui est un ensemble de ressources que le Centre de contrôle Astra déploie. Dans la demande de modification de l'opérateur, recherchez la définition de déploiement pour `acc-operator-controller-manager` Et entrez le FQDN de votre registre avec le nom d'organisation tel qu'il a été donné lors de l'envoi des images au Registre (dans cet exemple, `astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra`) en remplaçant le texte `ASTRA_IMAGE_REGISTRY` et fournir le nom du secret que nous venons de créer dans `imagePullSecrets` section. Vérifier les autres détails de l'opérateur, enregistrer et fermer.
+
[listing]
----
[netapp-user@rhel7 ~]$ vim astra_control_center_operator_deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: ASTRA_IMAGE_REGISTRY/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        image: astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra/acc-operator:21.08.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets: [name: astra-registry-cred]
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----
. Créer l'opérateur en exécutant la commande suivante.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create -f astra_control_center_operator_deploy.yaml
----
. Créez un espace de noms dédié pour installer toutes les ressources Astra Control Center.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create ns netapp-astra-cc
namespace/netapp-astra-cc created
----
. Créez le secret pour accéder au registre d'images dans cet espace de noms.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc create secret docker-registry astra-registry-cred --docker-server=astra-registry.apps.ocp-vmw.cie.netapp.com --docker-username=ocp-user --docker-password=password -n netapp-astra-cc

secret/astra-registry-cred created
----
. Modifiez le fichier CRD de l'Astra Control Center `astra_control_center_min.yaml` Saisissez le nom de domaine complet, les détails du registre d'images, l'adresse e-mail de l'administrateur et d'autres détails.
+
[listing]
----
[netapp-user@rhel7 ~]$ vim astra_control_center_min.yaml

apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  accountName: "NetApp HCG Solutions"
  astraVersion: "21.08.65"
  astraAddress: "astra-control-center.cie.netapp.com"
  autoSupport:
    enrolled: true
  email: "solutions_tme@netapp.com"
  firstName: "NetApp HCG"
  lastName: "Admin"
  imageRegistry:
    name: "astra-registry.apps.ocp-vmw.cie.netapp.com/netapp-astra"     # use your registry
    secret: "astra-registry-cred"             # comment out if not needed
----
. Créez le CRD du centre de contrôle Astra dans l'espace de noms créé pour celui-ci.
+
[listing]
----
[netapp-user@rhel7 ~]$ oc apply -f astra_control_center_min.yaml -n netapp-astra-cc
astracontrolcenter.astra.netapp.io/astra created
----



NOTE: Le fichier précédent `astra_control_center_min.yaml` Est la version minimale du CRD du centre de contrôle Astra. Si vous souhaitez créer le CRD avec plus de contrôle, comme définir un storageclass autre que la valeur par défaut pour la création de PVC ou fournir des détails SMTP pour les notifications de courrier électronique, vous pouvez modifier le fichier `astra_control_center.yaml`, Entrez les détails nécessaires et utilisez-les pour créer le CRD.
