---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: NetApp propose plusieurs produits qui aident nos clients à orchestrer et à gérer les données persistantes dans des environnements basés sur des conteneurs, tels que Anthos. 
---
= Présentation de l'intégration du stockage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/




== Programme partenaire pour le stockage Anthos Ready.

Google Cloud demande régulièrement la mise à jour des intégrations du stockage pour les partenaires avec les nouvelles versions de Anthos dans le cadre de leur programme de partenariat pour le stockage Anthos. Vous trouverez une liste des solutions de stockage actuellement validées, des pilotes CSI, des fonctionnalités disponibles et des versions de Anthos prises en charge https://cloud.google.com/anthos/docs/resources/partner-storage["ici"^].

NetApp a maintenu la conformité régulièrement, tous les trimestres, à l'aide de demandes de validation de notre orchestrateur de stockage conforme à Astra Trident CSI et de notre système de stockage ONTAP avec des versions d'Anthos.

Le tableau suivant contient les versions Anthos testées par les ingénieurs partenaires NetApp et NetApp pour la validation des pilotes et des ensembles de fonctionnalités NetApp Astra Trident CSI, dans le cadre du programme partenaires pour le stockage Anthos Ready :

|===


| Type de déploiement | Version | System de stockage | Version d'Astra Trident | Protocole | Caractéristiques 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | NAS | Multiwriter, extension de volume, instantanés, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | SAN | Bloc brut, extension de volume, instantanés, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | Multiwriter, extension de volume, instantanés, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | SAN | Bloc brut, extension de volume, instantanés, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | Multiwriter, extension de volume, instantanés, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | SAN | Bloc brut, extension de volume, instantanés, PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | Rédacteur multiple, extension de volume, snapshots 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | SAN | Bloc brut, extension de volume, snapshots 


| VMware | 1.11 | Élément 12.3 | 22.04 | SAN | Bloc brut, extension de volume, snapshots 


| bare-metal | 1.10 | ONTAP 9.8 | 22.01 | NAS | Rédacteur multiple, extension de volume, snapshots 


| bare-metal | 1.10 | ONTAP 9.8 | 22.01 | SAN | Bloc brut, extension de volume, snapshots 
|===


== Intégrations du stockage NetApp

NetApp propose plusieurs produits pour orchestrer et gérer les données persistantes dans des environnements basés sur des conteneurs, tels que Anthos.

NetApp Astra Trident est un orchestrateur de stockage open source entièrement pris en charge pour les conteneurs et les distributions Kubernetes, y compris Anthos. Pour en savoir plus, rendez-vous sur le site Web Astra Trident https://docs.netapp.com/us-en/trident/index.html["ici"].

Les pages suivantes présentent des informations supplémentaires sur les produits NetApp validés pour la gestion des applications et du stockage persistant dans la solution Anthos avec NetApp.

link:a-w-n_overview_trident.html["Ensuite, présentation de NetApp Astra Trident."]
