---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_advanced.html 
keywords: Advanced Configuration, Load Balancers 
summary: 'Cette section est dédiée aux personnalisations que les utilisateurs du monde réel devraient probablement réaliser lors du déploiement de cette solution en production, telles que le déploiement d"instances personnalisées d"équilibreur de charge.' 
---
= Options de configuration avancées
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


La solution la plus facile à déployer est généralement la mieux adaptée, mais dans certains cas, des personnalisations avancées sont nécessaires pour satisfaire les exigences ou les spécifications d'une application spécifique ou de l'environnement vers lequel la solution est déployée. À cette fin, la solution Red Hat OpenShift avec NetApp offre les personnalisations suivantes pour satisfaire ces besoins.


NOTE: Cette section décrit quelques options de configuration avancées, telles que l'utilisation d'équilibreurs de charge tiers ou la création d'un registre privé pour héberger des images de conteneurs personnalisées. Les deux conditions requises pour l'installation du centre de contrôle NetApp Astra sont essentielles.

Les pages suivantes présentent des informations supplémentaires sur les options de configuration avancée validées dans la solution Red Hat OpenShift avec NetApp :

link:a-w-n_load_balancers.html["Suivant : exploration des options d'équilibrage de la charge."]
