---
sidebar: sidebar 
permalink: vmw-sc/sc-overview.html 
keywords: NetApp Solutions, vmware, sovereign cloud 
summary:  
---
= Présentation de VMware Sovereign Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour de nombreuses entités qui traitent et conservent des données hautement sensibles, telles que les administrations nationales et gouvernementales, et les secteurs où les réglementations sont très strictes, comme la finance et la santé, le concept de souveraineté fait son apparition. Les gouvernements nationaux cherchent également à étendre leurs capacités économiques numériques et à réduire la dépendance envers les entreprises multinationales pour leurs services cloud.



== Initiative VMware Sovereign Cloud

VMware définit un cloud souverain comme un cloud qui :

* Protège et valorise les données stratégiques (par exemple, les données nationales, les données d'entreprise et les données personnelles) pour les entreprises du secteur public et privé
* Une capacité nationale pour l'économie numérique
* Sécurisation des données grâce à des contrôles de sécurité vérifiés
* Garantit la conformité aux lois sur la confidentialité des données
* Améliore le contrôle des données en garantissant à la fois la résidence et la souveraineté des données tout en assurant un contrôle juridictionnel total




== Partenariat avec un fournisseur de services clouds souverains VMware de confiance

Pour assurer leur réussite, les entreprises doivent collaborer avec des partenaires en qui ils ont confiance et qui sont capables d'héberger des plateformes cloud souveraines authentiques et autonomes. Les fournisseurs cloud VMware reconnus dans le cadre de l'initiative Sovereign Cloud de VMware s'engagent à concevoir et à exploiter des solutions cloud basées sur des architectures Software-defined modernes, qui incarnent les principes clés et les meilleures pratiques décrits dans le cadre du cloud souverain de VMware.

* *Souveraineté des données et contrôle juridictionnel* – toutes les données résident et sont soumises au contrôle et à l'autorité exclusifs de l'État-nation où ces données ont été recueillies. Les opérations sont entièrement gérées dans la juridiction
* *Accès et intégrité des données* – l'infrastructure cloud est résiliente et disponible dans au moins deux centres de données de la juridiction avec des options de connectivité privée et sécurisée.
* *Sécurité et conformité des données* – les contrôles du système de gestion de la sécurité de l'information sont certifiés par rapport à une norme mondiale (ou régionale) reconnue par l'industrie et vérifiés régulièrement.
* *Indépendance et mobilité des données* – prise en charge des architectures d'applications modernes pour empêcher la dépendance vis-à-vis d'un fournisseur de cloud et permettre la portabilité et l'indépendance des applications


Pour plus d'informations sur VMware, consultez le site :

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["Présentation de VMware Sovereign Cloud"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["Qu'est-ce que le cloud souverain de VMware ?"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["Voici la nouvelle initiative VMware Sovereign Cloud"]
* link:https://www.vmware.com/content/dam/learn/en/amer/fy22/pdf/1173457_Sovereign_Cloud_Technical_Whitepaper_V3.pdf["Livre blanc technique sur le cloud souverain de VMware"]

