---
sidebar: sidebar 
permalink: vmw-sc/sc-use-cases.html 
keywords: NetApp Solutions, vmware, sovereign cloud, netapp, use case 
summary:  
---
= NetApp avec cloud souverain VMware : utilisations
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp prend en charge les concepts de cloud souverain VMware grâce à l'intégration de plusieurs technologies NetApp.

Utilisez le(s) lien(s) suivant(s) pour en savoir plus sur les intégrations technologiques NetApp avec VMware Sovereign Cloud :

* link:#storageGRID["NetApp StorageGRID en tant qu'extension de magasin d'objets"]




== NetApp StorageGRID en tant qu'extension de magasin d'objets

NetApp a collaboré avec VMware pour intégrer NetApp StorageGRID dans VMware Cloud Director afin de prendre en charge le cloud souverain VMware. Ce plug-in à VMware Cloud Director permet aux fournisseurs de services d'utiliser StorageGRID en tant qu'offre de stockage objet (quel que soit le cas d'utilisation) et de gérer StorageGRID à l'aide de la même solution mutualisée VMware (VMware Cloud Director) que celle utilisée par les fournisseurs de services pour gérer d'autres parties de leur catalogue.

Les partenaires qui proposent des clouds souverains VMware peuvent choisir NetApp StorageGRID pour les aider à gérer et à gérer des environnements cloud avec des données non structurées. Sa compatibilité universelle dans sa prise en charge native des API standard telles qu'Amazon S3 contribue à assurer une interopérabilité fluide dans divers environnements cloud, ainsi que des innovations uniques telles que la gestion automatisée du cycle de vie permettent d'assurer une sauvegarde, un stockage et une conservation à long terme plus économiques des données non structurées des clients.

L'intégration souveraine de NetApp avec Cloud Director permet aux clients de bénéficier des avantages suivants :

* Vous avez la garantie que les données sensibles, y compris les métadonnées, restent sous contrôle souverain tout en empêchant l'accès d'autorités étrangères susceptibles de violer les lois sur la confidentialité des données.
* Sécurité et conformité accrues qui protègent les applications et les données contre les vecteurs d'attaque en constante évolution tout en assurant la conformité continue avec une infrastructure locale de confiance. infrastructures, structures intégrées et experts locaux.
* Une infrastructure pérenne capable de réagir rapidement à l'évolution des réglementations en matière de confidentialité des données, des menaces de sécurité et de la géopolitique.
* La capacité à exploiter tout le potentiel des données avec le partage et l'analyse sécurisés des données pour stimuler l'innovation sans violer les lois sur la confidentialité. L'intégrité des données est protégée pour une information précise.


Pour en savoir plus sur l'intégration de StorageGRID, consultez les documents suivants :

* link:https://www.netapp.com/newsroom/press-releases/news-rel-20231107-561294/["Annonce NetApp"]

