---
sidebar: sidebar 
permalink: containers/bmanthos_solution_requirements.html 
keywords: Hardware, software, compute, storage, requirements 
summary: 'Les fonctionnalités indépendantes du matériel de Anthos sur un système d"exploitation sans système d"exploitation vous permettent de sélectionner une plateforme de calcul optimisée pour votre cas d"utilisation. Votre infrastructure peut donc s"adapter à votre infrastructure existante, ce qui réduit vos dépenses d"investissement.' 
---
= De la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les fonctionnalités indépendantes du matériel de Anthos sur un système d'exploitation sans système d'exploitation vous permettent de sélectionner une plateforme de calcul optimisée pour votre cas d'utilisation. Votre infrastructure peut donc s'adapter à votre infrastructure existante, ce qui réduit vos dépenses d'investissement.



== Configuration matérielle requise



=== Calcul : Bring your own Server

Les fonctionnalités indépendantes du matériel de Anthos sur un système bare Metal vous permettent de sélectionner une plateforme de calcul optimisée pour votre cas d'utilisation. Votre infrastructure peut donc s'adapter à votre infrastructure existante, ce qui réduit vos dépenses d'investissement.

Le tableau suivant répertorie le nombre minimal de composants matériels de calcul requis pour implémenter cette solution, bien que les modèles matériels utilisés puissent varier en fonction des exigences du client.

|===
| Du stockage | Matériel et modèle | Quantité 


| Nœuds d'administration | Cisco UCS B200 | 3 


| Nœuds worker | HP ProLiant DL360 | 4 
|===


=== Stockage : NetApp ONTAP

Le tableau suivant répertorie le nombre minimal de composants de matériel de stockage nécessaire pour implémenter la solution, bien que les modèles matériels utilisés puissent varier en fonction des exigences du client.

|===
| Sous-jacent | Modèle | Quantité 


| NetApp AFF | NetApp AFF A300 | 2 (1 paire HA) 
|===


== Configuration logicielle requise

Les versions logicielles identifiées dans le tableau suivant ont été utilisées par NetApp et ses partenaires pour valider la solution avec NetApp, mais les composants logiciels utilisés peuvent varier en fonction des besoins du client.

|===
| Logiciel | Objectif | Version 


| Ubuntu | Système d'exploitation sur 3 administrateurs | 20.04 


|  | Se sur Worker4 | 20.04 


|  | Se sur Worker3 | 18.04 


| CentOS | Se sur Worker2 | 8.2 


| Red Hat Enterprise Linux | Se sur Worker1 | 8.1 


| Anthos sur bare Metal | Orchestration de conteneurs | 1.6.0 


| NetApp ONTAP | OS de stockage | 9.7P8 


| NetApp Astra Trident | Gestion du stockage de conteneurs | 20.10 
|===

NOTE: Cet environnement multi-systèmes d'exploitation montre l'interopérabilité avec les versions de système d'exploitation prises en charge de la solution Anthos sur des systèmes d'exploitation sans système d'exploitation. Nous prévoyons que les clients standardiseront sur un ou plusieurs systèmes d'exploitation à des fins de déploiement.

Pour obtenir des informations sur les exigences matérielles et logicielles pour Anthos, consultez le https://cloud.google.com/anthos/clusters/docs/bare-metal/latest["Documentation Anthos sur les métaux nus"^] page.
