---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= Vidéos et démonstrations : Red Hat OpenShift avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les vidéos suivantes présentent certaines des fonctionnalités décrites dans ce document :

.Intégration de Cloud Insights à OpenShift Virtualization
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.Utilisation de Red Hat MTV pour migrer des machines virtuelles vers OpenShift Virtualization avec le stockage NetApp ONTAP
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.Accélérez le développement logiciel avec Astra Control et la technologie NetApp FlexClone - Red Hat OpenShift avec NetApp
video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto,width=360]
.Utilisez l'Astra de NetApp pour effectuer une analyse post-mortem et restaurer votre application
video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto,width=360]
.Protection des données dans un pipeline ci/CD avec Astra Control Center
video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto,width=360]
.Migration de workloads à l'aide d'Astra Control Center : Red Hat OpenShift avec NetApp
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto,width=360]
.Migration des charges de travail - Red Hat OpenShift avec NetApp
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.Installation d'OpenShift Virtualization - Red Hat OpenShift avec NetApp
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.Déploiement d'une machine virtuelle avec OpenShift Virtualization - Red Hat OpenShift avec NetApp
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.NetApp HCI pour Red Hat OpenShift sur Red Hat Virtualization
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]