---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_rosa_solution_overview.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift Service on AWS, 
summary: Red Hat OpenShift Service sur AWS avec NetApp ONTAP 
---
= Red Hat OpenShift Service sur AWS avec NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans cette section, nous allons apprendre à utiliser FSX pour ONTAP en tant que couche de stockage persistant pour les applications qui s'exécutent sur ROSA. Il présente l'installation du pilote NetApp Trident CSI sur un cluster ROSA, le provisionnement d'un système de fichiers FSX pour ONTAP et le déploiement d'un exemple d'application avec état. Il présente également des stratégies de sauvegarde et de restauration des données de votre application. Cette solution intégrée vous permet d'établir une structure de stockage partagée qui s'adapte facilement aux zones de disponibilité, simplifiant ainsi les processus d'évolutivité, de protection et de restauration de vos données à l'aide du pilote Trident CSI.
