---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= Vidéos et démonstrations : Red Hat OpenShift avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Les vidéos suivantes présentent certaines des fonctionnalités décrites dans ce document :

[cols="5a, 5a, 5a"]
|===


 a| 
Accélérez le développement logiciel avec Astra Control et la technologie NetApp FlexClone - Red Hat OpenShift avec NetApp

 a| 
Utilisez l'Astra de NetApp pour effectuer une analyse post-mortem et restaurer votre application

 a| 
Protection des données dans un pipeline ci/CD avec Astra Control Center




 a| 
Migration de workloads à l'aide d'Astra Control Center : Red Hat OpenShift avec NetApp

 a| 
Migration des charges de travail - Red Hat OpenShift avec NetApp

 a| 
Installation d'OpenShift Virtualization - Red Hat OpenShift avec NetApp




 a| 
Déploiement d'une machine virtuelle avec OpenShift Virtualization - Red Hat OpenShift avec NetApp

 a| 
NetApp HCI pour Red Hat OpenShift sur Red Hat Virtualization

 a| 

|===
link:rh-os-n_additional_information.html["Suivant : informations complémentaires Red Hat OpenShift avec NetApp."]
