---
sidebar: sidebar 
permalink: containers/rh-os-n_load_balancers.html 
keywords: Advanced Configuration, Load Balancers, MetalLB 
summary: 'Cette section décrit les options d"équilibrage de charge pour les utilisateurs qui souhaitent personnaliser leur déploiement Red Hat OpenShift avec NetApp.' 
---
= Exploration des options d'équilibreur de charge avec Red Hat OpenShift avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Dans la plupart des cas, Red Hat OpenShift met les applications à la disposition du monde extérieur via des routes. Un service est exposé en lui donnant un nom d'hôte accessible en externe. La route définie et les points de terminaison identifiés par son service peuvent être utilisés par un routeur OpenShift pour fournir cette connectivité nommée aux clients externes.

Cependant, dans certains cas, les applications nécessitent le déploiement et la configuration d'équilibreurs de charge personnalisés pour exposer les services appropriés. Il s'agit notamment du centre de contrôle NetApp Astra, Pour répondre à ce besoin, nous avons évalué un certain nombre d'options d'équilibrage de charge personnalisé. Leur installation et leur configuration sont décrites dans cette section.

Les pages suivantes présentent des informations supplémentaires sur les options de équilibreur de charge validées dans la solution Red Hat OpenShift avec NetApp :

* link:rh-os-n_LB_MetalLB.html["MetalLB"]
* link:rh-os-n_LB_F5BigIP.html["F5 BIG-IP"]


link:rh-os-n_use_cases.html["Ensuite, dossiers de validation/d'utilisation de la solution : Red Hat OpenShift avec NetApp."]
