---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_rosa_prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, ROSA, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: Red Hat OpenShift Virtualization sur ROSA 
---
= Déployez Red Hat OpenShift Virtualization avec FSxN sur ROSA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section fournit des détails sur la configuration de FSX pour NetApp ONTAP en tant que classe de stockage par défaut pour le cluster ROSA, puis sur la création d'un ordinateur virtuel qui utilisera le stockage FSX ONTAP pour ses volumes. Nous allons également nous intéresser à la connexion à l'ordinateur virtuel à l'aide des informations d'identification de l'invité et au redémarrage de l'ordinateur virtuel. Enfin, nous effectuerons une migration dynamique de la machine virtuelle du nœud actuel vers un nouveau nœud. Nous examinerons le contenu du stockage sur disque après le redémarrage d'une machine virtuelle et la migration en direct .



== Prérequis

* link:https://signin.aws.amazon.com/signin?redirect_uri=https://portal.aws.amazon.com/billing/signup/resume&client_id=signup["Compte AWS"]
* link:https://console.redhat.com/["Un compte Red Hat"]
* Utilisateur IAM link:https://www.rosaworkshop.io/rosa/1-account_setup/["avec les autorisations appropriées"]pour créer et accéder au cluster ROSA
* link:https://aws.amazon.com/cli/["CLI AWS"]
* link:https://console.redhat.com/openshift/downloads["CLI ROSA"]
* link:https://console.redhat.com/openshift/downloads["Interface de ligne de commandes OpenShift"] (oc)
* link:https://docs.aws.amazon.com/eks/latest/userguide/helm.html["Documentation Helm 3"]
* link:https://docs.openshift.com/rosa/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html["UN CLUSTER HCP ROSA"] (avec au moins 3 nœuds worker bare metal)
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/virtualization/installing#virt-aws-bm_preparing-cluster-for-virt["OpenShift Virtualization installé sur ROSA Cluster"]
* link:https://console.redhat.com/openshift/overview["Accès à la console Web Red Hat OpenShift"]

