---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_conclusion.html 
keywords: VDS, Virtual Desktop Service, HCI, conclusion 
summary: 'NetApp Virtual Desktop Service fournit un environnement d"applications et de postes de travail virtuels très facile à utiliser, qui répond parfaitement aux enjeux métier. L"extension de VDS à NetApp HCI vous permet d"utiliser des fonctions NetApp puissantes dans un environnement VDS, notamment la déduplication à la volée, la compaction, le provisionnement fin et la compression.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Virtual Desktop Service fournit un environnement d'applications et de postes de travail virtuels très facile à utiliser, qui répond parfaitement aux enjeux métier. L'extension de VDS à l'environnement ONTAP local vous permet d'utiliser des fonctionnalités NetApp puissantes dans un environnement VDS, notamment le clonage rapide, la déduplication à la volée, la compaction et le provisionnement fin et à la compression. Réduisez les coûts de stockage et améliorez la performance avec le stockage 100 % Flash. Avec l'hyperviseur VMware vSphere, réduisez les délais de provisionnement des serveurs grâce aux volumes virtuels et à l'API vSphere pour l'intégration des baies. Avec le cloud hybride, les clients peuvent choisir l'environnement qui convient à leurs workloads exigeants et réaliser des économies. La session de postes de travail exécutée sur site peut accéder à des ressources clouds basées sur des règles.
