---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_why_ontap.html 
keywords: VDS, Virtual Desktop Service, ONTAP, FlexGroup, File System analytics, cloud tiering, global namespace 
summary: Fonctionnalités de ONTAP pour le service de postes de travail virtuels 
---
= Fonctionnalités de ONTAP pour le service de postes de travail virtuels
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les fonctionnalités ONTAP suivantes font du choix une solution intéressante pour un service de poste de travail virtuel.

* *Système de fichiers scale-out.* les volumes ONTAP FlexGroup peuvent atteindre une taille de plus de 20 po et contenir plus de 400 milliards de fichiers dans un seul espace de noms. Le cluster peut contenir jusqu'à 24 nœuds de stockage, chacun disposant d'un nombre flexible de cartes d'interface réseau en fonction du modèle utilisé.
+
Les postes de travail virtuels, les dossiers locaux et les conteneurs de profil utilisateur, les données partagées, etc. Peuvent croître à la demande sans craindre les limitations du système de fichiers.

* *Analyse du système de fichiers.* vous pouvez utiliser l'outil XCP pour obtenir des informations sur les données partagées. Avec ONTAP 9.8+ et ActiveIQ Unified Manager, vous pouvez facilement interroger et récupérer les informations de métadonnées de fichier et identifier les données inactives.
* *Cloud Tiering.* vous pouvez migrer des données inactives vers un magasin d'objets dans le cloud ou vers tout stockage compatible S3 de votre datacenter.
* *Les versions de fichiers*. Les utilisateurs peuvent restaurer des fichiers protégés par les copies Snapshot NetApp ONTAP. Les copies Snapshot de ONTAP sont très peu gourmandes en espace car elles n'enregistrent que les blocs modifiés.
* *Espace de noms global.* la technologie ONTAP FlexCache permet la mise en cache à distance du stockage de fichiers, ce qui facilite la gestion des données partagées à travers des emplacements contenant des systèmes de stockage ONTAP.
* *Prise en charge de la colocation sécurisée.* Un cluster de stockage physique unique peut être présenté sous forme de plusieurs baies de stockage virtuelles chacune avec ses propres volumes, protocoles de stockage, interfaces réseau logiques, domaine d'authentification et d'identité, utilisateurs de gestion, etc. C'est pourquoi vous pouvez partager la baie de stockage entre plusieurs unités commerciales ou environnements, comme le test, le développement et la production.
+
Pour garantir les performances, vous pouvez utiliser la QoS adaptative pour définir des niveaux de performance en fonction de l'espace utilisé ou alloué. Vous pouvez également contrôler la capacité de stockage à l'aide de quotas.

* *Intégration VMware.* les outils ONTAP pour VMware vSphere fournissent un plug-in vCenter pour le provisionnement des datastores, la mise en œuvre des meilleures pratiques de l'hôte vSphere et la surveillance des ressources ONTAP.
+
ONTAP prend en charge les API vStorage pour l'intégration de baies (VAAI) pour transférer les opérations SCSI/fichiers vers la baie de stockage. ONTAP prend également en charge les API vStorage pour Storage Awareness (VASA) et les volumes virtuels pour les protocoles de niveau bloc et fichier.

+
Le plug-in SnapCenter pour VMware vSphere constitue un moyen simple de sauvegarder et restaurer les machines virtuelles à l'aide de la fonctionnalité Snapshot sur une baie de stockage.

+
ActiveIQ Unified Manager offre une visibilité complète sur le réseau de stockage, dans un environnement vSphere. Les administrateurs peuvent facilement identifier les problèmes de latence susceptibles de survenir dans les environnements de postes de travail virtuels hébergés sur ONTAP.

* *Conformité à la sécurité.* avec Active IQ Unified Manager, vous pouvez surveiller plusieurs systèmes ONTAP avec des alertes pour toute violation de stratégie.
* *Prise en charge multiprotocole.* ONTAP prend en charge les blocs (iSCSI, FC, FCoE et NVMe/FC), les fichiers (NFSv3, Protocoles de stockage NFSv4.1, SMB2.x et SMB3.x) et objet (S3).
* *Prise en charge de l'automatisation.* ONTAP fournit des modules API REST, Ansible et PowerShell pour automatiser les tâches avec le portail de gestion VDS.

