---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_management_portal.html 
keywords: VDS, Cloud Management, Portal 
summary: 'Le portail NetApp VDS Cloud Workspace Management Suite permet une gestion centralisée de différents déploiements VDS, notamment un site défini pour les utilisateurs sur site, les administrateurs, le catalogue d"applications et les événements utilisant des scripts. Le portail est également utilisé par les utilisateurs administratifs pour le provisionnement manuel des applications si nécessaire et pour se connecter à n"importe quel ordinateur pour le dépannage.' 
---
= Portail de gestion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Le portail NetApp VDS Cloud Workspace Management Suite est disponible https://manage.cloudworkspace.com/["ici"^] la version à venir est également disponible https://preview.manage.cloudworkspace.com/["ici"^].

Le portail permet une gestion centralisée de différents déploiements VDS, y compris un site défini pour les utilisateurs sur site, les utilisateurs administratifs, le catalogue d'applications et les événements avec script. Le portail est également utilisé par les utilisateurs administratifs pour le provisionnement manuel des applications si nécessaire et pour se connecter à n'importe quel ordinateur pour le dépannage.

Les prestataires de services peuvent utiliser ce portail pour ajouter leurs propres partenaires de distribution et leur permettre de gérer leurs propres clients.

link:hcvdivds_user_management.html["Suivant : gestion des utilisateurs"]
