---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_application_management.html 
keywords: tech worker, application, Remote Desktop Services, VDS 
summary: 'Les employés chargés de tâches peuvent rapidement lancer une application à partir de la liste des applications mises à leur disposition. Les services d"application publient des applications à partir des hôtes de session Remote Desktop Services. Avec WVD, les groupes d"applications offrent des fonctionnalités similaires à partir de pools d"hôtes Windows 10 multi-session.' 
---
= Gestion des applications
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les employés chargés de tâches peuvent rapidement lancer une application à partir de la liste des applications mises à leur disposition. Les services d'application publient des applications à partir des hôtes de session Remote Desktop Services. Avec WVD, les groupes d'applications offrent des fonctionnalités similaires à partir de pools d'hôtes Windows 10 multi-session.

Pour les employés du bureau qui souhaitent pouvoir alimenter les utilisateurs, les applications dont ils ont besoin peuvent être provisionnées manuellement via un tableau de services ou provisionnées automatiquement à l'aide de la fonctionnalité d'événements scripts dans NetApp VDS.

Pour plus d'informations, reportez-vous à la section https://docs.netapp.com/us-en/virtual-desktop-service/guide_application_entitlement.html["Droits des applications NetApp"^].
