---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html 
keywords: TR-4861, VDS, Windows Virtual Desktop, Remote Desktop Services, Virtual Desktop Services, 
summary: 'VDS (Virtual Desktop Service) NetApp orchestre les services RDS (Remote Desktop Services) dans les principaux clouds publics et privés. VDS prend en charge Windows Virtual Desktop (WVD) sur Microsoft Azure. VDS automatise de nombreuses tâches à effectuer après le déploiement de WVD ou RDS, notamment la configuration des partages de fichiers SMB (pour les profils d"utilisateurs, les données partagées et le disque dur domestique des utilisateurs), l"activation des fonctionnalités Windows, de l"installation des applications et des agents, du pare-feu et des règles, etc.' 
---
= Tr-4861 : VDI dans le cloud hybride avec service de postes de travail virtuels
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


T echnologiques Suresh, NetApp

[role="lead"]
VDS (Virtual Desktop Service) NetApp orchestre les services RDS (Remote Desktop Services) dans les principaux clouds publics et privés. VDS prend en charge Windows Virtual Desktop (WVD) sur Microsoft Azure. VDS automatise de nombreuses tâches à effectuer après le déploiement de WVD ou RDS, notamment la configuration des partages de fichiers SMB (pour les profils d'utilisateurs, les données partagées et le disque dur domestique des utilisateurs), l'activation des fonctionnalités Windows, de l'installation des applications et des agents, du pare-feu et des règles, etc.

Les utilisateurs consomment VDS pour les postes de travail dédiés, les postes de travail partagés et les applications distantes. VDS fournit des événements utilisant des scripts pour automatiser la gestion des applications des bureaux et réduit le nombre d'images à gérer.

VDS fournit un portail de gestion unique pour la gestion des déploiements dans des environnements clouds publics et privés.



== En valeur pour le client

Avec l'explosion de 2020 000 employés, les exigences de continuité de l'activité ont changé. Les départements INFORMATIQUES sont confrontés à de nouveaux challenges qui doivent provisionner rapidement les postes de travail virtuels. Par conséquent, ils nécessitent une agilité du provisionnement, une gestion à distance et les avantages en termes de coût total de possession d'un cloud hybride qui simplifie le provisionnement des ressources sur site et dans le cloud. Ils ont besoin d'une solution de cloud hybride qui :

* Répond à la réalité de l'espace de travail post-COVID pour mettre en place des modèles de travail flexibles dotés de dynamiques mondiales
* Favorise le travail par équipe en simplifiant et en accélérant le déploiement d'environnements de travail pour tous les employés, des travailleurs chargés de tâches aux utilisateurs intensifs
* Mobilise vos équipes en fournissant des ressources VDI riches et sécurisées, quel que soit l'emplacement physique
* Simplifie le déploiement du cloud hybride
* Automatise et simplifie la gestion de la réduction des risques

