---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_solutions_for_industry.html 
keywords: GPU, Azure, NVIDIA, Tesla M60, 
summary: 'Les postes de travail graphiques sont généralement utilisés dans des secteurs tels que l"industrie, la santé, l"énergie, les médias et le divertissement, l"éducation, accidentelle, etc. La mobilité est souvent limitée pour les applications graphiques.' 
---
= Solutions industrielles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Les postes de travail graphiques sont généralement utilisés dans des secteurs tels que l'industrie, la santé, l'énergie, les médias et le divertissement, l'éducation, accidentelle, etc. La mobilité est souvent limitée pour les applications graphiques.

Pour résoudre les problèmes de mobilité, les services de postes de travail virtuels proposent un environnement de postes de travail pour tous les types de collaborateurs, des travailleurs chargés des tâches aux utilisateurs experts, en utilisant des ressources matérielles dans le cloud ou avec NetApp HCI, et en proposant notamment des options de configurations de processeurs graphiques flexibles. VDS permet aux utilisateurs d'accéder à leur environnement de travail depuis n'importe où avec des ordinateurs portables, des tablettes et d'autres appareils mobiles.

Pour exécuter des charges de travail de fabrication avec des logiciels tels que ANSYS Fluent, ANSYS Mechanical, Autodesk AutoCAD, Autodesk Inventor, Autodesk 3ds Max, Dassault systèmes SOLIDWORKS, Dassault systèmes CATIA, PTC Creo, Siemens PLM NX, etc. En janvier 2021, les GPU disponibles sur différents clouds sont répertoriés dans le tableau suivant.

[cols="20,20,20,20,20"]
|===
| Modèle de GPU | Microsoft Azure | Google Compute (GCP) | Services Web Amazon (AWS) | Sur site (NetApp HCI) 


| NVIDIA M60 | Oui. | Oui. | Oui. | Non 


| NVIDIA T4 | Non | Oui. | Oui. | Oui. 


| NVIDIA P100 | Non | Oui. | Non | Non 


| NVIDIA P4 | Non | Oui. | Non | Non 
|===
Des sessions de postes de travail partagés avec d'autres utilisateurs et des postes de travail personnels dédiés sont également disponibles. Les postes de travail virtuels peuvent disposer de un à quatre processeurs graphiques ou utiliser des GPU partiels avec NetApp HCI. NVIDIA T4 est une carte graphique polyvalente qui répond aux demandes d'un large éventail de charges de travail des utilisateurs. Chaque carte graphique du NetApp HCI H615C dispose de 16 Go de mémoire tampon trame et de trois cartes par serveur. Le nombre d'utilisateurs pouvant être hébergés sur un seul serveur H615C dépend de la charge de travail de l'utilisateur.

[cols="25,25,25,25"]
|===
| Utilisateurs/serveur | Lumière (4 Go) | Moyen (8 Go) | Lourd (16 Go) 


| H615C | 12 | 6 | 3 
|===
Pour déterminer le type d'utilisateur, exécutez l'outil de profileur GPU lorsque les utilisateurs travaillent avec des applications exécutant des tâches types. Le profileur GPU capture les demandes en mémoire, le nombre d'affichages et la résolution dont les utilisateurs ont besoin. Vous pouvez ensuite choisir le profil vGPU qui répond à vos besoins.

Les postes de travail virtuels avec processeurs graphiques peuvent prendre en charge une résolution d'affichage pouvant atteindre 8 Ko. Par ailleurs, l'utilitaire nView permet de diviser un seul moniteur en régions pour travailler avec différents jeux de données.

Grâce au stockage de fichiers ONTAP, vous bénéficiez de nombreux avantages :

* Un seul espace de nom pouvant atteindre 20 po de stockage avec 400 milliards de fichiers, sans qu'il soit nécessaire d'effectuer des tâches d'administration
* Espace de noms pouvant s'étendre sur le globe avec un cache de fichiers global
* Colocation sécurisée avec le stockage NetApp géré
* La migration de données inactives vers des magasins d'objets à l'aide de NetApp FabricPool
* Statistiques rapides sur les fichiers et analytique du système de fichiers
* Évolutivité d'un cluster de stockage jusqu'à 24 nœuds pour de meilleures capacités et performances
* La possibilité de contrôler l'espace de stockage à l'aide de quotas, de performances garanties et des limites de QoS
* Sécurisation des données avec le chiffrement
* Répondre aux exigences générales de conformité et de protection des données
* Des options flexibles de continuité de l'activité


link:vdi-vds/hcvdivds_conclusion.html["Suivant: Conclusion"]
