---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_use_cases.html 
keywords: Use cases, target audience 
summary: 'La VDI hybride avec NetApp VDS permet aux fournisseurs de services et aux administrateurs des postes de travail virtuels d"étendre facilement les ressources à d"autres environnements clouds sans affecter les utilisateurs. La présence de ressources sur site sur NetApp HCI permet un meilleur contrôle des ressources GPU et permet d"étendre les nœuds de calcul ou de stockage à la demande.' 
---
= Cas d'utilisation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La VDI hybride avec NetApp VDS permet aux fournisseurs de services et aux administrateurs des postes de travail virtuels d'étendre facilement les ressources à d'autres environnements clouds sans affecter les utilisateurs. La présence de ressources sur site offre un meilleur contrôle des ressources et un large choix de solutions (calcul, GPU, stockage et réseau) pour répondre à la demande.

Cette solution s'applique aux cas d'utilisation suivants :

* Le cloud bursting permet aux postes de travail et aux applications distants de bénéficier de plus de demande croissante
* En réduisant le TCO des postes de travail et applications distants à longue durée d'exécution, et en les hébergeant sur site avec des ressources de processeurs graphiques et de stockage Flash
* Facilité de gestion des postes de travail et des applications distants dans les environnements clouds
* Bénéficiez de postes de travail et d'applications à distance en utilisant un modèle de logiciel en tant que service avec des ressources sur site




== Public visé

La solution cible plusieurs groupes d'utilisateurs :

* Les architectes EUC/VDI qui souhaitent comprendre les exigences d'un VDS hybride
* Partenaires NetApp qui voudraient aider les clients en termes de besoins en termes d'applications et de postes de travail distants
* Clients NetApp HCI existants qui souhaitent répondre aux besoins des applications et des postes de travail à distance

