---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: 'Lors de l"utilisation d"un H610C ou d"une technologie H615C, la licence du GPU doit être obtenue auprès des partenaires NVIDIA autorisés à revendre les licences.' 
---
= Les licences NVIDIA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Lors de l'utilisation d'un H610C ou d'une technologie H615C, la licence du GPU doit être obtenue auprès des partenaires NVIDIA autorisés à revendre les licences. Vous pouvez trouver des partenaires NVIDIA avec le https://www.nvidia.com/object/partner-locator.html["outil de recherche de partenaires"^]. Recherchez des compétences telles que Virtual GPU (vGPU) ou Tesla.

Le logiciel NVIDIA vGPU est disponible en quatre éditions :

* NVIDIA GRID Virtual PC (GRID VPC)
* NVIDIA GRID Virtual applications (vApps)
* Station de travail NVIDIA Quadro Virtual Data Center (Quadro VDWS)
* NVIDIA Virtual ComputeServer (vComputeServer)




== PC virtuel GRID

Ce produit est idéal pour les utilisateurs qui recherchent un poste de travail virtuel offrant une expérience utilisateur exceptionnelle pour les applications Microsoft Windows, les navigateurs, la vidéo haute définition et la prise en charge multi-moniteurs. La solution NVIDIA GRID Virtual PC offre une expérience native dans un environnement virtualisé, ce qui vous permet d'exécuter toutes les applications de votre PC à des performances optimales.



== APPLICATIONS virtuelles DE GRID

Les vApps DU GRID sont destinées aux entreprises qui déploient un hôte de session de bureau à distance (RDSH) ou d'autres solutions de streaming au niveau des applications ou des sessions. Conçus pour fournir des applications Microsoft Windows à des performances maximales, les postes de travail RDSH hébergés par Windows Server sont également pris en charge par les vApps DU GRID.



== Station de travail Quadro Virtual Data Center

Cette édition est idéale pour les concepteurs grand public et haut de gamme qui utilisent de puissantes applications de création de contenu 3D comme Dassault CATIA, SOLIDWORKS, 3Dexcite, Siemens NX, PTC, Creo Schlumberger Petrel ou Autodesk Maya. La carte NVIDIA Quadro VDWS permet aux utilisateurs d'accéder à leurs applications graphiques professionnelles, avec des fonctionnalités et des performances complètes, partout sur n'importe quel périphérique.



== NVIDIA Virtual ComputeServer

De nombreuses entreprises exécutent des charges de travail serveur gourmandes en ressources système, telles que l'intelligence artificielle (IA), l'apprentissage profond (AP) et la data science. Pour ces cas d'utilisation, le logiciel NVIDIA vComputeServer virtualise le processeur graphique NVIDIA, qui accélère les charges de travail serveur intensives en ressources de calcul grâce à des fonctionnalités telles que le code de correction d'erreur, le retrait de page, la liaison peer-to-peer sur NVLink et le multivGPU.


NOTE: Une licence Quadro VDWS vous permet d'utiliser GRID VPC et NVIDIA vComputeServer.

link:hcvdivds_deployment.html["Suivant : déploiement"]
