---
sidebar: sidebar 
permalink: vdi-vds/vdi-index.html 
keywords: vdi, vds, virtual desktop, end use computing, 
summary: 'Les employés chargés de tâches peuvent rapidement lancer une application à partir de la liste des applications mises à leur disposition. Les services d"application publient des applications à partir des hôtes de session Remote Desktop Services. Avec WVD, les groupes d"applications offrent des fonctionnalités similaires à partir de pools d"hôtes Windows 10 multi-session.' 
---
= Solutions d'end-user computing (EUC) et d'infrastructure de postes de travail virtuels (VDI)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Que vous déployiez des postes de travail virtuels sur site ou dans le cloud, NetApp propose une multitude de solutions EUC/VDI pour répondre à vos besoins.



== NetApp Virtual Desktop Services (VDS)

VDS (Virtual Desktop Service) NetApp orchestre les services RDS (Remote Desktop Services) dans les principaux clouds publics et privés.

Solutions disponibles pour VDS :

* link:hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html["VDI cloud hybride avec NetApp Virtual Desktop Service"]




== End-User Computing avec VMware Horizon

NetApp a vérifié les architectures pour VMware Horizon couvrant plusieurs configurations de calcul. Les solutions disponibles incluent :

* link:https://www.netapp.com/pdf.html?item=/media/7121-nva1132design.pdf["End-User Computing avec VMware (Guide de conception)"]
* link:https://www.netapp.com/us/media/nva-1129-design.pdf["End-User Computing avec VMware et processeurs graphiques NVIDIA (Guide de conception)"]
* link:https://www.netapp.com/us/media/nva-1129-deploy.pdf["End-User Computing avec VMware et processeurs graphiques NVIDIA (Guide de déploiement)"]
* link:https://www.netapp.com/us/media/tr-4792.pdf["End-user computing avec VMware pour les graphiques 3D"]

