---
sidebar: sidebar 
permalink: virtualization/vmware-vcf-overview.html 
keywords: netapp, vmware, cloud, foundation, vcf, flexpod 
summary:  
---
= Socle cloud VMware
:allow-uri-read: 




== Socle cloud VMware

[role="lead"]
VMware Cloud Foundation (VCF) est un ensemble de technologies qui facilite l'accès à une expérience de cloud hybride. Dans la solution VCF, la prise en charge est assurée pour les workloads Kubernetes natifs et basés sur des machines virtuelles. Les services essentiels comme VMware vSphere, VMware VSAN, VMware NSX-T Data Center et VMware vRealize Cloud Management font partie intégrante du package VCF. Ces services permettent ainsi d'établir une infrastructure Software-defined capable de gérer le calcul, le stockage, la mise en réseau, la sécurité et la gestion du cloud. Cette infrastructure collective offre une expérience hybride dans laquelle la structure VCF étend l'environnement du data Center sur site à Amazon Web Services (AWS), Azure et Google Cloud.



=== Ressources de documentation

Pour plus d'informations sur les offres NetApp pour VMware Cloud Foundation, consultez la série de blogs à quatre (4) parties :

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-getting-started/["NetApp et VMware Cloud Foundation en toute simplicité 1re partie : mise en route"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-ontap-principal-storage/["La Fondation NetApp et VMware Cloud en toute simplicité 2e partie : stockage principal VCF et ONTAP"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-element-principal-storage/["La base du cloud NetApp et VMware est simplifiée partie 3 : stockage principal VCF et Element"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-supplemental-storage/["NetApp et VMware Cloud Foundation en toute simplicité - partie 4 : Outils ONTAP pour VMware et stockage supplémentaire"]


*Solutions NetApp FlexPod pour VMware Cloud Foundation*

* link:https://www.netapp.com/blog/expanding-flexpod-hybrid-cloud-with-vmware-cloud-foundation/["L'extension du cloud hybride FlexPod avec VMware Cloud Foundation"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf.html["FlexPod en tant que domaine de charge de travail pour VMware Cloud Foundation"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf_design.html["Guide de conception de la base FlexPod en tant que domaine de charge de travail pour VMware Cloud"]

