---
sidebar: sidebar 
permalink: virtualization/vmware-vsphere8-intro.html 
keywords: vSphere, vSphere 8, vSphere 8u1, ONTAP 9.12, interoperability, VMware compatibility 
summary:  
---
= Nouveautés de VMware vSphere 8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Auteur : Chris Reno, Ingénierie de solutions NetApp

L'intégration des technologies NetApp et VMware a une expérience acquise au cours des 20 dernières années et pendant des milliers d'heures d'ingénierie. Avec l'avènement de vSphere 8 et de ONTAP 9.12, les deux entreprises fournissent des produits qui répondent aux charges de travail les plus exigeantes. Lorsque ces produits sont combinés dans des solutions, sont de véritables problématiques client résolues, que ce soit sur site ou dans les clouds publics. Lorsque ces produits sont combinés dans des solutions, les challenges des clients sont résolus, que ce soit sur site ou dans les clouds publics.

Pour vous aider à déterminer les capacités de support des produits, des protocoles, des systèmes d'exploitation, etc., veuillez consulter les ressources ci-dessous :

* Le https://["Matrice d'interopérabilité NetApp"] (IMT). La IMT définit les composants et versions qualifiés que vous pouvez utiliser pour créer des configurations FC/FCoE, iSCSI, NFS et CIFS, ainsi que des intégrations avec des plug-ins et des offres logicielles supplémentaires.
* Le https://["Guide de compatibilité VMware"]. Le Guide de compatibilité VMware répertorie les systèmes, les E/S, le stockage/SAN, la compatibilité des sauvegardes et bien plus encore avec VMware Infrastructure et les logiciels.
* https://["Outils NetApp ONTAP pour VMware"]. Les outils ONTAP pour VMware vSphere sont un plug-in vCenter Server unique qui inclut des extensions Virtual Storage Console (VSC), VASA Provider et Storage Replication adapter (SRA). Entièrement pris en charge par VMware vSphere 8, OTV 9.12 apporte quotidiennement de la valeur ajoutée aux clients.




== Versions prises en charge par NetApp ONTAP et VMware


NOTE: Veuillez laisser les pages se développer lorsque vous sélectionnez un lien dans les tableaux ci-dessous.

|===


| *VMware vSphere version* | *SAN* | *NFS* | *OTV* | *SnapCenter* 


| *VSphere 8* | https://["Lien"] | https://["Lien"] | https://["Lien"] | https://["Lien"] 


| *VSphere 8u1* | https://["Lien"] | https://["Lien"] | - | - 
|===
|===


| *VMware vSphere version* | *Système de stockage / protocoles* | *OTV - SRA* | *OTV – VASA Provider* | *Plug-in SnapCenter pour VMware vSphere* 


| *VSphere 8* | https://["Lien"] | https://["Lien"] | https://["Lien"] | https://["Lien"] 


| *VSphere 8u1* | https://["Lien"] | - | - | https://["Lien"] 
|===