---
sidebar: sidebar 
permalink: virtualization/vsphere_admin_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 'Cette page décrit les meilleures pratiques relatives à l"implémentation d"une solution de stockage NetApp ONTAP dans un environnement VMware vSphere.' 
---
= Introduction à ONTAP pour les administrateurs vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Pourquoi choisir ONTAP pour vSphere ?

NetApp ONTAP simplifie les opérations de stockage et de gestion des données et complète distinctement les environnements VMware, que ce soit lors du déploiement sur site ou dans le cloud. Parmi les raisons qui ont poussé des dizaines de milliers de clients à choisir ONTAP comme solution de stockage pour les déploiements vSphere, on compte notamment la protection des données, des innovations en termes d'efficacité du stockage et des performances exceptionnelles dans les architectures VMware basées sur SAN et NAS.

NetApp fournit de nombreux plug-ins, validations et qualifications VMware de différents produits VMware pour aider les clients confrontés aux défis uniques liés à l'administration d'un environnement de virtualisation. NetApp est destiné à la gestion du stockage et des données ce que VMware fait pour la virtualisation, ce qui permet aux clients de se concentrer sur leurs compétences principales plutôt que sur la gestion du stockage physique. Ce partenariat de près de 20 ans entre VMware et NetApp continue d'évoluer et d'apporter de la valeur ajoutée au client à mesure que de nouvelles technologies comme VMware Cloud Foundation et Tanzu émergent, tout en continuant à prendre en charge la base de vSphere.

Principaux facteurs dont les clients sont :

* *Stockage unifié*
* *Efficacité du stockage*
* *Volumes virtuels et gestion basée sur des stratégies de stockage*
* *Cloud hybride*


Pour plus d'informations sur les solutions NetApp et VMware prises en charge, consultez les ressources suivantes :

* https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp"^] (IMT). Le système IMT définit les composants et les versions qui peuvent être utilisés pour créer des configurations FC/FCoE, iSCSI, NFS et CIFS.
* https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guide de compatibilité VMware"^]. Le guide de compatibilité VMware répertorie la compatibilité système, E/S, stockage/SAN et sauvegarde avec les produits logiciels et infrastructures VMware
* https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/["Outils NetApp ONTAP pour VMware"^]. Les outils ONTAP pour VMware vSphere sont un plug-in vCenter Server unique, notamment les extensions VSC, VASA Provider et Storage Replication adapter (SRA).

