---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Cette page contient des vidéos et des didacticiels. 
---
= Vidéos et démonstrations de virtualisation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Visionnez les vidéos et démonstrations suivantes portant sur des fonctionnalités spécifiques des solutions de cloud hybride, de virtualisation et de conteneurs.

.Outils NetApp ONTAP pour VMware vSphere
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Outils ONTAP pour VMware - Présentation

 a| 
Provisionnement des datastores iSCSI VMware avec ONTAP

 a| 
Provisionnement des datastores VMware NFS avec ONTAP


|===
====
.VMware Cloud sur AWS avec AWS FSX pour NetApp ONTAP
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Stockage connecté à un invité Windows avec ONTAP FSX utilisant iSCSI

 a| 
Stockage connecté par un invité Linux avec FSX ONTAP à l'aide de NFS

 a| 
Économies en termes de coût total de possession de VMware Cloud sur AWS avec Amazon FSX pour NetApp ONTAP




 a| 
VMware Cloud sur AWS datastore supplémentaire avec Amazon FSX pour NetApp ONTAP

 a| 
Déploiement et configuration de VMware HCX pour VMC

 a| 
Démonstration de la migration VMotion avec VMware HCX pour VMC et FSxN




 a| 
Démonstration de la migration à froid avec VMware HCX pour VMC et FSxN

 a| 
 a| 

|===
====
.Azure VMware Services sur Azure avec Azure NetApp Files (ANF)
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Solution Azure VMware datastore supplémentaire avec Azure NetApp Files

 a| 
Solution de reprise après incident Azure VMware avec Cloud Volumes ONTAP, SnapCenter et JetStream

 a| 
Démonstration de la migration à froid avec VMware HCX pour AVS et ANF




 a| 
Démonstration de VMotion avec VMware HCX pour AVS et ANF

 a| 
Démonstration de la migration en bloc avec VMware HCX pour AVS et ANF

 a| 

|===
====
.Plug-in SnapCenter pour VMware vSphere
[%collapsible]
====
Le logiciel SnapCenter est une plateforme qui permet de coordonner et de gérer facilement et en toute sécurité la protection de vos données sur l'ensemble des applications, bases de données et systèmes de fichiers.

Le plug-in SnapCenter pour VMware vSphere vous permet d'effectuer des sauvegardes, des restaurations et des liaisons pour les machines virtuelles, ainsi que des opérations de sauvegarde et de montage pour les datastores enregistrés auprès de SnapCenter directement dans VMware vCenter.

Pour plus d'informations sur le plug-in NetApp SnapCenter pour VMware vSphere, consultez le link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Présentation du plug-in NetApp SnapCenter pour VMware vSphere"].

[cols="5a, 5a, 5a"]
|===


 a| 
Plug-in SnapCenter pour VMware vSphere : conditions requises pour la solution

 a| 
Plug-in SnapCenter pour VMware vSphere : déploiement

 a| 
Plug-in SnapCenter pour VMware vSphere - Workflow de sauvegarde




 a| 
Plug-in SnapCenter pour VMware vSphere : restaurez les flux de travail

 a| 
SnapCenter - flux de travail de restauration SQL

 a| 

|===
====
.NetApp avec VMware Tanzu
[%collapsible]
====
VMware Tanzu permet aux clients de déployer, d'administrer et de gérer leur environnement Kubernetes via vSphere ou VMware Cloud Foundation. Cette gamme de produits VMware permet aux clients de gérer tous leurs clusters Kubernetes pertinents à partir d'un seul plan de contrôle en choisissant l'édition VMware Tanzu qui répond le mieux à leurs besoins.

Pour plus d'informations sur VMware Tanzu, reportez-vous au https://tanzu.vmware.com/tanzu["Présentation de VMware Tanzu"^]. Cette revue couvre les cas d'utilisation, les ajouts disponibles et plus d'informations sur VMware Tanzu.

[cols="5a, 5a, 5a"]
|===


 a| 
Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 1

video::ZtbXeOJKhrc[youtube,width=360] a| 
Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 2

video::FVRKjWH7AoE[youtube,width=360] a| 
Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 3

video::Y-34SUtTTtU[youtube,width=360]
|===
====