---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: Cette page contient des vidéos et des didacticiels. 
---
= Vidéos et démonstrations de virtualisation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Visionnez les vidéos et démonstrations suivantes portant sur des fonctionnalités spécifiques des solutions de cloud hybride, de virtualisation et de conteneurs.

.Outils NetApp ONTAP pour VMware vSphere
[%collapsible]
====
.Outils ONTAP pour VMware - Présentation
video::d2ac19ba-28c4-4c07-8724-b01200f99845[panopto]
.Provisionnement des datastores iSCSI VMware avec ONTAP
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.Provisionnement des datastores VMware NFS avec ONTAP
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.VMware Cloud sur AWS avec AWS FSX pour NetApp ONTAP
[%collapsible]
====
.Stockage connecté à un invité Windows avec ONTAP FSX utilisant iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Stockage connecté par un invité Linux avec FSX ONTAP à l'aide de NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Économies en termes de coût total de possession de VMware Cloud sur AWS avec Amazon FSX pour NetApp ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.VMware Cloud sur AWS datastore supplémentaire avec Amazon FSX pour NetApp ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.Déploiement et configuration de VMware HCX pour VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Démonstration de la migration VMotion avec VMware HCX pour VMC et FSxN
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Démonstration de la migration à froid avec VMware HCX pour VMC et FSxN
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Azure VMware Services sur Azure avec Azure NetApp Files (ANF)
[%collapsible]
====
.Solution Azure VMware datastore supplémentaire avec Azure NetApp Files
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Solution de reprise après incident Azure VMware avec Cloud Volumes ONTAP, SnapCenter et JetStream
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.Démonstration de la migration à froid avec VMware HCX pour AVS et ANF
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.Démonstration de VMotion avec VMware HCX pour AVS et ANF
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.Démonstration de la migration en bloc avec VMware HCX pour AVS et ANF
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.Plug-in SnapCenter pour VMware vSphere
[%collapsible]
====
Le logiciel SnapCenter est une plateforme qui permet de coordonner et de gérer facilement et en toute sécurité la protection de vos données sur l'ensemble des applications, bases de données et systèmes de fichiers.

Le plug-in SnapCenter pour VMware vSphere vous permet d'effectuer des sauvegardes, des restaurations et des liaisons pour les machines virtuelles, ainsi que des opérations de sauvegarde et de montage pour les datastores enregistrés auprès de SnapCenter directement dans VMware vCenter.

Pour plus d'informations sur le plug-in NetApp SnapCenter pour VMware vSphere, consultez le link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Présentation du plug-in NetApp SnapCenter pour VMware vSphere"].

.Plug-in SnapCenter pour VMware vSphere : conditions requises pour la solution
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.Plug-in SnapCenter pour VMware vSphere : déploiement
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.Plug-in SnapCenter pour VMware vSphere - Workflow de sauvegarde
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.Plug-in SnapCenter pour VMware vSphere : restaurez les flux de travail
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - flux de travail de restauration SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.3-2-1 Solutions de protection des données
[%collapsible]
====
Les solutions de protection des données 3-2-1 combinent les sauvegardes primaires et secondaires sur site, à l'aide de la technologie SnapMirror, avec les copies répliquées vers le stockage objet à l'aide de la sauvegarde et de la restauration BlueXP.

.3-2-1 protection des données pour les datastores VMFS avec le plug-in SnapCenter pour VMware vSphere et la sauvegarde et restauration BlueXP pour les machines virtuelles
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.NetApp avec VMware Tanzu
[%collapsible]
====
VMware Tanzu permet aux clients de déployer, d'administrer et de gérer leur environnement Kubernetes via vSphere ou VMware Cloud Foundation. Cette gamme de produits VMware permet aux clients de gérer tous leurs clusters Kubernetes pertinents à partir d'un seul plan de contrôle en choisissant l'édition VMware Tanzu qui répond le mieux à leurs besoins.

Pour plus d'informations sur VMware Tanzu, reportez-vous au https://tanzu.vmware.com/tanzu["Présentation de VMware Tanzu"^]. Cette revue couvre les cas d'utilisation, les ajouts disponibles et plus d'informations sur VMware Tanzu.

.Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 1
video::ZtbXeOJKhrc[youtube,width=360]
.Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 2
video::FVRKjWH7AoE[youtube,width=360]
.Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 3
video::Y-34SUtTTtU[youtube,width=360]
====
.NetApp Cloud Insights
[%collapsible]
====
NetApp Cloud Insights est une plateforme complète de surveillance et d'analytique conçue pour fournir la visibilité et le contrôle sur votre infrastructure sur site et dans le cloud.

.NetApp Cloud Insights : l'observabilité pour le data Center moderne
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====