---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Cette page contient des vidéos et des didacticiels. 
---
= Vidéos et démonstrations sur le cloud hybride, la virtualisation et les conteneurs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Visionnez les vidéos et démonstrations suivantes portant sur des fonctionnalités spécifiques des solutions de cloud hybride, de virtualisation et de conteneurs.

.Outils NetApp ONTAP pour VMware vSphere
====
.Outils ONTAP pour VMware - Présentation
=====
video::otv_overview.mp4[]
=====
.Provisionnement des datastores iSCSI VMware avec ONTAP
=====
video::otv_iscsi_provision.mp4[]
=====
.Provisionnement des datastores VMware NFS avec ONTAP
=====
video::otv_nfs_provision.mp4[]
=====
====
.VMware Cloud sur AWS avec AWS FSX pour NetApp ONTAP
====
.Stockage connecté à un invité Windows avec ONTAP FSX utilisant iSCSI
=====
video::vmc_windows_vm_iscsi.mp4[]
=====
.Stockage connecté par un invité Linux avec FSX ONTAP à l'aide de NFS
=====
video::vmc_linux_vm_nfs.mp4[]
=====
.Économies en termes de coût total de possession de VMware Cloud sur AWS avec Amazon FSX pour NetApp ONTAP
=====
video::FSxN-NFS-Datastore-on-VMC-TCO-calculator.mp4[]
=====
.VMware Cloud sur AWS datastore supplémentaire avec Amazon FSX pour NetApp ONTAP
=====
video::FSxN-NFS-Datastore-on-VMC.mp4[]
=====
.VMware Cloud sur AWS migration avec FSxN, VMware HCX
=====
video::VMC_HCX_Setup.mp4[]
video::Migration_HCX_VMC_FSxN_VMotion.mp4[]
video::Migration_HCX_VMC_FSxN_cold_migration.mp4[]
=====
====
.Azure VMware Services sur Azure avec Azure NetApp Files (ANF)
====
.Solution Azure VMware datastore supplémentaire avec Azure NetApp Files
=====
video::ANF-NFS-datastore-on-AVS.mp4[]
=====
.Solution de reprise après incident Azure VMware avec Cloud Volumes ONTAP, SnapCenter et JetStream
=====
video::AVS-guest-connect-DR-use-case.mp4[]
=====
.Migration de la solution Azure VMware avec ANF, VMware HCX
=====
video::Migration_HCX_AVS_ANF_ColdMigration.mp4[]
video::Migration_HCX_AVS_ANF_VMotion.mp4[]
video::Migration_HCX_AVS_ANF_Bulk.mp4[]
=====
====
.Plug-in SnapCenter pour VMware vSphere
====
Le logiciel SnapCenter est une plateforme qui permet de coordonner et de gérer facilement et en toute sécurité la protection de vos données sur l'ensemble des applications, bases de données et systèmes de fichiers.

Le plug-in SnapCenter pour VMware vSphere vous permet d'effectuer des sauvegardes, des restaurations et des liaisons pour les machines virtuelles, ainsi que des opérations de sauvegarde et de montage pour les datastores enregistrés auprès de SnapCenter directement dans VMware vCenter.

Pour plus d'informations sur le plug-in NetApp SnapCenter pour VMware vSphere, consultez le link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Présentation du plug-in NetApp SnapCenter pour VMware vSphere"].

.Plug-in SnapCenter pour VMware vSphere : conditions requises pour la solution
=====
video::scv_prereq_overview.mp4[]
=====
.Plug-in SnapCenter pour VMware vSphere : déploiement
=====
video::scv_deployment.mp4[]
=====
.Plug-in SnapCenter pour VMware vSphere - Workflow de sauvegarde
=====
video::scv_backup_workflow.mp4[]
=====
.Plug-in SnapCenter pour VMware vSphere : restaurez les flux de travail
=====
video::scv_restore_workflow.mp4[]
=====
.SnapCenter - flux de travail de restauration SQL
=====
video::scv_sql_restore.mp4[]
=====
====
.NetApp avec VMware Tanzu
====
VMware Tanzu permet aux clients de déployer, d'administrer et de gérer leur environnement Kubernetes via vSphere ou VMware Cloud Foundation. Cette gamme de produits VMware permet aux clients de gérer tous leurs clusters Kubernetes pertinents à partir d'un seul plan de contrôle en choisissant l'édition VMware Tanzu qui répond le mieux à leurs besoins.

Pour plus d'informations sur VMware Tanzu, reportez-vous au https://tanzu.vmware.com/tanzu["Présentation de VMware Tanzu"^]. Cette revue couvre les cas d'utilisation, les ajouts disponibles et plus d'informations sur VMware Tanzu.

* https://www.youtube.com/watch?v=ZtbXeOJKhrc["Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 1"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 2"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["Comment utiliser vvols avec NetApp et VMware Tanzu Basic, partie 3"^]


====
.NetApp avec Red Hat OpenShift
====
Red Hat OpenShift, une plateforme Kubernetes d'entreprise, vous permet d'exécuter des applications basées sur des conteneurs avec une stratégie de cloud hybride ouverte. Disponible en tant que service cloud sur des clouds publics de premier plan ou en tant que logiciel autogéré, Red Hat OpenShift offre aux clients la flexibilité dont ils ont besoin pour concevoir leur solution basée sur des conteneurs.

Pour plus d'informations sur Red Hat OpenShift, consultez ce document https://www.redhat.com/en/technologies/cloud-computing/openshift["Présentation de Red Hat OpenShift"^]. Pour en savoir plus sur Red Hat OpenShift, consultez également la documentation produit et les options de déploiement.

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["Migration des charges de travail - Red Hat OpenShift avec NetApp"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["Red Hat OpenShift Deployment sur RHV : Red Hat OpenShift avec NetApp"^]


====