---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_conclusion.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, vcenter, disaster 
summary: VMware vCenter site Recovery Manager est une offre de reprise après incident qui assure une orchestration automatisée et des tests sans interruption de plans de reprise après incident centralisés, afin de simplifier la gestion de la reprise après incident pour toutes les applications virtualisées. 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


VMware vCenter site Recovery Manager est une offre de reprise après incident qui assure une orchestration automatisée et des tests sans interruption de plans de reprise après incident centralisés, afin de simplifier la gestion de la reprise après incident pour toutes les applications virtualisées.

En déployant SRM sur les systèmes NetApp ONTAP, vous pouvez considérablement réduire les coûts et la complexité de la reprise après incident. Grâce à ses dispositifs de stockage évolutifs, haute performance et faciles à gérer, et à ses offres logicielles robustes, NetApp offre des solutions flexibles de gestion du stockage et des données qui prennent en charge les environnements vSphere.

Les recommandations et les meilleures pratiques fournies dans ce guide ne sont pas une solution universelle. Ce document comprend un ensemble de meilleures pratiques et de recommandations qui vous aident à planifier, déployer et gérer vos plans de reprise après incident SRM. Consultez un expert VMware local NetApp pour planifier et déployer des environnements VMware vCenter site Recovery sur du stockage NetApp. Les experts NetApp VMware peuvent rapidement identifier les besoins et demandes des environnements vSphere et adapter la solution de stockage en conséquence.
