---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_additional_information.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, additional, information 
summary: Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web. 
---
= Informations supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Tr-4597 : VMware vSphere pour ONTAPhttps://["https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html"^]
* Tr-4400 : volumes virtuels VMware vSphere avec ONTAPhttps://["https://www.netapp.com/pdf.html?item=/media/13555-tr4400.pdf"^]
* Tr-4015 Guide des meilleures pratiques en matière de configuration de SnapMirror pour ONTAP 9https://[]
* Créateur d'utilisateurs RBAC pour ONTAPhttps://["https://mysupport.netapp.com/site/tools/tool-eula/rbac"^]
* Outils ONTAP pour les ressources VMware vSpherehttps://["https://mysupport.netapp.com/site/products/all/details/otv/docsandkb-tab"^]
* Documentation VMware site Recovery Managerhttps://["https://docs.vmware.com/en/Site-Recovery-Manager/index.html"^]


Reportez-vous à la http://["Matrice d'interopérabilité (IMT)"^] Le site de support NetApp vous assure que les versions de produits et de fonctionnalités mentionnées dans le présent document sont prises en charge par votre environnement. NetApp IMT définit les composants et versions de produits qu'il est possible d'utiliser pour créer des configurations prises en charge par NetApp. Les résultats spécifiques dépendent de l'installation de chaque client conformément aux spécifications publiées.
