---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_conclusion.html 
keywords: bare metal, infrastructure, stateful, Trident 
summary: 'Anthos sur un système bare Metal avec NetApp offre une plateforme robuste pour exécuter efficacement des charges de travail basées sur des conteneurs en permettant la personnalisation de l"infrastructure déployée.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Anthos sur un système bare Metal avec NetApp offre une plateforme robuste pour exécuter efficacement des charges de travail basées sur des conteneurs en permettant la personnalisation de l'infrastructure déployée. Les clients peuvent utiliser l'infrastructure de serveur et le système d'exploitation pris en charge de leur choix, ou même déployer la solution au sein de leur infrastructure existante. La puissance et la flexibilité de ces environnements s'améliorent considérablement grâce à l'intégration de NetApp ONTAP et de NetApp Astra Trident, qui prennent en charge les workloads applicatifs avec état en provisionnant et en gérant efficacement le stockage persistant pour les conteneurs. En étendant le potentiel de Google Cloud à leur data Center optimisé par NetApp, vous bénéficiez d'une solution Kubernetes entièrement prise en charge, extrêmement disponible, facilement évolutive et entièrement gérée pour le développement et la production de vos workloads applicatifs.

link:bmanthos_where_to_find_additional_information.html["Suivant : où trouver des informations supplémentaires ?"]
