---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: 'NetApp et Google Cloud se sont solides depuis plusieurs années, et NetApp a d"abord lancé des services de données cloud vers Google Cloud avec Cloud Volumes ONTAP et Cloud Volumes Service. Cette relation a ensuite été développée en validant la plateforme NetApp HCI pour être utilisée avec Google Cloud Anthos sur site, une solution Kubernetes multicloud hybride basée sur hyperviseur et déployée sur VMware vSphere. NetApp a ensuite réussi la qualification Anthos Ready pour NetApp Astra Trident, ONTAP et le protocole NFS, afin de fournir un stockage persistant dynamique pour les conteneurs.' 
---
= WP-7337 : Anthos sur les métaux nus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Alan Cowles et Nikhil M Kulkarni, NetApp

NetApp et Google Cloud se sont solides depuis plusieurs années, et NetApp a lancé pour la première fois des services de données cloud pour Google Cloud avec Cloud Volumes ONTAP et Cloud Volumes Service. Cette relation a ensuite été développée en validant la plateforme NetApp HCI pour être utilisée avec Google Cloud Anthos sur site, une solution Kubernetes multicloud hybride basée sur hyperviseur et déployée sur VMware vSphere. NetApp a ensuite réussi la qualification Anthos Ready pour NetApp Astra Trident, ONTAP et le protocole NFS, afin de fournir un stockage persistant dynamique pour les conteneurs.

Anthos peut désormais être installée directement sur des serveurs bare-Metal dans l'environnement d'un client, ce qui offre une possibilité supplémentaire aux clients d'étendre Google Cloud à leurs data centers locaux sans hyperviseur. Avec les fonctionnalités du système d'exploitation du stockage NetApp ONTAP et de l'Astra Trident, vous pouvez étendre les fonctionnalités de votre plateforme en intégrant le stockage persistant pour les conteneurs.

Cette combinaison vous permet d'exploiter tout le potentiel de vos serveurs, de votre stockage et de vos ressources réseau, ainsi que l'assistance, les niveaux de service, la facturation mensuelle et la flexibilité à la demande offertes par Google Cloud. Comme vous utilisez votre propre matériel, votre réseau et votre stockage, vous bénéficiez d'un contrôle direct sur l'évolutivité des applications, la sécurité et la latence du réseau, tout en bénéficiant des avantages des applications gérées et conteneurisées de Anthos sur un système bare Metal.

link:bmanthos_solution_overview.html["Ensuite : présentation de la solution."]
