---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_solution_validation.html 
keywords: validation, google cloud, nginx 
summary: 'Le déploiement actuel de cette solution a été soumis à deux processus de validation rigoureux, à l"aide d"outils fournis par l"équipe Google Cloud.' 
---
= Validation des solutions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Le déploiement actuel de cette solution a été soumis à deux processus de validation rigoureux, à l'aide d'outils fournis par l'équipe Google Cloud. Ces validations incluent un sous-ensemble des tests suivants :

* Validation par les partenaires de la plateforme pour Anthos :
+
** Vérifiez que tous les services de plateforme Anthos sur système d'exploitation sont installés et exécutés.
** Faites évoluer vos ressources physiques sur un cluster bare Metal, passant de quatre nœuds workers à trois, puis à quatre.
** Créez et supprimez un espace de noms personnalisé.
** Créez un déploiement du serveur web Nginx, en faisant évoluer ce déploiement en augmentant le nombre de répliques.
** Créez une entrée pour l'application Nginx et vérifiez la connectivité en curling index.html.
** Nettoyez toutes les activités de la suite de tests avec succès et remettez le cluster en état de pré-test.


* Validation par les partenaires du stockage prêt pour Anthos :
+
** Créez un déploiement avec une demande de volume persistant.
** Utilisez NetApp Astra Trident pour provisionner et joindre le volume persistant demandé à NetApp ONTAP.
** Validez la capacité de détachement et de rattachement des volumes persistants.
** Valider l'accès multi-attacher et en lecture seule des volumes persistants à partir d'autres pods sur le nœud.
** Valider l'opération de redimensionnement du volume hors ligne.
** Vérifiez que le volume persistant survit à une opération de mise à l'échelle du cluster.




link:bmanthos_conclusion.html["Suivant: Conclusion."]
