= 
:allow-uri-read: 


. Configurer les informations d'identification.
. Créer des types d'informations d'identification. Pour les solutions impliquant ONTAP, vous devez configurer le type d'informations d'identification pour qu'il corresponde aux entrées de nom d'utilisateur et de mot de passe.
+
.. Accédez à Administration → types d'informations d'identification, puis cliquez sur Ajouter.
.. Indiquez le nom et la description.
.. Collez le contenu suivant dans la configuration d'entrée :
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: Destination Cluster Username
  - id: dst_cluster_password
    type: string
    label: Destination Cluster Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
----
.. Collez le contenu suivant dans Configuration d'injecteur, puis cliquez sur Enregistrer :
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
----


. Créer des informations d'identification pour ONTAP
+
.. Accédez à Ressources → informations d'identification, puis cliquez sur Ajouter.
.. Entrez le nom et les informations d'organisation des informations d'identification ONTAP
.. Sélectionnez le type d'informations d'identification créé à l'étape précédente.
.. Sous Détails du type, entrez le nom d'utilisateur et le mot de passe de vos clusters source et destination.
.. Cliquez sur Save


. Créez des informations d'identification pour Oracle
+
.. Accédez à Ressources → informations d'identification, puis cliquez sur Ajouter.
.. Entrez le nom et les détails de l'organisation pour Oracle
.. Sélectionnez le type d'informations d'identification de la machine.
.. Sous Détails du type, entrez le nom d'utilisateur et le mot de passe des hôtes Oracle.
.. Sélectionnez la méthode d'escalade des privilèges appropriée et saisissez le nom d'utilisateur et le mot de passe.
.. Cliquez sur Save
.. Répétez le processus si nécessaire pour une autre information d'identification pour l'hôte dr_oracle.



