= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS prend en charge le stockage NetApp dans les configurations suivantes :

* FSX ONTAP en tant que stockage invité connecté
* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* FSX ONTAP en tant que datastore NFS supplémentaire


Afficher les détails link:aws/aws-guest.html["Options de stockage à connexion invité pour VMC"]. Afficher les détails link:aws/aws-native-nfs-datastore-option.html["Options supplémentaires des datastores NFS pour VMC"].

Afficher les détails link:aws-guest.html["Options de stockage à connexion invité pour VMC"]. Afficher les détails link:aws-native-nfs-datastore-option.html["Options supplémentaires des datastores NFS pour VMC"].

--
.Azure/AVS
--
Azure prend en charge le stockage NetApp dans les configurations suivantes :

* Azure NetApp Files (ANF) comme stockage connecté invité
* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* Azure NetApp Files (ANF) comme datastore NFS supplémentaire^1^


Afficher les détails link:azure/azure-guest.html["Option de stockage avec connexion invité pour AVS"]. Afficher les détails link:azure/azure-native-nfs-datastore-option.html["Options supplémentaires de datastore NFS pour AVS"].

Afficher les détails link:azure-guest.html["Option de stockage avec connexion invité pour AVS"]. Afficher les détails link:azure-native-nfs-datastore-option.html["Options supplémentaires de datastore NFS pour AVS"].


NOTE: 1 - ANF en tant que datastore NFS supplémentaire pour AVS est actuellement en préversion publique. En savoir plus https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["ici"].

--
.GCP/GCVE
--
Google Cloud prend en charge le stockage NetApp dans les configurations suivantes :

* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* Cloud Volumes Service (CVS) comme stockage connecté invité
* Cloud Volumes Service (CVS) comme datastore NFS supplémentaire^1^


Afficher les détails link:gcp/gcp-guest.html["Options de stockage de connexion invité pour GCVE"].

Afficher les détails link:gcp-guest.html["Options de stockage de connexion invité pour GCVE"].

En savoir plus sur link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["Cloud Volumes Service (CVS) en tant que datastore NFS supplémentaire^1"^].


NOTE: 1 - actuellement en aperçu privé

--
====