= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS prend en charge le stockage NetApp dans les configurations suivantes :

* FSX ONTAP en tant que stockage invité connecté
* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* FSX ONTAP en tant que datastore NFS supplémentaire


Afficher les détails link:aws-guest.html["Options de stockage à connexion invité pour VMC"]. Afficher les détails link:aws-native-nfs-datastore-option.html["Options supplémentaires des datastores NFS pour VMC"].

Afficher les détails link:aws-guest.html["Options de stockage à connexion invité pour VMC"]. Afficher les détails link:aws-native-nfs-datastore-option.html["Options supplémentaires des datastores NFS pour VMC"].

--
.Azure/AVS
--
Azure prend en charge le stockage NetApp dans les configurations suivantes :

* Azure NetApp Files (ANF) comme stockage connecté invité
* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* Azure NetApp Files (ANF) comme datastore NFS supplémentaire


Afficher les détails link:azure-guest.html["Option de stockage avec connexion invité pour AVS"]. Afficher les détails link:azure-native-nfs-datastore-option.html["Options supplémentaires de datastore NFS pour AVS"].

Afficher les détails link:azure-guest.html["Option de stockage avec connexion invité pour AVS"]. Afficher les détails link:azure-native-nfs-datastore-option.html["Options supplémentaires de datastore NFS pour AVS"].

--
.GCP/GCVE
--
Google Cloud prend en charge le stockage NetApp dans les configurations suivantes :

* Cloud Volumes ONTAP (CVO) comme stockage connecté à l'invité
* Cloud Volumes Service (CVS) comme stockage connecté invité
* Cloud Volumes Service (CVS) comme datastore NFS supplémentaire


Afficher les détails link:gcp-guest.html["Options de stockage de connexion invité pour GCVE"].

Afficher les détails link:gcp-guest.html["Options de stockage de connexion invité pour GCVE"].

En savoir plus sur link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Prise en charge du datastore NetApp Cloud Volumes Service pour Google Cloud VMware Engine (blog NetApp)"^] ou link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Comment utiliser NetApp CVS en tant que datastores pour Google Cloud VMware Engine (blog Google)"^]

--
====