---
sidebar: sidebar 
permalink: databases/automation_ora_clone_lifecycle.html 
keywords: Database, Oracle, DataGuard, AWS, FSx ONTAP, Azure, ANF, 
summary: 'La solution fournit un kit d"outils d"automatisation basé sur Ansible pour la configuration, le clonage et l"actualisation des bases de données de clone Oracle à partir d"une base de données primaire. La base de données primaire peut être la base de données physique de secours dans la configuration d"Oracle Data Guard. La solution peut être appliquée dans un data Center privé, dans le cloud AWS avec le stockage FSX ONTAP en configuration NFS ou ASM, ou dans le cloud Azure avec stockage Azure NetApp Files en configuration NFS.' 
---
= SnapCenter automatisation du cycle de vie des clones Oracle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Allen Cao, Niyaz Mohamed, NetApp

[role="lead"]
La solution fournit un kit d'outils d'automatisation basé sur Ansible pour la configuration, le clonage et l'actualisation des bases de données de clone Oracle à partir d'une base de données primaire. La base de données primaire peut être la base de données physique de secours dans la configuration d'Oracle Data Guard. La solution peut être appliquée dans un data Center privé, dans le cloud AWS avec le stockage FSX ONTAP en configuration NFS ou ASM, ou dans le cloud Azure avec stockage Azure NetApp Files en configuration NFS.



== Objectif

Les clients apprécient la fonction FlexClone du stockage NetApp ONTAP : elle permet de cloner rapidement (en minutes) de grandes bases de données et de réaliser des économies de stockage supplémentaires si la fonctionnalité de clone dynamique est activée sur une offre de stockage particulière dans un data Center privé ou dans un cloud public. Ce kit basé sur Ansible automatise la configuration, le clonage et l'actualisation des bases de données Oracle clonées selon la planification à l'aide des utilitaires de ligne de commande NetApp SnapCenter qui simplifient la gestion du cycle de vie. Le kit s'applique aux bases de données Oracle déployées dans un système de stockage ONTAP sur site ou dans le cloud public (AWS ou Azure) et gérées par l'outil de l'interface utilisateur NetApp SnapCenter.

Cette solution répond aux cas d'utilisation suivants :

* Configurez le fichier de configuration de la spécification de clonage de la base de données Oracle.
* Créez et actualisez la base de données Oracle clone selon un planning défini par l'utilisateur.




== Public

Cette solution est destinée aux personnes suivantes :

* Administrateur de bases de données qui gère les bases de données Oracle avec SnapCenter.
* Administrateur du stockage qui gère le stockage ONTAP avec SnapCenter.
* Propriétaire d'application ayant accès à l'interface utilisateur de SnapCenter.




== Licence

En accédant au contenu de ce référentiel GitHub, en le téléchargeant, en l'installant ou en l'utilisant, vous acceptez les conditions de la licence énoncées dans link:https://github.com/NetApp/na_ora_hadr_failover_resync/blob/master/LICENSE.TXT["Fichier de licence"^].


NOTE: Il existe certaines restrictions concernant la production et/ou le partage de travaux dérivés avec le contenu de ce référentiel GitHub. Assurez-vous de lire les termes de la Licence avant d'utiliser le contenu. Si vous n'acceptez pas toutes les conditions, n'accédez pas au contenu de ce référentiel, ne le téléchargez pas et ne l'utilisez pas.



== Déploiement de la solution



=== Conditions préalables au déploiement

[%collapsible]
====
Le déploiement nécessite les conditions préalables suivantes.

....
Ansible controller:
  Ansible v.2.10 and higher
  ONTAP collection 21.19.1
  Python 3
  Python libraries:
    netapp-lib
    xmltodict
    jmespath
....
....
SnapCenter server:
  version 5.0 and up, 6.1 for Azure NetApp Files
  backup policy configured
  Source database protected with a backup policy
....
....
Oracle servers:
  Source server managed by SnapCenter (In Data Guard, this would be the physical standby serer)
  Target server managed by SnapCenter (clone DB host)
....

NOTE: Pour plus de simplicité, le serveur Oracle cible du clone doit être configuré de manière identique au serveur Oracle de secours, tel que la pile logicielle Oracle, ainsi qu'à la disposition des répertoires pour Oracle Home, etc

====


=== Téléchargez la boîte à outils

[%collapsible]
====
[source, cli]
----
git clone https://bitbucket.ngage.netapp.com/scm/ns-bb/na_oracle_clone_lifecycle.git
----

NOTE: La boîte à outils est uniquement accessible à l'utilisateur interne de NetApp avec un accès au bitbucket pour le moment. Pour les utilisateurs externes intéressés, veuillez demander l'accès à l'équipe de gestion de compte ou contacter l'équipe d'ingénierie des solutions NetApp.

====


=== Configuration des fichiers des hôtes cibles Ansible

[%collapsible]
====
Le kit d'outils inclut un fichier hosts qui définit les cibles sur lesquelles un PlayBook Ansible s'exécute. Il s'agit généralement des hôtes clones Oracle cibles. Voici un exemple de fichier. Une entrée d'hôte comprend l'adresse IP de l'hôte cible ainsi que la clé ssh permettant à un utilisateur admin d'accéder à l'hôte pour exécuter la commande clone ou refresh.

#Hôtes de clonage Oracle

....
[clone_1]
ora_04.cie.netapp.com ansible_host=10.61.180.29 ansible_ssh_private_key_file=ora_04.pem
....
 [clone_2]
 [clone_3]
====


=== Configuration des variables globales

[%collapsible]
====
Les playbooks Ansible prennent des entrées variables à partir de plusieurs fichiers variables. Vous trouverez ci-dessous un exemple de fichier de variable globale vars.yml.

 # ONTAP specific config variables
 # SnapCtr specific config variables
....
snapctr_usr: xxxxxxxx
snapctr_pwd: 'xxxxxxxx'
....
 backup_policy: 'Oracle Full offline Backup'
 # Linux specific config variables
 # Oracle specific config variables
====


=== Configuration des variables hôte

[%collapsible]
====
Les variables hôtes sont définies dans le répertoire host_vars nommé {{ host_name }}.yml. Vous trouverez ci-dessous un exemple de fichier de variable hôte Oracle cible ora_04.cie.netapp.com.yml qui montre une configuration typique.

 # User configurable Oracle clone db host specific parameters
....
# Source database to clone from
source_db_sid: NTAP1
source_db_host: ora_03.cie.netapp.com
....
....
# Clone database
clone_db_sid: NTAP1DEV
....
 snapctr_obj_id: '{{ source_db_host }}\{{ source_db_sid }}'
====


=== Configuration du serveur Oracle cible de clone supplémentaire

[%collapsible]
====
La pile logicielle Oracle du serveur Oracle cible de clone doit être identique à celle du serveur Oracle source installé et corrigé. $ORACLE_BASE et $ORACLE_HOME sont configurés pour l'utilisateur ORACLE .bash_profile. De plus, la variable $ORACLE_HOME doit correspondre au paramètre du serveur Oracle source. Voici un exemple.

 # .bash_profile
....
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
....
....
# User specific environment and startup programs
export ORACLE_BASE=/u01/app/oracle
export ORACLE_HOME=/u01/app/oracle/product/19.0.0/NTAP1
....
====


=== Exécution de PlayBook

[%collapsible]
====
Au total, trois playbooks permettent d'exécuter le cycle de vie des clones d'une base de données Oracle avec les utilitaires de l'interface de ligne de commande SnapCenter.

. Installez les prérequis du contrôleur Ansible, une seule fois.
+
[source, cli]
----
ansible-playbook -i hosts ansible_requirements.yml
----
. Fichier de spécification de clone de configuration - une seule fois.
+
[source, cli]
----
ansible-playbook -i hosts clone_1_setup.yml -u admin -e @vars/vars.yml
----
. Créez et actualisez régulièrement la base de données de clones à partir de crontab avec un script shell pour appeler un PlayBook d'actualisation.
+
[source, cli]
----
0 */4 * * * /home/admin/na_oracle_clone_lifecycle/clone_1_refresh.sh
----



NOTE: Remplacez le nom d'utilisateur par votre utilisateur sudo pour la configuration SnapCenter.

Pour une base de données clone supplémentaire, créez un clone_n_setup.yml et un clone_n_refresh.yml et un clone_n_refresh.sh. Configurez les hôtes cibles Ansible et le fichier hostname.yml dans le répertoire host_vars en conséquence.

====


== Où trouver des informations complémentaires

Pour en savoir plus sur l'automatisation de la solution NetApp, consultez ce site Web link:../automation/automation_introduction.html["Automatisation des solutions NetApp"^]
