---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prereq_cloud.html 
summary: 'Avant d"installer Cloud Manager Connector et Cloud Volumes ONTAP et de configurer SnapMirror, nous devons préparer notre environnement cloud. Cette page décrit le travail à effectuer, ainsi que les considérations relatives au déploiement de Cloud Volumes ONTAP.' 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= Conditions préalables au cloud public
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_prereq_onprem.html["Précédent : conditions préalables sur site."]

[role="lead"]
Avant d'installer Cloud Manager Connector et Cloud Volumes ONTAP et de configurer SnapMirror, nous devons préparer notre environnement cloud. Cette page décrit le travail à effectuer, ainsi que les considérations relatives au déploiement de Cloud Volumes ONTAP.



== Liste de contrôle des conditions préalables au déploiement de Cloud Manager et de Cloud Volumes ONTAP

* Identifiant NetApp Cloud Central
* Accès au réseau à partir d'un navigateur Web vers plusieurs noeuds finaux
* Emplacement réseau d'un connecteur
* Les autorisations du fournisseur cloud
* Mise en réseau pour des services individuels


Pour en savoir plus sur ce dont vous avez besoin pour démarrer, consultez le site https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["documentation cloud"^].



== Considérations



=== 1. Qu'est-ce qu'un connecteur Cloud Manager ?

Dans la plupart des cas, un administrateur de compte Cloud Central doit déployer un connecteur dans votre réseau cloud ou sur site. Ce connecteur permet à Cloud Manager de gérer les ressources et les processus au sein de votre environnement de cloud public.

Pour plus d'informations sur les connecteurs, visitez notre https://docs.netapp.com/us-en/occm/concept_connectors.html["documentation cloud"^].



=== 2. Dimensionnement et architecture de Cloud Volumes ONTAP

Lors du déploiement de Cloud Volumes ONTAP, vous avez le choix entre un package prédéfini ou la création de votre propre configuration. Bon nombre de ces valeurs peuvent être modifiées ultérieurement, sans interrompre l'activité, mais certaines décisions clés doivent être prises avant le déploiement, en fonction des charges de travail à déployer dans le cloud.

Chaque fournisseur de cloud propose différentes options de déploiement et chaque workload dispose de ses propres propriétés. NetApp a une https://cloud.netapp.com/cvo-sizer["Outil de dimensionnement CVO"^] cela peut aider à dimensionner correctement les déploiements en fonction de la capacité et des performances, mais il a été conçu autour de certains concepts de base qui méritent d'être pris en compte :

* Capacité requise
* Capacité réseau de la machine virtuelle du cloud
* Les caractéristiques de performances du stockage cloud


L'essentiel est de planifier une configuration qui non seulement répond aux besoins actuels en termes de capacité et de performances, mais qui étudie également la croissance future. Ce chiffre est généralement appelé marge de capacité et marge de performance.

Si vous souhaitez des informations complémentaires, lisez la documentation sur la planification correcte https://docs.netapp.com/us-en/occm/task_planning_your_config.html["AWS"^], https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["Azure"^], et https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["GCP"^].



=== 3. Un seul nœud ou haute disponibilité ?

Dans tous les clouds, il est possible de déployer Cloud volumes ONTAP dans un seul nœud ou dans une paire haute disponibilité en cluster avec deux nœuds. Selon le cas de figure, vous pouvez déployer un nœud unique pour réduire les coûts ou une paire haute disponibilité pour améliorer la disponibilité et la redondance.

Pour une reprise après incident ou l'exécution de systèmes de stockage temporaires pour le développement et le test, des nœuds uniques sont courants, car l'impact d'une panne d'infrastructure soudaine ou d'un zone est moindre. Toutefois, pour toutes les utilisations de production, et lorsque les données ne se trouvent que dans un seul emplacement ou que le dataset doit avoir plus de redondance et de disponibilité, la haute disponibilité est recommandée.

Pour plus d'informations sur l'architecture de la version haute disponibilité de chaque Cloud, consultez la documentation pour https://docs.netapp.com/us-en/occm/concept_ha.html["AWS"^], https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Azure"^] et https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["GCP"^].

link:hybrid_dbops_snapcenter_getting_started.html["Présentation de mise en route."]
