---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_getting_started.html 
summary: Cette section présente un récapitulatif des tâches à accomplir pour répondre aux exigences préalables requises, comme indiqué dans la section précédente. La section suivante énumère les tâches générales, à la fois pour les opérations sur site et dans le cloud public. Les processus et procédures détaillés sont accessibles en cliquant sur les liens correspondants. 
keywords: introduction, workflow 
---
= Présentation de mise en route
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


[role="lead"]
Cette section présente un récapitulatif des tâches à accomplir pour répondre aux exigences préalables requises, comme indiqué dans la section précédente. La section suivante énumère les tâches générales, à la fois pour les opérations sur site et dans le cloud public. Les processus et procédures détaillés sont accessibles en cliquant sur les liens correspondants.



== Sur site

* Configurer l'utilisateur admin de la base de données dans SnapCenter
* Conditions préalables à l'installation du plug-in SnapCenter
* Installation du plug-in hôte SnapCenter
* Découverte de ressources DE BASE DE DONNÉES
* Configuration de la réplication du volume de peering de clusters et de BDD
* Ajouter le SVM de stockage de base de données CVO à SnapCenter
* Configurez la stratégie de sauvegarde de la base de données dans SnapCenter
* Mise en œuvre d'une stratégie de sauvegarde pour protéger la base de données
* Validation de la sauvegarde




== Cloud public AWS

* Contrôle avant vol
* Étapes de déploiement de Cloud Manager et de Cloud Volumes ONTAP dans AWS
* Déployez l'instance de calcul EC2 pour les workloads de base de données


Cliquez sur les liens suivants pour plus d'informations :

link:hybrid_dbops_snapcenter_getting_started_onprem.html["Sur site"], link:hybrid_dbops_snapcenter_getting_started_aws.html["Cloud public - AWS"]
