---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prerequisite.html 
summary: 'Certaines conditions préalables doivent être configurées à la fois sur site et dans le cloud avant d"exécuter des workloads de base de données de cloud hybride. La section suivante fournit un résumé de ce processus de haut niveau et les liens suivants fournissent des informations supplémentaires sur la configuration du système nécessaire.' 
keywords: workflow, prerequisites, licensing, networking, security 
---
= Configuration des prérequis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_requirements.html["Précédent : exigences relatives aux solutions."]

[role="lead"]
Certaines conditions préalables doivent être configurées à la fois sur site et dans le cloud avant d'exécuter des workloads de base de données de cloud hybride. La section suivante fournit un résumé de ce processus de haut niveau et les liens suivants fournissent des informations supplémentaires sur la configuration du système nécessaire.



== Sur site

* Installation et configuration de SnapCenter
* Configuration du stockage du serveur de bases de données sur site
* Licences requises
* Mise en réseau et sécurité
* Automatisation




== Cloud public

* Identifiant NetApp Cloud Central
* Accès au réseau à partir d'un navigateur Web vers plusieurs noeuds finaux
* Emplacement réseau d'un connecteur
* Les autorisations du fournisseur cloud
* Mise en réseau pour des services individuels


Remarques importantes :

. Où déployer Cloud Manager Connector ?
. Architecture et dimensionnement de Cloud volumes ONTAP
. Un seul nœud ou une haute disponibilité ?


Vous trouverez des informations supplémentaires sur les liens suivants :

link:hybrid_dbops_snapcenter_prereq_onprem.html["Sur site"]

link:hybrid_dbops_snapcenter_prereq_cloud.html["Cloud public"]

link:hybrid_dbops_snapcenter_prereq_onprem.html["Suivant : conditions préalables sur site."]
