---
sidebar: sidebar 
permalink: databases/marketing_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 'Cette page décrit la méthode automatisée de déploiement d"Oracle19c sur le stockage ONTAP NetApp.' 
---
= Présentation de la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Déploiement automatisé d'Oracle19c pour ONTAP sur NFS

Les entreprises automatisent leur environnement pour gagner en efficacité, accélérer les déploiements et réduire les efforts manuels. Les outils de gestion de la configuration comme Ansible sont utilisés pour rationaliser les opérations des bases de données d'entreprise. Dans cette solution, nous vous montrerons comment utiliser Ansible pour automatiser le provisionnement et la configuration d'Oracle 19c avec NetApp ONTAP. En permettant aux administrateurs du stockage, aux administrateurs système et aux administrateurs de bases de données de déployer de façon cohérente et rapide un nouveau stockage, de configurer des serveurs de base de données et d'installer le logiciel Oracle 19c, vous bénéficiez des avantages suivants :

* Éliminez les complexités de la conception et les erreurs humaines, et mettez en œuvre un déploiement cohérent et des meilleures pratiques reproductibles
* Réduction du temps de provisionnement du stockage, de la configuration des hôtes de base de données et d'installation d'Oracle
* Augmentez la productivité des administrateurs de bases de données, des systèmes et des administrateurs du stockage
* Permettre l'évolutivité du stockage et des bases de données en toute simplicité


NetApp fournit aux clients des modules et des rôles Ansible validés pour accélérer le déploiement, la configuration et la gestion du cycle de vie de votre environnement de base de données Oracle. Cette solution fournit des instructions et un code de PlayBook Ansible pour vous aider à :

* Créer et configurer le stockage ONTAP NFS pour Oracle Database
* Installez Oracle 19c sur RedHat Enterprise Linux 7/8 ou Oracle Linux 7/8
* Configuration d'Oracle 19c sur un système de stockage NFS ONTAP


Pour en savoir plus ou pour commencer, consultez les vidéos de présentation ci-dessous.



=== Déploiements AWX/Tower

Partie 1 : mise en route, exigences, détails d'automatisation et configuration initiale AWX/Tour


Partie 2 : variables et exécution du manuel de vente




=== Déploiement de l'interface de ligne de

Partie 1 : mise en route, exigences, détails d'automatisation et configuration de l'hôte Ansible Control


Partie 2 : variables et exécution du manuel de vente

