---
sidebar: sidebar 
permalink: databases/sql-srv-anf_conclusion.html 
keywords: takeaways, hybrid-cloud 
summary: 'Que vous souhaitiez cibler un cloud 100 % cloud ou un cloud hybride avec des bases de données étendues, Azure NetApp Files offre d"excellentes options pour déployer et gérer les charges de travail de base de données tout en réduisant le coût total de possession en rendant les données requises de manière transparente pour la couche applicative.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Que vous souhaitiez cibler un cloud 100 % cloud ou un cloud hybride avec des bases de données étendues, Azure NetApp Files offre d'excellentes options pour déployer et gérer les charges de travail de base de données tout en réduisant le coût total de possession en rendant les données requises de manière transparente pour la couche applicative.

Ce document contient des recommandations pour la planification, la conception, l'optimisation et l'évolutivité des déploiements Microsoft SQL Server avec Azure NetApp Files, qui peuvent varier considérablement d'une implémentation à l'autre. Les détails techniques de l'implémentation et les exigences métier détermineront la solution à adopter pour chaque projet.



== Messages clés

Les points clés de ce document sont les suivants :

* Vous pouvez maintenant utiliser Azure NetApp Files pour héberger la base de données et le témoin de partage de fichiers pour le cluster SQL Server.
* Vous pouvez accélérer les temps de réponse des applications et assurer une disponibilité de 99.9999 % pour accéder aux données SQL Server où et quand vous en avez besoin.
* Vous pouvez simplifier la complexité globale du déploiement de SQL Server et de la gestion continue, telles que l'entrelacement raid, avec un redimensionnement simple et instantané.
* Ses fonctionnalités intelligentes vous permettent de déployer des bases de données SQL Server en quelques minutes et d'accélérer leurs cycles de développement.
* Si Azure Cloud est la destination incontournable, Azure NetApp Files est la solution de stockage idéale pour optimiser le déploiement.

