---
sidebar: sidebar 
permalink: databases/tr-4722.html 
keywords:  
summary:  
---
= Tr-4722 : base de données MySQL sur les meilleures pratiques NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Anup Bharti, Manohar Kulkarni, Jeffrey Steiner NetApp

[role="lead"]
MySQL et ses variantes, dont MariaDB et Percona, sont largement utilisés pour de nombreuses applications d'entreprise. Ces applications vont des sites de réseaux sociaux mondiaux, des systèmes d'e-commerce massifs aux systèmes d'hébergement SMB contenant des milliers d'instances de base de données. Ce document décrit la configuration requise et fournit des conseils sur le réglage et la configuration du stockage pour le déploiement de MySQL sur le logiciel de gestion des données NetApp® ONTAP®. Pour savoir si les environnements, les configurations et les versions spécifiés dans ce rapport sont compatibles avec votre environnement, consultez la matrice d'interopérabilité (IMT).

link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf["Tr-4722 : base de données MySQL sur les meilleures pratiques NetApp ONTAP"^]
