---
sidebar: sidebar 
permalink: databases/tr-4250-link.html 
keywords:  
summary:  
---
= Tr-4250 : SAP avec Oracle sous UNIX et NFS avec NetApp clustered Data ONTAP et SnapManager pour SAP 3.4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer, NetApp

Le rapport TR-4250 décrit les défis que pose la conception de solutions de stockage pour prendre en charge les produits de la suite d'affaires SAP à l'aide d'une base de données Oracle. L'objectif principal de ce document est de faire face aux défis posés par la conception, le déploiement, l'exploitation et la gestion de l'infrastructure de stockage par les dirigeants et LES responsables IT qui utilisent la dernière génération de solutions SAP. Les recommandations contenues dans ce document sont génériques, elles ne sont pas spécifiques à une application SAP ou à la taille et à la portée de l'implémentation SAP. Dans le rapport TR-4250, nous partons du principe que le lecteur connaît les technologies et le fonctionnement des produits NetApp et SAP. Le rapport TR-4250 a été développé sur la base des interactions du personnel technique de NetApp, SAP, Oracle et de nos clients.

link:https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf["https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf"^]
