---
sidebar: sidebar 
permalink: ehc/dro/azure-dro-overview.html 
keywords: NetApp Solutions, hybrid, multicloud, multi cloud, hyperscalers, vmware, disaster recovery orchestrator, DRO 
summary:  
---
= Tr-4955 : reprise d'activité avec Azure NetApp Files (ANF) et solution Azure VMware (AVS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Niyaz Mohamed, NetApp



== Présentation



== Pour commencer



== Installation de DRO



== Configuration DRO



== Avantages

* Utilisation de la réplication SnapMirror efficace et résiliente.
* Restauration à tout point dans le temps avec la conservation des copies Snapshot
* Automatisation complète de toutes les étapes nécessaires à la restauration de centaines de milliers de machines virtuelles à partir des étapes de validation du stockage, du calcul, du réseau et des applications.
* Restauration de charge de travail avec la technologie ONTAP FlexClone utilisant une méthode qui ne modifie pas le volume répliqué.
+
** Évite le risque de corruption des données pour les volumes et les copies Snapshot.
** Evite les interruptions de réplication pendant les workflows de test de reprise après incident
** Utilisation potentielle des données de reprise d'activité avec des ressources de cloud computing pour les workflows hors reprise d'activité, comme DevTest, les tests de sécurité, les tests de correctifs ou de mise à niveau, et les tests de résolution de problèmes.


* L'optimisation du processeur et de la RAM pour réduire les coûts liés au cloud grâce à la restauration sur des clusters de calcul plus petits.

