---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-architecture_overview.html 
keywords: architecture overview, control plane, data plane 
summary: 'L"architecture et la sécurité font partie des processus de confiance aux solutions cloud. Cette section décrit différents aspects de l"architecture Cloud Volumes Service de Google qui contribuent à réduire les risques de sécurisation des données et indique les domaines dans lesquels des étapes de configuration supplémentaires peuvent être nécessaires pour obtenir le déploiement le plus sécurisé.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-security-considerations-and-attack-surfaces.html["Précédent : considérations de sécurité et surfaces d'attaque."]

[role="lead"]
L'architecture et la sécurité font partie des processus de confiance aux solutions cloud. Cette section décrit différents aspects de l'architecture Cloud Volumes Service de Google qui contribuent à réduire les risques de sécurisation des données et indique les domaines dans lesquels des étapes de configuration supplémentaires peuvent être nécessaires pour obtenir le déploiement le plus sécurisé.

L'architecture générale d'Cloud Volumes Service peut être décomposée en deux composants principaux : le plan de contrôle et le plan de données.



== Plan de contrôle

Le plan de contrôle d'Cloud Volumes Service est l'infrastructure back-end gérée par les administrateurs Cloud Volumes Service et le logiciel d'automatisation natif de NetApp. Ce plan est totalement transparent pour les utilisateurs finaux. Il inclut des fonctionnalités de mise en réseau, du matériel de stockage, des mises à jour logicielles, etc. Pour que les solutions hébergées dans le cloud telles que Cloud Volumes Service puissent apporter de la valeur ajoutée.



== Plan de données

Le plan de données de Cloud Volumes Service inclut les volumes de données réels et la configuration Cloud Volumes Service globale (contrôle d'accès, authentification Kerberos, etc.). Le plan de données est entièrement sous le contrôle des utilisateurs finaux et des consommateurs de la plateforme Cloud Volumes Service.

La façon dont chaque plan est sécurisé et géré est différente. Ces différences sont en commençant par la présentation de l'architecture Cloud Volumes Service.

link:ncvs-gc-cloud-volumes-service-architecture.html["Ensuite : architecture Cloud Volumes Service."]
