---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Cloud Volumes Service expose plusieurs ports TCP pour servir les partages NFS et SMB. 
---
= Pare-feu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-data-encryption-at-rest.html["Précédent : chiffrement des données au repos."]

[role="lead"]
Cloud Volumes Service expose plusieurs ports TCP pour servir les partages NFS et SMB :

* https://["Ports requis pour l'accès NFS"^]
* https://["Ports requis pour l'accès SMB"^]


En outre, SMB, NFS avec LDAP, y compris Kerberos, et des configurations à double protocole requièrent l'accès à un domaine Windows Active Directory. Les connexions Active Directory doivent être de https://["configuré"^] par région. Les contrôleurs de domaine (DC) Active Directory sont identifiés à l'aide de https://["Découverte de data Center basée sur DNS"^] Utilisation des serveurs DNS spécifiés. Tous les DCS renvoyés sont utilisés. La liste des DCS admissibles peut être limitée en spécifiant un site Active Directory.

Cloud Volumes Service atteint son niveau avec les adresses IP de la plage CIDR allouée à l' `gcloud compute address` commande pendant https://["Intégration de la Cloud Volumes Service"^]. Vous pouvez utiliser ce CIDR comme adresses source pour configurer les pare-feu entrants sur vos contrôleurs de domaine Active Directory.

Les contrôleurs de domaine Active Directory doivent https://["Exposer les ports aux rapports CIDR Cloud Volumes Service comme indiqué ici"^].

link:ncvs-gc-nas-protocols_overview.html["Next : présentation des protocoles NAS."]
