---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: 'La sécurité, notamment dans le cloud où l"infrastructure ne contrôle pas les administrateurs du stockage, est primordiale pour faire confiance aux données des offres de services des fournisseurs cloud. Ce document présente les offres de sécurité de NetApp Cloud Volumes Service pour Google Cloud.' 
---
= Tr-4918 : présentation de la sécurité - NetApp Cloud Volumes Service dans Google Cloud
:allow-uri-read: 


Oliver Krause, Justin Parisi, NetApp



== Étendue du document

La sécurité, notamment dans le cloud où l'infrastructure ne contrôle pas les administrateurs du stockage, est primordiale pour faire confiance aux données des offres de services des fournisseurs cloud. Ce document présente les offres de sécurité de NetApp https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service fournit dans Google Cloud"^].



== Public visé

Le public visé par ce document comprend, mais sans s'y limiter, les rôles suivants :

* Fournisseurs de cloud
* Administrateurs du stockage
* Les architectes du stockage
* Ressources sur site
* Décideurs de l'entreprise


Pour toute question sur le contenu de ce rapport technique, consultez la section link:ncvs-gc-additional-information.html#contact-us["« Contactez-nous. »"]

|===
| Abréviation | Définition 


| CVS-SW | Cloud Volumes Service, CVS de type de service 


| CVS-Performance | Cloud volumes Service, CVS-Performance type de service 


| PSA |  
|===
link:ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html["Ensuite, comment Cloud Volumes Service dans Google Cloud sécurise vos données."]
