---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-tools.html 
keywords: deployment, backup tools, snapcenter server, Veeam server, 
summary: 'Pour effectuer un basculement de nos VM applicatifs et de nos volumes de base de données vers les services VMware Cloud volumes exécutés dans AWS, il était nécessaire d"installer et de configurer une instance d"exécution à la fois de SnapCenter Server et de Veeam Backup and Replication Server. À la fin du basculement, ces outils doivent également être configurés pour reprendre les opérations de sauvegarde normales, jusqu"à ce que la restauration du data Center sur site soit planifiée et exécutée.' 
---
= Outils de sauvegarde dans le cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-compute.html["Précédent : calculer."]

Pour effectuer un basculement de nos VM applicatifs et de nos volumes de base de données vers les services VMware Cloud volumes exécutés dans AWS, il était nécessaire d'installer et de configurer une instance d'exécution à la fois de SnapCenter Server et de Veeam Backup and Replication Server. À la fin du basculement, ces outils doivent également être configurés pour reprendre les opérations de sauvegarde normales, jusqu'à ce que la restauration du data Center sur site soit planifiée et exécutée.



== Déploiement des outils de sauvegarde

Le serveur SnapCenter et le serveur Veeam Backup & Replication peuvent être installés dans le SDDC VMware Cloud ou sur des instances EC2 résidant dans un VPC avec la connectivité réseau dans l'environnement VMware Cloud.



=== Serveur SnapCenter

Le logiciel SnapCenter est disponible sur le site du support NetApp et peut être installé sur les systèmes Microsoft Windows résidant dans un domaine ou dans un groupe de travail. Un guide de planification détaillé et des instructions d'installation sont disponibles sur le link:https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["Centre de documentation NetApp"^].

Le logiciel SnapCenter est disponible à l'adresse https://mysupport.netapp.com["ce lien"^].



=== Serveur de sauvegarde et de réplication Veeam

Vous pouvez installer le serveur Veeam Backup & Replication sur un serveur Windows dans VMware Cloud sur AWS ou sur une instance EC2. Pour obtenir des conseils détaillés sur la mise en œuvre, reportez-vous au https://www.veeam.com/documentation-guides-datasheets.html["Documentation technique du centre d'aide Veeam"^].



== Les outils de sauvegarde et la configuration

Une fois installés, SnapCenter et Veeam Backup & Replication doivent être configurés pour que la restauration des données vers VMware Cloud sur AWS s'effectue sur les tâches nécessaires.



=== Configuration SnapCenter

Pour restaurer les données d'application mises en miroir vers FSX ONTAP, vous devez d'abord effectuer une restauration complète de la base de données SnapCenter sur site. Une fois ce processus terminé, la communication avec les machines virtuelles est rétablie, et les sauvegardes des applications peuvent maintenant reprendre l'utilisation de FSX ONTAP comme stockage primaire.

Pour obtenir la liste des étapes à suivre sur le serveur SnapCenter résidant dans AWS, consultez la section link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-windows-snapcenter-server["Déployez un serveur SnapCenter secondaire Windows"].



=== Configuration de Veeam Backup & Replication

Pour restaurer les machines virtuelles qui ont été sauvegardées sur le stockage Amazon S3, le serveur Veeam doit être installé sur un serveur Windows et configuré pour communiquer avec VMware Cloud, FSX ONTAP, ainsi qu'avec le compartiment S3 contenant le référentiel de sauvegarde d'origine. Le service informatique doit également configurer un nouveau référentiel de sauvegarde sur FSX ONTAP afin de réaliser de nouvelles sauvegardes sur les machines virtuelles une fois restaurées.

Pour obtenir la liste complète des étapes requises pour effectuer le basculement des machines virtuelles d'application, consultez la section link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-veeam-backup-&-replication-server["Déploiement du système Veeam Backup etamp secondaire ; Replication Server"].

link:aws-guest-dr-snapcenter-overview.html["Suivant : présentation - reprise sur incident."]
