---
sidebar: sidebar 
permalink: ehc/aws/aws-solutions.html 
keywords: NetApp Solutions, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Solutions NetApp pour Amazon VMware Managed Cloud (VMC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
En savoir plus sur les solutions NetApp pour AWS.

VMware définit les workloads cloud en trois catégories :

* Protection (y compris la reprise après incident et la sauvegarde/restauration)
* Migrer
* Extension


Parcourez les solutions disponibles dans les sections suivantes.

[role="tabbed-block"]
====
.Protéger
--
* link:aws-guest-dr-solution-overview.html["Reprise après incident avec VMC sur AWS (connecté à l'invité)"]
* link:aws-vmc-veeam-fsx-solution.html["Sauvegarde Veeam  ; Restauration dans VMC avec FSX for ONTAP"]
* link:../dro/aws-dro-overview.html["Reprise après sinistre (DRO) avec FSX pour ONTAP et VMC"]


--
.Migrer
--
* link:aws-migrate-vmware-hcx.html["Migrez vos charges de travail vers le datastore FSxN à l'aide de VMware HCX"]


--
.Extension
--
DISPONIBLE PROCHAINEMENT !

--
====