---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-config.html 
keywords: secondary, windows, snapcenter server, veeam server 
summary: 'Pour effectuer un basculement des VM applicatives et des volumes de base de données vers les services VMware Cloud volumes exécutés dans AWS, vous devez installer et configurer une instance en cours d"exécution de SnapCenter Server et Veeam Backup and Replication Server. Une fois le basculement terminé, vous devez également configurer ces outils pour reprendre les opérations de sauvegarde normales jusqu"à ce que la restauration du data Center sur site soit planifiée et exécutée.' 
---
= Outils et configuration de sauvegarde dans le cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-config-veeam.html["Précédent : déploiement et configuration de Veeam Backup Server."]

Pour effectuer un basculement des VM applicatives et des volumes de base de données vers les services VMware Cloud volumes exécutés dans AWS, vous devez installer et configurer une instance en cours d'exécution de SnapCenter Server et Veeam Backup and Replication Server. Une fois le basculement terminé, vous devez également configurer ces outils pour reprendre les opérations de sauvegarde normales jusqu'à ce que la restauration du data Center sur site soit planifiée et exécutée.



== Déploiement d'un serveur Windows SnapCenter secondaire

Le serveur SnapCenter est déployé dans le SDDC VMware Cloud ou installé sur une instance EC2 résidant dans un VPC avec une connectivité réseau vers l'environnement VMware Cloud.

Le logiciel SnapCenter est disponible sur le site du support NetApp et peut être installé sur les systèmes Microsoft Windows résidant dans un domaine ou un groupe de travail. Un guide de planification détaillé et des instructions d'installation sont disponibles sur le https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["Centre de documentation NetApp"^].

Le logiciel SnapCenter est disponible sur la page https://mysupport.netapp.com["ce lien"^].



== Configurez le serveur SnapCenter secondaire

Pour restaurer les données d'application en miroir vers FSX ONTAP, vous devez d'abord effectuer une restauration complète de la base de données SnapCenter sur site. Une fois ce processus terminé, la communication avec les machines virtuelles est rétablie, et les sauvegardes des applications peuvent maintenant reprendre en utilisant FSX ONTAP comme stockage primaire.

Pour ce faire, vous devez effectuer les opérations suivantes sur le serveur SnapCenter :

. Configurez le nom de l'ordinateur pour qu'il soit identique au serveur SnapCenter sur site d'origine.
. Configurez le réseau pour communiquer avec VMware Cloud et l'instance FSX ONTAP.
. Terminez la procédure de restauration de la base de données SnapCenter.
. Vérifiez que SnapCenter est en mode reprise après incident pour vous assurer que FSX est désormais le stockage principal pour les sauvegardes.
. Confirmer que la communication est rétablie avec les machines virtuelles restaurées.


Pour plus d'informations sur ces étapes, reportez-vous à la section à link:aws-guest-dr-failover.html#snapcenter-database-restore-process["Processus de restauration de base de données SnapCenter"].



== Déployez le serveur Veeam Backup & Replication secondaire

Vous pouvez installer le serveur Veeam Backup & Replication sur un serveur Windows dans le cloud VMware sur AWS ou sur une instance EC2. Pour obtenir des conseils détaillés sur la mise en œuvre, reportez-vous au https://www.veeam.com/documentation-guides-datasheets.html["Documentation technique du centre d'aide Veeam"^].



== Configuration du serveur Veeam Backup & Replication secondaire

Pour effectuer une restauration des machines virtuelles qui ont été sauvegardées sur le stockage Amazon S3, vous devez installer Veeam Server sur un serveur Windows et le configurer pour qu'il communique avec VMware Cloud, FSX ONTAP et le compartiment S3 qui contient le référentiel de sauvegarde d'origine. Le système informatique doit également configurer un nouveau référentiel de sauvegarde sur FSX ONTAP afin de réaliser de nouvelles sauvegardes des machines virtuelles après leur restauration.

Pour effectuer ce processus, les éléments suivants doivent être effectués :

. Configuration du réseau pour communiquer avec VMware Cloud, FSX ONTAP et un compartiment S3 contenant le référentiel de sauvegarde d'origine
. Configurez un partage SMB sur FSX ONTAP en tant que nouveau référentiel de sauvegarde.
. Montez le compartiment S3 d'origine utilisé dans le référentiel de sauvegarde scale-out sur site.
. Après la restauration de la machine virtuelle, établir de nouvelles tâches de sauvegarde afin de protéger les machines virtuelles SQL et Oracle.


Pour plus d'informations sur la restauration des VM à l'aide de Veeam, reportez-vous à la section link:aws-guest-dr-restore-veeam-full.html["Restauration des VM applications avec Veeam Full Restore"].

link:aws-guest-dr-snapcenter-db-backup.html["Next : sauvegarde de bases de données SnapCenter pour la reprise après incident."]
