---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-snapcenter-overview.html 
keywords: overview, dr, snapcenter, data replication, snapmirror 
summary: Dans cette solution, SnapCenter fournit des snapshots cohérents au niveau des applications pour les données des applications SQL Server et Oracle. Combinée à la technologie SnapMirror, cette configuration assure une réplication des données ultra-rapide entre nos clusters AFF et FSX ONTAP sur site. De plus, Veeam Backup & Replication offre des fonctionnalités de sauvegarde et de restauration pour nos machines virtuelles. 
---
= Présentation - reprise après incident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-cloud-backup-tools.html["Précédent : outils de sauvegarde dans le cloud."]

Dans cette solution, SnapCenter fournit des snapshots cohérents au niveau des applications pour les données des applications SQL Server et Oracle. Combinée à la technologie SnapMirror, cette configuration assure une réplication des données ultra-rapide entre nos clusters AFF et FSX ONTAP sur site. De plus, Veeam Backup & Replication offre des fonctionnalités de sauvegarde et de restauration pour nos machines virtuelles.

Dans cette section, nous allons parler de la configuration de SnapCenter, SnapMirror et Veeam pour la sauvegarde et la restauration.

Les sections suivantes couvrent la configuration et les étapes nécessaires pour effectuer le basculement sur le site secondaire :

* Configuration de SnapMirror et des planifications de conservation (stockage secondaire)
* Déploiement et configuration de Windows SnapCenter Server sur site
* Déploiement et configuration du serveur Veeam Backup & Replication sur site
* Déployez et configurez les outils de sauvegarde dans le cloud, SnapCenter et Veeam.
* Sauvegarde des bases de données SnapCenter pour la reprise après incident.
* Restauration de base de données SnapCenter sur un site secondaire.
* Restauration des machines virtuelles d'applications à l'aide de Veeam Backup & Replication
* Restaurez les données applicatives SQL Server.
* Restaurez les données de l'application Oracle.


link:aws-guest-dr-config-snapmirror.html["Configuration des relations SnapMirror et des planifications de conservation"]
