---
sidebar: sidebar 
permalink: vmware/migrate-vms-to-ec2-fsxn.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: 'Ce rapport technique explique comment migrer des machines virtuelles VMware vSphere sur site vers une instance Amazon EC2 avec des disques de données placés sur des LUN iSCSI FSX ONTAP à l"aide de la fonctionnalité « mobilité des données en tant que code » MigrationTM de Cirrus Migrate Cloud (CMC).' 
---
= Migration des machines virtuelles vers Amazon EC2 à l'aide d'Amaxon FSX pour ONTAP : présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les entreprises accélèrent leurs migrations vers des solutions de cloud computing sur AWS, en profitant de services tels que les instances Amazon Elastic Compute Cloud (Amazon EC2) et Amazon FSX pour NetApp ONTAP (FSX ONTAP) pour moderniser leurs infrastructures IT, réaliser des économies et améliorer l'efficacité opérationnelle. Ces offres AWS permettent des migrations qui optimisent le TCO grâce à des modèles de tarification basés sur la consommation et à des fonctionnalités de stockage haute performance, offrant la flexibilité et l'évolutivité nécessaires pour répondre à l'évolution des besoins de l'entreprise à travers le monde.



== Présentation

Pour les entreprises fortement investies dans VMware vSphere, la migration vers AWS est une option économique compte tenu des conditions actuelles du marché, qui représente une opportunité unique.

Lors de la transition vers AWS, ces entreprises cherchent à tirer parti de l'agilité et des économies du cloud, tout en préservant les fonctionnalités déjà en place, notamment en matière de stockage. Lors de la migration des workloads ou de la configuration de solutions de reprise après incident, il est essentiel de préserver la transparence des opérations grâce aux protocoles de stockage connus, en particulier iSCSI, les processus, les outils et les compétences.

En utilisant le service de stockage géré AWS FSX ONTAP pour conserver les fonctionnalités de stockage d'entreprise, telles que les solutions de stockage sur site proposées par des fournisseurs tiers, les entreprises peuvent exploiter toute la puissance d'AWS tout en minimisant les perturbations et en optimisant leurs investissements futurs.

Ce rapport technique explique comment migrer des machines virtuelles VMware vSphere sur site vers une instance Amazon EC2 avec des disques de données placés sur des LUN iSCSI FSX ONTAP à l'aide de la fonctionnalité MigrateOps « mobilité des données en tant que code » de Cirrus Migrate Cloud (CMC).



== De la solution

Les clients VMware cherchent actuellement à relever un certain nombre de défis. Ces entreprises souhaitent :

. Valoriser les fonctionnalités de stockage, telles que le provisionnement fin, les technologies d'efficacité du stockage, les clones sans encombrement, les sauvegardes intégrées, la réplication de niveau bloc, et le tiering. Cela permet d'optimiser les efforts de migration et de pérenniser le déploiement sur AWS dès le premier jour.
. Optimisez les déploiements de stockage sur AWS qui utilisent les instances Amazon EC2 en intégrant FSX ONTAP et les fonctionnalités d'optimisation des coûts qu'il fournit.
. Réduisez le coût total de possession (TCO) de l'utilisation des instances Amazon EC2 avec des solutions de stockage bloc en redimensionnant correctement les instances Amazon EC2 pour répondre aux paramètres d'IOPS et de débit requis. Avec le stockage bloc, les opérations sur disque Amazon EC2 plafonner la bande passante et les débits d'E/S. Le stockage de fichiers avec FSX ONTAP utilise la bande passante réseau. En d'autres termes, FSX ONTAP n'a pas de limite d'E/S au niveau des VM.




== Présentation des composants techniques



=== Concepts relatifs à FSX ONTAP

Amazon FSX ONTAP est un service de stockage AWS entièrement géré qui fournit aux systèmes de fichiers NetApp® ONTAP® toutes les fonctionnalités familières de gestion des données ONTAP, les performances et les API sur AWS. Son stockage haute performance prend en charge plusieurs protocoles (NFS, SMB, iSCSI), offrant un service unique pour les workloads utilisant des instances EC2 Windows, Linux et MacOS.

Étant donné que FSX ONTAP est un système de fichiers ONTAP, il intègre une multitude de fonctionnalités et de services NetApp familiers, notamment la technologie de réplication des données SnapMirror®, les clones fins et les copies Snapshot™ NetApp. En exploitant un Tier de capacité à faible coût par Tiering des données, FSX ONTAP est élastique et peut atteindre une évolutivité pratiquement illimitée. De plus, grâce à la technologie d'efficacité du stockage NetApp, les coûts de stockage sur AWS sont encore réduits. Pour plus d'informations, voir link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Commencez à utiliser Amazon FSX ONTAP"].



==== Système de fichiers

La ressource centrale de FSX ONTAP est son système de fichiers basé sur le stockage SSD. Lors du provisionnement d'un système de fichiers FSX ONTAP, l'utilisateur saisit le débit et la capacité de stockage souhaités, puis sélectionne un VPC Amazon dans lequel le système de fichiers doit résider.

Les utilisateurs ont également le choix entre deux modèles de déploiement haute disponibilité intégrés pour le système de fichiers : déploiement dans une zone de disponibilité multiple ou dans une zone de disponibilité unique. Chacune de ces options offre son propre niveau de durabilité et de disponibilité, que les clients peuvent sélectionner en fonction des exigences de continuité de l'activité de leur utilisation. Les déploiements multi-AZ consistent en deux nœuds qui répliquent de manière transparente dans deux zones de disponibilité. L'option de déploiement pour une disponibilité AZ plus économique structure le système de fichiers en deux nœuds répartis entre deux domaines de panne distincts qui résident tous deux dans une même zone de disponibilité AZ.



=== Ordinateurs virtuels de stockage

Les données du système de fichiers FSX ONTAP sont accessibles via une partition de stockage logique appelée SVM (Storage Virtual machine). Un SVM est en fait son propre serveur de fichiers équipé de ses propres données et de ses propres points d'accès admin. Lors de l'accès aux LUN iSCSI sur un système de fichiers FSX ONTAP, l'instance Amazon EC2 s'interface directement avec le SVM en utilisant l'adresse IP du terminal iSCSI du SVM.

Bien qu'il soit possible de maintenir un seul SVM dans un cluster, l'exécution de plusieurs SVM dans un cluster peut présenter de nombreux usages et avantages. Les clients peuvent déterminer le nombre optimal de SVM à configurer en tenant compte de leurs besoins, notamment de leurs exigences en matière d'isolation des charges de travail.



==== Volumes

Les données d'un SVM FSX ONTAP sont stockées et organisées dans des structures appelées volumes, qui agissent comme des conteneurs virtuels. Un volume individuel peut être configuré avec une ou plusieurs LUN. Les données stockées dans chaque volume consomment de la capacité de stockage dans le système de fichiers. Toutefois, puisque FSX ONTAP provisionne légèrement le volume, le volume ne prend en charge que la capacité de stockage correspondant à la quantité de données stockées.



=== Le concept de migration vers le cloud de Cirrus Migrate

CMC est une offre SaaS (Software-as-a-Service) transactable de Cirrus Data Solutions, Inc. Disponible sur AWS Marketplace. MigrateOps est une fonctionnalité d'automatisation de la mobilité des données en tant que code de CMC qui vous permet de gérer de manière déclarative vos opérations de mobilité des données à grande échelle à l'aide de configurations d'opérations simples dans YAML. Une configuration MigrateOps détermine la façon dont vous souhaitez exécuter vos tâches de mobilité des données. Pour en savoir plus sur MigrateOps, voir link:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["À propos de MigrateOps"].

MigrateOps utilise une approche axée sur l'automatisation, conçue spécialement pour rationaliser l'ensemble du processus, garantissant ainsi la mobilité des données d'entreprise à l'échelle du cloud sans interruption des opérations. Outre les fonctionnalités déjà riches en fonctionnalités offertes par CMC pour l'automatisation, MigrateOps ajoute d'autres automatisations souvent gérées en externe, telles que :

* Correction du système d'exploitation
* Planification de la mise en service et de l'approbation des applications
* Migration des clusters sans temps d'indisponibilité
* L'intégration d'une plateforme de cloud public/privé
* Intégration de la plateforme de virtualisation
* Intégration de la gestion du stockage d'entreprise
* Configuration SAN (iSCSI)


Les tâches ci-dessus étant entièrement automatisées, toutes les étapes fastidieuses de préparation de la machine virtuelle source sur site (par exemple, l'ajout d'agents et d'outils AWS), la création de LUN FSX de destination, la configuration d'iSCSI et de chemins d'accès multiples/MPIO sur l'instance de destination AWS, de plus, toutes les tâches d'arrêt/démarrage des services d'application sont éliminées en spécifiant simplement des paramètres dans un fichier YAML.

FSX ONTAP fournit les LUN de données et dimensionnez correctement le type d'instance Amazon EC2, tout en fournissant toutes les fonctionnalités disponibles précédemment dans leurs environnements sur site. La fonction MigrateOps de CMC sera utilisée pour automatiser toutes les étapes impliquées, y compris le provisionnement des LUN iSCSI mappés, ce qui en fait une opération déclarative prévisible.

*Remarque* : CMC nécessite l'installation d'un agent très léger sur les instances de machines virtuelles source et de destination pour assurer le transfert sécurisé des données du stockage source vers FSX ONTAP.



== Avantages de l'utilisation d'Amazon FSX ONTAP avec les instances EC2

Le stockage ONTAP FSX pour les instances Amazon EC2 offre plusieurs avantages :

* Un stockage à débit élevé et à faible latence qui fournit des performances élevées et prévisibles pour les charges de travail les plus exigeantes
* La mise en cache intelligente NVMe améliore les performances
* La capacité, le débit et les IOPS ajustables peuvent être modifiés à la volée et s'adapter rapidement à l'évolution des besoins de stockage
* Réplication des données basée sur les blocs depuis le stockage ONTAP sur site vers AWS
* L'accessibilité multiprotocole, y compris pour iSCSI, qui est largement utilisé dans les déploiements VMware sur site
* La technologie Snapshot™ de NetApp et la reprise sur incident orchestrée par SnapMirror empêchent la perte de données et accélèrent la restauration
* Fonctionnalités d'efficacité du stockage qui réduisent l'empreinte et les coûts du stockage, notamment l'allocation dynamique, la déduplication, la compression et la compaction des données
* La réplication efficace réduit le temps nécessaire à la création des sauvegardes, qui passe de plusieurs heures à quelques minutes, optimisant ainsi le RTO
* Options granulaires pour la sauvegarde et la restauration de fichiers à l'aide de NetApp SnapCenter®


Le déploiement des instances Amazon EC2 avec FSX ONTAP en tant que couche de stockage iSCSI offre des performances élevées, des fonctionnalités de gestion des données stratégiques et des fonctionnalités d'efficacité du stockage qui réduisent les coûts et transforment votre déploiement sur AWS.

Grâce à l'exécution d'un Flash cache, à plusieurs sessions iSCSI et à l'exploitation d'une taille de jeu de travail de 5 %, FSX ONTAP peut fournir des IOPS d'environ 350 000, garantissant des niveaux de performances adaptés aux charges de travail les plus exigeantes.

Puisque seules les limites de bande passante réseau sont appliquées à FSX ONTAP, et non les limites de bande passante du stockage bloc, les utilisateurs peuvent exploiter les petits types d'instances Amazon EC2 tout en obtenant les mêmes taux de performance que les types d'instances de plus grande taille. L'utilisation de tels types d'instances peu importants permet également de maîtriser les coûts de calcul et d'optimiser le TCO.

Autre avantage de FSX ONTAP : sa capacité à prendre en charge plusieurs protocoles permet de standardiser un service de stockage AWS pour répondre à un large éventail de besoins en services de fichiers et de données. Pour les entreprises fortement investies dans VMware vSphere, la migration vers AWS est une option économique compte tenu des conditions actuelles du marché, qui représente une opportunité unique.
