---
sidebar: sidebar 
permalink: vmware/netapp-vsphere8.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Prise en charge de NetApp pour vSphere 8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Le partenariat entre NetApp et VMware est le seul partenaire dans lequel un système de stockage unique répond à tous les cas d'utilisation clés définis par VMware.



== Solution 100 % Flash moderne et connectée au cloud pour vSphere 8

Les implémentations ONTAP s'exécutent sur plusieurs plateformes, notamment les appliances NetApp, le matériel générique et dans le cloud public. ONTAP offre un stockage unifié, que vous accédiez aux protocoles SAN ou NAS, ainsi qu'à des configurations allant du Flash ultra-rapide au support plus économique et au stockage basé sur le cloud. NetApp propose également des plateformes Flash dédiées pour simplifier et segmenter vos besoins de stockage sans créer de silos. De plus, NetApp propose des logiciels qui permettent de déplacer facilement des données entre les installations sur site et le cloud. Enfin, NetApp BlueXP offre un tableau de bord unique pour gérer toutes ces relations et l'empreinte du stockage.

* link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["Plateformes NetApp"]
* link:../ehc/index.html["Multicloud hybride NetApp avec les solutions VMware"]

