---
sidebar: sidebar 
permalink: vmware/tr-4792.html 
keywords: design, HCI, computing, vmware, cloud, graphics, virtualization 
summary: 'Le rapport technique TR-4792 fournit des recommandations sur l"utilisation du NetApp HCI 615C pour les workloads de graphiques 3D dans un environnement VMware Horizon optimisé par les processeurs graphiques (GPU) et le logiciel de virtualisation NVIDIA.' 
---
= NetApp HCI pour l'infrastructure de postes de travail virtuels avec VMware Horizon 7 : offrez aux utilisateurs intensifs des graphiques 3D
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


T echnologiques Suresh, NetApp

[role="lead"]
Le rapport technique TR-4792 fournit des conseils sur l'utilisation du nœud de calcul NetApp H615C pour les workloads de graphiques 3D dans un environnement VMware Horizon optimisé par les processeurs graphiques (GPU) et le logiciel de virtualisation NVIDIA. Il fournit également les résultats des tests préliminaires de SPECviewperf 13 pour le H615C.

link:https://www.netapp.com/pdf.html?item=/media/7125-tr4792.pdf["NetApp HCI pour l'infrastructure de postes de travail virtuels avec VMware Horizon 7 : offrez aux utilisateurs intensifs des graphiques 3D"^]
---
encadré : encadré
lien permanent : vmware/tr-4792.html
Mots-clés : conception, HCI, calcul, vmware, cloud, graphiques, virtualisation
résumé : « l'article TR-4792 propose des recommandations sur l'utilisation du NetApp HCI 615C pour les workloads de graphiques 3D dans un environnement VMware Horizon optimisé par les processeurs graphiques (GPU) et les logiciels de virtualisation NVIDIA. »
---



= NetApp HCI pour l'infrastructure de postes de travail virtuels avec VMware Horizon 7 : offrez aux utilisateurs intensifs des graphiques 3D

T echnologiques Suresh, NetApp

[role="lead"]
Le rapport technique TR-4792 fournit des conseils sur l'utilisation du nœud de calcul NetApp H615C pour les workloads de graphiques 3D dans un environnement VMware Horizon optimisé par les processeurs graphiques (GPU) et le logiciel de virtualisation NVIDIA. Il fournit également les résultats des tests préliminaires de SPECviewperf 13 pour le H615C.

link:https://www.netapp.com/pdf.html?item=/media/7125-tr4792.pdf["NetApp HCI pour l'infrastructure de postes de travail virtuels avec VMware Horizon 7 : offrez aux utilisateurs intensifs des graphiques 3D"^]
