---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= Multicloud hybride
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les architectures multicloud hybrides de VMware avec NetApp permettent une intégration transparente entre l'infrastructure sur site et les services de cloud public, offrant ainsi flexibilité et évolutivité.



== Introduction

Cette approche permet aux entreprises de migrer facilement les charges de travail, d'optimiser l'utilisation des ressources et de maintenir la cohérence des opérations dans les deux environnements.

Pour en savoir plus sur les scénarios de cloud hybride avec VMware et NetApp, consultez link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["Présentation du multicloud hybride NetApp avec VMware"].



== Scénarios de déploiement de VMware avec NetApp

Cette section décrit les différentes options de déploiement des environnements VMware sur site et dans les clouds publics. Chacun des fournisseurs cloud prend en charge une pile VMware Software Defined Data Center (SDDC) et/ou VMware Cloud Foundation (VCF) dans ses offres de cloud public respectives.

* *VMware sur site*


L'utilisation de VMware avec le stockage NetApp sur site offre un environnement de virtualisation robuste, évolutif et flexible. En associant les fonctionnalités avancées de gestion des données de NetApp, telles que la déduplication, la compression et les copies Snapshot efficaces, au système de stockage approprié optimisé par ONTAP, les clients peuvent choisir la plateforme qui leur convient. Cette combinaison assure des performances élevées, une fiabilité élevée et une gestion simplifiée des charges de travail virtualisées, ce qui améliore l'efficacité globale du data Center.

* *Solution Azure VMware*


Azure VMware solution est un service de cloud hybride qui permet d'assurer un fonctionnement optimal des SDDC VMware dans le cloud public Microsoft Azure. Azure VMware solution est une solution première entièrement gérée et prise en charge par Microsoft, vérifiée par VMware exploitant l'infrastructure Azure. Cela signifie qu'lors du déploiement de la solution Azure VMware, les clients bénéficient de VMware ESXi pour la virtualisation du calcul, de VSAN pour le stockage hyper-convergé, Enfin, NSX pour la mise en réseau et la sécurité, tout en exploitant la présence mondiale de Microsoft Azure, d'installations de data Center de premier plan et à proximité de notre riche écosystème de services et de solutions Azure natifs.

* *VMware Cloud sur AWS*


VMware Cloud sur AWS permet au logiciel SDDC de VMware d'entreprise d'accéder au cloud AWS grâce à un accès optimisé aux services AWS natifs. Optimisée par VMware Cloud Foundation, VMware Cloud sur AWS intègre les produits de virtualisation du réseau, du stockage et de calcul de VMware (VMware vSphere, VMware VSAN et VMware NSX), ainsi que la solution de gestion de VMware vCenter Server, optimisée pour s'exécuter sur une infrastructure AWS dédiée, flexible et sans système d'exploitation.

* *Google Cloud VMware Engine*


Google Cloud VMware Engine est une offre d'infrastructure en tant que service (IaaS) basée sur l'infrastructure évolutive hautement performante de Google Cloud et sur la pile VMware Cloud Foundation (VMware vSphere, vCenter, VSAN et NSX-T. ce service permet une migration rapide vers le cloud, en migrant ou en étendant de manière transparente les workloads VMware existants depuis les environnements sur site vers Google Cloud Platform, sans le coût, les efforts et le risque de remanier les applications ou les outils. Il s'agit d'un service vendu et pris en charge par Google, en étroite collaboration avec VMware.
