---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-data-infrastructure-insights.html 
keywords: vmware, getting, started, overview, netapp, data, infrastructure, insights, dii 
summary:  
---
= Informations sur l'infrastructure de données (DII)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Data Infrastructure Insights est un outil de surveillance de l'infrastructure cloud qui permet de bénéficier d'une grande visibilité sur l'ensemble de l'infrastructure.



== Introduction

Avec Data Infrastructure Insights, vous pouvez surveiller et optimiser toutes les ressources et résoudre les problèmes, y compris dans les clouds publics et dans vos data centers privés.

Pour plus d'informations sur Data Infrastructure Insights, voir link:https://docs.netapp.com/us-en/data-infrastructure-insights/index.html["Documentation sur les informations exploitables de l'infrastructure de données"].



== Fonctionnalités d'informations exploitables sur l'infrastructure de données

* Les informations sur l'infrastructure de données fournissent une surveillance multicloud hybride, ce qui assure l'observabilité intégrale de l'infrastructure et des workloads.
* Collecteurs de données pour infrastructure et workloads hétérogènes, y compris Kubernetes
* Ouvrez le collecteur Telegraf et les API ouvertes pour faciliter l'intégration
* Alertes et notifications complètes
* Machine learning pour des informations exploitables
* Optimisez l'utilisation des ressources
* Tableaux de bord intégrés ou personnalisables avec filtres avancés pour réduire le bruit d'affichage afin de répondre aux questions
* Découvrez l'état de santé des opérations de stockage ONTAP 
* Protégez vos ressources les plus précieuses : les données contre les attaques par ransomware ou les destructions de données

