---
sidebar: sidebar 
permalink: vmware/vmw-vcf-migrate.html 
keywords: vmware, vcf, migrate, import 
summary:  
---
= Migration de l'infrastructure existante vers VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La conversion d'un environnement vSphere avec des datastores existants s'exécutant sur ONTAP en un environnement VMware Cloud Foundation (VCF) implique d'intégrer l'infrastructure existante dans une architecture de cloud privé moderne.

Ce processus tire parti de la flexibilité du stockage ONTAP pour une gestion et un accès transparents aux données. Une fois le domaine de gestion VCF établi, les administrateurs peuvent importer efficacement des environnements vSphere supplémentaires dans l'écosystème VCF. Cette intégration améliore l'utilisation des ressources, simplifie la gestion du cloud privé et assure une transition en douceur avec une interruption minimale des charges de travail existantes.

Pour plus d'informations techniques sur la conversion d'une instance vCenter, reportez-vous aux solutions suivantes.

* link:vmw-vcf-mgmt-nfs.html["Conversion d'une instance vCenter existante en domaine de gestion VCF (NFS)"]
* link:vmw-vcf-mgmt-fc.html["Convertir l'instance vCenter (datastore FC) en domaine de gestion VCF"]

