---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-sc.html 
keywords: vmware, vcf, protect, snapcenter 
summary:  
---
= Protéger les workloads avec SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le plug-in SnapCenter pour VMware vSphere optimise le socle cloud VMware en simplifiant la sauvegarde et la restauration, en garantissant la cohérence des sauvegardes au niveau des applications et en optimisant le stockage grâce aux technologies d'efficacité de NetApp.

Il prend en charge des flux de travail automatisés et des opérations évolutives tout en assurant une intégration transparente au client vSphere. Avec la réplication SnapMirror qui fournit une sauvegarde secondaire sur site ou dans le cloud, elle assure une protection robuste des données et une efficacité opérationnelle dans les environnements virtualisés.

Pour plus d'informations, reportez-vous aux solutions suivantes.

* link:vmw-vcf-scv-wkld.html["Protégez le domaine de charge de travail VCF"]
* link:vmw-vcf-scv-multiwkld.html["Protégez VCF avec plusieurs domaines de workloads"]
* link:vmw-vcf-scv-nvme.html["Protégez VCF Workload Domain avec NVMe"]
* link:vmw-vcf-scv-321.html["3-2-1 protection des données pour VMware avec le plug-in SnapCenter et sauvegarde et restauration BlueXP pour les VM"]

