---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-vm-data-collector.html 
keywords: vmware, getting, started, overview, netapp, vm, data, collector, vmdc 
summary:  
---
= Data Collector VM (VMDC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour dimensionner correctement et prévoir les opportunités d'optimisation, il est essentiel de comprendre l'état actuel de l'environnement VMware.



== Introduction

Virtual machine Data Collector (VMDC) est un kit d'outils gratuit, léger et simple basé sur une interface utilisateur graphique pour les environnements VMware qui permet aux utilisateurs de collecter des informations d'inventaire détaillées sur leurs machines virtuelles (VM), leurs hôtes, leur stockage et leurs réseaux.

Pour plus d'informations sur Virtual machine Data Collector, reportez-vous à link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmdc.html["Documentation du Data Collector de la machine virtuelle"]la section .



== Fonctionnalités VMDC

VMDC n'est qu'un pas en avant pour collecter des statistiques rapides et instantanées afin de prévoir les possibilités d'optimisation pour les licences VMware Core, ainsi que pour les CPU virtuels et la RAM. Les informations exploitables de l'infrastructure de données NetApp qui requièrent l'installation d'un contrôleur d'accès aux États-Unis et de collecteurs de données doivent être la prochaine étape évidente pour comprendre la topologie détaillée des machines virtuelles, le regroupement de machines virtuelles à l'aide d'annotations afin d'adapter la taille des workloads et de pérenniser l'infrastructure.

Échantillonnage des mesures recueillies avec VMDC :

* Informations sur les VM
+
** Nom du VM
** État d'alimentation de la machine virtuelle
** Informations sur le processeur du VM
** Informations sur la mémoire de la machine virtuelle
** Emplacement des machines virtuelles
** Informations sur le réseau des machines virtuelles
** entre autres


* Performances des VM
+
** Données de performances des VM à un intervalle sélectionné
** Informations de lecture/écriture de la machine virtuelle
** Informations sur les IOPS des machines virtuelles
** Latence des machines virtuelles
** entre autres


* Informations sur l'hôte ESXi
+
** Informations sur le data Center hôte
** Informations sur le cluster hôte
** Informations sur le modèle hôte
** Informations sur le processeur hôte
** Informations sur la mémoire hôte
** entre autres



