---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary:  
---
= Développez l'environnement VCF avec le stockage supplémentaire
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation (VCF) prend en charge un large éventail d'options de stockage supplémentaires pour l'extension du stockage dans les domaines de la gestion VCF et des charges de travail VI.

Les outils ONTAP de NetApp pour VMware vSphere fournissent une solution efficace pour cette extension en intégrant le stockage NetApp en toute transparence dans l'environnement VCF. Les outils ONTAP simplifient la configuration et la gestion des datastores, ce qui permet aux administrateurs de provisionner et de gérer le stockage directement depuis le client vSphere. Les fonctionnalités avancées de ONTAP, telles que les copies Snapshot, le clonage et la protection des données, améliorent les performances du stockage, l'efficacité et l'évolutivité au sein de l'environnement VCF.

Veuillez vous reporter aux solutions suivantes pour obtenir des détails techniques sur l'extension de l'environnement VCF.

* link:vmw-vcf-mgmt-supplemental-iscsi.html["Domaine de gestion avec iSCSI"]
* link:vmw-vcf-mgmt-supplemental-fc.html["Domaine de gestion avec FC"]
* link:vmw-vcf-viwld-supplemental-vvols.html["Domaine de charge de travail de l'infrastructure virtuelle avec vVols (iSCSI)"]
* link:vmw-vcf-viwld-supplemental-nfs-vvols.html["Domaine de charge de travail de l'infrastructure virtuelle avec vVols (NFS)"]
* link:vmw-vcf-viwld-supplemental-nvme.html["Domaine de charge de travail de l'infrastructure virtuelle avec NVMe/TCP"]
* link:vmw-vcf-viwld-supplemental-fc.html["Virtual Infrastructure Workload Domain avec FC"]

