---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-ontap-apis-automation.html 
keywords:  
summary:  
---
= Utilisation des API NetApp pour améliorer l'administration VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les API (application Programming interfaces) jouent un rôle crucial dans l'administration VMware en permettant l'automatisation, l'intégration et la gestion rationalisée des environnements virtualisés.



== Introduction

VMware propose toute une gamme d'API qui permettent aux administrateurs d'interagir par programmation avec divers produits et services VMware, améliorant ainsi l'efficacité et la cohérence des opérations. De plus, les API NetApp ONTAP offrent un ensemble robuste d'outils qui permettent aux administrateurs d'automatiser, d'intégrer et d'optimiser la gestion des environnements de stockage, notamment avec les charges de travail VMware. Ces API facilitent une interaction transparente entre les systèmes de stockage ONTAP et VMware, améliorant ainsi l'efficacité, les performances et la protection des données.



== API VMware

* *API VMware vSphere :* l'API vSphere est une API complète qui permet aux administrateurs de gérer et d'automatiser les environnements VMware vSphere. Il permet d'accéder à un large éventail de fonctionnalités vSphere, notamment le provisionnement des serveurs virtuels, la configuration, la surveillance et la gestion du cycle de vie.
* *API REST de VMware vCenter Server :* l'API REST de vCenter Server fournit une interface RESTful moderne pour la gestion de vCenter Server et de ses composants associés. Il simplifie l'automatisation et l'intégration avec d'autres systèmes et outils.
* *API VMware Cloud Foundation :* les API VMware Software-Defined Data Center (SDDC) fournissent un accès programmatique aux différents composants et services d'un environnement VMware SDDC. Ces API permettent aux administrateurs et aux développeurs d'automatiser, de gérer et d'intégrer les différents aspects du data Center, notamment les services de calcul, de stockage, de mise en réseau et de gestion.
* *API de stockage VMware vSphere - Storage Awareness:* VASA est un ensemble d'API permettant l'intégration des baies de stockage à vCenter pour la gestion et l'administration. L'architecture repose sur plusieurs composants, notamment le fournisseur VASA qui gère la communication entre VMware vSphere et les systèmes de stockage. Avec ONTAP, le fournisseur est implémenté dans le cadre des outils ONTAP pour VMware vSphere.
* *VMware vSphere Storage APIs - Array Integration:* VAAI est un ensemble d'API qui permettent la communication entre les hôtes VMware vSphere ESXi et les périphériques de stockage. L'API inclut un ensemble d'opérations primitives utilisées par les hôtes pour décharger les opérations de stockage vers la baie. VAAI permet d'améliorer considérablement les performances des tâches consommatrices de stockage.




== API basées sur ONTAP

* *API REST NetApp ONTAP :* l'API REST ONTAP fournit une interface RESTful moderne pour la gestion des systèmes de stockage ONTAP. Il simplifie l'automatisation des tâches de stockage telles que le provisionnement, la surveillance et la configuration. Il facilite l'intégration à VMware vSphere et à d'autres outils de gestion VMware, permettant d'automatiser les opérations de stockage directement à partir d'environnements VMware. Il prend en charge un large éventail d'opérations, de la gestion de base du stockage aux tâches avancées de protection des données et de réplication, pour une gestion du stockage évolutive et flexible.
* *Outils ONTAP pour VMware vSphere :* les outils ONTAP pour VMware vSphere sont un ensemble d'outils permettant d'intégrer ONTAP et vSphere. Il implémente les fonctionnalités de fournisseur du framework d'API VASA. Les outils ONTAP incluent également le plug-in vCenter, un adaptateur de réplication du stockage (SRA) pour VMware site Recovery Manager et un serveur d'API REST qui vous permet de créer des applications d'automatisation.




== Récapitulatif

En résumé, grâce aux API ONTAP, les administrateurs peuvent créer et configurer des scripts pour les datastores dans les environnements VMware, afin de garantir un provisionnement du stockage rapide et cohérent. En outre, ils peuvent automatiser la création, la planification et la suppression de snapshots pour les machines virtuelles VMware, offrant ainsi des options efficaces de protection et de récupération des données. Les API SnapMirror facilitent l'automatisation de la configuration et de la gestion des relations de réplication, assurant ainsi des solutions robustes de reprise d'activité pour les workloads VMware. Les administrateurs peuvent également implémenter des scripts pour surveiller les metrics de performance du stockage et déclencher des alertes ou des actions automatisées lorsque les seuils de performance sont atteints, garantissant ainsi des performances de stockage optimales pour les workloads VMware. En intégrant les API ONTAP aux API VMware, telles que celles fournies par vSphere et vRealize, les administrateurs bénéficient d'une gestion fluide et hautement automatisée, ce qui améliore l'efficacité et la fiabilité globales de leur infrastructure virtualisée.
