---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS sur FC en tant que stockage principal pour les domaines de charge de travail VI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans ce scénario, nous examinerons comment configurer un datastore VMFS avec Fibre Channel (FC) comme stockage principal pour le déploiement d'un domaine de charge de travail VI dans VCF. Le cas échéant, nous nous référons à la documentation externe pour connaître les étapes à suivre dans le gestionnaire SDDC de VCF, et nous aborderons les étapes spécifiques à la partie relative à la configuration du stockage.



== Avantages de la technologie Fibre Channel

*Haute performance :* FC fournit des vitesses de transfert de données haut débit, ce qui le rend idéal pour les applications nécessitant un accès rapide et fiable à de grandes quantités de données.

*Faible latence :* très faible latence, ce qui est crucial pour les applications sensibles aux performances comme les bases de données et les environnements virtualisés.

*Fiabilité:* les réseaux FC sont connus pour leur robustesse et leur fiabilité, avec des fonctionnalités comme la redondance intégrée et la correction d'erreurs.

*Bande passante dédiée :* FC fournit une bande passante dédiée pour le trafic de stockage, réduisant ainsi le risque d'encombrement du réseau.

Pour plus d'informations sur l'utilisation de Fibre Channel avec les systèmes de stockage NetApp, reportez-vous àla section https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisionnement SAN avec FC"].



== Présentation du scénario

Ce scénario couvre les étapes générales suivantes :

* Créez un SVM (Storage Virtual machine) avec des interfaces logiques (LIF) pour le trafic FC.
* Collectez les informations WWPN des hôtes à déployer et créez les groupes initiateurs correspondants sur le système de stockage ONTAP.
* Créez un volume FC sur le système de stockage ONTAP.
* Mappez les groupes initiateurs pour créer un volume FC
* Utilisez la segmentation cible-initiateur unique sur les commutateurs FC. Créer une zone pour chaque initiateur (zone initiateur unique).
+
** Pour chaque zone, inclure une cible faisant l'interface logique (WWPN) FC ONTAP pour les SVM. Il devrait y avoir au minimum deux interfaces logiques par nœud et par SVM. N'utilisez pas le WWPN des ports physiques.


* Créez un pool réseau pour le trafic vMotion dans SDDC Manager.
* Commission des hôtes dans VCF pour une utilisation dans un domaine de charge de travail VI.
* Déployez un domaine de charge de travail VI dans VCF en utilisant un datastore FC comme stockage principal.



NOTE: Cette solution s'applique aux plateformes ONTAP qui prennent en charge le stockage NFS, y compris NetApp AFF et FAS.



== Prérequis

Les composants et configurations suivants sont utilisés dans ce scénario :

* Un système de stockage ONTAP AFF ou ASA avec des ports FC connectés aux commutateurs FC.
* Création d'un SVM avec des lif FC.
* VSphere avec HBA FC connecté aux commutateurs FC.
* La segmentation cible-initiateur unique est configurée sur des commutateurs FC.



NOTE: NetApp recommande les chemins d'accès multiples pour les LUN FC.



== Étapes de déploiement



=== Domaine de gestion - Cluster par défaut

Le stockage principal FC sur le cluster initial n'est pris en charge qu'avec l'outil d'importation brownfield VCF. Si VCF est déployé avec l'outil cloudbuilder (jusqu'à la version 5.2.x), seul VSAN est pris en charge. Reportez-vous https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["Conversion de l'environnement vSphere existant en domaine de gestion"] à pour plus d'informations.



=== Domaine de gestion - Cluster supplémentaire

Le cluster vSphere supplémentaire sur le domaine de gestion peut être déployé avec les options suivantes : * disposer d'un cluster supplémentaire dans l'environnement vSphere et utiliser l'outil d'importation VCF brownfield pour convertir l'environnement vSphere en domaine de gestion. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Les outils ONTAP pour VMware vSphere"], https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager ou API ONTAP"] Peut être utilisé pour déployer le datastore VMFS sur un cluster vSphere. * Utilisez l'API SDDC pour déployer un cluster supplémentaire. Le datastore VMFS doit être configuré pour les hôtes vSphere. Utilisez https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager ou API ONTAP"] pour déployer LUN sur des hôtes vSphere. * Utilisez l'interface utilisateur de SDDC Manager pour déployer un cluster supplémentaire. Mais cette option ne crée que le datastore VSAN jusqu'à la version 5.2.x.



=== VI Workload Domain - Cluster par défaut

Une fois le domaine de gestion opérationnel, il est possible de créer le domaine VI Workload :

* À l'aide de l'interface utilisateur de SDDC Manager. Le datastore VMFS doit être configuré pour les hôtes vSphere. Utilisez System Manager ou l'API ONTAP pour déployer les LUN sur les hôtes vSphere.
* Importez un environnement vSphere existant en tant que nouveau domaine de charge de travail VI. Les outils ONTAP pour VMware vSphere, System Manager ou l'API ONTAP peuvent être utilisés pour déployer le datastore VMFS sur un cluster vSphere.




=== Domaine de charge de travail VI - Cluster supplémentaire

Une fois la charge de travail de l'infrastructure virtuelle opérationnelle, des clusters supplémentaires peuvent être déployés avec VMFS sur une LUN FC à l'aide des options suivantes.

* Clusters supplémentaires dans l'environnement vSphere importés à l'aide de l'outil d'importation de brownfield VCF. Les outils ONTAP pour VMware vSphere, System Manager ou l'API ONTAP peuvent être utilisés pour déployer le datastore VMFS sur un cluster vSphere.
* Déploiement d'un cluster supplémentaire à l'aide de l'interface utilisateur ou de l'API SDDC Manager. Le datastore VMFS doit être configuré pour les hôtes vSphere. Utilisez System Manager ou l'API ONTAP pour déployer les LUN sur les hôtes vSphere.




== Informations supplémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP, reportez-vous au link:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour plus d'informations sur la configuration de VCF, reportez-vous link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentation de VMware Cloud Foundation"]à la section .
