---
sidebar: sidebar 
permalink: vmware/vmw-vcf-provision.html 
keywords: vmware, vcf, provision, principal, storage 
summary:  
---
= Provisionnement de l'environnement VCF avec le stockage principal
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le stockage NetApp ONTAP constitue la solution de stockage principale idéale pour la gestion VMware Cloud Foundation (VCF) et les domaines des charges de travail d'infrastructure virtuelle. Elle offre des performances élevées, une évolutivité optimale, une gestion avancée des données et une intégration transparente, ce qui améliore l'efficacité opérationnelle et la protection des données.

Veuillez vous reporter aux solutions suivantes pour obtenir des détails techniques sur l'approvisionnement d'un environnement VCF dans le domaine approprié et avec le protocole approprié.

* link:vmw-vcf-mgmt-principal-fc.html["Domaine de gestion avec FC"]
* link:vmw-vcf-mgmt-principal-nfs.html["Domaine de gestion avec NFS"]
* link:vmw-vcf-viwld-principal-fc.html["Virtual Infrastructure Workload Domain avec FC"]
* link:vmw-vcf-viwld-principal-nfs.html["Virtual Infrastructure Workload Domain avec NFS"]

