---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= Haute disponibilité avec VMware vSphere Metro Storage Cluster (vMSC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La haute disponibilité NetApp ONTAP, intégrée à VMware vSphere Metro Storage Cluster (vMSC), offre une solution robuste pour la gestion VMware Cloud Foundation (VCF) et les domaines de charge de travail VI.

Cette combinaison assure la disponibilité continue des données, des basculements et des reprises après incident sur l'ensemble des sites dispersés géographiquement, ce qui améliore la résilience et la continuité opérationnelle des workloads stratégiques. Avec la synchronisation active SnapMirror, les services de l'entreprise continuent de fonctionner même en cas de défaillance complète d'un site, ce qui permet aux applications de basculer en toute transparence au moyen d'une copie secondaire. Aucune intervention manuelle ni script personnalisé n'est nécessaire pour déclencher un basculement avec la synchronisation active SnapMirror.

Pour plus d'informations, reportez-vous aux solutions suivantes.

* link:vmw-vcf-vmsc-mgmt-smas.html["Cluster étendu pour le domaine de gestion à l'aide de la synchronisation active SnapMirror"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["Cluster étendu pour domaine de gestion à l'aide de MetroCluster"]
* link:vmw-vcf-vmsc-viwld-smas.html["Cluster étendu pour domaine de charge de travail VI utilisant la synchronisation active SnapMirror"]
* link:vmw-vcf-vmsc-viwld-mcc.html["Cluster étendu pour domaine de charge de travail VI à l'aide de MetroCluster"]

