---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-migration.html 
keywords: vmware, getting, started, overview, netapp 
summary:  
---
= Migration de machines virtuelles vers des datastores ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La migration des workloads VMware vers NetApp ONTAP simplifie la gestion des données et améliore les performances grâce aux fonctionnalités avancées de stockage de ONTAP, telles que la déduplication, la compression et les copies Snapshot efficaces.



== Introduction

Cette migration permet une intégration transparente, une meilleure protection des données et une gestion plus flexible des environnements virtualisés, ce qui assure une transition en douceur avec un temps d'indisponibilité minimal.

Pour plus d'informations sur la migration des workloads VMware vers des datastores ONTAP, consultez le link:https://docs.netapp.com/us-en/netapp-solutions/vmware/migrate-vms-to-ontap-datastore.html["Migrez vos machines virtuelles vers les datastores ONTAP"].



== Cas d'utilisation

Si vous envisagez de migrer vers des datastores ONTAP, vous avez le choix entre la source et la destination.

* Migration à partir de systèmes de stockage tiers (y compris VSAN) vers des datastores ONTAP.
* Migration de machines virtuelles dans le même cluster vSphere
* Migration des machines virtuelles sur plusieurs clusters vSphere
* Migration des machines virtuelles sur les serveurs vCenter dans le même domaine SSO
* Migration des machines virtuelles sur les serveurs vCenter dans différents domaines SSO
* Migration de machines virtuelles dans des data centers
* Migration à partir de systèmes de stockage tiers (y compris VSAN) vers des datastores ONTAP.
* Migration des machines virtuelles dans un environnement cloud hybride

