---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-snapcenter.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Plug-in SnapCenter pour VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le plug-in SnapCenter pour VMware vSphere offre des opérations de sauvegarde et de restauration rapides, efficaces et cohérentes avec les machines virtuelles pour les machines virtuelles (VM), les datastores et les VMDK. Combiné au serveur SnapCenter, ce logiciel offre des fonctionnalités de sauvegarde et de restauration basées sur les applications pour les plug-ins spécifiques aux applications SnapCenter.



== Ressources de documentation

Pour plus d'informations, reportez-vous aux ressources de documentation suivantes.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Documentation du plug-in SnapCenter pour VMware vSphere"]




== Ressources de la solution

Reportez-vous à la solution de sauvegarde 3-2-1 suivante qui intègre le plug-in SnapCenter pour VMware vSphere et la sauvegarde et restauration BlueXP pour les VM.

Rapport technique : link:../ehc/bxp-scv-hybrid-solution.html["3-2-1 protection des données pour VMware avec le plug-in SnapCenter et sauvegarde et restauration BlueXP pour les VM"]

Blog Tech OnTap : link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["3-2-1 protection des données pour VMware avec le plug-in SnapCenter et sauvegarde et restauration BlueXP pour les VM"]



== Ressources vidéo

.Plug-in SnapCenter pour VMware vSphere : conditions requises pour la solution
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.Plug-in SnapCenter pour VMware vSphere : déploiement
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.Plug-in SnapCenter pour VMware vSphere - Workflow de sauvegarde
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.Plug-in SnapCenter pour VMware vSphere : restaurez les flux de travail
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - flux de travail de restauration SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]