---
sidebar: sidebar 
permalink: vmware/vmw-vcf-draas-bxp.html 
keywords: vmware, vcf, dr, disaster recovery, draas, bluexp 
summary:  
---
= Reprise après incident à l'aide de la DRaaS BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La reprise après incident NetApp BlueXP  en tant que service (DRaaS) met en œuvre la reprise après incident via une réplication au niveau des blocs entre un site principal et un site de reprise après incident.

La DRaaS BlueXP  est une méthode efficace et économique pour protéger les workloads contre les défaillances de site et les problèmes d'intégrité des données, y compris les attaques par ransomware. Par ailleurs, la DRaaS NetApp BlueXP  améliore cette stratégie en fournissant une solution de reprise d'activité gérée dans le cloud, pour une restauration rapide et des interruptions minimales en cas d'incident.

Pour plus d'informations techniques, reportez-vous aux solutions suivantes.

* link:vmw-dr-draas-vmfs.html["Reprise après incident à l'aide de la DRaaS BlueXP  pour les datastores VMFS"]
* link:vmw-dr-draas-nfs.html["Reprise après incident à l'aide de la DRaaS BlueXP  pour les datastores NFS"]

