---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-ontap-tools-for-vmware.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= Outils ONTAP pour VMware (OTV)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP pour VMware vSphere offrent une gestion de bout en bout du cycle de vie des machines virtuelles dans des environnements VMware qui utilisent des systèmes de stockage NetApp.



== Introduction

Il permet aux administrateurs de gérer directement le stockage dans vCenter Server et de simplifier la gestion du stockage et des données dans les environnements VMware. Le plug-in VMware vSphere client est conçu pour intégrer la fonctionnalité de plug-in au client vSphere sans avoir à l'exécuter dans vCenter Server. Cela permet d'isoler les plug-ins et de faire évoluer horizontalement les plug-ins qui fonctionnent dans de grands environnements vSphere.



== Composants des outils ONTAP

* *Virtual Storage Console (VSC)* VSC inclut l'interface intégrée au client vSphere, dans laquelle vous pouvez ajouter des contrôleurs de stockage, provisionner des datastores, surveiller les performances des datastores et afficher et mettre à jour les paramètres des hôtes ESXi.
* *VASA Provider* le fournisseur VMware vSphere APIs for Storage Awareness (VASA) pour ONTAP envoie des informations sur le stockage utilisé par VMware vSphere au serveur vCenter, permettant le provisionnement de datastores VMware Virtual volumes (vVols), la création et l'utilisation de profils de fonctionnalités de stockage, la vérification de conformité et la surveillance des performances.
* *Storage Replication adapter (SRA)* lorsqu'il est activé et utilisé avec VMware site Recovery Manager (SRM), SRA facilite la récupération des datastores et des machines virtuelles vCenter Server en cas de panne, permettant ainsi la configuration des sites protégés et des sites de reprise après incident.


Pour plus d'informations sur les outils NetApp ONTAP pour VMware, voir https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Documentation sur les outils ONTAP pour VMware vSphere"].
