---
sidebar: sidebar 
permalink: vmware/vmware_vcf_aff_supp_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS sur FC en tant que datastore supplémentaire VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans ce scénario, nous montrerons comment déployer un datastore VMFS avec back-end Fibre Channel(FC) pour des domaines de gestion et de charge de travail à l'aide des outils ONTAP.

Auteur: Suresh Thoppay



== Présentation du scénario

Le datastore supplémentaire VCF est mis à niveau dans le cadre des opérations du 2e jour à l'aide de vCenter. Ce scénario couvre les étapes générales suivantes :

* Déploiement des outils ONTAP dans le domaine de gestion
* Enregistrez les serveurs vCenter de la charge de travail VI sur les outils ONTAP
* Définissez le stockage back-end sur le plug-in des outils ONTAP pour VMware vSphere
* Provisionner VMFS sur le transport FC




== Prérequis

Ce scénario nécessite les composants et configurations suivants :

* Un système de stockage ONTAP avec des ports FC connectés aux commutateurs FC.
* Création d'un SVM avec des lif FC.
* VSphere avec HBA FC connecté aux commutateurs FC.
* La segmentation cible-initiateur unique est configurée sur des commutateurs FC.
+

NOTE: Utiliser l'interface logique du SVM FC en configuration de zone plutôt que les ports FC physiques sur les systèmes ONTAP.



NetApp recommande les chemins d'accès multiples pour les LUN FC.



== Étapes de déploiement pour le domaine de gestion

Pour déployer les outils ONTAP et les utiliser pour créer un datastore VMFS sur le domaine de gestion VCF, procédez comme suit :

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Déployez les outils ONTAP dans le domaine de gestion"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Définir le back-end de stockage à l'aide de l'interface client vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Provisionnement VMFS sur FC"]




== Étapes de déploiement pour le domaine de charge de travail VI

Pour déployer les outils ONTAP et les utiliser pour créer un datastore VMFS sur le domaine de charge de travail VCF VI, procédez comme suit :

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Enregistrez vCenter de la charge de travail VI pour activer le plug-in vCenter"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Définir le back-end de stockage à l'aide de l'interface client vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Provisionnement VMFS sur FC"]




== Informations supplémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP, reportez-vous au link:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour plus d'informations sur la configuration de VCF, reportez-vous link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentation de VMware Cloud Foundation"]à la section .



== Vidéo de démonstration de cette solution

.Datastore VMFS(FC) en tant que stockage supplémentaire pour le domaine de gestion VCF
video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto,width=360]