---
sidebar: sidebar 
permalink: vmware/vmware_vcf_asa_prin_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS sur FC en tant que datastore principal VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans ce scénario, nous montrerons comment déployer un datastore VMFS avec back-end Fibre Channel(FC) pour les domaines de gestion et de charge de travail.

Auteur: Suresh Thoppay



== Présentation du scénario

Le stockage principal VCF fait référence à tout type de stockage déployé, converti ou importé dans le cadre du processus de configuration du domaine VCF. Ce document couvre les scénarios suivants.

[cols="20% 20% 20% 20% 20%"]
|===
| Type de stockage | Domaine de gestion - Cluster par défaut | Domaine de gestion - Cluster supplémentaire | VI Workload Domain - Cluster par défaut | Domaine de charge de travail VI - Cluster supplémentaire 


| VMFS sur FC | *Outil d'importation* | *Outil d'importation, SDDC API* | Oui. | Oui. 
|===


== Prérequis

Ce scénario nécessite les composants et configurations suivants :

* Un système de stockage ONTAP avec des ports FC connectés aux commutateurs FC.
* Création d'un SVM avec des lif FC.
* VSphere avec HBA FC connecté aux commutateurs FC.
* La segmentation cible-initiateur unique est configurée sur des commutateurs FC.
+

NOTE: Utiliser l'interface logique du SVM FC en configuration de zone plutôt que les ports FC physiques sur les systèmes ONTAP.



NetApp recommande les chemins d'accès multiples pour les LUN FC.



== Étapes de déploiement



=== Domaine de gestion - Cluster par défaut

Le stockage principal FC sur le cluster initial n'est pris en charge qu'avec l'outil d'importation brownfield VCF. Si VCF est déployé avec l'outil cloudbuilder (jusqu'à la version 5.2.x), seul VSAN est pris en charge. Reportez-vous https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["Conversion de l'environnement vSphere existant en domaine de gestion"] à pour plus d'informations.



=== Domaine de gestion - Cluster supplémentaire

Le cluster vSphere supplémentaire sur le domaine de gestion peut être déployé avec les options suivantes : * disposer d'un cluster supplémentaire dans l'environnement vSphere et utiliser l'outil d'importation VCF brownfield pour convertir l'environnement vSphere en domaine de gestion. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Les outils ONTAP pour VMware vSphere"], https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager ou API ONTAP"] Peut être utilisé pour déployer le datastore VMFS sur un cluster vSphere. * Utilisez l'API SDDC pour déployer un cluster supplémentaire. Le datastore VMFS doit être configuré pour les hôtes vSphere. Utilisez https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager ou API ONTAP"] pour déployer LUN sur des hôtes vSphere. * Utilisez l'interface utilisateur de SDDC Manager pour déployer un cluster supplémentaire. Mais cette option ne crée que le datastore VSAN jusqu'à la version 5.2.x.



=== VI Workload Domain - Cluster par défaut

Une fois le domaine de gestion opérationnel, vous pouvez créer un domaine de charge de travail VI * à l'aide de l'interface utilisateur SDDC Manager. Le datastore VMFS doit être configuré pour les hôtes vSphere. Utilisez System Manager ou l'API ONTAP pour déployer les LUN sur les hôtes vSphere. * Importer un environnement vSphere existant en tant que nouveau domaine de charge de travail VI. Les outils ONTAP pour VMware vSphere, System Manager ou l'API ONTAP peuvent être utilisés pour déployer le datastore VMFS sur un cluster vSphere.



=== Domaine de charge de travail VI - Cluster supplémentaire

Une fois la charge de travail de l'infrastructure virtuelle opérationnelle, des clusters supplémentaires peuvent être déployés avec VMFS sur une LUN FC à l'aide des options suivantes.

* Clusters supplémentaires dans l'environnement vSphere importés à l'aide de l'outil d'importation de brownfield VCF. Les outils ONTAP pour VMware vSphere, System Manager ou l'API ONTAP peuvent être utilisés pour déployer le datastore VMFS sur un cluster vSphere.
* Déploiement d'un cluster supplémentaire à l'aide de l'interface utilisateur ou de l'API SDDC Manager. Le datastore VMFS doit être configuré pour les hôtes vSphere. Utilisez System Manager ou l'API ONTAP pour déployer les LUN sur les hôtes vSphere.




== Informations supplémentaires

Pour plus d'informations sur la configuration des systèmes de stockage ONTAP, reportez-vous au link:https://docs.netapp.com/us-en/ontap["Documentation ONTAP 9"] centre.

Pour plus d'informations sur la configuration de VCF, reportez-vous link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentation de VMware Cloud Foundation"]à la section .
