---
sidebar: sidebar 
permalink: vmware/vsphere_auto_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 'Cette page décrit les avantages de l"automatisation de la fonctionnalité ONTAP de base dans un environnement VMware vSphere.' 
---
= Introduction à l'automatisation pour ONTAP et vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette page décrit les avantages de l'automatisation de la fonctionnalité ONTAP de base dans un environnement VMware vSphere.



== Automatisation avec VMware

Depuis les premiers jours de VMware ESX, l'automatisation fait partie intégrante de la gestion des environnements VMware. La possibilité de déployer une infrastructure en tant que code et d'étendre les pratiques aux opérations de cloud privé permet de réduire les problèmes liés à l'évolutivité, à la flexibilité, au provisionnement automatique et à l'efficacité.

L'automatisation peut être organisée selon les catégories suivantes :

* *Déploiement d'infrastructure virtuelle*
* *Fonctionnement de la machine invité*
* *Opérations dans le cloud*


Les administrateurs disposent de nombreuses options pour automatiser leur infrastructure. Qu'il s'agisse d'utiliser des fonctionnalités vSphere natives, telles que des profils d'hôtes ou des spécifications de personnalisation des machines virtuelles vers des API disponibles sur les composants logiciels VMware, les systèmes d'exploitation et les systèmes de stockage NetApp, la documentation et les conseils fournis sont considérables.

Data ONTAP 8.0.1 et versions ultérieures prennent en charge certaines API VMware vSphere pour l'intégration de baies (VAAI) lorsque l'hôte ESX exécute ESX 4.1 ou une version ultérieure. VAAI est un ensemble d'API qui permettent la communication entre les hôtes VMware vSphere ESXi et les périphériques de stockage. Ces fonctionnalités permettent de décharger l'hôte ESX vers le système de stockage et d'augmenter le débit du réseau. L'hôte ESX active ces fonctionnalités automatiquement dans l'environnement adéquat. Vous pouvez déterminer dans quelle mesure votre système utilise des fonctions VAAI en consultant les statistiques contenues dans les compteurs VAAI.

Le point de départ le plus courant pour l'automatisation du déploiement d'un environnement VMware consiste à provisionner des datastores basés sur des blocs ou des fichiers. Il est important de définir les exigences des tâches réelles avant de développer l'automatisation correspondante.

Pour plus d'informations sur l'automatisation des environnements VMware, consultez les ressources suivantes :

* https://netapp.io/configuration-management-and-automation/["NetApp Pub"^]. Gestion et automatisation de la configuration NetApp.
* https://galaxy.ansible.com/community/vmware["Communauté Ansible Galaxy pour VMware"^]. Ensemble de ressources Ansible pour VMware.
* https://community.broadcom.com/vmware-code/home["Ressources VMware {code}"^]. Ressources nécessaires à la conception de solutions pour le Software-Defined Data Center, y compris des forums, des normes de conception, des exemples de code et des outils de développement.

