---
sidebar: sidebar 
permalink: vmware/vsphere_ontap_auto_block_iscsi.html 
keywords: vSphere, datastore, VMFS, iSCSI, ONTAP tools, vlan, network interface, service policy 
summary: 'Cette page décrit les étapes du déploiement d"un datastore VMFS iSCSI pour le stockage NetApp ONTAP dans un environnement VMware vSphere.' 
---
= Datastore VMFS vSphere - stockage iSCSI back-end avec ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section décrit la création d'un datastore VMFS avec un stockage iSCSI ONTAP.

Pour le provisionnement automatisé, utilisez le script suivant : <<Ansible>>.



== Ce dont vous avez besoin

* Les compétences de base nécessaires à la gestion d'un environnement vSphere et d'ONTAP.
* Un système de stockage ONTAP (FAS/AFF/CVO/ONTAP Select/ASA) exécutant {ontap_version}
* Identifiants ONTAP (nom du SVM, ID d'utilisateur et mot de passe)
* Informations relatives au port réseau ONTAP, au SVM et aux LUN pour iSCSI
* link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-429C4DDD-5EC0-4DBD-8EA8-76082AB7ADEC.html++["Une fiche de configuration iSCSI remplie"]
* Informations d'identification du serveur vCenter
* Informations sur les hôtes vSphere
+
** {vsphere_version}


* Informations IP de l'adaptateur VMKernel iSCSI
* Commutateur(s) réseau
+
** Grâce aux ports de données du système ONTAP et aux hôtes vSphere connectés
** VLAN(s) configurés(s) pour iSCSI
** (Facultatif) agrégation de liens configurée pour les ports de données réseau ONTAP


* L'outil ONTAP pour VMware vSphere est déployé, configuré et prêt à l'emploi




== Étapes

. Vérifiez la compatibilité avec le https://mysupport.netapp.com/matrix["Matrice d'interopérabilité (IMT)"].
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-7D444A0D-02CE-4A21-8017-CB1DC99EFD9A.html++["Vérifiez que la configuration iSCSI est prise en charge."]
. Effectuez les tâches ONTAP et vSphere suivantes.




== Tâches ONTAP

. link:https://docs.netapp.com/us-en/ontap-cli-98/system-license-show.html["Vérifiez la licence ONTAP pour iSCSI"].
+
.. Utilisez le `system license show` Commande pour vérifier si iSCSI est répertorié.
.. Utiliser `license add -license-code <license code>` pour ajouter la licence.


. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-ED75D939-C45A-4546-8B22-6B765FF6083F.html++["Vérifier que le protocole iSCSI est activé sur le SVM"]
. Vérifier que les interfaces logiques réseau iSCSI sont disponibles sur le SVM.
+

NOTE: Lorsqu'un SVM est créé via l'interface utilisateur graphique, les interfaces réseau iSCSI sont également créées.

. Utilisez le `Network interface` commande pour afficher ou apporter des modifications à l'interface réseau.
+

TIP: Deux interfaces réseau iSCSI par nœud sont recommandées.

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-CEE760DF-A059-4018-BE6C-6B3A034CB377.html++["Créez une interface réseau iSCSI."] Vous pouvez utiliser la stratégie de service blocs de données par défaut.
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-BBC2D94B-DD3A-4029-9FCE-F71F9C157B53.html++["Vérifiez que le service Data-iscsi est inclus dans la stratégie de service."] Vous pouvez utiliser `network interface service-policy show` à vérifier.
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DE59CF49-3A5F-4F38-9F17-E2C16B567DC0.html++["Vérifiez que les trames Jumbo sont activées."]
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-D4DAC7DB-A6B0-4696-B972-7327EE99FD72.html++["Créer et mapper la LUN."] Ignorez cette étape si vous utilisez les outils ONTAP pour VMware vSphere. Répétez cette procédure pour chaque LUN.




== Tâches VMware vSphere

. Vérifiez qu'au moins une carte réseau est disponible pour le VLAN iSCSI. Deux cartes réseau sont à privilégier pour de meilleures performances et une meilleure tolérance aux pannes.
. link:++https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-single-host-management-vmware-host-client-7-0/networking-in-the-vsphere-host-client-vSphereSingleHostManagementVMwareHostClient/managing-physical-network-adapters-in-the-vsphere-host-client-vSphereSingleHostManagementVMwareHostClient/view-physical-network-adapter-information-in-the-vsphere-host-client-vSphereSingleHostManagementVMwareHostClient.html++["Identifier le nombre de cartes réseau physiques disponibles sur l'hôte vSphere."]
. link:++https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/configuring-iscsi-and-iser-adapters-and-storage-with-esxi/configure-the-software-iscsi-adapter-with-esxi.html++["Configurez l'initiateur iSCSI."] Un cas d'utilisation typique est un initiateur iSCSI logiciel.
. link:++https://techdocs.broadcom.com/us/en/vmware-cis/vsan/vsan/8-0/vsan-network-design/ip-network-transport-configuration/vsphere-tcp-ip-stacks.html++["Vérifiez que la pile TCPIP pour iSCSI est disponible"].
. link:++https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/assign-a-port-group-or-network-to-a-network-protocol-profile.html++["Vérifiez que les groupes de ports iSCSI sont disponibles"].
+
** Nous utilisons généralement un seul commutateur virtuel avec plusieurs ports de liaison ascendante.
** Utilisez le mappage de carte 1:1.


. Vérifiez que les adaptateurs iSCSI VMKernel sont activés pour correspondre au nombre de cartes réseau et que les adresses IP sont attribuées.
. link:++https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/configuring-iscsi-and-iser-adapters-and-storage-with-esxi/configure-the-software-iscsi-adapter-with-esxi.html++["Reliez la carte logicielle iSCSI aux adaptateurs VMKernel iSCSI."]
. link:++https://docs.netapp.com/vapp-98/topic/com.netapp.doc.vsc-iag/GUID-D7CAD8AF-E722-40C2-A4CB-5B4089A14B00.html++["Provisionnement du datastore VMFS avec les outils ONTAP"]. Répétez cette étape pour tous les datastores.
. link:++https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/storage-hardware-acceleration-in-vsphere/vsphere-hardware-acceleration-on-block-storage/managing-hardware-acceleration-filter-and-plug-ins/verify-hardware-acceleration-support-status.html++["Vérifier la prise en charge de l'accélération matérielle."]




== Et la suite ?

Une fois ces tâches terminées, le datastore VMFS est prêt à utiliser pour le provisionnement des machines virtuelles.

.PlayBook Ansible
[source]
----
## Disclaimer: Sample script for reference purpose only.

- hosts: '{{ vsphere_host }}'
  name: Play for vSphere iSCSI Configuration
  connection: local
  gather_facts: false
  tasks:
    # Generate Session ID for vCenter
    - name: Generate a Session ID for vCenter
      uri:
        url: "https://{{ vcenter_hostname }}/rest/com/vmware/cis/session"
        validate_certs: false
        method: POST
        user: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
        force_basic_auth: yes
        return_content: yes
      register: vclogin

    # Generate Session ID for ONTAP tools with vCenter
    - name: Generate a Session ID for ONTAP tools with vCenter
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/security/user/login"
        validate_certs: false
        method: POST
        return_content: yes
        body_format: json
        body:
          vcenterUserName: "{{ vcenter_username }}"
          vcenterPassword: "{{ vcenter_password }}"
      register: login

    # Get existing registered ONTAP Cluster info with ONTAP tools
    - name: Get ONTAP Cluster info from ONTAP tools
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/storage/clusters"
        validate_certs: false
        method: Get
        return_content: yes
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
      register: clusterinfo

    - name: Get ONTAP Cluster ID
      set_fact:
        ontap_cluster_id: "{{ clusterinfo.json | json_query(clusteridquery) }}"
      vars:
        clusteridquery: "records[?ipAddress == '{{ netapp_hostname }}' && type=='Cluster'].id | [0]"

    - name: Get ONTAP SVM ID
      set_fact:
        ontap_svm_id: "{{ clusterinfo.json | json_query(svmidquery) }}"
      vars:
        svmidquery: "records[?ipAddress == '{{ netapp_hostname }}' && type=='SVM' && name == '{{ svm_name }}'].id | [0]"

    - name: Get Aggregate detail
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/storage/clusters/{{ ontap_svm_id }}/aggregates"
        validate_certs: false
        method: GET
        return_content: yes
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
          cluster-id: "{{ ontap_svm_id }}"
      when: ontap_svm_id != ''
      register: aggrinfo

    - name: Select Aggregate with max free capacity
      set_fact:
        aggr_name: "{{ aggrinfo.json | json_query(aggrquery) }}"
      vars:
        aggrquery: "max_by(records, &freeCapacity).name"

    - name: Convert datastore size in MB
      set_fact:
        datastoreSizeInMB: "{{ iscsi_datastore_size | human_to_bytes/1024/1024 | int }}"

    - name: Get vSphere Cluster Info
      uri:
        url: "https://{{ vcenter_hostname }}/api/vcenter/cluster?names={{ vsphere_cluster }}"
        validate_certs: false
        method: GET
        return_content: yes
        body_format: json
        headers:
          vmware-api-session-id: "{{ vclogin.json.value }}"
      when: vsphere_cluster != ''
      register: vcenterclusterid

    - name: Create iSCSI VMFS-6 Datastore with ONTAP tools
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/3.0/admin/datastore"
        validate_certs: false
        method: POST
        return_content: yes
        status_code: [200]
        body_format: json
        body:
          traditionalDatastoreRequest:
            name: "{{ iscsi_datastore_name }}"
            datastoreType: VMFS
            protocol: ISCSI
            spaceReserve: Thin
            clusterID:  "{{ ontap_cluster_id }}"
            svmID: "{{ ontap_svm_id }}"
            targetMoref: ClusterComputeResource:{{ vcenterclusterid.json[0].cluster }}
            datastoreSizeInMB: "{{ datastoreSizeInMB | int }}"
            vmfsFileSystem: VMFS6
            aggrName: "{{ aggr_name }}"
            existingFlexVolName: ""
            volumeStyle: FLEXVOL
            datastoreClusterMoref: ""
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
      when: ontap_cluster_id != '' and ontap_svm_id != '' and aggr_name != ''
      register: result
      changed_when: result.status == 200
----