---
sidebar: sidebar 
permalink: ai/a400-thinksystem-test-plan.html 
keywords: test plan, validation, image recognition training, processes 
summary: 'Dans cette validation, nous avons suivi une formation sur la reconnaissance d"images comme spécifié par MLPerf v2.0. Nous avons plus particulièrement entraîné le modèle ResNet v2.0 avec le dataset ImageNet. La mesure principale est le temps d"atteindre la précision souhaitée. Nous avons également établi des rapports sur la bande passante d"entraînement en images par seconde afin de mieux évaluer l"efficacité évolutive.' 
---
= Plan de test
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Dans cette validation, nous avons suivi une formation sur la reconnaissance d'images comme spécifié par MLPerf v2.0. Nous avons plus particulièrement entraîné le modèle ResNet v2.0 avec le dataset ImageNet jusqu'à ce que nous soyons parvenus à un niveau de précision de 76.1 %. La mesure principale est le temps d'atteindre la précision souhaitée. Nous avons également établi des rapports sur la bande passante d'entraînement en images par seconde afin de mieux évaluer l'efficacité évolutive.

Le principal cas d'essai a évalué plusieurs processus de formation indépendants (un par nœud) exécutés simultanément. Cela simule l'utilisation principale, un système partagé utilisé par plusieurs data Scientists. Dans le deuxième cas, l'efficacité du stockage scale-out a été évaluée.
