---
sidebar: sidebar 
permalink: ai/ai-edge-conclusion.html 
keywords: acknowledgements, version history, additional information 
summary: 'L"automatisation basée sur l"IA et l"Edge Computing constituent une approche majeure pour aider les entreprises à réussir la transformation digitale et à optimiser l"efficacité opérationnelle et la sécurité. Avec l"Edge Computing, le traitement des données est beaucoup plus rapide car il n"est pas nécessaire de se rendre au data Center ni de les déplacer. C"est pourquoi les coûts associés à l"envoi de données vers des data centers ou le cloud sont réduits.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-edge-architecture-sizing-options.html["Précédent : options de dimensionnement de l'architecture."]

L'automatisation basée sur l'IA et l'Edge Computing constituent une approche majeure pour aider les entreprises à réussir la transformation digitale et à optimiser l'efficacité opérationnelle et la sécurité. Avec l'Edge Computing, le traitement des données est beaucoup plus rapide car il n'est pas nécessaire de se rendre au data Center ni de les déplacer. C'est pourquoi les coûts associés à l'envoi de données vers des data centers ou le cloud sont réduits. Une latence plus faible et une vitesse plus élevée peuvent être utiles pour les entreprises qui doivent prendre des décisions en temps quasi réel à l'aide de modèles d'inférence d'IA déployés à la périphérie.

Les systèmes de stockage NetApp offrent les performances identiques ou supérieures au stockage SSD local et offrent les avantages suivants aux data Scientists, aux ingénieurs du data Center, aux développeurs d'IA/ML et aux décideurs IT ou business :

* Partage sans effort des données entre des systèmes d'IA, l'analytique et d'autres systèmes métier stratégiques. Ce partage des données permet de réduire la surcharge de l'infrastructure, d'améliorer les performances et de rationaliser la gestion des données à l'échelle de l'entreprise.
* Faites évoluer indépendamment les ressources de calcul et de stockage pour réduire les coûts et améliorer l'utilisation des ressources.
* Rationalisation des workflows de développement et de déploiement à l'aide de copies et de clones Snapshot intégrés pour des espaces de travail utilisateur instantanés et compacts, un contrôle intégré des versions et un déploiement automatisé.
* Une protection des données d'entreprise pour la reprise après incident et la continuité de l'activité. La solution NetApp et Lenovo présentée dans ce document est une architecture scale-out flexible, idéale pour les déploiements d'inférence d'IA en périphérie.




== Remerciements

* J.J. Falkanger Directeur des solutions HPC et d'IA, Lenovo
* Dave Arnette, Ingénieur marketing et technique, NetApp
* Joey Parnell, Tech Lead E-Series ai Solutions, NetApp
* Cody Harryman, ingénieur QA, NetApp




== Où trouver des informations complémentaires

Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web :

* Page produit sur les baies NetApp AFF A-Series
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* Le logiciel de gestion des données NetApp ONTAP – bibliothèque d'informations ONTAP 9
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* Tr-4727 : introduction à la gamme EF-Series de NetApp
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* Logiciel SANtricity NetApp E-Series : Fiche technique
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* NetApp Trident pour le stockage persistant pour les conteneurs
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Diminution des
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* NetApp Cloud Sync
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Banc d'essai TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Serveur Lenovo ThinkSystem SE350 Edge
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Baie de stockage Flash unifiée Lenovo ThinkSystem DM5100F
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array^["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"^]





== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Mars 2021 | Version initiale 


| Version 2.0 | Octobre 2021 | Mise à jour avec EF et MLPerf Inférence v1.1 
|===