---
sidebar: sidebar 
permalink: ai/ai-protopia-where-to-find-additional-information,-acknowledgements,-and-version-history.html 
keywords:  
summary:  
---
= Où trouver des informations supplémentaires, des accusés de réception et l'historique des versions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-conclusion.html["Précédent: Conclusion."]

[role="lead"]
Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web :

* Le logiciel de gestion des données NetApp ONTAP : bibliothèque d'informations ONTAP
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* NetApp Trident pour le stockage persistant pour les conteneurs
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Kit NetApp DataOps
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Kubernetes pour les conteneurs : NetApp Astra Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Protopia ai - Inférence confidentielle
+
https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/["https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/"^]

* Copie et synchronisation NetApp BlueXP
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Serveur d'inférence NVIDIA Triton
+
https://developer.nvidia.com/nvidia-triton-inference-server["https://developer.nvidia.com/nvidia-triton-inference-server"^]

* Documentation NVIDIA Triton Inférence Server
+
https://docs.nvidia.com/deeplearning/triton-inference-server/index.html["https://docs.nvidia.com/deeplearning/triton-inference-server/index.html"^]

* Coffrets en PyTorch
+
https://github.com/zisianw/FaceBoxes.PyTorch["https://github.com/zisianw/FaceBoxes.PyTorch"^]





== Remerciements

* Mark Cates, responsable produits senior, NetApp
* Sufian Ahmad, Ingénieur marketing et technique, NetApp
* Hadi Esmaeilzadeh, directeur technique et professeur, Protopia ai




== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | À mai 2022 | Version initiale. 
|===