---
sidebar: sidebar 
permalink: ai/ai-protopia-conclusion.html 
keywords: conclusion, ai inferencing, 
summary: 'Les données existent dans trois États : au repos, en transit et dans le calcul. Un service d"inférence d"IA doit contenir des données non menaces lors de l"intégralité du processus. La protection des données pendant l"inférence est essentielle. En effet, le processus peut exposer des informations privées aux clients externes et à l"entreprise fournissant le service d"inférence.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-obfuscation-speed.html["Précédent : vitesse d'obfuscation."]

[role="lead"]
Les données existent dans trois États : au repos, en transit et dans le calcul. Un service d'inférence d'IA doit contenir des données non menaces lors de l'intégralité du processus. La protection des données pendant l'inférence est essentielle. En effet, le processus peut exposer des informations privées aux clients externes et à l'entreprise fournissant le service d'inférence. Protopia ai est une solution logicielle unique non-intégrée pour l'inférence confidentielle de l'IA sur le marché actuel. Avec Protopia, l'IA est alimenté uniquement les informations transformées dans les dossiers de données, essentielles pour mener à bien les tâches d'IA et DE ML. Cette transformation stochastique n'est pas une forme de masquage et est basée sur la modification mathématiquement de la représentation des données à l'aide d'un bruit adapté.

Les systèmes de stockage NetApp dotés des fonctionnalités ONTAP offrent des performances identiques ou supérieures au stockage SSD local. Associés au kit NetApp DataOps, ils offrent les avantages suivants aux data Scientists, aux ingénieurs de données, aux développeurs d'IA/AM et aux décideurs IT d'entreprise ou d'entreprise :

* Partage sans effort des données entre des systèmes d'IA, l'analytique et d'autres systèmes métier stratégiques. Ce partage des données permet de réduire la surcharge de l'infrastructure, d'améliorer les performances et de rationaliser la gestion des données à l'échelle de l'entreprise.
* Faites évoluer indépendamment les ressources de calcul et de stockage pour réduire les coûts et améliorer l'utilisation des ressources.
* Rationalisation des workflows de développement et de déploiement à l'aide de copies et de clones Snapshot intégrés pour des espaces de travail utilisateur instantanés et compacts, un contrôle intégré des versions et un déploiement automatisé.
* Protection et gouvernance des données pour la reprise après incident, la continuité de l'activité et les exigences réglementaires.
* Appel simplifié à des opérations de gestion des données ; prise rapide de copies Snapshot d'espaces de travail de data Scientists pour la sauvegarde et la traçabilité à partir du kit NetApp DataOps Toolkit dans des ordinateurs portables Jupyter.


La solution NetApp et Protopia offre une architecture flexible et scale-out, idéale pour les déploiements d'inférence d'IA haute performance. Il protège les données et garantit la confidentialité des informations sensibles pour lesquelles les exigences d'inférence d'IA confidentielles peuvent être respectées grâce à des pratiques d'IA responsables dans les déploiements sur site et dans le cloud hybride.

link:ai-protopia-where-to-find-additional-information,-acknowledgements,-and-version-history.html["Suivant : où trouver des informations supplémentaires, des accusés de réception et l'historique des versions ?"]
