---
sidebar: sidebar 
permalink: ai/ai-protopia-solution-areas.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: 'Le traitement numérique de l"image présente de nombreux avantages, permettant ainsi à de nombreuses entreprises d"exploiter au mieux les données associées aux représentations visuelles. Cette solution NetApp et Protopia propose une conception unique d"inférence d"IA pour protéger et privatiser les données d"IA/ML tout au long du cycle de vie DU ML/DL. Il permet aux clients de conserver la propriété des données sensibles, d"utiliser des modèles de déploiement de cloud public ou hybride pour l"évolutivité et l"efficacité en allégeant les problèmes de confidentialité et en déployant l"inférence d"IA à la périphérie.' 
---
= Domaines de solutions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-overview.html["Précédent : présentation."]

Le traitement numérique de l'image présente de nombreux avantages, permettant ainsi à de nombreuses entreprises d'exploiter au mieux les données associées aux représentations visuelles. Cette solution NetApp et Protopia propose une conception unique d'inférence d'IA pour protéger et privatiser les données d'IA/ML tout au long du cycle de vie DU ML/DL. Il permet aux clients de conserver la propriété des données sensibles, d'utiliser des modèles de déploiement de cloud public ou hybride pour l'évolutivité et l'efficacité en allégeant les problèmes de confidentialité et en déployant l'inférence d'IA à la périphérie.



== Intelligence environnementale

Il existe de nombreuses façons dont les industries peuvent tirer parti de l'analyse géospatiale dans les domaines des dangers environnementaux. Les gouvernements et le ministère des travaux publics peuvent obtenir des renseignements exploitables sur la santé publique et les conditions météorologiques afin de mieux conseiller le public lors d'une pandémie ou d'une catastrophe naturelle comme les incendies de forêt. Par exemple, vous pouvez identifier un patient COVID-positif dans les espaces publics, tels que les aéroports ou les hôpitaux, sans compromettre la confidentialité de la personne concernée et avertir les autorités respectives et le public à proximité de ces mesures de sécurité.



== Les dispositifs de bord sont wearables

Dans l'armée et sur les champs de bataille, vous pouvez utiliser l'inférence d'IA sur la périphérie comme dispositifs portables pour suivre la santé des soldats, surveiller le comportement des conducteurs et alerter les autorités sur la sécurité et les risques associés à l'approche des véhicules militaires tout en préservant et en protégeant la vie privée des soldats. L'avenir de l'armée passe en haute technologie avec l'Internet des objets du champ de bataille (IoBT) et l'Internet des objets militaires (IoMT) pour des engins de combat portables qui aident les soldats à identifier leurs ennemis et à réaliser de meilleures performances dans les combats grâce à l'informatique de pointe rapide. La protection et la préservation des données visuelles collectées depuis des appareils en périphérie tels que les drones et les équipements portables sont essentielles pour que les pirates et l'ennemi soit à la hauteur.



== Opérations d'évacuation sans combattant

Les opérations d'évacuation des non-combattants (ONE) sont menées par le DoD pour aider à l'évacuation des citoyens et des ressortissants américains, du personnel civil DoD et des personnes désignées (pays hôte (HN) et des ressortissants de pays tiers (AMT) dont la vie est en danger pour un refuge sûr approprié. Les contrôles administratifs en place utilisent en grande partie les processus de dépistage manuel des évacuées. Cependant, l'exactitude, la sécurité et la rapidité de l'identification des données évacuées, du suivi des évacués et du filtrage des menaces peuvent être améliorées via des outils d'IA/DE ML hautement automatisés combinés aux technologies d'obfuscation vidéo d'IA et DE ML.



== Santé et recherche biomédicale

Le traitement des images est utilisé pour diagnostiquer des pathologies à des fins de planification chirurgicale à partir d'images 3D issues d'une tomographie informatisée (TI) ou d'une imagerie par résonance magnétique (IRM). Les règles de confidentialité HIPAA régissent la façon dont les données doivent être collectées, traitées et effacées par les entreprises pour toutes les données personnelles et images numériques, telles que les photographies. Pour que les données puissent être partagées conformément aux réglementations HIPAA Safe Harbor, les images photographiques en plein visage et les images comparables doivent être supprimées. Les techniques automatisées telles que la déidentification ou le décapage du crâne utilisées pour masquer les caractéristiques faciales d'un individu provenant d'images TDM/RM structurelles sont devenues un élément essentiel du processus de partage des données pour les établissements de recherche biomédicale.



== Migration vers le cloud de l'analytique d'IA/DE ML

Les clients grands comptes ont traditionnellement entraîné et déployé des modèles d'IA/ML sur site. Pour des raisons d'évolutivité et d'efficacité, ces clients étendent leurs fonctions d'IA/ML aux déploiements dans un cloud public, hybride ou multicloud. Mais elles sont liées aux données qui peuvent être exposées à d'autres infrastructures. Les solutions NetApp répondent à l'ensemble des menaces de cybersécurité requises https://www.netapp.com/data-protection/?internal_promo=mdw_aiml_ww_all_awareness-coas_blog["protection des données"^] Enfin, lorsqu'elle est associée à la transformation des données Protopia, l'évaluation de la sécurité a réduit les risques associés à la migration de workloads d'IA/DE ML d'images vers le cloud.

Pour en savoir plus sur les champs d'application du calcul en périphérie et de l'inférence d'IA dans d'autres secteurs, consultez la page https://docs.netapp.com/us-en/netapp-solutions/ai/ai-edge-introduction.html["Tr-4886 inférence d'IA à la périphérie"^] Et le blog NetApp ai, https://www.netapp.com/blog/federated-learning-intelligence-vs-privacy/["L'intelligence contre la confidentialité"^].

link:ai-protopia-technology-overview.html["Suivant : présentation de la technologie."]
