---
sidebar: sidebar 
permalink: ai/ai-sent-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Où trouver des informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Démonstrations interactives en 3D
+
http://www.netapp.com/ai["www.netapp.com/ai"^]

* Entrez en contact directement avec un spécialiste de l'IA NetApp
+
https://www.netapp.com/artificial-intelligence/["https://www.netapp.com/artificial-intelligence/"^]

* Description de la solution NVDIA base Command Platform avec NetApp
+
https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf["https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf"^]

* Infographie NetApp pour l'IA 10 : bonnes raisons de choisir NetApp
+
https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf["https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf"^]

* L'IA dans le domaine de la santé : l'apprentissage profond pour identifier les lésions de la COVID-19 dans les analyses CT pulmonaires
+
https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf["https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf"^]

* L'IA dans le domaine de la santé : surveillance de l'utilisation du masque facial dans les établissements de santé. Livre blanc
+
https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf["https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf"^]

* Rapport technique sur l'IA dans le domaine de la santé : imagerie diagnostique
+
https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf["https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf"^]

* L'IA pour le Retail : NetApp transversaux à l'IA avec NVIDIA RIVA
+
link:cainvidia_executive_summary.html["Synthèse"]

* Description de la solution NetApp ONTAP ai
+
https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf["https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf"^]

* Description de la solution du kit DataOps NetApp
+
https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf["https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf"^]

* Description de la solution NetApp ai Control plane
+
https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf["https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf"^]

* Transformation du secteur grâce à l'eBook Data Drive IA
+
https://www.netapp.com/us/media/na-337.pdf["https://www.netapp.com/us/media/na-337.pdf"^]

* Description de la solution d'IA NetApp EF-Series
+
https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf["https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf"^]

* Description de la solution NetApp ai et Lenovo ThinkSystem for ai Inférence
+
https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf["https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf"^]

* Description des solutions NetApp pour l'IA et le ML Lenovo ThinkSystem pour les entreprises
+
https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf["https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf"^]

* NetApp et NVIDIA : redéfinir le contenu du possible avec la vidéo d'IA
+
https://www.youtube.com/watch?v=38xw65SteUc["https://www.youtube.com/watch?v=38xw65SteUc"^]


