---
sidebar: sidebar 
permalink: ai/aicp_performance_testing.html 
keywords: Performance, Testing, benchmark, Tensorflow, Docker 
summary: 'Nous avons effectué une comparaison simple des performances dans le cadre de la création de cette solution. Nous avons exécuté plusieurs tâches standard de banc d"essai NetApp avec Kubernetes, et nous avons comparé les résultats du banc d"essai avec les sous-activités qui ont été réalisées à l"aide d"une simple commande Docker run.' 
---
= Test des performances
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Nous avons effectué une comparaison simple des performances dans le cadre de la création de cette solution. Nous avons exécuté plusieurs tâches standard de banc d'essai NetApp ai avec Kubernetes, et nous avons comparé les résultats du banc d'essai avec les sous-activités qui ont été réalisées à l'aide d'une simple commande Docker run. Nous n'avons pas constaté de différence notable au niveau des performances. Nous en avons donc conclu que l'utilisation de Kubernetes pour orchestrer les tâches d'entraînement d'IA conteneurisées n'avait pas de conséquences négatives sur les performances. Pour consulter les résultats de cette comparaison, consultez le tableau suivant.

|===
| Banc d'essai | Jeu de données | Docker Run (images/s) | Kubernetes (images/s) 


| TensorFlow à un nœud | Données synthétiques | 6,667.2475 | 6,661.93125 


| TensorFlow à un nœud | ImageNet | 6,570.2025 | 6,530.59125 


| TensorFlow distribué synchrone à deux nœuds | Données synthétiques | 13,213.70625 | 13,218.288125 


| TensorFlow distribué synchrone à deux nœuds | ImageNet | 12,941.69125 | 12,881.33875 
|===