---
sidebar: sidebar 
permalink: ai/aicp_conclusion.html 
keywords: NetApp AI Machine Deep Learning 
summary:  
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Toutes les entreprises, quelle que soit leur taille et tous les secteurs, se tournent vers l'intelligence artificielle (IA), le machine learning (ML) et le deep learning (DL) pour résoudre des problèmes concrets, proposer des produits et des services innovants et se démarquer sur un marché de plus en plus concurrentiel. Alors que les entreprises ont de plus en plus recours à l'IA, AU ML et au DL, elles sont confrontées à de nombreux défis, notamment l'évolutivité des workloads et la disponibilité des données. Ces difficultés peuvent être résolues via l'utilisation de la solution NetApp ai Control plane.

Cette solution permet de cloner rapidement un espace de noms de données. Vous pouvez par ailleurs définir et implémenter des workflows d'entraînement d'IA, DE ML et de DL pour intégrer la création quasi instantanée de données et de modèles de base à des fins de traçabilité et de gestion des versions. Avec cette solution, vous pouvez suivre l'entraînement de chaque modèle individuel sur le(s) dataset(s) exact(s) auquel le modèle a été entraîné et/ou validé. Enfin, cette solution vous permet de provisionner rapidement des espaces de travail Jupyter Notebook avec un accès à des jeux de données volumineux.

Cette solution cible les data Scientists et les ingénieurs de données, une expertise minimale de NetApp ou de NetApp ONTAP est requise. Avec cette solution, les fonctions de gestion des données peuvent être exécutées à l'aide d'outils et d'interfaces simples et familiers. De plus, cette solution utilise des composants entièrement open source et libres. Par conséquent, si vous disposez déjà d'un système de stockage NetApp dans votre environnement, vous pouvez implémenter cette solution dès aujourd'hui. Si vous souhaitez essayer cette solution, mais que vous ne disposez pas encore de système de stockage NetApp, rendez-vous sur http://["cloud.netapp.com"^], Et vous pouvez être opérationnel avec une solution de stockage NetApp basée sur le cloud en un rien de temps.
