---
sidebar: sidebar 
permalink: ai/aicp_example_notebooks_and_pipelines.html 
keywords: Jupyter Notebook, Kubeflow Pipeline, NetApp DataOps Toolkit 
summary: 'MLOps open source avec NetApp : utilisez le kit NetApp DataOps avec Kubeflow' 
---
= Utilisez le kit NetApp DataOps avec Kubeflow
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s["Kit NetApp Data Science Toolkit pour Kubernetes"] Peut être utilisé avec Kubeflow. Grâce au kit NetApp Data Science Toolkit avec Kubeflow, il offre les avantages suivants :

* Les data Scientists peuvent effectuer des opérations avancées de gestion des données NetApp, telles que la création de snapshots et de clones, directement depuis un ordinateur portable Jupyter.
* Les opérations avancées de gestion des données NetApp, telles que la création de snapshots et de clones, peuvent être intégrées dans des workflows automatisés à l'aide de la structure Kubeflow pipelines.


Reportez-vous à la https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s/Examples/Kubeflow["Exemples Kubeflow"] Section du référentiel GitHub pour le kit NetApp Data Science pour plus d'informations sur l'utilisation du kit avec Kubeflow.
