---
sidebar: sidebar 
permalink: ai/aicp_example_trident_operations_overview.html 
keywords: Trident 
summary: 'Opérations MLOps open source avec NetApp : exemple d"opérations Astra Trident' 
---
= Exemple d'opérations Astra Trident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section contient des exemples d'opérations que vous pouvez exécuter avec Astra Trident.



== Importer un volume existant

Si votre système/plateforme de stockage NetApp contient des volumes que vous souhaitez monter sur des conteneurs au sein de votre cluster Kubernetes, mais qui ne sont pas liés aux demandes de volume persistant dans le cluster, vous devez importer ces volumes. Vous pouvez utiliser la fonctionnalité d'importation de volumes Trident pour importer ces volumes.

Les exemples de commandes qui suivent montrent l'importation d'un volume nommé `pb_fg_all`. Pour plus d'informations sur les ESV, consultez le https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentation officielle Kubernetes"^]. Pour plus d'informations sur la fonctionnalité d'importation de volume, reportez-vous à la section https://docs.netapp.com/us-en/trident/index.html["Documentation Trident"^].

An `accessModes` valeur de `ReadOnlyMany` Est spécifié dans les fichiers de spécifications PVC d'exemple. Pour plus d'informations sur le `accessMode` voir https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentation officielle Kubernetes"^].

....
$ cat << EOF > ./pvc-import-pb_fg_all-iface1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface1
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface1
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface1 pb_fg_all -f ./pvc-import-pb_fg_all-iface1.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1 | 10 TiB | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ tridentctl get volume -n trident
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
|               NAME               |  SIZE   |           STORAGE CLASS           | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1   | 10 TiB  | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
$ kubectl get pvc
NAME                 STATUS   VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1     Bound    default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   25h
....


== Provisionner un nouveau volume

Vous pouvez utiliser Trident pour provisionner un nouveau volume sur votre système ou plateforme de stockage NetApp.



=== Provisionnez un nouveau volume à l'aide de kubectl

Les exemples de commandes suivants montrent le provisionnement d'un nouveau volume FlexVol à l'aide de kubectl.

An `accessModes` valeur de `ReadWriteMany` Est spécifié dans l'exemple de fichier de définition de PVC suivant. Pour plus d'informations sur le `accessMode` voir https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentation officielle Kubernetes"^].

....
$ cat << EOF > ./pvc-tensorflow-results.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-ai-flexvols-retain
EOF
$ kubectl create -f ./pvc-tensorflow-results.yaml
persistentvolumeclaim/tensorflow-results created
$ kubectl get pvc
NAME                              STATUS    VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1                  Bound     default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   26h
tensorflow-results                Bound     default-tensorflow-results-2fd60   1073741824       RWX            ontap-ai-flexvols-retain            25h
....


=== Provisionnez un nouveau volume à l'aide du kit NetApp DataOps

Vous pouvez également utiliser le kit NetApp DataOps pour Kubernetes pour provisionner un nouveau volume sur votre système ou plateforme de stockage NetApp. Le kit NetApp DataOps pour Kubernetes utilise Trident pour provisionner les volumes, mais simplifie le processus pour l'utilisateur. Reportez-vous à la link:https://github.com/NetApp/netapp-dataops-toolkit/blob/main/netapp_dataops_k8s/docs/volume_management.md["documentation"] pour plus d'informations.
