---
sidebar: sidebar 
permalink: ai/aicp_example_notebooks_and_pipelines.html 
keywords: Jupyter Notebook, Kubeflow Pipeline 
summary: Exemple de Jupyter Notebooks et Kubeflow pipelines 
---
= Exemple de carnets de bord et de pipelines
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Le https://github.com/NetApp/netapp-data-science-toolkit/tree/main/Kubernetes["Kit NetApp Data Science Toolkit pour Kubernetes"] Peut être utilisé avec Kubeflow. Grâce au kit NetApp Data Science Toolkit avec Kubeflow, il offre les avantages suivants :

* Les data Scientists peuvent effectuer des opérations avancées de gestion des données NetApp directement depuis un ordinateur portable Jupyter.
* Les opérations avancées de gestion des données NetApp peuvent être intégrées aux workflows automatisés grâce à la structure Kubeflow pipelines.


Reportez-vous à la https://github.com/NetApp/netapp-data-science-toolkit/tree/main/Kubernetes/Examples/Kubeflow["Exemples Kubeflow"] Section du référentiel GitHub pour le kit NetApp Data Science pour plus d'informations sur l'utilisation du kit avec Kubeflow.

link:aicp_apache_airflow_deployment.html["Suivant : déploiement du flux d'air Apache."]
