---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: MLOps open source avec NetApp - Architecture 
---
= Architecture
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette solution ne dépend pas de matériel spécifique. La solution est compatible avec toute appliance de stockage physique, instance Software-defined ou service cloud NetApp, prise en charge par Trident. Par exemple, un système de stockage NetApp AFF, Amazon FSX pour NetApp ONTAP, Azure NetApp Files ou une instance NetApp Cloud Volumes ONTAP. De plus, la solution peut être implémentée sur n'importe quel cluster Kubernetes tant que la version Kubernetes utilisée est prise en charge par Kubeflow et NetApp Astra Trident. Pour obtenir la liste des versions Kubernetes prises en charge par Kubeflow, voir la https://www.kubeflow.org/docs/started/getting-started/["Documentation officielle Kubeflow"^]. Pour obtenir la liste des versions de Kubernetes prises en charge par Trident, consultez le https://docs.netapp.com/us-en/trident/index.html["Documentation Trident"^]. Pour plus de détails sur l'environnement utilisé pour valider la solution, reportez-vous aux tableaux suivants.

|===
| Composant logiciel | Version 


| Débit d'air Apache | 2.0.1 


| Graphique Helm à flux d'air Apache | 8.0.8 


| Kubeflow | 1.7, déployé via link:https://www.deploykf.org["DeployKF"] 0.1.1 


| Kubernetes | 1.26 


| NetApp Astra Trident | 23.07 
|===


== Assistance

NetApp n'offre pas de prise en charge d'entreprise pour Apache Airflow, Kubeflow ou Kubernetes. Si vous êtes intéressé par une plateforme MLOps entièrement prise en charge, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["Contactez NetApp"] Découvrez les solutions MLOps entièrement prises en charge proposées conjointement par NetApp et ses partenaires.
