---
sidebar: sidebar 
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html 
keywords: Trident, Kubernetes, Storageclass 
summary: Cette page décrit les tâches que vous devez effectuer pour installer et configurer NetApp Trident dans votre cluster Kubernetes. 
---
= Déploiement et configuration de NetApp Trident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit les tâches que vous devez effectuer pour installer et configurer NetApp Trident dans votre cluster Kubernetes.



== Prérequis

Avant d'effectuer l'exercice de déploiement décrit dans cette section, nous supposons que vous avez déjà effectué les tâches suivantes :

. Vous disposez déjà d'un cluster Kubernetes opérationnel, et vous exécutez une version de Kubernetes prise en charge par Trident. Pour obtenir la liste des versions prises en charge, reportez-vous à la section https://docs.netapp.com/us-en/trident/["Documentation Trident"^].
. Vous disposez déjà d'un dispositif de stockage NetApp, d'une instance Software-defined ou d'un service de stockage cloud, pris en charge par Trident.




== Installation de Trident

Pour installer et configurer NetApp Trident dans votre cluster Kubernetes, effectuez les tâches suivantes à partir de l'hôte de démarrage du déploiement :

. Déployez Trident selon l'une des méthodes suivantes :
+
** Si vous avez utilisé NVIDIA DeepOps pour déployer votre cluster Kubernetes, vous pouvez également utiliser NVIDIA DeepOps pour déployer Trident dans votre cluster Kubernetes. Pour déployer Trident avec DeepOps, suivez le https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#netapp-trident["Instructions de déploiement de Trident"] Sur le site GitHub NVIDIA DeepOps.
** Si vous n'avez pas utilisé NVIDIA DeepOps pour déployer votre cluster Kubernetes ou si vous préférez simplement déployer Trident manuellement, vous pouvez déployer Trident en suivant les instructions du https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html["instructions de déploiement"^] Dans la documentation Trident. Veillez à créer au moins un système back-end Trident et au moins une classe de stockage Kubernetes pour plus d'informations sur la configuration https://docs.netapp.com/us-en/trident/trident-use/backends.html["Systèmes back-end"^] et https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["Les classes de stockage"^] Consultez les sous-sections liées dans NetApp Docs.
+

NOTE: Si vous déployez la solution NetApp ai Control plane sur un pod ONTAP ai, consultez la link:aicp_example_trident_backends_for_ontap_ai_deployments.html["Exemple de systèmes back-end Trident pour les déploiements d'IA de ONTAP"] Pour certains exemples de systèmes back-end Trident, vous pouvez créer et link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html["Exemple de Kubernetes Storageclasse pour les déploiements d'IA ONTAP"] Vous voudrez peut-être créer des exemples de classes de stockage Kubernetes différentes.




