---
sidebar: sidebar 
permalink: ai/aicp_kubernetes_deployment.html 
keywords: NVIDIA, GPU, Kubernetes, Control Plane, Trident 
summary: 'Cette page décrit les tâches que vous devez réaliser pour déployer un cluster Kubernetes dans lequel implémenter la solution NetApp ai Control plane. Si vous disposez déjà d"un cluster Kubernetes, vous pouvez ignorer cette section tant que vous exécutez une version de Kubernetes prise en charge par Kubeflow et NetApp Trident.' 
---
= Déploiement Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit les tâches que vous devez réaliser pour déployer un cluster Kubernetes dans lequel implémenter la solution NetApp ai Control plane. Si vous disposez déjà d'un cluster Kubernetes, vous pouvez ignorer cette section tant que vous exécutez une version de Kubernetes prise en charge par Kubeflow et NetApp Trident. Pour obtenir la liste des versions Kubernetes prises en charge par Kubeflow, voir la https://www.kubeflow.org/docs/started/getting-started/["Documentation officielle Kubeflow"^]. Pour obtenir la liste des versions de Kubernetes prises en charge par Trident, consultez le https://netapp-trident.readthedocs.io/["Documentation Trident"^].

Pour les déploiements Kubernetes sur site intégrant des nœuds bare-Metal avec processeurs graphiques NVIDIA, NetApp recommande l'utilisation de l'outil de déploiement DeepOps Kubernetes de NVIDIA. Cette section décrit le déploiement d'un cluster Kubernetes avec DeepOps.



== Prérequis

Avant d'effectuer l'exercice de déploiement décrit dans cette section, nous supposons que vous avez déjà effectué les tâches suivantes :

. Vous avez déjà configuré des nœuds Kubernetes bare-Metal (par exemple, un système NVIDIA DGX qui fait partie d'un pod ONTAP ai) conformément aux instructions de configuration standard.
. Vous avez installé un système d'exploitation pris en charge sur tous les nœuds maîtres et workers Kubernetes et sur un hôte de démarrage du déploiement. Pour obtenir la liste des systèmes d'exploitation pris en charge par DeepOps, reportez-vous au https://github.com/NVIDIA/deepops["Site GitHub DeepOps"^].




== Utilisez NVIDIA DeepOps pour installer et configurer Kubernetes

Pour déployer et configurer votre cluster Kubernetes avec NVIDIA DeepOps, effectuez les tâches suivantes à partir d'un hôte de démarrage du déploiement :

. Téléchargez NVIDIA DeepOps en suivant les instructions sur le https://github.com/NVIDIA/deepops/tree/master/docs["Page de démarrage"^] Sur le site GitHub NVIDIA DeepOps.
. Déployez Kubernetes dans votre cluster en suivant les instructions du https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster["Page Guide de déploiement Kubernetes"^] Sur le site GitHub NVIDIA DeepOps.


link:aicp_netapp_trident_deployment_and_configuration_overview.html["Ensuite : présentation du déploiement et de la configuration de NetApp Trident."]
