---
sidebar: sidebar 
permalink: ai/aicp_example_trident_operations_overview.html 
keywords: Trident 
summary: 'Exemple d"opérations Trident' 
---
= Exemple d'opérations Trident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section comprend des exemples d'opérations que vous pouvez effectuer avec Trident.



== Importer un volume existant

Si votre système/plateforme de stockage NetApp contient des volumes que vous souhaitez monter sur des conteneurs au sein de votre cluster Kubernetes, mais qui ne sont pas liés aux demandes de volume persistant dans le cluster, vous devez importer ces volumes. Vous pouvez utiliser la fonctionnalité d'importation de volumes Trident pour importer ces volumes.

Les exemples de commandes ci-dessous montrent l'importation du même volume, nommé `pb_fg_all,` Deux fois, une fois pour chaque système back-end Trident créé dans l'exemple de la section link:aicp_example_trident_backends_for_ontap_ai_deployments.html["Exemple de systèmes back-end Trident pour les déploiements d'IA de ONTAP"], étape 1. Si vous importez le même volume deux fois de cette manière, vous pouvez monter le volume (un volume FlexGroup existant) plusieurs fois sur plusieurs LIF, comme décrit dans la section link:aicp_example_trident_backends_for_ontap_ai_deployments.html["Exemple de systèmes back-end Trident pour les déploiements d'IA de ONTAP"], étape 1. Pour plus d'informations sur les ESV, consultez le https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentation officielle Kubernetes"^]. Pour plus d'informations sur la fonctionnalité d'importation de volume, reportez-vous à la section https://netapp-trident.readthedocs.io/["Documentation Trident"^].

An `accessModes` valeur de `ReadOnlyMany` Est spécifié dans les fichiers de spécifications PVC d'exemple. Pour plus d'informations sur le `accessMode` voir https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentation officielle Kubernetes"^].


NOTE: Les noms de back-end spécifiés dans l'exemple de commandes d'importation suivant correspondent aux Backend créés dans l'exemple de la section link:aicp_example_trident_backends_for_ontap_ai_deployments.html["Exemple de systèmes back-end Trident pour les déploiements d'IA de ONTAP"], étape 1. Les noms de classes de stockage spécifiés dans les exemples de fichiers de définition de PVC suivants correspondent aux classes de stockage créées dans l'exemple de la section link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html["Exemple de classes de stockage Kubernetes pour les déploiements d'IA ONTAP"], étape 1.

....
$ cat << EOF > ./pvc-import-pb_fg_all-iface1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface1
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface1
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface1 pb_fg_all -f ./pvc-import-pb_fg_all-iface1.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1 | 10 TiB | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ cat << EOF > ./pvc-import-pb_fg_all-iface2.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface2
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface2
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface2 pb_fg_all -f ./pvc-import-pb_fg_all-iface2.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface2-85aee | 10 TiB | ontap-ai-flexgroups-retain-iface2 | file     | 61814d48-c770-436b-9cb4-cf7ee661274d | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ tridentctl get volume -n trident
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
|               NAME               |  SIZE   |           STORAGE CLASS           | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1   | 10 TiB  | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
| default-pb-fg-all-iface2-85aee   | 10 TiB  | ontap-ai-flexgroups-retain-iface2 | file     | 61814d48-c770-436b-9cb4-cf7ee661274d | online | true    |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
$ kubectl get pvc
NAME                 STATUS   VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1     Bound    default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   25h
pb-fg-all-iface2     Bound    default-pb-fg-all-iface2-85aee     10995116277760   ROX            ontap-ai-flexgroups-retain-iface2   25h
....


== Provisionner un nouveau volume

Vous pouvez utiliser Trident pour provisionner un nouveau volume sur votre système ou plateforme de stockage NetApp. L'exemple suivant montre le provisionnement d'un nouveau volume FlexVol. Dans cet exemple, le volume est provisionné à l'aide de la classe de stockage créée dans l'exemple de la section link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html["Exemple de classes de stockage Kubernetes pour les déploiements d'IA ONTAP"], étape 2.

An `accessModes` valeur de `ReadWriteMany` Est spécifié dans l'exemple de fichier de définition de PVC suivant. Pour plus d'informations sur le `accessMode` voir https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Documentation officielle Kubernetes"^].

....
$ cat << EOF > ./pvc-tensorflow-results.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-ai-flexvols-retain
EOF
$ kubectl create -f ./pvc-tensorflow-results.yaml
persistentvolumeclaim/tensorflow-results created
$ kubectl get pvc
NAME                              STATUS    VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1                  Bound     default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   26h
pb-fg-all-iface2                  Bound     default-pb-fg-all-iface2-85aee     10995116277760   ROX            ontap-ai-flexgroups-retain-iface2   26h
tensorflow-results                Bound     default-tensorflow-results-2fd60   1073741824       RWX            ontap-ai-flexvols-retain            25h
....
link:aicp_example_high-performance_jobs_for_ontap_ai_deployments_overview.html["Next : exemple - Présentation des tâches hautes performances pour les déploiements d'IA ONTAP."]
