---
sidebar: sidebar 
permalink: ai/aicp_example_trident_backends_for_ontap_ai_deployments.html 
keywords: ONTAP, Trident, AI, Deployment, 
summary: 'Opérations MLOps open source avec NetApp : exemple de systèmes back-end Trident pour les déploiements NetApp AIPod' 
---
= Exemple de systèmes back-end Trident pour les déploiements NetApp AIPod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Avant de pouvoir utiliser Trident pour provisionner dynamiquement les ressources de stockage dans votre cluster Kubernetes, vous devez créer un ou plusieurs systèmes back-end Trident. Les exemples suivants représentent différents types de backends que vous pouvez créer si vous déployez des composants de cette solution sur un link:aipod_nv_intro.html["Pod NetApp AIPod"^]. Pour plus d'informations sur les systèmes back-end, et par exemple sur les systèmes back-end pour d'autres plateformes/environnements, reportez-vous au link:https://docs.netapp.com/us-en/trident/index.html["Documentation Trident"^].

. NetApp recommande de créer un système de stockage Trident compatible FlexGroup pour votre FlexPod AIPod.
+
Les exemples de commandes ci-après illustrent la création d'un back-end Trident compatible FlexGroup pour une machine virtuelle de stockage AIPod. Ce back-end utilise le `ontap-nas-flexgroup` pilote de stockage ONTAP prend en charge deux principaux types de volumes de données : FlexVol et FlexGroup. La taille des volumes FlexVol est limitée (à compter de cette écriture, la taille maximale dépend du déploiement spécifique). Au contraire, les volumes FlexGroup peuvent évoluer de manière linéaire jusqu'à 20 po et 400 milliards de fichiers, fournissant un espace de nom unique qui simplifie considérablement la gestion des données. Par conséquent, les volumes FlexGroup sont optimaux pour les workloads d'IA et DE ML qui s'appuient sur des quantités importantes de données.

+
Si vous travaillez avec un volume de données réduit et que vous souhaitez utiliser des volumes FlexVol plutôt que des volumes FlexGroup, vous pouvez créer des systèmes back-end Trident qui utilisent le `ontap-nas` pilote de stockage au lieu du `ontap-nas-flexgroup` pilote de stockage

+
....
$ cat << EOF > ./trident-backend-aipod-flexgroups-iface1.json
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "backendName": "aipod-flexgroups-iface1",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexgroups-iface1.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....
. NetApp recommande également de créer un système back-end Trident compatible FlexVol. Vous pouvez utiliser des volumes FlexVol pour héberger des applications permanentes, stocker des résultats, des résultats, des informations de débogage, etc. Si vous souhaitez utiliser des volumes FlexVol, vous devez créer un ou plusieurs systèmes back-end Trident compatibles avec FlexVol. Les exemples de commandes qui suivent montrent la création d'un seul back-end Trident compatible avec FlexVol.


....
$ cat << EOF > ./trident-backend-aipod-flexvols.json
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "aipod-flexvols",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexvols.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....