---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: 'NetApp AIPod avec les systèmes NVIDIA DGX : où trouver des informations supplémentaires' 
---
= NetApp AIPod avec les systèmes NVIDIA DGX - conclusion et informations supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_validation_sizing.html["Précédent : NetApp AIPod avec les systèmes NVIDIA DGX - conseils de validation et de dimensionnement de la solution"]



== Conclusion

L'architecture DGX BasePOD est une plateforme de deep learning nouvelle génération qui requiert des fonctionnalités avancées de stockage et de gestion des données. En combinant DGX BasePOD avec les systèmes NetApp AFF, l'architecture NetApp AIPod peut être implémentée dans presque toutes les échelles, à partir d'un seul GPU dans un serveur OEM associé à un système de stockage AFF A250 jusqu'à 48 systèmes DGX H100 dans un cluster AFF A900 de 24 nœuds. Associé aux fonctionnalités SDS et d'intégration au cloud d'NetApp ONTAP, AFF couvre l'ensemble des pipelines de traitement de données de la périphérie au cœur jusqu'au cloud pour l'apprentissage profond.



== Informations supplémentaires

Pour en savoir plus sur les informations fournies dans ce document, veuillez consulter les documents et/ou sites web suivants :

* Le logiciel de gestion des données NetApp ONTAP : bibliothèque d'informations ONTAP
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* Systèmes de stockage NetApp AFF A900,
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* Informations NetApp ONTAP RDMA -
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* Kit NetApp DataOps
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html["https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html"^]

* ONTAP ai : architectures validées NetApp avec les systèmes NVIDIA DGX A100
+
https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html["https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html"^]

* NVIDIA BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* SYSTÈMES DE STOCKAGE NVIDIA DGX A100
+
https://www.nvidia.com/en-us/data-center/dgx-a100/["https://www.nvidia.com/en-us/data-center/dgx-a100/"^]

* Mise en réseau NVIDIA
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA ai Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== Remerciements

Ce document est le travail des équipes de solutions NetApp et d'ingénieurs ONTAP, David Arnette, Olga Kornievskaia, Dustin Fischer, Srikanth Kaligotla, Mohit Kumar et Rajeev Badrinath. Les auteurs tiennent également à remercier NVIDIA et l'équipe d'ingénieurs BasePOD pour leur soutien continu.
