---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: FlexPod pour IA NetApp avec les systèmes NVIDIA DGX - conclusion 
---
= FlexPod pour IA NetApp avec les systèmes NVIDIA DGX - conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_storage.html["Précédent : FlexPod NetApp ai Pod avec les systèmes NVIDIA DGX - conseils de conception et de dimensionnement des systèmes de stockage."]



== Conclusion

L'architecture DGX BasePOD est une plateforme de deep learning nouvelle génération qui requiert des fonctionnalités avancées de stockage et de gestion des données. En combinant DGX BasePOD avec les systèmes NetApp AFF, cette architecture peut être implémentée dans presque toutes les échelles, d'un seul DGX A100 associé à un système de stockage AFF A250 jusqu'à 48 systèmes DGX A100 sur un cluster AFF A800 à 24 nœuds. Associé aux fonctionnalités SDS et d'intégration au cloud d'NetApp ONTAP, AFF couvre l'ensemble des pipelines de traitement de données de la périphérie au cœur jusqu'au cloud pour l'apprentissage profond.

link:aipod_nv_additional_information.html["Next : FlexPod NetApp ai Pod avec les systèmes NVIDIA DGX - informations supplémentaires."]
