---
sidebar: sidebar 
permalink: ai/aipod_lenovo_NVA1172.html 
keywords:  
summary:  
---
= NVA-1172-DESIGN : NetApp AIPod avec Lenovo pour NVIDIA OVX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Bobby Oommen, Abhinav Singh, Roney Daniel, NetApp

[role="lead"]
Cette architecture de référence associe des serveurs ThinkSystem OVX Lenovo certifiés NVIDIA, optimisés par des processeurs graphiques NVIDIA L40S, à la mise en réseau NVIDIA Spectrum afin de fournir une solution d'infrastructure optimale pour optimiser et déployer les LLMS (modèles grand langage). Le but de ce document est de fournir des conseils sur le stockage d'une configuration OVX. Cette plateforme convient à plusieurs charges de travail Generative ai, notamment RAG (Retrieval Augmented Generation), le réglage précis et l'entraînement de modèles légers.

link:https://www.netapp.com/pdf.html?item=/media/111933-lenovoaipod-nva-1172-design-v20.pdf["NVA-1172-DESIGN : Guide de conception NetApp AIPod avec Lenovo pour NVIDIA OVX"^]
