---
sidebar: sidebar 
permalink: ai/aks-anf_monitor_dask_and_rapids_with_prometheus_and_grafana.html 
keywords: monitoring, monitor, dask, rapids, prometheus, grafana, 
summary: Une fois que tout est déployé, exécutez des inférences sur les nouvelles données. Les modèles prédisent si un utilisateur clique sur une publicité en fonction des activités de navigation. Les résultats de la prédiction sont stockés dans un DASK cuDF. Vous pouvez surveiller les résultats avec Prometheus et visualiser dans les tableaux de bord Grafana. 
---
= Surveillez DAsk et RAPIDS avec Prometheus et Grafana
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_training_time_comparison.html["Précédent : comparaison des temps de formation."]

Une fois que tout est déployé, exécutez des inférences sur les nouvelles données. Les modèles prédisent si un utilisateur clique sur une publicité en fonction des activités de navigation. Les résultats de la prédiction sont stockés dans un DASK cuDF. Vous pouvez surveiller les résultats avec Prometheus et visualiser dans les tableaux de bord Grafana.

Pour plus d'informations, reportez-vous à ce document https://medium.com/rapids-ai/monitoring-dask-rapids-with-prometheus-grafana-96eaf6b8f3a0["RAPIDS ai moyen post"^].

link:aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html["Suivant : gestion des versions de modèles et de datasets avec le kit d'outils NetApp DataOps."]
