---
sidebar: sidebar 
permalink: ai/aks-anf_click-through_rate_prediction_use_case_summary.html 
keywords: use case, terabyte click log, random forest, training 
summary: Cette page récapitule les avantages de Azure NetApp Files en matière de formation distribuée ou à grande échelle. 
---
= Récapitulatif de l'utilisation des prédictions de taux par clic
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_cloud_resource_requirements.html["Précédent : ressources cloud requises."]

Il s'agit d'un cas d'utilisation basé sur le cloud public http://labs.criteo.com/2013/12/download-terabyte-click-logs/["Fichiers de clic sur un téraoctet"^] jeu de données de https://ailab.criteo.com/["Criteo ai Lab"^]. Avec les récentes avancées des plates-formes ET des applications DE ML, une grande attention se porte maintenant sur l'apprentissage à grande échelle. Le taux de clics (CTR) est défini comme le nombre moyen de clics par cent impressions de publicités en ligne (exprimé en pourcentage). Elle est largement adoptée comme indicateur clé dans différents secteurs d'activité et champs d'application, notamment le marketing digital, la vente au détail, l'e-commerce et les fournisseurs de services. Voici quelques exemples d'utilisation de CTR comme mesure importante pour le trafic potentiel des clients :

* *Marketing numérique:* in https://support.google.com/google-ads/answer/2615875?hl=en["Google Analytics"^], CTR peut être utilisé pour évaluer la manière dont bien un annonceur ou les mots-clés, annonces, et les listes libres sont en cours de réalisation. Un CTR élevé est une bonne indication que les utilisateurs trouvent vos annonces et listes utiles et pertinentes. CTR contribue également à votre mot clé CTR attendu, qui est un composant de https://support.google.com/google-ads/answer/1752122?hl=en["Rang d'annonce"^].
* * E-commerce:* en plus de tirer parti https://analytics.google.com/analytics/web/provision/#/provision["Google Analytics"^], il y a au moins quelques statistiques de visiteurs dans un back-end de commerce électronique. Bien que ces statistiques ne semblent pas utiles à première vue, elles sont généralement faciles à lire et peuvent être plus précises que d'autres informations. Les ensembles de données de première partie composés de ces statistiques sont propriétaires et sont donc les plus pertinents pour les vendeurs, les acheteurs et les plates-formes de commerce électronique. Ces ensembles de données peuvent être utilisés pour établir des bancs d'essai, en comparant les résultats à l'année dernière et à la veille, en élaborant une série chronologique pour une analyse plus approfondie.
* *Retail:* les détaillants Brick-et-mortier peuvent mettre en corrélation le nombre de visiteurs et le nombre de clients avec le CTR. Le nombre de clients est visible depuis leur historique des points de vente. Le CTR sur les sites Web des détaillants ou le trafic publicitaire peut entraîner les ventes susmentionnées. Les programmes de fidélité sont un autre cas d'utilisation, car les clients redirigés depuis des publicités en ligne ou d'autres sites Web peuvent se joindre pour gagner des récompenses. Les détaillants peuvent acquérir des clients par le biais de programmes de fidélité et enregistrer des comportements liés aux histoires de vente pour élaborer un système de recommandations qui non seulement prédit les comportements d'achat des consommateurs dans différentes catégories, mais également personnalise les bons de réduction et diminue le nombre de départs.
* *Fournisseurs de services:* les entreprises de télécommunications et les fournisseurs de services Internet disposent d'une abondance de données de télémétrie utilisateur de première partie pour des cas d'utilisation instructifs de l'IA, DU ML et de l'analytique. Par exemple, un opérateur télécom peut utiliser quotidiennement ses journaux d'historique de domaine de premier niveau pour affiner les modèles existants afin de générer une segmentation de l'audience à jour, d'anticiper le comportement des clients et de collaborer avec les annonceurs pour placer des publicités en temps réel et améliorer l'expérience en ligne. Dans ce flux de travail de marketing axé sur les données, CTR est une mesure importante pour refléter les conversions.


Dans le cadre du marketing numérique, http://labs.criteo.com/2013/12/download-terabyte-click-logs/["Criteo Terabyte cliquez sur journaux"^] Sont désormais le dataset de référence pour évaluer l'évolutivité des plateformes ET des algorithmes DE ML. En prédisant le taux de clics, un annonceur peut sélectionner les visiteurs qui sont les plus susceptibles de répondre aux annonces, analyser leur historique de navigation, et montrer les annonces les plus pertinentes en fonction des intérêts de l'utilisateur.

La solution proposée dans ce rapport technique présente les avantages suivants :

* Avantages de Azure NetApp Files dans le cadre d'une formation distribuée ou à grande échelle
* RAPIDES, traitement de données CUDA (cuDF, cuPy, etc.) et algorithmes DE ML (cuML)
* Le cadre informatique parallèle DASK pour la formation distribuée


Un workflow complet basé SUR RAPIDS dans l'IA et Azure NetApp Files démontre l'amélioration drastique du temps d'entraînement des modèles forestiers aléatoires de deux ordres de grandeur. Cette amélioration est très significative par rapport à l'approche Pandas classique lors du traitement des journaux de clics du monde réel avec 45 Go de données tabulaires structurées (en moyenne) chaque jour. Cela équivaut à un DataFrame contenant environ vingt milliards de lignes. Dans ce rapport technique, nous allons présenter la configuration de l'environnement de cluster, l'installation de la structure et de la bibliothèque, le chargement et le traitement des données, les méthodes conventionnelles par rapport à la formation distribuée, la visualisation et la surveillance, et comparer les résultats critiques de l'exécution de bout en bout.

link:aks-anf_install_and_set_up_the_aks_cluster.html["Ensuite : installez et configurez le cluster aks."]
