---
sidebar: sidebar 
permalink: ai/aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html 
keywords: toolkit, dataops, kubernetes, abstraction, python, jupyterlab 
summary: 'Le kit NetApp DataOps pour Kubernetes extrait les ressources de stockage et les workloads Kubernetes jusqu"à l"espace de travail data-science. Ces fonctionnalités sont packagées dans une interface simple et conviviale conçue pour les data Scientists et les ingénieurs de données.' 
---
= Gestion des versions de datasets et de modèles avec le kit NetApp DataOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_monitor_dask_and_rapids_with_prometheus_and_grafana.html["Précédent : surveillez DAsk et RAPIDS avec Prometheus et Grafana."]

Le kit NetApp DataOps pour Kubernetes extrait les ressources de stockage et les workloads Kubernetes jusqu'à l'espace de travail data-science. Ces fonctionnalités sont packagées dans une interface simple et conviviale conçue pour les data Scientists et les ingénieurs de données. Ce kit, qui se présente sous la forme familière d'un programme Python, permet aux scientifiques et aux ingénieurs des données de provisionner et de déployer des espaces de travail JupyterLab en quelques secondes. Ces espaces de travail peuvent contenir des téraoctets, voire des pétaoctets, de capacité de stockage, ce qui permet aux data Scientists de stocker tous leurs datasets d'entraînement directement dans leur espace de travail de projet. Il ne fait plus que gérer séparément les espaces de travail et les volumes de données.

Pour en savoir plus, visitez la boîte à outils https://github.com/NetApp/netapp-data-science-toolkit["Référentiel GitHub"^].

link:aks-anf_conclusion.html["Suivant: Conclusion."]
