---
sidebar: sidebar 
permalink: ai/cainvidia_conclusion.html 
keywords: Conclusion 
summary:  
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Un véritable système d'IA et d'échange s'engage dans un dialogue similaire à celui de l'homme, comprend le contexte et propose des réponses intelligentes. Ces modèles d'IA sont souvent énormes et extrêmement complexes. Avec les processeurs graphiques NVIDIA et le stockage NetApp, des modèles linguistiques de pointe peuvent être entraînés et optimisés pour exécuter rapidement l'inférence. C'est une tendance majeure vers la fin du compromis entre un modèle d'IA qui est rapide contre un modèle important et complexe. Les modèles de compréhension du langage optimisés par les GPU peuvent être intégrés aux applications d'IA dans des secteurs tels que la santé, le commerce de détail et les services financiers, permettant ainsi aux assistants numériques avancés dans les enceintes intelligentes et les lignes de services client. Ces systèmes d'IA conversationnels de haute qualité permettent aux entreprises de tous les marchés verticaux de fournir des services personnalisés jusqu'alors inaccessibles lors de l'entretien avec les clients.

Jarvis permet le déploiement de cas d'utilisation tels que des assistants virtuels, des avatars numériques, des Fusion de capteur multimodal (CV fusionné avec ASR/NLP/TTS), ou tout cas d'utilisation autonome ASR/NLP/TTS/CV, comme la transcription. Nous avons créé un assistant de vente au détail virtuel qui répond à vos questions concernant la météo, les points d'intérêt et les prix des stocks. Nous avons également démontré comment améliorer les fonctionnalités de compréhension du langage naturel du système d'IA conversationnel en archivant l'historique des conversations à l'aide de BlueXP Copy and Sync et en formant les modèles Nemo aux nouvelles données.
