---
sidebar: sidebar 
permalink: ai/cainvidia_executive_summary.html 
keywords: WP-7328, wp7328, 7328, Executive Summary, NVIDIA, Jarvis, 
summary:  
---
= WP-7328 : la stratégie d'IA de NetApp basée sur NVIDIA Jarvis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, Sung-Han Lin, NetApp Davide Onofrio, NVIDIA

La gamme NVIDIA DGX comprend les premiers systèmes basés sur l'intelligence artificielle intégrée (IA) conçus pour l'IA d'entreprise. Les systèmes de stockage NetApp AFF combinent performances optimales et fonctionnalités de pointe pour la gestion des données dans le cloud hybride. NetApp et NVIDIA se sont associés pour créer l'architecture de référence NetApp ONTAP ai, une solution clé en main qui prend en charge les workloads d'IA et de machine learning (ML), tout en offrant des performances et une fiabilité exceptionnelles.

Ce livre blanc fournit des recommandations aux clients qui conçoivent des systèmes d'IA pour divers champs d'application dans différents secteurs d'activité. Elle inclut des informations sur le déploiement du système à l'aide de NVIDIA Jarvis. Les tests ont été réalisés avec une station NVIDIA DGX et un système de stockage NetApp AFF A220.

La solution cible plusieurs groupes d'utilisateurs :

* Les architectes d'entreprise qui conçoivent des solutions pour le développement de modèles et de logiciels d'IA dans le cadre de l'élaboration d'outils d'IA, tels que l'assistant de détail virtuel
* Les data Scientists à la recherche de moyens efficaces pour atteindre les objectifs de développement de la modélisation linguistique
* Les ingénieurs de données sont chargés de maintenir et de traiter les données texte telles que les questions des clients et les transcriptions des dialogues
* Dirigeants, décideurs IT et responsables qui veulent transformer les échanges d'expérience d'IA et accélérer le time-to-market des initiatives d'IA


link:cainvidia_solution_overview.html["Ensuite : présentation de la solution"]
