---
sidebar: sidebar 
permalink: ai/dataops-toolkit.html 
keywords:  
summary:  
---
= Kit NetApp DataOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Le kit NetApp DataOps est un outil Python qui simplifie la gestion des espaces de travail de développement/formation et des serveurs d'inférence, lesquels sont basés sur un stockage NetApp haute performance et scale-out. Les fonctionnalités principales comprennent :

* Provisionnez rapidement de nouveaux espaces de travail JupyterLab haute capacité, soutenus par un stockage NetApp haute performance et scale-out.
* Provisionnez rapidement les nouvelles instances NVIDIA Triton Inférence Server, qui sont sauvegardées par un système de stockage NetApp de grande qualité.
* Clonez quasi instantanément les espaces de travail JupyterLab de grande capacité afin de permettre l'expérimentation ou l'itération rapide.
* Sauvegardez quasi instantanément des snapshots d'espaces de travail JupyterLab haute capacité pour la sauvegarde et/ou la traçabilité/référence.
* Provisionnez, clonez et snapshot de manière quasi instantanée des volumes de données haute capacité et haute performance.


link:https://github.com/NetApp/netapp-dataops-toolkit["Kit NetApp DataOps"^]
