---
sidebar: sidebar 
permalink: ai/hcaios_ontap_ai_deployment.html 
keywords: ONTAP AI, Deployment, networking, compute, storage 
summary:  
---
= Avec le déploiement d'ONTAP ai
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le déploiement de ONTAP ai nécessite l'installation et la configuration du matériel de réseau, de calcul et de stockage. Ce rapport n'a pas pour objectif d'obtenir des instructions spécifiques pour le déploiement de l'infrastructure d'IA d'ONTAP, Pour plus d'informations sur le déploiement, reportez-vous à https://www.netapp.com/pdf.html?item=/media/7674-nva-1121-deploypdf.pdf["NVA-1121-DEPLOY : NetApp ONTAP ai, optimisé par NVIDIA"^]la section.

Pour la validation de cette solution, un volume unique a été créé et monté sur le système DGX-1. Ce point de montage a ensuite été monté sur les conteneurs pour faciliter l'accès aux données pour l'entraînement. Pour les déploiements à grande échelle, NetApp Trident automatise la création et le montage des volumes de manière à éliminer les surcharges administratives et à permettre la gestion des ressources des utilisateurs finaux.
