---
sidebar: sidebar 
permalink: ai/hcaios_where_to_find_additional_information.html 
keywords: NetApp Additional Information 
summary:  
---
= Sources d'informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce document, consultez les ressources suivantes :

* Cnvrg.io ( https://cnvrg.io["https://cnvrg.io"^]) :
+
** CŒUR Cnvrg (plateforme DE ML gratuite)
+
https://cnvrg.io/platform/core[]

** Documents Cnvrg
+
https://app.cnvrg.io/docs["https://app.cnvrg.io/docs"^]



* Serveurs NVIDIA DGX-1 :
+
** Serveurs NVIDIA DGX-1
+
https://www.nvidia.com/en-us/data-center/dgx-1/[]

** GPU NVIDIA Tesla V100 à cœurs Tensor
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[]

** NVIDIA GPU CLOUD (NGC)
+
https://www.nvidia.com/en-us/gpu-cloud/[]



* Systèmes NetApp AFF :
+
** Fiche technique AFF
+
https://www.netapp.com/us/media/d-3582.pdf[]

** NetApp Flash Advantage pour AFF
+
https://www.netapp.com/us/media/ds-3733.pdf[]

** Documentation ONTAP 9.x.
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[]

** Rapport technique NetApp FlexGroup
+
https://www.netapp.com/us/media/tr-4557.pdf[]



* Le stockage persistant NetApp pour les conteneurs :
+
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[]



* Matrice d'interopérabilité NetApp :
+
** Matrice d'interopérabilité NetApp
+
https://mysupport.netapp.com/matrix/#welcome[]



* Connectivité réseau d'ONTAP ai :
+
** Switchs Cisco Nexus 3232C
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[]

** Switchs Mellanox Spectrum 2000
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[]



* Structure ET outils ML :
+
** DALI
+
https://github.com/NVIDIA/DALI[]

** TensorFlow : un framework d'apprentissage machine open source pour tous
+
https://www.tensorflow.org/[]

** Horovod : le cadre d’apprentissage profond Open source distribué d’Uber pour TensorFlow
+
https://eng.uber.com/horovod/[]

** Optimisation des GPU dans l'écosystème d'exécution du conteneur
+
https://devblogs.nvidia.com/gpu-containers-runtime/[]

** Docker
+
https://docs.docker.com[]

** Kubernetes
+
https://kubernetes.io/docs/home/[]

** NVIDIA DeepOps
+
https://github.com/NVIDIA/deepops[]

** Kubeflow
+
http://www.kubeflow.org/[]

** Jupyter Notebook Server
+
http://www.jupyter.org/[]



* Dataset et bancs d'essai :
+
** Ensemble de données de radiographie du thorax NIH
+
https://nihcc.app.box.com/v/ChestXray-NIHCC[]

** Xiaotong Wang, Yifan Peng, le lu, Zhiyong lu, Mohammadadi Bagheri, Ronald Summers, ChestX-ray8: Base de données à rayons X dans les hôpitaux et bancs d'essai sur la classification faiblement supervisée et la localisation des maladies du thorax commun, IEEE CVPR, pp 3462-3471, 2017 TR-4841-0620



