---
sidebar: sidebar 
permalink: ai/hcaios_abstract.html 
keywords: NetApp Abstract ML AI 
summary:  
---
= Résumé
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La croissance exponentielle du volume des données et la croissance exponentielle du machine learning (ML) et de l'intelligence artificielle (IA) se sont convergentes pour permettre de créer une nouvelle économie avec des défis uniques en matière de développement et d'implémentation. Des quantités massives de données sont généralement stockées dans un data Lake à faible coût, où les ressources de calcul d'IA haute performance telles que les GPU ne peuvent pas y accéder de manière efficace. Dans ce rapport, nous présentons une solution nouvelle dans laquelle les professionnels de la science des données implémentent un hub de données et, d'un simple clic, créent un cache de jeux de données à proximité de leurs ressources de calcul, où qu'elles se trouvent. Ils peuvent ainsi faciliter l'entraînement des modèles haute performance et renforcer la collaboration avec un nouveau hub de version du dataset.
