---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= Cas d'utilisation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Bien que toutes les applications actuelles ne soient pas pilotées par l'IA, elles font évoluer des fonctionnalités qui leur permettent d'accéder aux avantages considérables de l'IA. Pour prendre en charge l'adoption de l'IA, les applications ont besoin d'une infrastructure qui leur fournit les ressources nécessaires pour fonctionner au mieux et soutenir leur évolution continue.

Pour les applications d'IA, les emplacements de la périphérie font office de principale source de données. Les données disponibles peuvent être utilisées pour l'entraînement lorsqu'elles sont collectées depuis plusieurs sites en périphérie sur une période donnée pour former un dataset d'entraînement. Le modèle entraîné peut ensuite être déployé à nouveau vers la périphérie où les données ont été collectées. Ainsi, l'inférence est plus rapide sans avoir à transférer plusieurs fois les données de production vers une plateforme d'inférence dédiée.

La solution d'inférence NetApp HCI ai, optimisée par les nœuds de calcul NetApp H615c avec les processeurs graphiques NVIDIA T4 et les systèmes de stockage NetApp connectés au cloud, a été développée et vérifiée par NetApp et NVIDIA. NetApp HCI simplifie le déploiement de solutions d'inférence d'IA dans les data centers en périphérie en éliminant les zones d'ambiguïté au niveau de la conception et en mettant fin aux approximations. Cette solution offre aux services INFORMATIQUES une architecture normative qui :

* Permet l'inférence d'IA dans les data centers en périphérie
* Optimisation de la consommation des ressources GPU
* Offre une plateforme d'inférence basée sur Kubernetes pour plus de flexibilité et d'évolutivité
* Simplifie la conception


Les data centers de périphérie gèrent et traitent les données à des emplacements très proches du point de génération. Cette proximité augmente l'efficacité et réduit la latence impliquée dans le traitement des données. De nombreux marchés verticaux ont compris les avantages d'un data Center à la périphérie et adoptent massivement cette approche distribuée pour le traitement des données.

Le tableau suivant répertorie les secteurs verticaux et les applications de périphérie.

|===
| Verticale | En termes de latence 


| Médical | Les diagnostics assistés par ordinateur aident le personnel médical à détecter rapidement les maladies 


| Pétrole et gaz | Inspection autonome des installations de production distantes, de la vidéo et de l'analyse d'images 


| Aviation | Assistance au contrôle du trafic aérien et analyse des flux vidéo en temps réel 


| Les médias et le divertissement | Filtrage de contenu audio/vidéo pour offrir des contenus adaptés aux familles 


| Analyses commerciales | Reconnaissance de la marque pour analyser l'apparence de la marque lors d'événements télévisés en direct 


| E-commerce | Regroupement intelligent des offres de fournisseurs pour trouver des combinaisons de commerçants et d'entrepôts idéales 


| Commerce | Paiement automatisé pour reconnaître les articles placés dans le panier d'un client et faciliter le paiement numérique 


| Smart City | Améliorer la circulation routière, optimiser le stationnement et améliorer la sécurité des piétons et des cyclistes 


| Secteur industriel | Contrôle de la qualité, surveillance de la ligne de montage et identification des défauts 


| Service clientèle | Automatisation des services clients pour analyser et trier les demandes (téléphone, e-mails et réseaux sociaux) 


| Agriculture | Exploitation et planification intelligente des activités agricoles pour optimiser l'application d'engrais et d'herbicides 
|===


== Public visé

La solution cible plusieurs groupes d'utilisateurs :

* Scientifiques des données
* Les architectes IT
* Consultants sur le terrain
* Des services professionnels
* Aux responsables INFORMATIQUES
* Quiconque a besoin d'une infrastructure qui assure l'innovation IT et des services robustes de données et d'applications sur des sites en périphérie

