---
sidebar: sidebar 
permalink: ai/mlops_fsxn_intro.html 
keywords: FSx ONTAP, FSx ONTAP, AWS S3, SageMaker, MLOps, NetApp ONTAP 
summary: 'Voici la page d"introduction à la section MLOps de FSX ONTAP.' 
---
= Amazon FSX pour NetApp ONTAP (FSX ONTAP) pour MLOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section examine l'application pratique du développement d'infrastructures d'IA et fournit une description de bout en bout de la construction d'un pipeline MLOps à l'aide de FSX ONTAP. Il comprend trois exemples complets et vous guide pour répondre à vos besoins MLOps via cette puissante plateforme de gestion des données.

*Auteur(s):*
Jian Jian (Ken), scientifique senior en données et applications, NetApp

Ces articles portent sur :

. link:./mlops_fsxn_s3_integration.html["1re partie : intégration d'Amazon FSX pour NetApp ONTAP (FSX ONTAP) en tant que compartiment S3 privé dans AWS SageMaker"]
. link:./mlops_fsxn_sagemaker_integration_training.html["Partie 2 - exploitation d'Amazon FSX pour NetApp ONTAP (FSX ONTAP) en tant que source de données pour l'entraînement des modèles dans SageMaker"]
. link:./mlops_fsxn_cictcd.html["Partie 3 - construire Un pipeline MLO simplifié (ci/CT/CD)"]


À la fin de cette section, vous aurez acquis une solide compréhension de l'utilisation de FSX ONTAP pour rationaliser les processus MLOps.
