---
sidebar: sidebar 
permalink: ai/mlrun_where_to_find_additional_information.html 
keywords: NetApp Find Additional Information 
summary:  
---
= Sources d'informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce document, consultez les ressources suivantes :

* Plan de contrôle pour l'IA de NetApp :
+
** Rapport technique sur le plan de contrôle d'IA de NetApp
+
https://www.netapp.com/us/media/tr-4798.pdf["https://www.netapp.com/us/media/tr-4798.pdf"^]



* Le stockage persistant NetApp pour les conteneurs :
+
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]



* Structure ET outils ML :
+
** TensorFlow : un framework d'apprentissage machine open source pour tous https://www.tensorflow.org/["https://www.tensorflow.org/"^]
** Docker
+
https://docs.docker.com["https://docs.docker.com"^]

** Kubernetes
+
https://kubernetes.io/docs/home/["https://kubernetes.io/docs/home/"^]

** Kubeflow
+
http://www.kubeflow.org/["http://www.kubeflow.org/"^]

** Jupyter Notebook Server
+
http://www.jupyter.org/["http://www.jupyter.org/"^]



* Plateforme Iguazio pour la science des données
+
** Documentation de la plateforme Iguazio pour la science des données
+
https://www.iguazio.com/docs/["https://www.iguazio.com/docs/"^]

** Fonction sans serveur Nucio
+
https://nuclio.io/["https://nuclio.io/"^]

** MLRun : framework d'orchestration du pipeline open source
+
https://www.iguazio.com/open-source/mlrun/["https://www.iguazio.com/open-source/mlrun/"^]



* Systèmes NVIDIA DGX-1
+
** Systèmes NVIDIA DGX-1
+
https://www.nvidia.com/en-us/data-center/dgx-1/["https://www.nvidia.com/en-us/data-center/dgx-1/"^]

** GPU NVIDIA Tesla V100 à cœurs Tensor
+
https://www.nvidia.com/en-us/data-center/tesla-v100/["https://www.nvidia.com/en-us/data-center/tesla-v100/"^]

** NVIDIA GPU Cloud
+
https://www.nvidia.com/en-us/gpu-cloud/["https://www.nvidia.com/en-us/gpu-cloud/"^]



* Systèmes NetApp AFF
+
** Fiche technique AFF
+
https://www.netapp.com/us/media/ds-3582.pdf["https://www.netapp.com/us/media/ds-3582.pdf"^]

** Avantages Flash de NetApp pour AFF
+
https://www.netapp.com/us/media/ds-3733.pdf["https://www.netapp.com/us/media/ds-3733.pdf"^]

** Documentation ONTAP 9.x.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

** Rapport technique NetApp FlexGroup
+
https://www.netapp.com/us/media/tr-4557.pdf["https://www.netapp.com/us/media/tr-4557.pdf"^]



* NetApp ONTAP ai
+
** Guide de conception d'ONTAP ai avec DGX-1 et connectivité réseau Cisco
+
https://www.netapp.com/us/media/nva-1121-design.pdf["https://www.netapp.com/us/media/nva-1121-design.pdf"^]

** Guide de déploiement d'ONTAP ai avec DGX-1 et réseau Cisco
+
https://www.netapp.com/us/media/nva-1121-deploy.pdf["https://www.netapp.com/us/media/nva-1121-deploy.pdf"^]

** Guide de conception d'ONTAP ai avec DGX-1 et réseau Mellanox
+
https://www.netapp.com/us/media/nva-1138-design.pdf["https://www.netapp.com/us/media/nva-1138-design.pdf"^]



* La connectivité réseau d'ONTAP ai
+
** Switchs de la gamme Cisco Nexus 3232C
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html"^]

** Gamme de commutateurs Ethernet SN2000 à évolutivité horizontale Mellanox
+
https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000["https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000"^]




