---
sidebar: sidebar 
permalink: ai/mlrun_software_and_hardware_requirements.html 
keywords: NetApp, Software, Hardware, Network, Requirements 
summary:  
---
= Configuration logicielle et matérielle requise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cet article définit les exigences matérielles à respecter pour déployer cette solution.



== Configuration du réseau

Voici les exigences de configuration réseau pour la configuration dans le cloud :

* Le cluster Iguazio et NetApp Cloud volumes doivent se trouver dans le même cloud privé virtuel.
* Le responsable cloud doit avoir accès au port 6443 sur les nœuds applicatifs Iguazio.
* Nous avons utilisé Amazon Web Services dans ce rapport technique. Toutefois, les utilisateurs peuvent déployer la solution auprès de n'importe quel fournisseur cloud.pour les tests sur site de ONTAP ai avec NVIDIA DGX-1, nous avons utilisé le service DNS hébergé d'Iguazio pour des raisons de commodité.


Les clients doivent pouvoir accéder aux domaines DNS créés de manière dynamique. Les clients peuvent utiliser leur propre DNS si nécessaire.



== Configuration matérielle requise

Vous pouvez installer Iguazio sur site dans votre propre cluster. Nous avons vérifié la solution dans NetApp ONTAP ai avec un système NVIDIA DGX-1. Le tableau suivant répertorie le matériel utilisé pour tester cette solution.

|===
| Sous-jacent | Quantité 


| Systèmes DGX-1 | 1 


| Système NetApp AFF A800 | 1 paire haute disponibilité (HA), comprend 2 contrôleurs et 48 SSD NVMe (3,8 To ou plus) 


| Switchs réseau Cisco Nexus 3232C | 2 
|===
Le tableau suivant répertorie les composants logiciels requis pour les tests sur site :

|===
| Logiciel | Version ou autres informations 


| Le logiciel de gestion des données NetApp ONTAP | 9.7 


| Firmware du switch Cisco NX-OS | 7.0(3)I6(1) 


| SYSTÈME D'EXPLOITATION NVIDIA DGX | 4.4 - Ubuntu 18.04 LTS 


| Plateforme de conteneurisation Docker | 19.03.5 


| Version du conteneur | 20.01-tf1-py2 


| Framework de machine learning | TensorFlow 1.15.0 


| Iguazio | Version 2.8+ 


| Serveur ESX | 6.5 
|===
Cette solution a été entièrement testée avec Iguazio version 2.5 et NetApp Cloud Volumes ONTAP pour AWS. Le cluster Iguazio et le logiciel NetApp s'exécutent tous les deux sur AWS.

|===
| Logiciel | Version ou type 


| Iguazio | Version 2.8+ 


| Nœud d'application | M5.4xlarge 


| Nœud de données | I3,4xlarge 
|===