---
sidebar: sidebar 
permalink: ai/nva-1153-design-link.html 
keywords:  
summary:  
---
= NVA-1153-DESIGN : NetApp ONTAP ai avec les systèmes NVIDIA DGX A100 et les switchs Ethernet Mellanox Spectrum
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette et Sung-Han Lin, NetApp

La conception NVA-1153 décrit une architecture vérifiée NetApp pour les workloads de machine learning (ML) et d'intelligence artificielle (IA) utilisant les systèmes de stockage NetApp AFF A800, les systèmes NVIDIA DGX A100 et les switchs Ethernet de 200 Go NVIDIA Mellanox Spectrum SN3700V. Cette conception comprend le protocole RDMA over Converged Ethernet (RoCE) pour la structure d'interconnexion des clusters de calcul. Elle offre aux clients une architecture entièrement basée sur ethernet pour les charges de travail haute performance. Ce document inclut également les résultats des tests de performance pour l'architecture mise en œuvre.

link:https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf["https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf"^]
