---
sidebar: sidebar 
permalink: ai/nva-1156-design.html 
keywords:  
summary:  
---
= NVA-1156-DESIGN : NetApp EF-Series ai avec les systèmes NVIDIA DGX A100 et BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Abdel Sadek, Tim Chau, Joe McCormick et David Arnette, NetApp

[role="lead"]
La conception NVA-1156 décrit une architecture vérifiée NetApp pour les workloads de machine learning (ML) et d'intelligence artificielle (IA) à l'aide des systèmes de stockage NVMe NetApp EF600, du système de fichiers parallèle BeeGFS, des systèmes NVIDIA DGX A100 et des switchs IB NVIDIA Mellanox QM8700 200 Gbit/s. Cette conception est dotée d'une architecture entièrement basée sur IB 200 Gbit/s pour la structure d'interconnexion des clusters de stockage et de calcul. Elle offre ainsi aux clients une architecture entièrement basée sur IB pour les charges de travail hautes performances. Ce document inclut également les résultats des tests de performance pour l'architecture mise en œuvre.

link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NVA-1156-DESIGN : NetApp EF-Series ai avec les systèmes NVIDIA DGX A100 et BeeGFS"^]
