---
sidebar: sidebar 
permalink: ai/nvaie_technology_overview.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA ai Enterprise with NetApp and VMware - Présentation technologique 
---
= Présentation de la technologie
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section propose une présentation technologique pour NVIDIA ai Enterprise avec NetApp et VMware.



== NVIDIA ai Enterprise

NVIDIA ai Enterprise est une suite logicielle cloud complète d'IA et d'analytique de données optimisée, certifiée et prise en charge par NVIDIA pour s'exécuter sur VMware vSphere avec les systèmes NVIDIA certifiés. Ce logiciel facilite le déploiement, la gestion et l'évolutivité simples et rapides des workloads d'IA dans un environnement de cloud hybride moderne.



== NVIDIA GPU CLOUD (NGC)

NVIDIA NGC héberge un catalogue de logiciels optimisés pour les GPU destinés aux professionnels de l'IA afin qu'ils développent leurs solutions d'IA. Elle permet également d'accéder à plusieurs services d'IA, notamment NVIDIA base Command pour l'entraînement des modèles, NVIDIA Fleet Command pour déployer et surveiller les modèles, et NGC Private Registry pour accéder et gérer en toute sécurité des logiciels d'IA propriétaires. En outre, les clients NVIDIA ai Enterprise peuvent demander une assistance via le portail NGC.



== VMware vSphere

VMware vSphere est la plateforme de virtualisation de VMware, qui transforme les data centers en infrastructures informatiques agrégées, incluant les ressources de CPU, de stockage et de réseau. VSphere gère ces infrastructures en tant qu'environnement d'exploitation unifié et fournit aux administrateurs les outils nécessaires pour gérer les data centers participant à cet environnement.

Les deux principaux composants de vSphere sont ESXi et vCenter Server. ESXi est la plateforme de virtualisation sur laquelle les administrateurs créent et exécutent des machines virtuelles et des appliances virtuelles. VCenter Server est le service par l'intermédiaire duquel les administrateurs gèrent plusieurs hôtes connectés dans un réseau et regroupent des ressources hôtes.



== NetApp ONTAP

ONTAP 9, la dernière génération de logiciel de gestion du stockage de NetApp, permet aux entreprises de moderniser l'infrastructure et de passer à un data Center prêt pour le cloud. Avec des capacités de gestion des données à la pointe du secteur, ONTAP permet de gérer et de protéger les données avec un seul ensemble d'outils, quel que soit leur emplacement. Vous pouvez aussi déplacer vos données librement partout où elles sont nécessaires : la périphérie, le cœur ou le cloud. ONTAP 9 comprend de nombreuses fonctionnalités qui simplifient la gestion des données, accélèrent et protègent les données stratégiques, et permettent d'utiliser des fonctionnalités d'infrastructure nouvelle génération dans toutes les architectures de cloud hybride.



=== Gestion simplifiée

La gestion des données est cruciale pour les opérations IT et les data Scientists, de sorte que les ressources appropriées sont utilisées pour les applications d'IA et pour l'entraînement des datasets d'IA/DE ML. Les informations supplémentaires suivantes sur les technologies NetApp ne sont pas incluses dans cette validation, mais elles peuvent être pertinentes en fonction de votre déploiement.

Le logiciel de gestion des données ONTAP comprend les fonctionnalités suivantes pour rationaliser et simplifier les opérations et réduire le coût total d'exploitation :

* Compaction des données à la volée et déduplication étendue La compaction des données réduit le gaspillage d'espace à l'intérieur des blocs de stockage, et la déduplication augmente considérablement la capacité effective. Cela s'applique aux données stockées localement et à leur placement dans le cloud.
* Qualité de service (AQoS) minimale, maximale et adaptative. Les contrôles granulaires de la qualité de service (QoS) permettent de maintenir les niveaux de performance des applications stratégiques dans des environnements hautement partagés.
* NetApp FabricPool Tiering automatique des données inactives vers des options de stockage de cloud public et privé, notamment Amazon Web Services (AWS), Azure et la solution de stockage NetApp StorageGRID. Pour plus d'informations sur FabricPool, voir https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["Tr-4598 : meilleures pratiques de FabricPool"^].




=== Accélération et protection des données

ONTAP offre des niveaux supérieurs de performances et de protection des données et étend ces fonctionnalités aux méthodes suivantes :

* Des performances élevées et une faible latence. ONTAP offre le débit le plus élevé possible à la latence la plus faible possible.
* Protection des données. ONTAP fournit des fonctionnalités de protection des données intégrées avec une gestion commune sur toutes les plateformes.
* NetApp Volume Encryption (NVE). ONTAP offre un chiffrement natif au niveau du volume avec un support de gestion des clés interne et externe.
* Colocation et authentification multifacteur. ONTAP permet le partage des ressources d'infrastructure avec les plus hauts niveaux de sécurité.




=== Une infrastructure pérenne

ONTAP permet de répondre aux besoins métier en constante évolution grâce aux fonctionnalités suivantes :

* Évolutivité transparente et opérations non disruptives. ONTAP prend en charge l'ajout non disruptif de capacité aux contrôleurs et l'évolution scale-out des clusters. Les clients peuvent effectuer la mise à niveau vers les technologies les plus récentes, telles que NVMe et FC 32 Gb, sans migration des données ni panne coûteuse.
* Connexion cloud. ONTAP est le logiciel de gestion de stockage le plus connecté au cloud, avec des options de stockage Software-defined (ONTAP Select) et des instances natives de cloud (Google Cloud NetApp volumes) dans tous les clouds publics.
* Intégration avec les applications émergentes ONTAP propose des services de données d'entreprise pour les plateformes et applications nouvelle génération, telles que les véhicules autonomes, les Smart cities et Industry 4.0, en utilisant la même infrastructure prenant en charge les applications d'entreprise existantes.




== Kit NetApp DataOps

Le kit NetApp DataOps est un outil Python qui simplifie la gestion des espaces de travail de développement/formation et des serveurs d'inférence, lesquels sont basés sur un stockage NetApp haute performance et scale-out. Les fonctionnalités principales comprennent :

* Provisionnez rapidement de nouveaux espaces de travail JupyterLab haute capacité, soutenus par un stockage NetApp haute performance et scale-out.
* Provisionnez rapidement les nouvelles instances NVIDIA Triton Inférence Server, qui sont sauvegardées par un système de stockage NetApp de grande qualité.
* Cloner simultanément des espaces de travail JupyterLab haute capacité afin de permettre des expériences ou une itération rapide.
* Vous pouvez sauvegarder simultanément des snapshots des espaces de travail JupyterLab haute capacité pour la sauvegarde et/ou la traçabilité/l'établissement de base.
* Provisionnement, clonage et snapshot quasi instantanés des volumes de données haute capacité haute performance.

