---
sidebar: sidebar 
permalink: ai/nvaie_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA ai Enterprise avec NetApp et VMware - Configuration initiale 
---
= Configuration initiale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section décrit les tâches de configuration initiales à effectuer afin d'utiliser NVIDIA ai Enterprise avec NetApp et VMware.



== Prérequis

Avant d'exécuter les étapes décrites dans cette section, nous supposons que vous avez déjà déployé VMware vSphere et NetApp ONTAP. Pour plus d'informations sur les versions de vSphere prises en charge, reportez-vous aulink:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html["Matrice de support des produits NVIDIA ai Enterprise"]. Pour plus d'informations sur le déploiement de VMware vSphere avec NetApp ONTAP, reportez-vous aulink:../vmware/index.html["Documentation des solutions NetApp et VMware"].



== Installez le logiciel hôte NVIDIA ai

Pour installer le logiciel hôte NVIDIA ai Entrprise, suivez les instructions décrites dans les sections 1-4 du link:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html["Guide de démarrage rapide de la solution NVIDIA ai Enterprise"].
