---
sidebar: sidebar 
permalink: ai/osrunai_executive_summary.html 
keywords:  
summary:  
---
= Tr-4858 : solution d'orchestration NetApp avec Run:ai
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, David Arnette, Sung-Han Lin, NetApp Yaron Goldberg, Run:ai

[role="lead"]
Les systèmes de stockage NetApp AFF combinent performances optimales et fonctionnalités de pointe pour la gestion des données dans le cloud hybride. NetApp et Run:ai se sont associés pour présenter les fonctionnalités uniques de la solution NetApp ONTAP ai pour les workloads d'intelligence artificielle (IA) et de machine learning (ML), qui offre des performances, une fiabilité et un support haute performance. Exécution :l'orchestration ai des workloads d'IA ajoute une plateforme Kubernetes de planification et d'utilisation des ressources afin d'aider les chercheurs à gérer et à optimiser l'utilisation des GPU. Associée aux systèmes NVIDIA DGX, la solution combinée de NetApp, NVIDIA et Run:ai fournit une pile d'infrastructure dédiée aux workloads d'IA d'entreprise. Ce rapport technique fournit des recommandations aux clients qui conçoivent des systèmes d'IA pour divers champs d'application et dans plusieurs secteurs d'activité. Vous y trouverez des informations sur le déploiement d'Run:ai et un système de stockage NetApp AFF A800, et sert d'architecture de référence pour déployer rapidement des initiatives d'IA de manière simple.

La solution cible plusieurs groupes d'utilisateurs :

* Les architectes d'entreprise qui conçoivent des solutions pour le développement de modèles et de logiciels d'IA pour des cas d'utilisation basés sur Kubernetes, tels que les microservices conteneurisés
* Data Scientists qui recherchent des méthodes efficaces pour atteindre leurs objectifs de développement de modèles dans un environnement en cluster comprenant plusieurs équipes et projets
* Les ingénieurs de données sont chargés de maintenir et d'exécuter des modèles de production
* Dirigeants, décideurs IT et responsables qui veulent créer une expérience optimale en matière d'utilisation des ressources des clusters Kubernetes et accélérer le time-to-market des initiatives d'IA

