---
sidebar: sidebar 
permalink: ai/osrunai_software_requirements.html 
keywords:  
summary:  
---
= Configuration logicielle requise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette solution a été validée à l'aide d'un déploiement Kubernetes de base avec l'opérateur Run:ai installé. Kubernetes a été déployé à l'aide du https://["NVIDIA DeepOps"^] le moteur de déploiement déploie tous les composants nécessaires pour un environnement prêt à la production. Déploiement automatique de DeepOps https://["NetApp Trident"^] Pour l'intégration du stockage persistant avec l'environnement k8s et des classes de stockage par défaut ont été créées afin que les conteneurs exploitent le stockage du système de stockage AFF A800. Pour en savoir plus sur Trident avec Kubernetes sur ONTAP ai, rendez-vous sur https://["TR-4798"^].

 The following table lists the software components that are required to implement the solution as tested.
|===
| Logiciel | Version ou autres informations 


| Le logiciel de gestion des données NetApp ONTAP | 9.6p4 


| Firmware du switch Cisco NX-OS | 7.0(3)I6(1) 


| SYSTÈME D'EXPLOITATION NVIDIA DGX | 4.0.4 - Ubuntu 18.04 LTS 


| Version Kubernetes | 1.17 


| Version Trident | 20.04.0 


| Exécutez :CLI ai | v2.1.13 


| Exécution : version de l'opérateur Kubernetes d'orchestration d'IA | 1.0.39 


| Plateforme de conteneurisation Docker | 18.06.1 ce [e68fc7a] 
|===
D'autres exigences logicielles supplémentaires pour Run:ai sont disponibles à l'adresse https://["Pré-requis pour le cluster de GPU Run:ai"^].

link:osrunai_optimal_cluster_and_gpu_utilization_with_run_ai_overview.html["Next : une utilisation optimale des clusters et des GPU avec l'exécution d'IA"].
