---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_48.html 
keywords:  
summary:  
---
= Détails des tests pour la section 4.8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section contient les détails des tests de la section link:osrunai_achieving_high_cluster_utilization_with_over-uota_gpu_allocation.html["Une utilisation élevée des clusters grâce à une allocation GPU sur-quota"].

Soumettre les travaux dans l'ordre suivant :

|===
| Projet | Image | NB de GPU | Total | Commentaire 


| équipe a | Jupyter | 1 | 1/4 | – 


| équipe a | NetApp | 1 | 2/4 | – 


| équipe a | Exécutez :ai | 2 | 4/4 | Utiliser tous leurs quotas 


| équipe-b | Exécutez :ai | 0.6 | 0.6/2 | GPU fractionnaires 


| équipe-b | Exécutez :ai | 0.4 | 1/2 | GPU fractionnaires 


| équipe-b | NetApp | 1 | 2/2 | – 


| équipe-b | NetApp | 2 | 4/2 | Deux sur le quota 


| equipe-c | Exécutez :ai | 0.5 | 0.5/2 | GPU fractionnaires 


| equipe-c | Exécutez :ai | 0.3 | 0.8/2 | GPU fractionnaires 


| equipe-c | Exécutez :ai | 0.2 | 1/2 | GPU fractionnaires 


| equipe-c | NetApp | 2 | 3/2 | Un au-delà des quotas 


| equipe-c | NetApp | 1 | 4/2 | Deux sur le quota 


| équipe-d | NetApp | 4 | 4/8 | Utilisant la moitié de leur quota 
|===
Structure de commande :

....
$ runai submit <job-name> -p <project-name> -g <#GPUs> -i <image-name>
....
Séquence de commande réelle utilisée lors du test :

....
$ runai submit a-1-1-jupyter -i jupyter/base-notebook -g 1 \
  --interactive --service-type=ingress --port 8888 \
  --args="--NotebookApp.base_url=team-a-test-ingress" --command=start-notebook.sh -p team-a
$ runai submit a-1-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-a
$ runai submit a-2-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a
$ runai submit b-1-g06 -i gcr.io/run-ai-demo/quickstart -g 0.6 --interactive -p team-b
$ runai submit b-2-g04 -i gcr.io/run-ai-demo/quickstart -g 0.4 --interactive -p team-b
$ runai submit b-3-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-b
$ runai submit b-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-b
$ runai submit c-1-g05 -i gcr.io/run-ai-demo/quickstart -g 0.5 --interactive -p team-c
$ runai submit c-2-g03 -i gcr.io/run-ai-demo/quickstart -g 0.3 --interactive -p team-c
$ runai submit c-3-g02 -i gcr.io/run-ai-demo/quickstart -g 0.2 --interactive -p team-c
$ runai submit c-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-c
$ runai submit c-5-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-c
$ runai submit d-1-gggg -i gcr.io/run-ai-demo/quickstart -g 4 -p team-d
....
À ce stade, vous devez avoir les États suivants :

|===
| Projet | GPU alloués | Charges de travail en file d'attente 


| équipe a | 4/4 (quota mou/allocation réelle) | Aucune 


| équipe-b | 4/2 | Aucune 


| equipe-c | 4/2 | Aucune 


| équipe-d | 4/8 | Aucune 
|===
Voir la section link:osrunai_achieving_high_cluster_utilization_with_over-uota_gpu_allocation.html["Optimiser l'utilisation des clusters grâce à l'allocation GPU sur-organismes"] pour les discussions sur le scénario de test en cours.
