---
sidebar: sidebar 
permalink: ai/osrunai_netapp_ontap_ai_and_ai_control_plane.html 
keywords:  
summary:  
---
= NetApp ONTAP ai et la solution ai Control plane
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'architecture NetApp ONTAP ai, optimisée par les systèmes NVIDIA DGX et les systèmes de stockage NetApp connectés au cloud. Et présente plusieurs avantages pour les SERVICES IT :

* Simplifie la conception
* Évolutivité indépendante des ressources de calcul et de stockage
* Possibilité de faire évoluer de manière fluide une infrastructure initiale de petite taille
* NetApp ONTAP ai propose différentes options de stockage pour répondre à des besoins de performance et de cout. Il intègre étroitement les systèmes DGX et de stockage NetApp AFF A800 avec une connectivité réseau optimale. Les systèmes NetApp ONTAP ai et DGX simplifient les déploiements d'IA en éliminant la complexité et les approximations. Les clients peuvent commencer avec un déploiement de petite taille, puis évoluer sans interruption d'activité, tout en gérant intelligemment leurs données de la périphérie au cœur, et jusqu'au cloud, et inversement.


NetApp ai Control plane est une solution complète d'IA, DE MACHINE LEARNING et de deep learning (DL) et de gestion des tests pour les data Scientists et les ingénieurs de données. Alors que les entreprises ont de plus en plus recours à l'IA, elles sont confrontées à de nombreux défis, notamment l'évolutivité des workloads et la disponibilité des données. NetApp ai Control plane répond à ces challenges grâce à des fonctionnalités telles que le clonage rapide d'un namespace de données comme vous le feriez avec un Git repo. Il définit et met en œuvre des workflows d'entraînement d'IA qui intègrent la création quasi instantanée de données et de références de modèles pour la traçabilité et la gestion des versions. NetApp ai Control plane vous permet de répliquer de manière transparente des données entre plusieurs sites et régions, et de provisionner rapidement des espaces de travail Jupyter Notebook avec un accès à des datasets volumineux.
