---
sidebar: sidebar 
permalink: ai/osrunai_optimal_cluster_and_gpu_utilization_with_run_ai_overview.html 
keywords:  
summary:  
---
= Optimisation de l'utilisation des clusters et des GPU avec Run:ai
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les sections suivantes décrivent l'installation de Run:ai, les scénarios de test et les résultats obtenus lors de cette validation.

Le fonctionnement et les performances de ce système ont été validées à l'aide d'outils de test standard du secteur, dont des bancs d'essai TensorFlow. Le dataset ImageNet a été utilisé pour entraîner le modèle ResNet-50, qui est un modèle d'apprentissage profond connu des réseaux neuronaux convolutifs (CNN) pour la classification d'images. RESNET-50 offre des résultats d'entraînement précis avec un temps de traitement plus rapide, ce qui nous a permis d'obtenir une demande suffisante en matière de stockage.

link:osrunai_run_ai_installation.html["Ensuite : exécutez l'installation d'IA"].
