---
sidebar: sidebar 
permalink: ai/rag_nemo_data_protection.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: 'RAG d"entreprise avec NetApp - base de connaissances RAG protection des données' 
---
= Protection des données de la base de connaissances RAG
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Comme les applications RAG deviennent des composants clés des flux de travail organisationnels importants, il est essentiel de protéger les bases de connaissances/magasins vectoriels qui sous-traitent ces applications RAG. Il est important de sauvegarder vos bases de données vectorielles et d'implémenter des workflows de reprise après incident comme vous le feriez pour toute autre base de données.



== Protégez votre base de connaissances Nemo RAG à l'aide de NetApp technologies

Les technologies NetApp, telles que link:https://docs.netapp.com/us-en/ontap/concepts/snapshot-copies-concept.html["Copies Snapshot"] et link:https://docs.netapp.com/us-en/ontap/concepts/snapmirror-disaster-recovery-data-transfer-concept.html["Reprise sur incident SnapMirror"], peut être utilisé pour protéger votre base de connaissances/magasin de vecteurs. Pour plus d'informations sur la protection des données de la base de données vectorielle, reportez-vous au link:https://docs.netapp.com/us-en/netapp-solutions/ai/vector-database-solution-with-netapp.html["Documentation de la solution de base de données NetApp Vector."]
