---
sidebar: sidebar 
permalink: ai/rag_introduction.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Enterprise RAG avec NVIDIA Nemo et NetApp - Introduction 
---
= Génération augmentée de récupération d'entreprise (RAG) avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mike Oglesby, NetApp
Thyagarajan Sathyish, NetApp

[role="lead"]
Generative ai transforme l'expérience de recherche d'entreprise. Grâce à elle, les utilisateurs des données peuvent découvrir les données qui résident partout, sur site ou dans le cloud public. Si l'IA générative est utilisée par les développeurs pour générer du code pour concevoir une application Web moderne, ou pour créer des animations à l'aide de données physiques et de mouvement réelles, les entreprises utilisent l'IA générative et des modèles de langage large (LLMS) pré-entraînés pour créer des applications d'IA transformatrices, concevoir de nouvelles fonctionnalités de produit, améliorer la productivité de l'ingénierie et augmenter l'expérience client.

Toutefois, l'IA générative et les LLMS ne peuvent garantir à eux seuls une valeur commerciale. Pour créer un impact commercial tangible, l'IA générative doit utiliser des données adaptées afin d'obtenir des résultats commerciaux de qualité. Les grandes entreprises se tournent donc vers un cadre émergent et essentiel appelé RAG (extraction augmentée Generation). Dans cette solution, nous présentons une architecture pour les organisations qui souhaitent construire un pipeline RAG. Cette solution peut vous aider à valoriser vos données privées en récupérant des informations contextuelles via un pipeline RAG privé.
