---
sidebar: sidebar 
permalink: ai/runai-ld_executive_summary.html 
keywords: azure, lane, detection, training, solution, design 
summary: 'Depuis mai 2019, Microsoft propose un service de portail Azure propriétaire natif pour les services de fichiers NFS et SMB d"entreprise basés sur la technologie NetApp ONTAP.' 
---
= Tr-4896: Formation distribuée dans Azure: Détection de voie - conception de la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Muneer Ahmad et Verron Martina, NetApp Ronen Dar, EXÉCUTEZ :ai

[role="lead"]
Depuis mai 2019, Microsoft propose un service de portail Azure propriétaire natif pour les services de fichiers NFS et SMB d'entreprise basés sur la technologie NetApp ONTAP. Ce développement est régi par un partenariat stratégique entre Microsoft et NetApp, et étend encore davantage la portée des services de données ONTAP à Azure.

NetApp, l'un des principaux fournisseurs de services de données cloud, s'est associé À CETTE SOLUTION : l'IA, une entreprise qui virtualise l'infrastructure d'IA pour accélérer les tests d'IA en utilisant pleinement les GPU. Ce partenariat permet aux équipes d'accélérer l'IA en exécutant de nombreuses expériences en parallèle, avec un accès rapide aux données et en exploitant des ressources de calcul sans limites. EXÉCUTION : l'IA permet l'utilisation totale des GPU en automatisant l'allocation des ressources. L'architecture éprouvée du Azure NetApp Files permet également à tous les tests de s'exécuter à la vitesse maximale en éliminant les obstacles au pipeline de données.

NetApp et LA GESTION : l'IA s'est associée afin de proposer aux clients une plateforme pérenne pour leur transition vers l'IA dans Azure. De l'analytique et du calcul haute performance aux décisions autonomes (où les clients peuvent optimiser leurs investissements IT en ne payant que ce dont ils ont besoin, quand ils en ont besoin), la alliance entre NetApp ET EXÉCUTION : l'IA offre une expérience unifiée dans le cloud Azure.
