---
sidebar: sidebar 
permalink: ai/runai-ld_additional_information.html 
keywords: azure, lane, detection, additional, information, websites 
summary: Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et sites web. 
---
= Informations supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Jeu de données : simple
+
https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection["https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection"^]

* Architecture de réseau d'apprentissage profond : réseau neuronal spatial
+
https://arxiv.org/abs/1712.06080["https://arxiv.org/abs/1712.06080"^]

* Framework de formation d'apprentissage profond distribué : Horovod
+
https://horovod.ai/["https://horovod.ai/"^]

* EXÉCUTION : solution d'orchestration de conteneurs d'IA : EXÉCUTION : présentation d'un produit d'IA
+
https://docs.run.ai/home/components/["https://docs.run.ai/home/components/"^]

* EXÉCUTION : documentation d'installation d'IA
+
https://docs.run.ai/Administrator/Cluster-Setup/cluster-install/#step-3-install-runai["https://docs.run.ai/Administrator/Cluster-Setup/cluster-install/#step-3-install-runai"^] https://docs.run.ai/Administrator/Researcher-Setup/cli-install/["https://docs.run.ai/Administrator/Researcher-Setup/cli-install/#runai-cli-installation"^]

* Soumission des tâches EN COURS D'EXÉCUTION : interface de ligne de commande d'IA
+
https://docs.run.ai/Researcher/cli-reference/runai-submit/["https://docs.run.ai/Researcher/cli-reference/runai-submit/"^]

+
https://docs.run.ai/Researcher/cli-reference/runai-submit-mpi/["https://docs.run.ai/Researcher/cli-reference/runai-submit-mpi/"^]

* Ressources cloud Azure : Azure NetApp Files
+
https://docs.microsoft.com/azure/azure-netapp-files/["https://docs.microsoft.com/azure/azure-netapp-files/"^]

* Service Azure Kubernetes
+
https://azure.microsoft.com/services/kubernetes-service/-features["https://azure.microsoft.com/services/kubernetes-service/-features"^]

* Références de machines virtuelles Azure
+
https://azure.microsoft.com/services/virtual-machines/["https://azure.microsoft.com/services/virtual-machines/"^]

* Machine virtuelle Azure avec références de processeurs graphiques
+
https://docs.microsoft.com/azure/virtual-machines/sizes-gpu["https://docs.microsoft.com/azure/virtual-machines/sizes-gpu"^]

* NetApp Trident
+
https://github.com/NetApp/trident/releases["https://github.com/NetApp/trident/releases"^]

* Data Fabric optimisée par NetApp
+
https://www.netapp.com/data-fabric/what-is-data-fabric/["https://www.netapp.com/data-fabric/what-is-data-fabric/"^]

* Documentation produit NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]


