---
sidebar: sidebar 
permalink: ai/runai-ld_conclusion.html 
keywords: azure, lane, detection, run, ai, workloads 
summary: 'NetApp Run ai s"est associé pour créer ce rapport technique afin de présenter les fonctionnalités uniques de Azure NetApp Files avec la plateforme D"IA EN COURS D"EXÉCUTION afin de simplifier l"orchestration des workloads d"IA.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp et EXÉCUTION : l'IA se sont associées à la création de ce rapport technique pour présenter les fonctionnalités uniques de Azure NetApp Files et DE L'EXÉCUTION : une plateforme d'IA qui simplifie l'orchestration des workloads d'IA. Ce rapport technique fournit une architecture de référence pour rationaliser le processus des pipelines de données et de l'orchestration de la charge de travail pour la formation sur la détection de voies distribuées.

En conclusion, en ce qui concerne la formation distribuée à grande échelle (notamment dans un environnement de cloud public), le composant d'orchestration et de stockage des ressources est essentiel à la solution. S'assurer que la gestion des données n'entrave pas le traitement plusieurs GPU, ce qui optimise l'utilisation des cycles GPU. Ainsi, le système est aussi rentable que possible à des fins de formation distribuée à grande échelle.

La Data Fabric fournie par NetApp relève le défi en permettant aux data Scientists et aux ingénieurs de données de se connecter sur site et dans le cloud à des données synchrones, sans aucune intervention manuelle. En d'autres termes, la Data Fabric opère en douceur pour gérer les workflows d'IA répartis sur plusieurs sites. Cette solution facilite également la disponibilité des données à la demande en rapprochant les données de calcul et en exécutant des opérations d'analyse, d'entraînement et de validation, quand et où vous en avez besoin. Cette fonctionnalité permet non seulement l'intégration des données, mais aussi la protection et la sécurité de l'ensemble du pipeline de données.
