---
sidebar: sidebar 
permalink: ai/runai-ld_additional_information.html 
keywords: azure, lane, detection, additional, information, websites 
summary: Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et sites web. 
---
= Informations supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Jeu de données : simple
+
https://["https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection"^]

* Architecture de réseau d'apprentissage profond : réseau neuronal spatial
+
https://["https://arxiv.org/abs/1712.06080"^]

* Framework de formation d'apprentissage profond distribué : Horovod
+
https://["https://horovod.ai/"^]

* EXÉCUTION : solution d'orchestration de conteneurs d'IA : EXÉCUTION : présentation d'un produit d'IA
+
https://["https://docs.run.ai/home/components/"^]

* EXÉCUTION : documentation d'installation d'IA
+
https://["https://docs.run.ai/Administrator/Cluster-Setup/cluster-install/#step-3-install-runai"^] https://["https://docs.run.ai/Administrator/Researcher-Setup/cli-install/#runai-cli-installation"^]

* Soumission des tâches EN COURS D'EXÉCUTION : interface de ligne de commande d'IA
+
https://["https://docs.run.ai/Researcher/cli-reference/runai-submit/"^]

+
https://["https://docs.run.ai/Researcher/cli-reference/runai-submit-mpi/"^]

* Ressources cloud Azure : Azure NetApp Files
+
https://["https://docs.microsoft.com/azure/azure-netapp-files/"^]

* Service Azure Kubernetes
+
https://["https://azure.microsoft.com/services/kubernetes-service/-features"^]

* Références de machines virtuelles Azure
+
https://["https://azure.microsoft.com/services/virtual-machines/"^]

* Machine virtuelle Azure avec références de processeurs graphiques
+
https://["https://docs.microsoft.com/azure/virtual-machines/sizes-gpu"^]

* NetApp Trident
+
https://["https://github.com/NetApp/trident/releases"^]

* Data Fabric optimisée par NetApp
+
https://["https://www.netapp.com/data-fabric/what-is-data-fabric/"^]

* Documentation produit NetApp
+
https://["https://www.netapp.com/support-and-training/documentation/"^]


