---
sidebar: sidebar 
permalink: ai/tr-4811.html 
keywords:  
summary:  
---
= Tr-4811 : Architecture de référence NetApp ONTAP ai pour le secteur de la santé : imagerie diagnostique - conception de la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Rick Huang, Sung-Han Lin, Satish Thyagarajan, NetApp Jacci Cencii, NVIDIA

[role="lead"]
Cette architecture de référence apporte des lignes directrices aux clients du secteur de la santé qui créent des infrastructures d'intelligence artificielle (IA) reposant sur des systèmes NVIDIA DGX-2 et de stockage NetApp AFF. Vous y trouverez des informations sur les workflows généraux utilisés dans le développement de modèles de deep learning (DL) pour l'imagerie diagnostique médicale, des scénarios et des résultats de tests de validation Il inclut également des recommandations de dimensionnement pour les déploiements client.

link:https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf["Tr-4811 : Architecture de référence NetApp ONTAP ai pour le secteur de la santé : imagerie diagnostique - conception de la solution"^]
