---
sidebar: sidebar 
permalink: ai/tr-4785-link.html 
keywords:  
summary:  
---
= Tr-4785 : déploiement de l'IA avec NetApp E-Series et BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nagalakshmi Radu, Daniel Landes, Nathan Swartz, Amine Bennani, NetApp

Les applications d'intelligence artificielle (IA), de machine learning (ML) et de deep learning (DL) impliquent des datasets volumineux et des calculs importants. Pour exécuter correctement ces charges de travail, vous avez besoin d'une infrastructure agile qui vous permet de faire évoluer horizontalement les nœuds de calcul et de stockage de manière transparente. Ce rapport comprend des étapes pour exécuter un modèle d'entraînement d'IA dans un mode distribué, qui permet une évolutivité scale-out transparente des nœuds de calcul et de stockage. Il inclut également plusieurs metrics de performance pour démontrer comment une solution alliant le stockage NetApp E-Series et le système de fichiers parallèle BeeGFS fournit une solution simple, flexible et économique pour les workloads d'IA.

link:https://www.netapp.com/pdf.html?item=/media/17040-tr4785pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17040-tr4785pdf.pdf"^]
