---
sidebar: sidebar 
permalink: ai/tr-4799.html 
keywords:  
summary:  
---
= Tr-4799 : architecture de référence NetApp ONTAP ai pour les workloads de conduite autonome
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


David Arnette et Sung-Han Lin, NetApp

[role="lead"]
La gamme NVIDIA DGX est la première plateforme d'intelligence artificielle intégrée au monde conçue spécialement pour l'IA d'entreprise. Les systèmes de stockage NetApp AFF combinent performances optimales et fonctionnalités de pointe pour la gestion des données dans le cloud hybride. NetApp et NVIDIA se sont associés pour créer l'architecture de référence NetApp ONTAP ai, afin de proposer une solution clé en main qui prend en charge les workloads d'IA et de machine learning (ML), tout en offrant des performances et une fiabilité exceptionnelles.

link:https://www.netapp.com/pdf.html?item=/media/8554-tr4799designpdf.pdf["Tr-4799 : architecture de référence NetApp ONTAP ai pour les workloads de conduite autonome"^]
