---
sidebar: sidebar 
permalink: ai/tr-4851.html 
keywords:  
summary:  
---
= Tr-4851 : Data Lake NetApp StorageGRID pour les charges de travail de conduite autonome - conception de solutions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


David Arnette, NetApp

[role="lead"]
Le rapport TR-4851 démontre l'utilisation du stockage objet NetApp StorageGRID en tant que système de gestion et de référentiel de données pour le développement des logiciels de machine learning (ML) et de deep learning (DL). Ce livre blanc décrit le flux et les exigences de développement logiciel de véhicules autonomes, ainsi que les fonctionnalités StorageGRID qui rationalisent le cycle de vie des données. Cette solution s'applique à tout workflow de pipeline de traitement de données à plusieurs étapes standard dans les processus de développement DU ML et du DL.

link:https://www.netapp.com/pdf.html?item=/media/19399-tr-4851.pdf["Tr-4851 : Data Lake NetApp StorageGRID pour les charges de travail de conduite autonome - conception de solutions"^]
