---
sidebar: sidebar 
permalink: ai/tr-4807-link.html 
keywords:  
summary:  
---
= Tr-4807 : architecture de référence NetApp ONTAP ai pour les workloads de services financiers - conception de la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthikeyan Nagalingam, Sung-Han Lin, NetApp Jacci Cenci, NVIDIA

Cette architecture de référence apporte des lignes directrices aux clients qui créent une infrastructure d'intelligence artificielle reposant sur des systèmes NVIDIA DGX-1 et de stockage NetApp AFF pour les champs d'application du secteur financier. Vous y trouverez des informations sur les workflows généraux utilisés dans le développement de modèles de deep learning pour les scénarios de test et les résultats des services financiers. Il inclut également des recommandations de dimensionnement pour les déploiements client.

link:https://www.netapp.com/pdf.html?item=/media/17205-tr4807pdf.pdf["Tr-4807 : architecture de référence NetApp ONTAP ai pour les workloads de services financiers - conception de la solution"^]
