---
sidebar: sidebar 
permalink: ai/tr-4915.html 
keywords:  
summary:  
---
= Tr-4915 : déplacement des données avec les workflows E-Series et BeeGFS pour l'IA et l'analytique
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Cody Harryman et Ryan rodine, NetApp

[role="lead"]
Le rapport TR-4915 explique comment déplacer des données depuis n'importe quel référentiel de données vers un système de fichiers BeeGFS reposant sur un système de stockage SAN NetApp E-Series. Pour les applications d'intelligence artificielle (IA) et de machine learning (ML), il peut être nécessaire de déplacer de grands jeux de données dépassant plusieurs pétaoctets de données vers leurs clusters BeeGFS pour le développement de modèles. Ce document explique comment utiliser les outils de copie et de synchronisation NetApp XCP et NetApp BlueXP.

link:https://www.netapp.com/pdf.html?item=/media/65882-tr-4915.pdf["Tr-4915 : déplacement des données avec les workflows E-Series et BeeGFS pour l'IA et l'analytique"^]
