---
sidebar: sidebar 
permalink: ai/vector-database-conclusion.html 
keywords: vector database, conclusion 
summary: conclusion - solution de base de données vectorielle pour NetApp 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Conclusion

En conclusion, ce document offre une vue d'ensemble complète du déploiement et de la gestion de bases de données vectorielles, telles que Milvus et pgvector, sur les solutions de stockage NetApp. Nous avons abordé les conseils d'infrastructure pour l'exploitation du stockage objet NetApp ONTAP et StorageGRID et validé la base de données Milvus dans AWS FSX pour NetApp ONTAP via un magasin de fichiers et d'objets.

Nous avons exploré la dualité fichier/objet de NetApp qui démontre son utilité non seulement pour les données dans des bases de données vectorielles, mais aussi pour d'autres applications. Nous avons également souligné comment SnapCenter, le produit de gestion d'entreprise de NetApp, propose des fonctionnalités de sauvegarde, de restauration et de clonage pour les données de bases de données vectorielles, assurant ainsi l'intégrité et la disponibilité des données.

Il examine également comment la solution de cloud hybride NetApp assure la réplication et la protection des données dans les environnements sur site et cloud, assurant ainsi une expérience de gestion des données transparente et sécurisée. Nous avons fourni des informations sur la validation des performances de bases de données vectorielles telles que Milvus et pgvecto sur NetApp ONTAP, et nous avons fourni des informations précieuses sur leur efficacité et leur évolutivité.

Enfin, nous avons abordé deux cas d'utilisation d'IA générative : RAG avec LLM et le ChatAI interne de NetApp. Ces exemples pratiques soulignent les applications et les avantages réels des concepts et des pratiques décrits dans ce document. Ce document sert de guide complet à tous ceux qui souhaitent tirer parti des puissantes solutions de stockage de NetApp pour la gestion des bases de données vectorielles.



=== Remerciements

L'auteur remercie chaleureusement les contributeurs ci-dessous, d'autres personnes qui ont fourni leurs commentaires et commentaires pour rendre ce document précieux aux clients de NetApp et aux champs de NetApp.

. Satish Thyagarajan, Ingénieur marketing et technique, ONTAP ai & Analytics, NetApp
. Mike Oglesby, Ingénieur marketing et technique, NetApp
. AJ Mahajan, Directeur principal, NetApp
. Joe Scott, responsable de l'ingénierie des performances des charges de travail, NetApp
. Puneet Dhawan, Directeur senior, solution FSX de gestion de produits, NetApp
. Yuval Kalderon, responsable produits senior, équipe produit FSX, NetApp




=== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Documentation Milvus - https://milvus.io/docs/overview.md[]
* Documentation autonome Milvus - https://milvus.io/docs/v2.0.x/install_standalone-docker.md[]
* Documentation produit NetApp
https://www.netapp.com/support-and-training/documentation/[]
* instaclustr - link:https://www.instaclustr.com/support/documentation/?_bt=&_bk=&_bm=&_bn=x&_bg=&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=1467100120&hsa_cam=20766399079&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAjw26KxBhBDEiwAu6KXtzOZhN0dl0H1smOMcj9nsC0qBQphdMqFR7IrVQqeG2Y4aHWydUMj2BoCdFwQAvD_BwE["documentation instalclustr"]




=== Historique des versions

|===


| Version | Date | Historique des versions du document 


| Version 1.0 | Avril 2024 | Version initiale 
|===