---
sidebar: sidebar 
permalink: ai/vector-database-solution-with-netapp.html 
keywords: vector database, milvus, usecases 
summary: 'Il s"agit d"une page abstraite pour la solution de base de données vectorielle avec NetApp.' 
---
= Solution de base de données Vector avec NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthikeyan Nagalingam et Rodrigo Nascimento, NetApp

[role="lead"]
Ce document contient une exploration approfondie du déploiement et de la gestion des bases de données vectorielles, telles que Milvus et pgvecto une extension PostgreSQL open source, à l'aide des solutions de stockage NetApp. Il détaille les conseils d'infrastructure pour l'utilisation du stockage objet NetApp ONTAP et StorageGRID et valide l'application de la base de données Milvus dans AWS FSX pour NetApp ONTAP. Il présente la dualité fichier/objet de NetApp et son utilité pour les bases de données vectorielles et les applications prenant en charge les codes vectoriels. Il met l'accent sur les fonctionnalités de sauvegarde et de restauration d'SnapCenter, produit de gestion d'entreprise de NetApp, pour les bases de données vectorielles, qui assurent l'intégrité et la disponibilité des données. Le document approfondit son analyse de la solution de cloud hybride NetApp, et aborde son rôle dans la réplication et la protection des données dans les environnements sur site et dans le cloud. Il comprend un aperçu de la validation des performances des bases de données vectorielles sur NetApp ONTAP et se termine par deux cas d'utilisation pratiques de l'IA générative : RAG avec LLM et le Charai interne de NetApp. Ce document fournit un guide complet sur l'exploitation des solutions de stockage NetApp pour la gestion des bases de données vectorielles.

L'architecture de référence se concentre sur les éléments suivants :

. link:./vector-database-introduction.html["Introduction"]
. link:./vector-database-solution-overview.html["Présentation de la solution"]
. link:./vector-database-vector-database.html["Base de données vectorielle"]
. link:./vector-database-technology-requirement.html["Exigences technologiques"]
. link:./vector-database-deployment-procedure.html["Procédure de déploiement"]
. link:./vector-database-solution-verification-overview.html["Présentation de la vérification de la solution"]
. link:./vector-database-instaclustr-with-pgvector.html["Base de données Vector avec Instaclustr à l'aide de PostgreSQL: Pgvector"]
. link:./vector-database-use-cases.html["Cas d'utilisation de la base de données Vector"]
. link:./vector-database-conclusion.html["Conclusion"]
. link:./vector-database-values-yaml.html["Annexe A : valeurs.yaml"]
. link:./vector-database-prepare-data-netapp-new-py.html["Annexe B : prepare_data_netapp_new.py"]
. link:./vector-database-verify-data-netapp-py.html["Annexe C : verify_data_netapp.py"]
. link:./vector-database-docker-compose-xml.html["Annexe D : docker-compose.yml"]

