---
sidebar: sidebar 
permalink: ai/vector-database-solution-overview.html 
keywords: Solution Overview vector database 
summary: Présentation de la solution pour la solution de base de données Vector pour NetApp 
---
= Présentation de la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section présente la solution de base de données NetApp Vector.



== Présentation de la solution

Cette solution présente les avantages et les capacités spécifiques de NetApp pour relever les défis auxquels sont confrontés les clients de bases de données vectorielles. Avec NetApp ONTAP, StorageGRID, les solutions cloud de NetApp et SnapCenter, les clients peuvent valoriser considérablement leurs opérations. Non seulement ces outils permettent de résoudre les problèmes existants, mais ils améliorent également l'efficacité et la productivité, contribuant ainsi à la croissance globale de l'entreprise.



=== Pourquoi choisir NetApp ?

* Les offres NetApp, telles que ONTAP et StorageGRID, permettent de séparer le stockage et le calcul pour une utilisation optimale des ressources selon des besoins spécifiques. Cette flexibilité permet aux clients de faire évoluer leur stockage indépendamment à l'aide des solutions de stockage NetApp.
* En exploitant les contrôleurs de stockage de NetApp, les clients peuvent transmettre efficacement des données à leur base de données vectorielle à l'aide des protocoles NFS et S3. Ces protocoles facilitent le stockage des données des clients et la gestion de l'index de la base de données Vector, éliminant ainsi la nécessité de plusieurs copies des données accessibles via les méthodes fichier et objet.
* NetApp ONTAP offre une prise en charge native du stockage NAS et objet sur les principaux fournisseurs de services cloud comme AWS, Azure et Google Cloud. Cette compatibilité étendue garantit une intégration transparente, ce qui permet la mobilité des données des clients, l'accessibilité globale, la reprise après incident, l'évolutivité dynamique et de hautes performances.
* Grâce aux puissantes fonctionnalités de gestion des données de NetApp, les clients sont assurés que leurs données sont bien protégées contre les risques et les menaces potentiels. NetApp privilégie la sécurité des données en offrant aux clients la tranquillité d'esprit en matière de sécurité et d'intégrité de leurs informations stratégiques.

