---
sidebar: sidebar 
permalink: ai/vector-database-solution-verification-overview.html 
keywords: Solution Overview vector database 
summary: présentation de la vérification de la solution - solution de base de données vector pour NetApp 
---
= Présentation de la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nous avons procédé à une validation complète de la solution dans cinq domaines clés dont les détails sont présentés ci-dessous. Chaque section traite des défis auxquels sont confrontés les clients, des solutions fournies par NetApp et des avantages qu'ils en tirent.

. link:./vector-database-milvus-cluster-setup.html["Configuration de clusters Milvus avec Kubernetes sur site"]
Challenges des clients : faire évoluer indépendamment les ressources de stockage et de calcul, et gérer efficacement l'infrastructure et les données. Dans cette section, nous détaillons le processus d'installation d'un cluster Milvus sur Kubernetes avec un contrôleur de stockage NetApp pour les données de cluster et les données client.
. link:./vector-database-milvus-with-Amazon-FSxN-for-NetApp-ONTAP.html["Milvus avec Amazon FSxN pour NetApp ONTAP : dualité fichier/objet"]
Dans cette section, pourquoi nous devons déployer une base de données vectorielle dans le cloud ainsi que des étapes pour déployer une base de données vectorielle ( milvus standalone ) dans Amazon FSxN pour NetApp ONTAP dans des conteneurs docker.
. link:./vector-database-protection-using-snapcenter.html["Protection de base de données Vector à l'aide de NetApp SnapCenter."]
Dans cette section, nous allons examiner comment SnapCenter protège les données de la base de données vectorielle et les données Milvus résidant dans ONTAP. Dans cet exemple, nous avons utilisé un compartiment NAS (milvusdbvol1) dérivé d'un volume ONTAP NFS (vol1) pour les données clients, et un volume NFS distinct (vectordbpv) pour les données de configuration du cluster Milvus.
. link:./vector-database-disaster-recovery-using-netapp-snapmirror.html["Reprise sur incident à l'aide de NetApp SnapMirror"]
Dans cette section, nous parlerons de l'importance de la reprise sur incident pour la base de données vectorielle et de la manière dont snapmirror, produit de reprise sur incident de NetApp, fournit une solution de reprise sur incident pour la base de données vectorielle.
. link:./vector-database-performance-validation.html["Validation des performances"]
Dans cette section, nous allons examiner la validation des performances des bases de données vectorielles, telles que Milvus et pgvecto.RS, en nous concentrant sur leurs caractéristiques de performances de stockage, telles que le profil d'E/S et le contrôleur de stockage NetApp qui prennent en charge les charges de travail RAG et d'inférence dans le cadre du cycle de vie LLM. Nous évaluerons et identifierons les différences de performances éventuelles lorsque ces bases de données sont combinées à la solution de stockage ONTAP. Notre analyse sera basée sur des indicateurs clés de performance, comme le nombre de requêtes traitées par seconde (QPS).

