---
sidebar: sidebar 
permalink: ai/vector-database-introduction.html 
keywords: vector database 
summary: Introduction à la solution de base de données vectorielle pour NetApp 
---
= Introduction
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section présente la solution de base de données vectorielle pour NetApp.



== Introduction

Les bases de données vectorielles répondent efficacement aux défis qui sont conçus pour gérer la complexité de la recherche sémantique dans les modèles de langage large (LLMS) et l'intelligence artificielle générative (ai). Contrairement aux systèmes traditionnels de gestion des données, les bases de données vectorielles sont capables de traiter et de rechercher à travers différents types de données, y compris des images, des vidéos, du texte, de l'audio, et d'autres formes de données non structurées, en utilisant le contenu des données elles-mêmes plutôt que des étiquettes ou des balises.

Les limites des systèmes de gestion de bases de données relationnelles (RDBMS) sont bien documentées, notamment dans leurs difficultés liées aux représentations de données massives et aux données non structurées communes aux applications d'IA. Les SGBDR nécessitent souvent un processus long et source d'erreurs, qui consiste à aplatir les données en structures plus gérables, ce qui entraîne des retards et des inefficacités dans les recherches. Les bases de données vectorielles, en revanche, sont conçues pour contourner ces problèmes et offrir une solution plus efficace et plus précise pour la gestion et la recherche de données complexes et dimensionnelles, facilitant ainsi l'avancement des applications d'IA.

Ce document fournit un guide complet aux clients qui utilisent ou prévoient d'utiliser des bases de données vectorielles, en détaillant les bonnes pratiques d'utilisation des bases de données vectorielles sur des plateformes telles que NetApp ONTAP, NetApp StorageGRID, Amazon FSxN pour NetApp ONTAP et SnapCenter. Le contenu fourni dans ce document couvre une grande variété de sujets :

* Recommandations d'infrastructure pour les bases de données vectorielles, telles que Milvus, fournies par le stockage NetApp via NetApp ONTAP et le stockage objet StorageGRID
* Validation de la base de données Milvus dans AWS FSX pour NetApp ONTAP via un magasin de fichiers et d'objets
* S'intègre dans la dualité fichier/objet de NetApp, démontrant ainsi son utilité pour les données dans les bases de données vectorielles et d'autres applications.
* SnapCenter, le produit NetApp de gestion de la protection des données, propose les fonctionnalités de sauvegarde et de restauration des données de bases de données vectorielles.
* Comment le cloud hybride NetApp assure la réplication et la protection des données dans l'ensemble des environnements sur site et cloud.
* Fournit des informations sur la validation des performances de bases de données vectorielles telles que Milvus et pgvector sur NetApp ONTAP.
* Deux cas d'utilisation spécifiques : récupération de la génération augmentée (RAG) avec des modèles de langage large (LLM) et Chai de l'équipe IT de NetApp, offrant ainsi des exemples pratiques des concepts et des pratiques présentés.

