---
sidebar: sidebar 
permalink: ai/wp-dgxc.html 
keywords: NetApp AI, AI, Artificial Intelligence, Data Management, Supercomputing 
summary: NVIDIA DGX Cloud avec NetApp Cloud volumes ONTAP/ANF 
---
= Services de données cloud NetApp pour NVIDIA DGX Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Dave Arnette et Sathyagarajan, NetApp

[role="lead"]
Gestion avancée des données pour des supercalculateurs de pointe



== Introduction

Ce document explique comment les clients peuvent utiliser NetApp Cloud volumes/ANF pour bénéficier de fonctionnalités avancées de gestion des données, associées à NVIDIA DGX Cloud, afin d'optimiser et de rationaliser les opérations de pipeline de données d'IA.



=== Partenariat entre NVIDIA, Microsoft et NetApp

DGX Cloud fournit aux clients un accès immédiat à un supercalculateur d'IA à partir d'un navigateur web.  Avec DGX Cloud, les entreprises peuvent accéder à l'entraînement d'IA à plusieurs nœuds à grande échelle pour accélérer la conception de modèles complexes. Si les entreprises choisissent de s'étendre à l'infrastructure sur site, elles peuvent consolider toutes leurs ressources pour fournir un cloud hybride en exploitant NetApp BlueXP™ et la plateforme NVIDIA base Command, qui offre aux développeurs une vue cohérente et centralisée.



=== NVIDIA DGX Cloud

~NVIDIA pour nous indiquer le contenu à ajouter ici



=== Microsoft Azure



=== NetApp BlueXP™



=== Azure NetApp Files®



=== Dualité fichier/objet NetApp



== Architecture et configuration



=== Design/Présentation de la solution



=== Dessin d'architecture



=== Déploiement de CVO/ANF

Avec BlueXP



=== Configuration de la dualité fichier/objet

Automatisé via Ansible ?



=== Connexion à DGXC



== Conclusion
