---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-conclusion.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 'Il s"agit de la solution NetApp ONTAP pour la configuration, le renforcement et la validation d"un cyber-coffre basé sur ONTAP' 
---
= Conclusion de la solution ONTAP Cyber Vault PowerShell
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
En tirant parti des méthodes de renforcement robustes fournies par ONTAP, NetApp vous permet de créer un environnement de stockage isolé et sécurisé, résilient face aux cybermenaces en constante évolution. Tout cela s'effectue tout en conservant l'agilité et l'efficacité de l'infrastructure de stockage existante. Cet accès sécurisé permet aux entreprises d'atteindre leurs objectifs stricts en matière de sécurité et de disponibilité en modifiant au minimum leur personnel, leur structure de processus et leur structure technologique.

Le cybercoffre ONTAP utilise des fonctionnalités natives de ONTAP est une approche simple pour une protection supplémentaire qui permet de créer des copies immuables et indélébiles de vos données. L'ajout du cyber-coffre NetApp basé sur ONTAP à la stratégie de sécurité globale permettra de :

* Créez un environnement distinct et déconnecté des réseaux de production et de sauvegarde et limitez l'accès des utilisateurs à celui-ci.

