---
sidebar: sidebar 
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening 
permalink: /cyber-vault/ontap-cyber-vault-sizing.html 
summary: Conseils pour vous aider à dimensionner un cyber-coffre-fort ONTAP 
---
= Dimensionnement de la baie cybernétique avec ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour dimensionner un cybersystème, il est nécessaire de comprendre la quantité de données à restaurer dans un objectif de délai de restauration (RTO) donné. De nombreux facteurs jouent un rôle important dans la conception d'une solution de cyber-coffre adaptée.



== Dimensionnement

. Quels sont les modèles de plateforme source (FAS v AFF A-Series v AFF C-Series) ?
. Quelle est la bande passante et la latence entre la source et le cyber-coffre ?
. Quelle est la taille des fichiers et combien de fichiers sont-ils volumineux ?
. Quel est votre objectif de délai de restauration ?
. Quelle quantité de données devez-vous restaurer dans l'objectif de délai de restauration ?
. Combien de relations « fan-in » SnapMirror le cybercoffre est-il en cours d'acquisition ?
. Y aura-t-il des restaurations uniques ou multiples en même temps ?
. Ces restaurations multiples auront-elles lieu sur le même système primaire ?
. SnapMirror sera-t-il répliqué vers le coffre-fort pendant la restauration à partir d'un coffre-fort ?

