---
sidebar: sidebar 
permalink: automation/automation_introduction.html 
summary: 'L"automatisation des solutions NetApp permet au client d"automatiser le déploiement, la configuration et l"exécution de nombreuses tâches d"infrastructure et d"applications courantes.' 
keywords: netapp, solutions, automation, ansible, terraform 
---
= Automatisation des solutions NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'automatisation des solutions NetApp permet au client d'automatiser le déploiement, la configuration et l'exécution de nombreuses tâches d'infrastructure et d'applications courantes.



== Introduction

En proposant des solutions qui répondent aux défis actuels des entreprises, NetApp fournit des solutions ayant les objectifs suivants :

* Fourniture d'étapes de déploiement et de configuration validées,
* Fournir des solutions faciles à consommables,
* Fournir un déploiement de solutions avec des résultats prévisibles est facilement répété et évolutif dans l'ensemble de l'entreprise du client.


Pour atteindre ces objectifs, il est primordial de simplifier le déploiement et la configuration de l'infrastructure et/ou des applications fournies par nos solutions via l'automatisation. NetApp s'engage à simplifier la consommation de ses solutions grâce à l'automatisation.

Grâce à des outils d'automatisation open source tels que Red Hat Ansible, HashiCorp Terraform ou Microsoft PowerShell, les solutions NetApp permettent d'automatiser le déploiement des applications, le provisionnement cloud, la gestion des configurations et de nombreuses autres tâches IT courantes. Les solutions NetApp tirent parti des artéfacts d'automatisation accessibles au public et de l'automatisation rédigée par NetApp pour simplifier le déploiement global d'une solution.

Lorsque des fonctionnalités d'automatisation sont disponibles, la documentation relative à la solution guide l'utilisateur tout au long du processus d'automatisation de la solution ou des étapes de la solution via les outils d'automatisation spécifiques.
